Repository thingsboard/thingsboard, pull requests merged in 2022-12, with the labels that each got.

#7761 [3.4.3] Fix no timeseries data in widget for entity view; fix State Chart invalid behavior
  application/src/main/java/org/thingsboard/server/service/subscription/DefaultTbEntityDataSubscriptionService.java
  common/data/src/main/java/org/thingsboard/server/common/data/kv/BaseReadTsKvQuery.java
  common/data/src/main/java/org/thingsboard/server/common/data/kv/BaseTsKvQuery.java
  dao/src/main/java/org/thingsboard/server/dao/timeseries/BaseTimeseriesService.java
  dao/src/test/java/org/thingsboard/server/dao/service/timeseries/BaseTimeseriesServiceTest.java
Labels: Bug, Core

#7773 [3.4.3][Bug] Getting a lot of updates over WS in case of aggregation query, even if no real updates happened
  application/src/main/java/org/thingsboard/server/service/subscription/TbAbstractDataSubCtx.java
  application/src/main/java/org/thingsboard/server/service/subscription/TbAlarmDataSubCtx.java
  application/src/main/java/org/thingsboard/server/service/subscription/TbEntityDataSubCtx.java
  dao/src/main/java/org/thingsboard/server/dao/timeseries/CassandraBaseTimeseriesDao.java
Labels: Bug, Core

#7783 [3.4.3] fixed device bulk import with empty credentials
  application/src/main/java/org/thingsboard/server/service/device/DeviceBulkImportService.java
  application/src/test/java/org/thingsboard/server/controller/BaseDeviceControllerTest.java
Labels: Bug, Core

#7786 [3.4.3] fixed saveDeviceWithCredentials notifications
  application/src/main/java/org/thingsboard/server/service/entitiy/device/DefaultTbDeviceService.java
  application/src/test/java/org/thingsboard/server/controller/BaseDeviceControllerTest.java
Labels: Bug, Core

#7791 [3.5] Bugfix: Node 'split array msg'. Empty array
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/TbSplitArrayMsgNode.java
Labels: Bug, Rule Engine

#7803 [3.4.3]fixed bulk import test infinite await
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/csv/AbstractBulkImportService.java
Labels: Ignore for release

#7758 [3.4.3] UI: Fixed validation in bulk import and improvement bulk import for Edge
  ui-ngx/src/app/modules/home/components/import-export/import-export.models.ts
  ui-ngx/src/app/modules/home/components/import-export/table-columns-assignment.component.html
  ui-ngx/src/app/modules/home/components/import-export/table-columns-assignment.component.ts
Labels: Bug, UI

#7782 [3.4.3] UI: Fixed Catalan locale designator
  ui-ngx/src/assets/locale/locale.constant-ca_ES.json
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: Bug, UI

#7785 [3.4.3] UI: Add new Danish language
  ui-ngx/src/assets/locale/locale.constant-da_DK.json
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI, Feature

#7795 [3.4.3] UI: Always visible action button in multiple input widgets
  ui-ngx/src/app/modules/home/components/widget/lib/multiple-input-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/multiple-input-widget.component.scss
Labels: UI, Feature

#7792 [3.4.3][Bug] Edge root rule chain update fix. USER entity support added. INACTIVITY_TIMEOUT pushed to edge.
  application/src/main/java/org/thingsboard/server/service/edge/DefaultEdgeNotificationService.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/constructor/RuleChainMsgConstructor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/RuleChainEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/TelemetryEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/sync/DefaultEdgeRequestsService.java
  application/src/test/java/org/thingsboard/server/edge/BaseDeviceEdgeTest.java
  application/src/test/java/org/thingsboard/server/edge/BaseRuleChainEdgeTest.java
  application/src/test/java/org/thingsboard/server/edge/BaseTelemetryEdgeTest.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/edge/AbstractTbMsgPushNode.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/edge/TbMsgPushToEdgeNodeTest.java
Labels: Bug, Edge

#7824 Fixed incorrect updated timewindow in Alarm table
  ui-ngx/src/app/core/api/widget-subscription.ts
Labels: Bug, UI

#7840 [3.5] Fixed incorrect index creation for edge event migration
  application/src/main/data/upgrade/3.4.1/schema_update.sql
Labels: Ignore for release

#7838 [3.5] fixed device sessions dump
  application/src/main/java/org/thingsboard/server/service/session/DefaultDeviceSessionCacheService.java
Labels: Bug, Core

#7856 [WIP][3.5] Improve swagger description for SaveAttributes
  application/src/main/java/org/thingsboard/server/controller/ControllerConstants.java
  application/src/main/java/org/thingsboard/server/controller/TelemetryController.java
Labels: Ignore for release

#7815 [3.4.4][Bug][Edge] Correctly set root rule chain on initial sync
  application/src/main/java/org/thingsboard/server/service/edge/rpc/fetch/RuleChainsEdgeEventFetcher.java
  application/src/main/java/org/thingsboard/server/service/entitiy/edge/DefaultTbEdgeService.java
  application/src/test/java/org/thingsboard/server/controller/BaseEdgeControllerTest.java
Labels: Bug, Edge

#7863 Optimizations for dashboard-pages that open in popover or dialog.
  ui-ngx/src/app/core/http/entity.service.ts
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.html
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.ts
  ui-ngx/src/app/modules/home/components/home-components.module.ts
  ui-ngx/src/app/modules/home/components/widget/widget-component.service.ts
  ui-ngx/src/app/modules/home/components/widget/widget.component.ts
Labels: Bug, UI

#7868 Fixed incorrect calculate width when used right layout dashboard
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.html
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.ts
Labels: Bug, UI

#7871 Detected changes of switching fixed layout side
  ui-ngx/src/app/modules/home/components/dashboard-page/layout/manage-dashboard-layouts-dialog.component.ts
Labels: Bug, UI

#7862 [3.5] Push latest timeseries key-value pair to edge on assignment entity to edge
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/AlarmEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/DeviceEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/RelationEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/sync/DefaultEdgeRequestsService.java
  application/src/test/java/org/thingsboard/server/edge/AbstractEdgeTest.java
  application/src/test/java/org/thingsboard/server/edge/BaseDeviceEdgeTest.java
Labels: Feature, Edge
