Repository thingsboard/thingsboard, pull requests merged in 2023-05, with the labels that each got.

#8440 Improvements for notification system
  application/src/main/java/org/thingsboard/server/controller/NotificationController.java
  application/src/main/java/org/thingsboard/server/controller/NotificationRuleController.java
  application/src/main/java/org/thingsboard/server/controller/NotificationTargetController.java
  application/src/main/java/org/thingsboard/server/controller/NotificationTemplateController.java
  application/src/main/java/org/thingsboard/server/service/notification/DefaultNotificationCenter.java
  common/data/src/main/java/org/thingsboard/server/common/data/notification/NotificationRequest.java
  common/data/src/main/java/org/thingsboard/server/common/data/notification/rule/trigger/NotificationRuleTriggerType.java
  dao/src/main/java/org/thingsboard/server/dao/notification/DefaultNotificationSettingsService.java
  dao/src/main/java/org/thingsboard/server/dao/notification/DefaultNotifications.java
  rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/NotificationCenter.java
Labels: Ignore for release

#8448 Updated in home page widgets bundle description and image
  application/src/main/data/json/system/widget_bundles/home_page_widgets.json
Labels: enhancement, UI, Ignore for release

#8450 Improve Edge translation
  ui-ngx/src/app/modules/home/pages/edge/edge-routing.module.ts
  ui-ngx/src/app/modules/home/pages/edge/edge.component.html
  ui-ngx/src/app/modules/home/pages/edge/edges-table-config.resolver.ts
  ui-ngx/src/app/modules/home/pages/rulechain/rulechains-table-config.resolver.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI, Edge, Ignore for release

#8447 Copy button for attribute table
  ui-ngx/src/app/modules/home/components/attribute/attribute-table.component.html
  ui-ngx/src/app/modules/home/components/attribute/attribute-table.component.scss
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI, Feature

#8458 Add/edit entity custom action code samples corrected
  ui-ngx/src/app/modules/home/components/widget/action/custom-sample-css.raw
  ui-ngx/src/app/modules/home/components/widget/action/custom-sample-html.raw
  ui-ngx/src/app/modules/home/components/widget/action/custom-sample-js.raw
  ui-ngx/src/assets/help/en_US/widget/action/examples/custom_pretty_create_dialog_html.md
  ui-ngx/src/assets/help/en_US/widget/action/examples/custom_pretty_edit_dialog_html.md
  ui-ngx/src/assets/help/en_US/widget/action/examples/custom_pretty_edit_dialog_js.md
  ui-ngx/src/assets/help/en_US/widget/action/examples_custom_pretty/custom_pretty_create_dialog_html.md
  ui-ngx/src/assets/help/en_US/widget/action/examples_custom_pretty/custom_pretty_edit_dialog_html.md
  ui-ngx/src/assets/help/en_US/widget/action/examples_custom_pretty/custom_pretty_edit_dialog_js.md
Labels: Bug, UI

#8461 Change alarm menu icon
  ui-ngx/src/app/core/services/menu.service.ts
  ui-ngx/src/app/modules/home/pages/alarm/alarm-routing.module.ts
Labels: enhancement, UI, Ignore for release

#8438 Widget extension module support in custom action
  ui-ngx/src/app/modules/home/components/widget/action/custom-action-pretty-resources-tabs.component.html
  ui-ngx/src/app/modules/home/components/widget/dialog/custom-dialog.service.ts
  ui-ngx/src/app/modules/home/components/widget/widget-components.module.ts
  ui-ngx/src/app/modules/home/components/widget/widget.component.ts
  ui-ngx/src/app/shared/models/widget.models.ts
Labels: UI, Feature

#8449 fixed using default timeout and improvements
  application/src/main/java/org/thingsboard/server/service/state/DefaultDeviceStateService.java
Labels: Bug, Core

#8472 kv validator improvements
  application/src/main/java/org/thingsboard/server/service/telemetry/DefaultTelemetrySubscriptionService.java
  dao/src/main/java/org/thingsboard/server/dao/service/NoXssValidator.java
  dao/src/main/java/org/thingsboard/server/dao/timeseries/BaseTimeseriesService.java
  dao/src/main/java/org/thingsboard/server/dao/util/KvUtils.java
Labels: Ignore for release

#8474 Improvements for usage stats
  application/src/main/java/org/thingsboard/server/service/apiusage/BaseApiUsageState.java
  application/src/main/java/org/thingsboard/server/service/apiusage/DefaultTbApiUsageStateService.java
  application/src/main/java/org/thingsboard/server/service/state/DefaultDeviceStateService.java
  application/src/main/resources/thingsboard.yml
  application/src/test/java/org/thingsboard/server/service/state/DefaultDeviceStateServiceTest.java
  application/src/test/java/org/thingsboard/server/service/stats/DevicesStatisticsTest.java
Labels: Ignore for release

#8469 Fixed default icon size for table cell action
  ui-ngx/src/app/modules/home/components/edge/edge-downlink-table-config.ts
  ui-ngx/src/app/modules/home/components/event/event-table-config.ts
Labels: Bug, UI, Ignore for release

#8470 Fixed error when we review in send notification
  ui-ngx/src/app/modules/home/pages/notification/sent/sent-notification-dialog.componet.ts
  ui-ngx/src/app/modules/home/pages/notification/template/template-configuration.ts
Labels: Bug, UI, Ignore for release

#8481 Event table fixed width for cell with copy button
  ui-ngx/src/app/modules/home/components/event/event-table-config.ts
Labels: Bug, UI

#8482 Fixed padding for repository settings fieldset
  ui-ngx/src/app/modules/home/pages/admin/settings-card.scss
Labels: Bug, UI

#8484 Fixed rulenode incorrect edit credentials
  rule-engine/rule-engine-components/src/main/resources/public/static/rulenode/rulenode-core-config.js
Labels: Bug, UI, Rule Engine, Ignore for release

#8485 Added decorators to coercion input component value
  ui-ngx/src/app/modules/common/modules-map.ts
  ui-ngx/src/app/modules/home/components/alarm/alarm-filter-config.component.ts
  ui-ngx/src/app/modules/home/components/device/device-info-filter.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/home-page/toggle-header.component.ts
  ui-ngx/src/app/modules/home/pages/notification/rule/escalations.component.ts
  ui-ngx/src/app/shared/components/button/copy-button.component.ts
  ui-ngx/src/app/shared/components/entity/entity-autocomplete.component.ts
  ui-ngx/src/app/shared/components/entity/entity-type-list.component.ts
  ui-ngx/src/app/shared/components/markdown.component.ts
  ui-ngx/src/app/shared/components/notification/notification.component.ts
  ui-ngx/src/app/shared/components/notification/template-autocomplete.component.ts
  ui-ngx/src/app/shared/components/popover.component.ts
  ui-ngx/src/app/shared/components/string-items-list.component.ts
  ui-ngx/src/app/shared/components/time/timeinterval.component.ts
  ui-ngx/src/app/shared/components/time/timewindow.component.ts
  ui-ngx/src/app/shared/decorators/coercion.ts
  ui-ngx/src/app/shared/decorators/public-api.ts
  ui-ngx/src/app/shared/public-api.ts
Labels: UI, Feature

#8487 fixed singleton mode update
  application/src/main/java/org/thingsboard/server/actors/ruleChain/RuleNodeActorMessageProcessor.java
Labels: Core, Ignore for release

#8501 moved views and functions to a separate file
  application/src/main/data/upgrade/3.4.4/schema_update.sql
  application/src/main/java/org/thingsboard/server/install/ThingsboardInstallService.java
  application/src/main/java/org/thingsboard/server/service/install/EntityDatabaseSchemaService.java
  application/src/main/java/org/thingsboard/server/service/install/SqlEntityDatabaseSchemaService.java
  dao/src/main/resources/sql/schema-entities.sql
  dao/src/main/resources/sql/schema-views-and-functions.sql
Labels: Build Scripts, Core

#8499 Minor noification improvement
  ui-ngx/src/app/modules/home/pages/notification/sent/sent-notification-dialog.component.html
  ui-ngx/src/app/modules/home/pages/notification/template/template-configuration.ts
  ui-ngx/src/app/modules/home/pages/notification/template/template-notification-dialog.component.html
  ui-ngx/src/app/shared/components/notification/notification.component.scss
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: Bug, UI, Ignore for release

#8466 [3.5] Added UI tests on assign from alarm widget
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/TestRestClient.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/base/AbstractBasePage.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/base/AbstractDriverBaseTest.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/pages/AlarmWidgetElements.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/pages/CreateWidgetPopupElements.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/pages/CreateWidgetPopupHelper.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/pages/DashboardPageElements.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/pages/DashboardPageHelper.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/pages/SideBarMenuViewElements.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/pages/SideBarMenuViewHelper.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/assignee/AssignFromAlarmWidgetTest.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/utils/EntityPrototypes.java
Labels: Build Scripts

#8502 Patch for library @mat-datetimepicker/core
  ui-ngx/patches/@mat-datetimepicker+core+11.0.3.patch
  ui-ngx/src/app/modules/home/pages/notification/sent/sent-notification-dialog.component.html
Labels: Bug, UI, Ignore for release

#8503 Fixed incorrect updated dataSource validator when changing dataSource type
  ui-ngx/src/app/modules/home/components/widget/widget-config.component.html
  ui-ngx/src/app/modules/home/components/widget/widget-config.component.ts
Labels: Bug, UI

#8508 Fixed queue autocomplete style
  ui-ngx/src/app/shared/components/queue/queue-autocomplete.component.html
  ui-ngx/src/app/shared/components/queue/queue-autocomplete.component.ts
Labels: Bug, UI, Ignore for release

#8547 Improve dashboard edit panel
  ui-ngx/src/app/modules/home/components/alias/aliases-entity-select.component.html
  ui-ngx/src/app/modules/home/components/alias/aliases-entity-select.component.scss
  ui-ngx/src/app/modules/home/components/alias/aliases-entity-select.component.ts
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.html
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.scss
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.ts
  ui-ngx/src/app/modules/home/components/filter/filters-edit.component.scss
  ui-ngx/src/app/modules/home/components/filter/filters-edit.component.ts
  ui-ngx/src/app/shared/components/time/timewindow.component.html
  ui-ngx/src/app/shared/components/time/timewindow.component.scss
  ui-ngx/src/app/shared/components/time/timewindow.component.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
  ui-ngx/src/theme-overwrites.scss
Labels: enhancement, UI

#8557 Check msg originator in DeviceActivityTriggerProcessor
  application/src/main/java/org/thingsboard/server/service/notification/rule/trigger/DeviceActivityTriggerProcessor.java
Labels: Ignore for release

#8526 [3.5.1] Added UI smoke tests on devices
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/TestRestClient.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/base/AbstractDriverBaseTest.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/pages/CustomerPageHelper.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/pages/DevicePageElements.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/pages/DevicePageHelper.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/devicessmoke/AbstractDeviceTest.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/devicessmoke/CreateDeviceTest.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/devicessmoke/DeleteDeviceTest.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/devicessmoke/DeleteSeveralDevicesTest.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/devicessmoke/EditDeviceTest.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/rulechainssmoke/RuleChainEditMenuTest.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/utils/Const.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/utils/DataProviderCredential.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/utils/EntityPrototypes.java
  msa/black-box-tests/src/test/resources/all.xml
  msa/black-box-tests/src/test/resources/smokeDevices.xml
  msa/black-box-tests/src/test/resources/uiTests.xml
Labels: Build Scripts

#8442 removed redundant constants
  dao/src/main/java/org/thingsboard/server/dao/model/ModelConstants.java
Labels: Ignore for release

#8429 added logs for widgets bundle
  application/src/main/java/org/thingsboard/server/controller/WidgetsBundleController.java
  application/src/main/java/org/thingsboard/server/service/entitiy/widgets/bundle/DefaultWidgetsBundleService.java
  application/src/main/java/org/thingsboard/server/service/entitiy/widgets/bundle/TbWidgetsBundleService.java
  application/src/main/resources/thingsboard.yml
  application/src/test/java/org/thingsboard/server/controller/WidgetsBundleControllerTest.java
Labels: enhancement, Core

#8565 fixed cookie deserialization vulnerability
  application/src/main/java/org/thingsboard/server/service/security/auth/oauth2/CookieUtils.java
  application/src/test/java/org/thingsboard/server/service/security/auth/oauth2/HttpCookieOAuth2AuthorizationRequestRepositoryTest.java
Labels: Bug, Core

#8527 Ability to disable notification rules
  application/src/main/data/upgrade/3.5.0/schema_update.sql
  application/src/main/java/org/thingsboard/server/install/ThingsboardInstallService.java
  application/src/main/java/org/thingsboard/server/service/install/SqlDatabaseUpgradeService.java
  application/src/main/java/org/thingsboard/server/service/notification/rule/DefaultNotificationRuleProcessor.java
  application/src/main/java/org/thingsboard/server/service/notification/rule/cache/DefaultNotificationRulesCache.java
  application/src/main/java/org/thingsboard/server/service/notification/rule/cache/NotificationRulesCache.java
  application/src/test/java/org/thingsboard/server/service/notification/AbstractNotificationApiTest.java
  application/src/test/java/org/thingsboard/server/service/notification/NotificationRuleApiTest.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/notification/NotificationRuleService.java
  common/data/src/main/java/org/thingsboard/server/common/data/notification/rule/NotificationRule.java
  dao/src/main/java/org/thingsboard/server/dao/model/ModelConstants.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/NotificationRuleEntity.java
  dao/src/main/java/org/thingsboard/server/dao/notification/DefaultNotificationRuleService.java
  dao/src/main/java/org/thingsboard/server/dao/notification/DefaultNotifications.java
  dao/src/main/java/org/thingsboard/server/dao/notification/NotificationRuleDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/notification/JpaNotificationRuleDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/notification/NotificationRuleRepository.java
  dao/src/main/resources/sql/schema-entities.sql
  ui-ngx/src/app/modules/home/components/entity/entities-table.component.html
  ui-ngx/src/app/modules/home/models/entity/entities-table-config.models.ts
  ui-ngx/src/app/modules/home/pages/notification/rule/rule-notification-dialog.component.html
  ui-ngx/src/app/modules/home/pages/notification/rule/rule-notification-dialog.component.ts
  ui-ngx/src/app/modules/home/pages/notification/rule/rule-table-config.resolver.ts
  ui-ngx/src/app/shared/models/notification.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI, Core

#8556 Added feature to disable sms messaging
  application/src/main/java/org/thingsboard/server/controller/AdminController.java
  application/src/main/java/org/thingsboard/server/service/apiusage/TenantApiUsageState.java
  application/src/main/java/org/thingsboard/server/service/security/auth/mfa/provider/impl/SmsTwoFaProvider.java
  application/src/main/java/org/thingsboard/server/service/sms/DefaultSmsService.java
  application/src/test/java/org/thingsboard/server/service/sms/DefaultSmsServiceTest.java
  common/data/src/main/java/org/thingsboard/server/common/data/UsageInfo.java
  common/data/src/main/java/org/thingsboard/server/common/data/audit/ActionType.java
  common/data/src/main/java/org/thingsboard/server/common/data/tenant/profile/DefaultTenantProfileConfiguration.java
  common/data/src/main/java/org/thingsboard/server/common/data/tenant/profile/TenantProfileConfiguration.java
  dao/src/main/java/org/thingsboard/server/dao/audit/AuditLogServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/usage/BasicUsageInfoService.java
  ui-ngx/src/app/modules/home/components/profile/tenant/default-tenant-profile-configuration.component.html
  ui-ngx/src/app/modules/home/components/profile/tenant/default-tenant-profile-configuration.component.scss
  ui-ngx/src/app/modules/home/components/profile/tenant/default-tenant-profile-configuration.component.ts
  ui-ngx/src/app/shared/models/audit-log.models.ts
  ui-ngx/src/app/shared/models/tenant.model.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI, Feature, Core

#8573 table name constants refactoring
  application/src/main/java/org/thingsboard/server/service/ttl/AuditLogsCleanUpService.java
  application/src/main/java/org/thingsboard/server/service/ttl/EdgeEventsCleanUpService.java
  dao/src/main/java/org/thingsboard/server/dao/model/ModelConstants.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/AdminSettingsEntity.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/AlarmCommentEntity.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/AlarmEntity.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/AssetEntity.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/AssetProfileEntity.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/AuditLogEntity.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/ComponentDescriptorEntity.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/CustomerEntity.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/DashboardEntity.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/DashboardInfoEntity.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/DeviceCredentialsEntity.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/DeviceEntity.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/DeviceInfoEntity.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/DeviceProfileEntity.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/EdgeEntity.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/EdgeEventEntity.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/EntityAlarmEntity.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/EntityViewEntity.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/OAuth2ClientRegistrationTemplateEntity.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/OAuth2DomainEntity.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/OAuth2MobileEntity.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/OAuth2ParamsEntity.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/OAuth2RegistrationEntity.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/QueueEntity.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/RelationEntity.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/RuleChainEntity.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/RuleNodeEntity.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/TenantEntity.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/TenantProfileEntity.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/UserAuthSettingsEntity.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/UserCredentialsEntity.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/UserEntity.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/UserSettingsEntity.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/WidgetTypeDetailsEntity.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/WidgetTypeEntity.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/WidgetsBundleEntity.java
  dao/src/main/java/org/thingsboard/server/dao/sql/alarm/JpaAlarmCommentDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/audit/JpaAuditLogDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/edge/JpaBaseEdgeEventDao.java
Labels: Core, Ignore for release

#8575 added ability to disable swagger
  application/src/main/java/org/thingsboard/server/config/SwaggerConfiguration.java
  application/src/main/resources/thingsboard.yml
Labels: Core

#8506 Spanish locale update
  ui-ngx/src/assets/locale/locale.constant-es_ES.json
Labels: enhancement, UI

#8529 Fixed queue bugs
  ui-ngx/src/app/modules/home/components/profile/queue/tenant-profile-queues.component.ts
  ui-ngx/src/app/modules/home/components/queue/queue-form.component.html
  ui-ngx/src/app/modules/home/components/queue/queue-form.component.ts
Labels: Bug, UI

#8539 Fixed control widgets setting change
  ui-ngx/src/app/modules/home/components/widget/lib/settings/control/round-switch-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/control/slide-toggle-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/control/switch-control-widget-settings.component.ts
Labels: Bug, UI

#8546 Fixed Api usage widget fill color
  ui-ngx/src/app/modules/home/pages/api-usage/api_usage_json.raw
Labels: Bug, UI

#8578 Custom translate for alarm type
  ui-ngx/src/app/modules/home/components/alarm/alarm-details-dialog.component.ts
  ui-ngx/src/app/modules/home/components/alarm/alarm-table-config.ts
  ui-ngx/src/app/shared/components/notification/notification.component.html
  ui-ngx/src/app/shared/components/notification/notification.component.ts
Labels: Bug, UI

#8600 Fix handle action "browser file" in file input components
  ui-ngx/src/app/shared/components/file-input.component.scss
  ui-ngx/src/app/shared/components/image-input.component.scss
  ui-ngx/src/app/shared/components/multiple-image-input.component.scss
Labels: Bug, UI

#8606 [3.5.2] UI smoke tests on assign devices
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/TestRestClient.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/base/AbstractDriverBaseTest.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/pages/CustomerPageElements.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/pages/DevicePageElements.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/pages/DevicePageHelper.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tabs/AssignDeviceTabElements.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tabs/AssignDeviceTabHelper.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tabs/CreateDeviceTabElements.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tabs/CreateDeviceTabHelper.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/devicessmoke/AbstractDeviceTest.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/devicessmoke/AssignToCustomerTest.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/devicessmoke/CreateDeviceTest.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/devicessmoke/DeleteSeveralDevicesTest.java
Labels: Build Scripts

#8533 Version control for notification configs
  application/src/main/data/upgrade/3.5.1/schema_update.sql
  application/src/main/java/org/thingsboard/server/service/sync/ie/DefaultEntitiesExportImportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/exporting/DefaultExportableEntitiesService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/exporting/impl/BaseEntityExportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/exporting/impl/NotificationRuleExportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/exporting/impl/NotificationTargetExportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/exporting/impl/NotificationTemplateExportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/NotificationRuleImportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/NotificationTargetImportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/NotificationTemplateImportService.java
  application/src/test/java/org/thingsboard/server/service/notification/NotificationRuleApiTest.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/entity/EntityDaoService.java
  common/data/src/main/java/org/thingsboard/server/common/data/notification/rule/NotificationRule.java
  common/data/src/main/java/org/thingsboard/server/common/data/notification/targets/NotificationTarget.java
  common/data/src/main/java/org/thingsboard/server/common/data/notification/template/NotificationTemplate.java
  common/data/src/main/java/org/thingsboard/server/common/data/notification/template/NotificationTemplateConfig.java
  common/data/src/main/java/org/thingsboard/server/common/data/sync/JsonTbEntity.java
  dao/src/main/java/org/thingsboard/server/dao/DaoUtil.java
  dao/src/main/java/org/thingsboard/server/dao/asset/AssetProfileServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/asset/BaseAssetService.java
  dao/src/main/java/org/thingsboard/server/dao/customer/CustomerServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/dashboard/DashboardServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/device/DeviceProfileServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/device/DeviceServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/model/BaseSqlEntity.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/NotificationRuleEntity.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/NotificationTargetEntity.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/NotificationTemplateEntity.java
  dao/src/main/java/org/thingsboard/server/dao/notification/DefaultNotificationRuleService.java
  dao/src/main/java/org/thingsboard/server/dao/notification/DefaultNotificationTargetService.java
  dao/src/main/java/org/thingsboard/server/dao/notification/DefaultNotificationTemplateService.java
  dao/src/main/java/org/thingsboard/server/dao/notification/NotificationRuleDao.java
  dao/src/main/java/org/thingsboard/server/dao/notification/NotificationTargetDao.java
  dao/src/main/java/org/thingsboard/server/dao/notification/NotificationTemplateDao.java
  dao/src/main/java/org/thingsboard/server/dao/rule/BaseRuleChainService.java
  dao/src/main/java/org/thingsboard/server/dao/sql/notification/JpaNotificationRuleDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/notification/JpaNotificationTargetDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/notification/JpaNotificationTemplateDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/notification/NotificationRuleRepository.java
  dao/src/main/java/org/thingsboard/server/dao/sql/notification/NotificationTargetRepository.java
  dao/src/main/java/org/thingsboard/server/dao/sql/notification/NotificationTemplateRepository.java
  dao/src/main/java/org/thingsboard/server/dao/widget/WidgetsBundleServiceImpl.java
  dao/src/main/resources/sql/schema-entities.sql
  ui-ngx/src/app/core/http/entity.service.ts
  ui-ngx/src/app/core/http/notification.service.ts
  ui-ngx/src/app/modules/home/components/vc/entity-types-version-create.component.html
  ui-ngx/src/app/modules/home/components/vc/entity-types-version-create.component.ts
  ui-ngx/src/app/modules/home/components/vc/entity-types-version-load.component.html
  ui-ngx/src/app/modules/home/components/vc/entity-types-version-load.component.ts
  ui-ngx/src/app/shared/models/entity-type.models.ts
  ui-ngx/src/app/shared/models/notification.models.ts
  ui-ngx/src/app/shared/models/vc.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI, Feature, Core

#8641 Fixed setting time window initialization being called twice
  ui-ngx/src/app/core/services/dashboard-utils.service.ts
  ui-ngx/src/app/modules/home/components/event/event-table.component.ts
  ui-ngx/src/app/shared/components/time/timewindow.component.html
  ui-ngx/src/app/shared/components/time/timewindow.component.ts
  ui-ngx/src/app/shared/models/time/time.models.ts
Labels: Bug, UI

#8645 Fix swagger queue servicetype
  application/src/main/java/org/thingsboard/server/controller/QueueController.java
  application/src/test/java/org/thingsboard/server/controller/BaseQueueControllerTest.java
  common/queue/src/main/java/org/thingsboard/server/queue/discovery/HashPartitionService.java
Labels: Bug

#8597 Fixed tenant profile form text fit
  ui-ngx/src/app/modules/home/components/entity/add-entity-dialog.component.html
  ui-ngx/src/app/modules/home/components/profile/queue/tenant-profile-queues.component.ts
  ui-ngx/src/app/modules/home/components/profile/tenant/default-tenant-profile-configuration.component.html
  ui-ngx/src/app/modules/home/components/queue/queue-form.component.html
Labels: Bug, UI

#8647 Fixed Chart widget legend settings expansion panel
  ui-ngx/src/app/modules/home/components/widget/lib/settings/chart/flot-widget-settings.component.html
Labels: Bug, UI

#8670 Fixed infinite loading alarm table
  ui-ngx/src/app/modules/home/components/alarm/alarm-table-config.ts
Labels: Bug, UI

#8460 migrate to java 17
  application/src/main/java/org/thingsboard/server/service/sync/vc/VersionControlTaskRedisCache.java
  application/src/main/java/org/thingsboard/server/service/sync/vc/autocommit/AutoCommitSettingsRedisCache.java
  application/src/main/java/org/thingsboard/server/service/sync/vc/repository/RepositorySettingsRedisCache.java
  application/src/test/java/org/thingsboard/server/controller/AbstractWebTest.java
  common/cache/src/main/java/org/thingsboard/server/cache/TbJavaRedisSerializer.java
  common/cache/src/main/java/org/thingsboard/server/cache/device/DeviceRedisCache.java
  common/cache/src/main/java/org/thingsboard/server/cache/usersUpdateTime/UsersSessionInvalidationRedisCache.java
  common/data/pom.xml
  common/data/src/main/java/org/thingsboard/server/common/data/JavaSerDesUtil.java
  common/data/src/main/java/org/thingsboard/server/common/data/device/profile/lwm2m/bootstrap/LwM2MServerSecurityConfig.java
  common/data/src/main/java/org/thingsboard/server/common/data/device/profile/lwm2m/bootstrap/NoSecLwM2MBootstrapServerCredential.java
  common/message/src/test/java/org/thingsboard/server/common/msg/TbMsgProcessingStackItemTest.java
  common/queue/src/main/java/org/thingsboard/server/queue/util/JavaDataDecodingEncodingService.java
  common/queue/src/main/java/org/thingsboard/server/queue/util/ProtoWithFSTService.java
  common/script/script-api/pom.xml
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/store/TbLwM2MDtlsSessionRedisStore.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/store/TbLwM2mRedisSecurityStore.java
  dao/src/main/java/org/thingsboard/server/dao/asset/AssetProfileRedisCache.java
  dao/src/main/java/org/thingsboard/server/dao/asset/AssetRedisCache.java
  dao/src/main/java/org/thingsboard/server/dao/dashboard/DashboardTitlesRedisCache.java
  dao/src/main/java/org/thingsboard/server/dao/device/DeviceCredentialsRedisCache.java
  dao/src/main/java/org/thingsboard/server/dao/device/DeviceProfileRedisCache.java
  dao/src/main/java/org/thingsboard/server/dao/edge/EdgeRedisCache.java
  dao/src/main/java/org/thingsboard/server/dao/entity/count/EntityCountRedisCache.java
  dao/src/main/java/org/thingsboard/server/dao/entityview/EntityViewRedisCache.java
  dao/src/main/java/org/thingsboard/server/dao/ota/OtaPackageRedisCache.java
  dao/src/main/java/org/thingsboard/server/dao/relation/RelationRedisCache.java
  dao/src/main/java/org/thingsboard/server/dao/tenant/TenantExistsRedisCache.java
  dao/src/main/java/org/thingsboard/server/dao/tenant/TenantProfileRedisCache.java
  dao/src/main/java/org/thingsboard/server/dao/tenant/TenantRedisCache.java
  dao/src/main/java/org/thingsboard/server/dao/user/UserSettingsRedisCache.java
  msa/monitoring/docker/Dockerfile
  msa/tb-node/docker/Dockerfile
  msa/tb/docker-cassandra/Dockerfile
  msa/tb/docker-postgres/Dockerfile
  msa/transport/coap/docker/Dockerfile
  msa/transport/http/docker/Dockerfile
  msa/transport/lwm2m/docker/Dockerfile
  msa/transport/mqtt/docker/Dockerfile
  msa/transport/snmp/docker/Dockerfile
  msa/vc-executor-docker/docker/Dockerfile
  packaging/java/build.gradle
  packaging/java/scripts/windows/install.bat
  pom.xml
Labels: Core
