Repository thingsboard/thingsboard, pull requests merged in 2023-01, with the labels that each got.

#7925 Added phone number to user profile
  ui-ngx/src/app/core/http/entity.service.ts
  ui-ngx/src/app/modules/home/pages/profile/profile.component.html
  ui-ngx/src/app/modules/home/pages/profile/profile.component.ts
  ui-ngx/src/app/modules/home/pages/user/user.component.html
  ui-ngx/src/app/modules/home/pages/user/user.component.ts
  ui-ngx/src/app/shared/models/user.model.ts
Labels: Ignore for release

#7878 [3.5] Add edge install instructions for docker
  application/src/main/data/json/edge/install_instructions/docker/instructions.md
  application/src/main/data/json/edge/install_instructions/docker/localhost_warning.md
  application/src/main/java/org/thingsboard/server/controller/BaseController.java
  application/src/main/java/org/thingsboard/server/controller/EdgeController.java
  application/src/main/java/org/thingsboard/server/service/edge/instructions/DefaultEdgeInstallService.java
  application/src/main/java/org/thingsboard/server/service/edge/instructions/EdgeInstallService.java
  application/src/test/java/org/thingsboard/server/controller/AbstractWebTest.java
  application/src/test/java/org/thingsboard/server/controller/BaseEdgeControllerTest.java
  common/data/src/main/java/org/thingsboard/server/common/data/edge/EdgeInstallInstructions.java
  rest-client/src/main/java/org/thingsboard/rest/client/RestClient.java
  ui-ngx/src/app/core/http/edge.service.ts
  ui-ngx/src/app/modules/home/pages/edge/edge-instructions-dialog.component.html
  ui-ngx/src/app/modules/home/pages/edge/edge-instructions-dialog.component.ts
  ui-ngx/src/app/modules/home/pages/edge/edge.component.html
  ui-ngx/src/app/modules/home/pages/edge/edge.module.ts
  ui-ngx/src/app/modules/home/pages/edge/edges-table-config.resolver.ts
  ui-ngx/src/app/shared/models/edge.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: Feature, Edge

#7914 [3.5] Added default edge rule chain to asset/device profiles
  application/src/main/java/org/thingsboard/server/install/ThingsboardInstallService.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/constructor/AssetProfileMsgConstructor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/constructor/DeviceMsgConstructor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/constructor/DeviceProfileMsgConstructor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/BaseEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/DeviceEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/RelationEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/TelemetryEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/sync/DefaultEdgeRequestsService.java
  application/src/main/java/org/thingsboard/server/service/install/SqlDatabaseUpgradeService.java
  application/src/test/java/org/thingsboard/server/edge/AbstractEdgeTest.java
  application/src/test/java/org/thingsboard/server/edge/BaseAssetProfileEdgeTest.java
  application/src/test/java/org/thingsboard/server/edge/BaseDeviceEdgeTest.java
  application/src/test/java/org/thingsboard/server/edge/BaseDeviceProfileEdgeTest.java
  common/data/src/main/java/org/thingsboard/server/common/data/DeviceProfile.java
  common/data/src/main/java/org/thingsboard/server/common/data/asset/AssetProfile.java
  common/edge-api/src/main/proto/edge.proto
  dao/src/main/java/org/thingsboard/server/dao/model/ModelConstants.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/AssetProfileEntity.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/DeviceProfileEntity.java
  dao/src/main/resources/sql/schema-entities.sql
  ui-ngx/src/app/modules/home/components/profile/add-device-profile-dialog.component.html
  ui-ngx/src/app/modules/home/components/profile/add-device-profile-dialog.component.ts
  ui-ngx/src/app/modules/home/components/profile/asset-profile.component.html
  ui-ngx/src/app/modules/home/components/profile/asset-profile.component.ts
  ui-ngx/src/app/modules/home/components/profile/device-profile.component.html
  ui-ngx/src/app/modules/home/components/profile/device-profile.component.ts
  ui-ngx/src/app/modules/home/components/rule-chain/rule-chain-autocomplete.component.html
  ui-ngx/src/app/modules/home/components/rule-chain/rule-chain-autocomplete.component.ts
  ui-ngx/src/app/shared/models/asset.models.ts
  ui-ngx/src/app/shared/models/device.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: Feature, Edge

#7929 [3.5] Push public customer to the edge - fixes usage of public dashboards on the edge
  application/src/main/data/upgrade/3.4.3/schema_update.sql
  application/src/main/java/org/thingsboard/server/controller/EntityViewController.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeSyncCursor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/fetch/CustomerEdgeEventFetcher.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/DeviceEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/entitiy/DefaultTbNotificationEntityService.java
  application/src/main/java/org/thingsboard/server/service/entitiy/TbNotificationEntityService.java
  application/src/main/java/org/thingsboard/server/service/entitiy/asset/DefaultTbAssetService.java
  application/src/main/java/org/thingsboard/server/service/entitiy/dashboard/DefaultTbDashboardService.java
  application/src/main/java/org/thingsboard/server/service/entitiy/device/DefaultTbDeviceService.java
  application/src/main/java/org/thingsboard/server/service/entitiy/edge/DefaultTbEdgeService.java
  application/src/main/java/org/thingsboard/server/service/entitiy/entityview/DefaultTbEntityViewService.java
  application/src/main/java/org/thingsboard/server/service/entitiy/entityview/TbEntityViewService.java
  application/src/main/java/org/thingsboard/server/service/install/SqlDatabaseUpgradeService.java
  application/src/test/java/org/thingsboard/server/controller/BaseAssetControllerTest.java
  application/src/test/java/org/thingsboard/server/controller/BaseDashboardControllerTest.java
  application/src/test/java/org/thingsboard/server/controller/BaseDeviceControllerTest.java
  application/src/test/java/org/thingsboard/server/controller/BaseEdgeControllerTest.java
  application/src/test/java/org/thingsboard/server/controller/BaseEntityViewControllerTest.java
  application/src/test/java/org/thingsboard/server/edge/AbstractEdgeTest.java
Labels: Bug, Edge

#7958 Add UI new rule node deduplication
  rule-engine/rule-engine-components/src/main/resources/public/static/rulenode/rulenode-core-config.js
Labels: Ignore for release

#7960 [3.5] Deduplication rule node to master
  application/src/main/java/org/thingsboard/server/actors/ruleChain/DefaultTbContext.java
  rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/TbContext.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/deduplication/DeduplicationId.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/deduplication/DeduplicationStrategy.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/deduplication/TbMsgDeduplicationNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/deduplication/TbMsgDeduplicationNodeConfiguration.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/delay/TbMsgDelayNode.java
  rule-engine/rule-engine-components/src/main/resources/public/static/rulenode/rulenode-core-config.js
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/action/TbMsgDeduplicationNodeTest.java
Labels: Ignore for release

#7963 [3.4.4] fixed js cache
  application/src/main/java/org/thingsboard/server/config/ThingsboardSecurityConfiguration.java
Labels: Bug, Core

#7980 Notification center: Rename target to recipient
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: Ignore for release

#7875 Fix phone input update on save changes
  ui-ngx/src/app/shared/components/phone-input.component.ts
Labels: Bug, UI

#7997 Improvement UI rule node deduplication
  rule-engine/rule-engine-components/src/main/resources/public/static/rulenode/rulenode-core-config.js
Labels: Ignore for release

#7995 [3.4.4] Deduplication rule node improvements
  application/src/main/java/org/thingsboard/server/service/install/DefaultSystemDataLoaderService.java
  application/src/main/java/org/thingsboard/server/service/install/TbRuleEngineQueueConfigService.java
  application/src/main/java/org/thingsboard/server/service/install/update/DefaultDataUpdateService.java
  application/src/test/java/org/thingsboard/server/controller/BaseTenantControllerTest.java
  application/src/test/java/org/thingsboard/server/controller/BaseTenantProfileControllerTest.java
  application/src/test/java/org/thingsboard/server/edge/AbstractEdgeTest.java
  application/src/test/java/org/thingsboard/server/service/queue/DefaultTbClusterServiceTest.java
  application/src/test/java/org/thingsboard/server/service/queue/TbMsgPackProcessingContextTest.java
  common/data/src/main/java/org/thingsboard/server/common/data/DataConstants.java
  common/queue/src/main/java/org/thingsboard/server/queue/discovery/QueueKey.java
  common/queue/src/test/java/org/thingsboard/server/queue/discovery/QueueKeyTest.java
  dao/src/main/java/org/thingsboard/server/dao/service/validator/TenantProfileDataValidator.java
  dao/src/main/java/org/thingsboard/server/dao/sql/queue/JpaQueueDao.java
  dao/src/test/java/org/thingsboard/server/dao/service/BaseQueueServiceTest.java
  dao/src/test/java/org/thingsboard/server/dao/service/BaseTenantProfileServiceTest.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/deduplication/DeduplicationId.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/deduplication/TbMsgDeduplicationNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/deduplication/TbMsgDeduplicationNodeConfiguration.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/transform/TbMsgDeduplicationNodeTest.java
Labels: enhancement

#7873 Fixed when deleting a value in the search field time shows null value
  ui-ngx/src/app/modules/home/components/entity/entities-table.component.ts
Labels: Bug, UI

#7903 Hotfix added gap for widget setting mobile mod and fix translation
  ui-ngx/src/app/modules/home/components/widget/data-keys.component.ts
  ui-ngx/src/app/modules/home/components/widget/widget-config.component.html
Labels: Bug, UI

#8009 [3.4.4] rollback "tellFailure" logic change in TbAbstractGetAttributesNode
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/metadata/TbAbstractGetAttributesNode.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/metadata/TbAbstractGetAttributesNodeTest.java
Labels: Bug, Rule Engine

#8002 [3.4.4] Fix data convertion for BigInteger values that stored in DB as String
  dao/src/main/java/org/thingsboard/server/dao/sql/query/EntityDataAdapter.java
  dao/src/test/java/org/thingsboard/server/dao/sql/query/EntityDataAdapterTest.java
Labels: Bug

#7951 Queue autocomplete add input hint
  ui-ngx/src/app/shared/components/queue/queue-autocomplete.component.html
  ui-ngx/src/app/shared/components/queue/queue-autocomplete.component.scss
  ui-ngx/src/app/shared/components/queue/queue-autocomplete.component.ts
Labels: UI, Feature

#8010 Fixed auto-indexing for keys with aggregation
  ui-ngx/src/app/core/utils.ts
  ui-ngx/src/app/modules/home/components/widget/data-key-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/widget-config.component.ts
Labels: Bug, UI

#7884 Update locale.constant-zh_TW.json
  ui-ngx/src/assets/locale/locale.constant-zh_TW.json
Labels: UI

#8012 Fixed applying custom translation to labels of latest data keys in timeseries widgets
  ui-ngx/src/app/core/api/widget-subscription.ts
Labels: Bug, UI

#8013 Fixed error on loading custom widgets module withing dashboard state component
  ui-ngx/src/app/modules/dashboard/dashboard-pages.routing.module.ts
  ui-ngx/src/app/modules/home/components/home-components.module.ts
  ui-ngx/src/app/modules/home/pages/home-pages.module.ts
Labels: Bug, UI
