Repository thingsboard/thingsboard, pull requests merged in 2023-09, with the labels that each got.

#9104 Notification to sysadmin when default JWT signing key is used
  application/src/main/java/org/thingsboard/server/config/CryptoConfig.java
  application/src/main/java/org/thingsboard/server/config/ThingsboardSecurityConfiguration.java
  application/src/main/java/org/thingsboard/server/service/notification/DefaultNotificationCenter.java
  application/src/main/java/org/thingsboard/server/service/security/auth/jwt/settings/DefaultJwtSettingsService.java
  application/src/main/java/org/thingsboard/server/service/security/system/DefaultSystemSecurityService.java
  application/src/test/java/org/thingsboard/server/service/notification/AbstractNotificationApiTest.java
  application/src/test/java/org/thingsboard/server/service/notification/NotificationApiTest.java
  application/src/test/java/org/thingsboard/server/service/security/auth/JwtTokenFactoryTest.java
  dao/src/main/java/org/thingsboard/server/dao/notification/DefaultNotifications.java
  rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/NotificationCenter.java
Labels: Ignore for release

#9162 fix math node default config argument name issue because UI have strict order of arguments
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/math/TbMathNodeConfiguration.java
Labels: Bug, Rule Engine

#9150 Improved timewindow position
  ui-ngx/src/app/core/services/utils.service.ts
  ui-ngx/src/app/modules/home/components/alarm/alarm-filter-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/alarms-table-widget.component.ts
  ui-ngx/src/app/shared/components/popover.component.ts
  ui-ngx/src/app/shared/components/popover.models.ts
  ui-ngx/src/app/shared/components/time/quick-time-interval.component.scss
  ui-ngx/src/app/shared/components/time/timewindow.component.ts
  ui-ngx/src/app/shared/models/overlay.models.ts
  ui-ngx/src/app/shared/models/public-api.ts
Labels: enhancement, UI, Ignore for release

#9164 Fixed set disabled state for rule node configuration
  ui-ngx/src/app/modules/home/pages/rulechain/rule-node-config.component.ts
  ui-ngx/src/app/shared/models/rule-node.models.ts
Labels: Bug, UI, Ignore for release

#9165 Fixed widget shacking
  ui-ngx/src/app/modules/home/components/dashboard/dashboard.component.ts
Labels: Bug, UI

#9166 Fixed blur icon in value card widget in vertical layout
  ui-ngx/src/app/modules/home/components/widget/lib/cards/value-card-widget.component.scss
Labels: Bug, UI, Ignore for release

#9167 Fix for entities table config 'Display entity label column' input disabled
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/entities-table-widget-settings.component.html
Labels: Bug, UI, Ignore for release

#9170 Fixed pipes in modules map
  ui-ngx/src/app/modules/common/modules-map.ts
Labels: enhancement, UI, Ignore for release

#9172 Fix for pie flot widget slice click action
  ui-ngx/src/app/modules/home/components/widget/lib/flot-widget.ts
Labels: Bug, UI

#9173 Update required error text for the entity type select
  ui-ngx/src/app/shared/components/entity/entity-type-list.component.html
  ui-ngx/src/assets/locale/locale.constant-ca_ES.json
  ui-ngx/src/assets/locale/locale.constant-cs_CZ.json
  ui-ngx/src/assets/locale/locale.constant-da_DK.json
  ui-ngx/src/assets/locale/locale.constant-de_DE.json
  ui-ngx/src/assets/locale/locale.constant-el_GR.json
  ui-ngx/src/assets/locale/locale.constant-en_US.json
  ui-ngx/src/assets/locale/locale.constant-es_ES.json
  ui-ngx/src/assets/locale/locale.constant-fa_IR.json
  ui-ngx/src/assets/locale/locale.constant-fr_FR.json
  ui-ngx/src/assets/locale/locale.constant-it_IT.json
  ui-ngx/src/assets/locale/locale.constant-ja_JP.json
  ui-ngx/src/assets/locale/locale.constant-ka_GE.json
  ui-ngx/src/assets/locale/locale.constant-ko_KR.json
  ui-ngx/src/assets/locale/locale.constant-lv_LV.json
  ui-ngx/src/assets/locale/locale.constant-pt_BR.json
  ui-ngx/src/assets/locale/locale.constant-ro_RO.json
  ui-ngx/src/assets/locale/locale.constant-ru_RU.json
  ui-ngx/src/assets/locale/locale.constant-sl_SI.json
  ui-ngx/src/assets/locale/locale.constant-tr_TR.json
  ui-ngx/src/assets/locale/locale.constant-uk_UA.json
  ui-ngx/src/assets/locale/locale.constant-zh_CN.json
  ui-ngx/src/assets/locale/locale.constant-zh_TW.json
Labels: enhancement, UI

#9174 Updated rule node after delete unnecessary component
  rule-engine/rule-engine-components/src/main/resources/public/static/rulenode/rulenode-core-config.js
Labels: UI, Rule Engine, Ignore for release

#9177 Validation for pie flot common settings
  ui-ngx/src/app/modules/home/components/widget/lib/settings/chart/flot-pie-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/chart/flot-pie-widget-settings.component.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI

#9180 Fixed show hint in custom property for queue settings
  ui-ngx/src/app/modules/home/components/queue/queue-form.component.html
Labels: Bug, UI, Ignore for release

#9157 Fix tenant profile update msg construction for Edge
  common/data/src/main/java/org/thingsboard/server/common/data/queue/ProcessingStrategy.java
  common/data/src/main/java/org/thingsboard/server/common/data/queue/SubmitStrategy.java
  dao/src/test/java/org/thingsboard/server/dao/service/TenantProfileServiceTest.java
Labels: Ignore for release

#9186 Fixed widget import in the dashboard when the duplicate IDs
  ui-ngx/src/app/modules/home/components/import-export/import-export.service.ts
Labels: Bug, UI

#9191 download cert improvements
  application/src/test/java/org/thingsboard/server/controller/DeviceConnectivityControllerTest.java
  dao/src/main/java/org/thingsboard/server/dao/device/DeviceConnectivityConfiguration.java
  dao/src/main/java/org/thingsboard/server/dao/device/DeviceConnectivityServiceImpl.java
Labels: Ignore for release

#9204 Fix for get attributes nodes upgrade when fetchToData is null
  application/src/main/java/org/thingsboard/server/service/install/update/DefaultDataUpdateService.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/metadata/TbAbstractGetAttributesNode.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/metadata/TbGetAttributesNodeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/metadata/TbGetDeviceAttrNodeTest.java
Labels: Bug, Rule Engine

#9184 Fixed doubled error message for missing translate
  ui-ngx/src/app/core/translate/missing-translate-handler.ts
Labels: enhancement, UI

#9203 Fixed min height with hint for alarm rule key filters row
  ui-ngx/src/app/modules/home/components/filter/filter-predicate-list.component.html
  ui-ngx/src/app/modules/home/components/filter/key-filter-list.component.html
Labels: Bug, UI

#9205 Fixed auth service function updatedAuthUserFromToken when authUser and tokenData in null
  ui-ngx/src/app/core/auth/auth.service.ts
Labels: Bug, UI, Ignore for release

#9213 Add Server-side Checks for Default Dashboard and Rule Chain on Edge Versions < 3.6.0
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/BaseEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/asset/AssetEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/asset/AssetProfileEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/device/DeviceEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/device/DeviceProfileEdgeProcessor.java
  application/src/test/java/org/thingsboard/server/service/edge/rpc/processor/BaseEdgeProcessorTest.java
  application/src/test/java/org/thingsboard/server/service/edge/rpc/processor/asset/AbstractAssetProcessorTest.java
  application/src/test/java/org/thingsboard/server/service/edge/rpc/processor/asset/AssetEdgeProcessorTest.java
  application/src/test/java/org/thingsboard/server/service/edge/rpc/processor/asset/AssetProfileEdgeProcessorTest.java
  application/src/test/java/org/thingsboard/server/service/edge/rpc/processor/device/AbstractDeviceProcessorTest.java
  application/src/test/java/org/thingsboard/server/service/edge/rpc/processor/device/DeviceEdgeProcessorTest.java
  application/src/test/java/org/thingsboard/server/service/edge/rpc/processor/device/DeviceProfileEdgeProcessorTest.java
  common/edge-api/src/main/java/org/thingsboard/edge/rpc/EdgeGrpcClient.java
  common/edge-api/src/main/proto/edge.proto
Labels: Edge, Ignore for release

#9216 Fix Widget Display Issues in Older Edge Versions Connected to 3.6 Servers
  application/src/main/java/org/thingsboard/server/service/edge/rpc/constructor/WidgetTypeMsgConstructor.java
  application/src/test/java/org/thingsboard/server/edge/WidgetEdgeTest.java
  common/edge-api/src/main/proto/edge.proto
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: Edge, Ignore for release

#9224 added executor to speed up rule nodes upgrade & added SQL upgrade for TbMsgAttributesNode & updated logback.xml with new debug entry to view the rule node upgrade logs
  application/src/main/java/org/thingsboard/server/service/install/SqlDatabaseUpgradeService.java
  application/src/main/java/org/thingsboard/server/service/install/update/DefaultDataUpdateService.java
  application/src/main/resources/logback.xml
Labels: Build Scripts

#9219 Fix Edge Downlink Table Errors and Add Support for RAW Values
  ui-ngx/src/app/modules/home/components/edge/edge-downlink-table-config.ts
  ui-ngx/src/app/shared/models/edge.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: Bug, UI, Ignore for release

#9218 Fixed add telemetry dialog validation hints
  ui-ngx/src/app/modules/home/components/attribute/add-attribute-dialog.component.html
  ui-ngx/src/app/modules/home/components/attribute/add-attribute-dialog.component.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: Bug, UI, Ignore for release

#9240 Add singletonMode and configurationVersion Fields to Edge RuleNodeProto
  application/src/main/java/org/thingsboard/server/service/edge/rpc/constructor/rule/AbstractRuleChainMetadataConstructor.java
  application/src/test/java/org/thingsboard/server/edge/RuleChainEdgeTest.java
  common/edge-api/src/main/proto/edge.proto
Labels: Edge, Ignore for release

#9237 fixed alarm severity change
  common/data/src/main/java/org/thingsboard/server/common/data/alarm/AlarmModificationRequest.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/action/TbAlarmResult.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/profile/TbDeviceProfileNodeTest.java
Labels: Bug, Core

#9248 Isolated queues: fix partitions recalculation
  application/src/main/java/org/thingsboard/server/service/queue/DefaultTbRuleEngineConsumerService.java
  application/src/test/java/org/thingsboard/server/queue/discovery/HashPartitionServiceTest.java
  common/queue/src/main/java/org/thingsboard/server/queue/discovery/HashPartitionService.java
Labels: Ignore for release

#9245 Edge instructions for ubuntu, centos
  application/src/main/data/json/edge/install_instructions/centos/instructions.md
  application/src/main/data/json/edge/install_instructions/docker/instructions.md
  application/src/main/data/json/edge/install_instructions/ubuntu/instructions.md
  application/src/main/java/org/thingsboard/server/controller/EdgeController.java
  application/src/main/java/org/thingsboard/server/service/edge/instructions/DefaultEdgeInstallService.java
  application/src/main/java/org/thingsboard/server/service/edge/instructions/EdgeInstallService.java
  application/src/test/java/org/thingsboard/server/controller/EdgeControllerTest.java
  common/data/src/main/java/org/thingsboard/server/common/data/edge/EdgeInstallInstructions.java
  ui-ngx/src/app/core/http/edge.service.ts
  ui-ngx/src/app/modules/home/pages/edge/edge-instructions-dialog.component.html
  ui-ngx/src/app/modules/home/pages/edge/edge-instructions-dialog.component.scss
  ui-ngx/src/app/modules/home/pages/edge/edge-instructions-dialog.component.ts
  ui-ngx/src/app/modules/home/pages/edge/edges-table-config.resolver.ts
  ui-ngx/src/app/shared/models/edge.models.ts
  ui-ngx/src/app/shared/models/user-settings.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: Edge

#9247 Bug fix/table cell global style
  ui-ngx/src/styles.scss
Labels: Bug, UI, Ignore for release

#9254 Added notification popover loadings state
  ui-ngx/src/app/modules/home/components/notification/show-notification-popover.component.html
  ui-ngx/src/app/modules/home/components/notification/show-notification-popover.component.ts
  ui-ngx/src/app/shared/models/websocket/notification-ws.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI

#9259 Fix restoreFocus to dynamic created components within mat-dialog
  ui-ngx/src/app/core/core.module.ts
Labels: enhancement, UI

#9260 Added default color for mat-hint; Added onTouch event for string items list component
  ui-ngx/src/app/shared/components/string-items-list.component.html
  ui-ngx/src/app/shared/components/string-items-list.component.ts
  ui-ngx/src/theme-overwrites.scss
Labels: enhancement, UI, Ignore for release

#9264 Remove initial name from datasource
  ui-ngx/src/app/core/services/dashboard-utils.service.ts
Labels: Bug, UI, Ignore for release

#9257 PartitionService improvements
  application/src/main/java/org/thingsboard/server/actors/service/DefaultActorService.java
  application/src/main/java/org/thingsboard/server/service/queue/DefaultTbRuleEngineConsumerService.java
  application/src/test/java/org/thingsboard/server/queue/discovery/HashPartitionServiceTest.java
  application/src/test/java/org/thingsboard/server/service/state/DefaultDeviceStateServiceTest.java
  common/message/src/main/java/org/thingsboard/server/common/msg/queue/PartitionChangeMsg.java
  common/queue/src/main/java/org/thingsboard/server/queue/discovery/HashPartitionService.java
  common/queue/src/main/java/org/thingsboard/server/queue/discovery/event/PartitionChangeEvent.java
Labels: Ignore for release

#9273 Added SNMP_ENABLED=false for install edge instructions in case TB is …
  application/src/main/data/json/edge/install_instructions/centos/instructions.md
  application/src/main/data/json/edge/install_instructions/ubuntu/instructions.md
Labels: Ignore for release

#9269 Edge tests stability improvements
  application/src/test/java/org/thingsboard/server/edge/AbstractEdgeTest.java
  application/src/test/java/org/thingsboard/server/edge/AssetEdgeTest.java
  application/src/test/java/org/thingsboard/server/edge/CustomerEdgeTest.java
  application/src/test/java/org/thingsboard/server/edge/DashboardEdgeTest.java
  application/src/test/java/org/thingsboard/server/edge/DeviceEdgeTest.java
  application/src/test/java/org/thingsboard/server/edge/EdgeTest.java
  application/src/test/java/org/thingsboard/server/edge/EntityViewEdgeTest.java
  application/src/test/java/org/thingsboard/server/edge/RuleChainEdgeTest.java
  application/src/test/java/org/thingsboard/server/edge/UserEdgeTest.java
  application/src/test/java/org/thingsboard/server/edge/imitator/EdgeImitator.java
  application/src/test/resources/application-test.properties
  dao/src/test/resources/sql/system-test-psql.sql
Labels: Ignore for release

#9263 Edge install instructions minor updates
  ui-ngx/src/app/modules/home/pages/edge/edge-instructions-dialog.component.scss
Labels: enhancement, UI, Edge

#9281 Minor gateway fixes
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-configuration.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-configuration.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-configuration.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-connectors.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-widget.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: Bug, UI, Ignore for release

#9276 Fixed add widget mode for widget bundles
  ui-ngx/src/app/modules/home/pages/widget/widgets-bundle-widgets.component.ts
Labels: Bug, UI, Ignore for release

#9275 Fixed toggle node library button for safari
  ui-ngx/src/app/modules/home/pages/rulechain/rulechain-page.component.scss
Labels: Bug, UI, Ignore for release

#9283 Updated rule node ui
  rule-engine/rule-engine-components/src/main/resources/public/static/rulenode/rulenode-core-config.js
Labels: UI, Rule Engine, Ignore for release

#9285 Add type "button" for help popup
  ui-ngx/src/app/shared/components/help-popup.component.html
Labels: enhancement, UI, Ignore for release

#9287 Fix missed style for delete timeseries panel
  ui-ngx/src/app/modules/home/components/attribute/delete-timeseries-panel.component.scss
Labels: Bug, UI, Ignore for release

#9288 Fixed notifications dialog
  ui-ngx/src/app/modules/home/pages/notification/sent/sent-notification-dialog.component.html
  ui-ngx/src/app/modules/home/pages/notification/sent/sent-notification-dialog.componet.ts
  ui-ngx/src/app/modules/home/pages/notification/template/template-notification-dialog.component.html
  ui-ngx/src/app/modules/home/pages/notification/template/template-notification-dialog.component.ts
Labels: enhancement, UI, Ignore for release

#9289 Add support import widgets bundles in old format
  ui-ngx/src/app/modules/home/components/import-export/import-export.service.ts
Labels: enhancement, UI, Ignore for release

#9290 Fixed padding for image input
  ui-ngx/src/app/shared/components/image-input.component.scss
Labels: enhancement, UI, Ignore for release

#9294 Updated db schema version from 3.5.2 to 3.6.0
  application/src/main/java/org/thingsboard/server/service/install/SqlDatabaseUpgradeService.java
  dao/src/main/resources/sql/schema-entities.sql
Labels: Ignore for release

#9286 fixed delete all types from widgets bundle
  dao/src/main/java/org/thingsboard/server/dao/service/Validator.java
  dao/src/main/java/org/thingsboard/server/dao/widget/WidgetTypeServiceImpl.java
  dao/src/test/java/org/thingsboard/server/dao/service/WidgetTypeServiceTest.java
Labels: Ignore for release

#9298 Fixed entity table fields overlaying
  ui-ngx/src/styles.scss
Labels: Bug, UI

#9299 Changed order of fetchers to sent tenant profile to the cloud as firs…
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeSyncCursor.java
  application/src/test/java/org/thingsboard/server/edge/TenantProfileEdgeTest.java
Labels: Bug, Ignore for release

#9306 Added api rate limits for tbel
  application/src/main/data/upgrade/3.6.0/schema_update.sql
  application/src/main/java/org/thingsboard/server/service/apiusage/BaseApiUsageState.java
  application/src/main/java/org/thingsboard/server/service/install/SqlDatabaseUpgradeService.java
  application/src/main/java/org/thingsboard/server/service/mail/DefaultMailService.java
  application/src/test/java/org/thingsboard/server/controller/HomePageApiTest.java
  common/data/src/main/java/org/thingsboard/server/common/data/ApiFeature.java
  common/data/src/main/java/org/thingsboard/server/common/data/ApiUsageRecordKey.java
  common/data/src/main/java/org/thingsboard/server/common/data/ApiUsageState.java
  common/data/src/main/java/org/thingsboard/server/common/data/UsageInfo.java
  common/data/src/main/java/org/thingsboard/server/common/data/tenant/profile/DefaultTenantProfileConfiguration.java
  common/script/script-api/src/main/java/org/thingsboard/script/api/AbstractScriptInvokeService.java
  common/script/script-api/src/main/java/org/thingsboard/script/api/js/AbstractJsInvokeService.java
  common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/DefaultTbelInvokeService.java
  dao/src/main/java/org/thingsboard/server/dao/model/ModelConstants.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/ApiUsageStateEntity.java
  dao/src/main/java/org/thingsboard/server/dao/usage/BasicUsageInfoService.java
  dao/src/main/java/org/thingsboard/server/dao/usagerecord/ApiUsageStateServiceImpl.java
  dao/src/main/resources/sql/schema-entities.sql
  ui-ngx/src/styles.scss
Labels: Core

#9337 Implement widgets bundles / widgets full search.
  application/src/main/data/upgrade/3.6.0/schema_update.sql
  application/src/main/java/org/thingsboard/server/controller/WidgetTypeController.java
  application/src/main/java/org/thingsboard/server/controller/WidgetsBundleController.java
  application/src/main/java/org/thingsboard/server/install/ThingsboardInstallService.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/constructor/WidgetTypeMsgConstructor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/fetch/SystemWidgetTypesEdgeEventFetcher.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/fetch/SystemWidgetsBundlesEdgeEventFetcher.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/fetch/TenantWidgetTypesEdgeEventFetcher.java
  application/src/main/java/org/thingsboard/server/service/install/DefaultSystemDataLoaderService.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/widget/WidgetTypeService.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/widget/WidgetsBundleService.java
  common/data/src/main/java/org/thingsboard/server/common/data/widget/DeprecatedFilter.java
  common/data/src/main/java/org/thingsboard/server/common/data/widget/WidgetTypeDetails.java
  common/data/src/main/java/org/thingsboard/server/common/data/widget/WidgetTypeInfo.java
  common/edge-api/src/main/proto/edge.proto
  dao/src/main/java/org/thingsboard/server/dao/model/ModelConstants.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/WidgetTypeDetailsEntity.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/WidgetTypeInfoEntity.java
  dao/src/main/java/org/thingsboard/server/dao/sql/widget/JpaWidgetTypeDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/widget/JpaWidgetsBundleDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/widget/WidgetTypeInfoRepository.java
  dao/src/main/java/org/thingsboard/server/dao/sql/widget/WidgetTypeRepository.java
  dao/src/main/java/org/thingsboard/server/dao/sql/widget/WidgetsBundleRepository.java
  dao/src/main/java/org/thingsboard/server/dao/util/mapping/AbstractArrayType.java
  dao/src/main/java/org/thingsboard/server/dao/util/mapping/AbstractArrayTypeDescriptor.java
  dao/src/main/java/org/thingsboard/server/dao/util/mapping/ArraySqlTypeDescriptor.java
  dao/src/main/java/org/thingsboard/server/dao/util/mapping/ArrayUtil.java
  dao/src/main/java/org/thingsboard/server/dao/util/mapping/ParameterizedParameterType.java
  dao/src/main/java/org/thingsboard/server/dao/util/mapping/StringArrayType.java
  dao/src/main/java/org/thingsboard/server/dao/util/mapping/StringArrayTypeDescriptor.java
  dao/src/main/java/org/thingsboard/server/dao/widget/WidgetTypeDao.java
  dao/src/main/java/org/thingsboard/server/dao/widget/WidgetTypeServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/widget/WidgetsBundleDao.java
  dao/src/main/java/org/thingsboard/server/dao/widget/WidgetsBundleServiceImpl.java
  dao/src/main/resources/sql/schema-entities.sql
  dao/src/main/resources/sql/schema-views-and-functions.sql
  dao/src/test/java/org/thingsboard/server/dao/service/WidgetsBundleServiceTest.java
  dao/src/test/java/org/thingsboard/server/dao/sql/widget/JpaWidgetTypeDaoTest.java
  dao/src/test/java/org/thingsboard/server/dao/sql/widget/JpaWidgetsBundleDaoTest.java
  ui-ngx/src/app/core/http/entity.service.ts
  ui-ngx/src/app/core/http/widget.service.ts
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.html
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.ts
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-widget-select.component.html
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-widget-select.component.scss
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-widget-select.component.ts
  ui-ngx/src/app/modules/home/components/grid/scroll-grid.component.html
  ui-ngx/src/app/modules/home/components/grid/scroll-grid.component.scss
  ui-ngx/src/app/modules/home/components/grid/scroll-grid.component.ts
  ui-ngx/src/app/modules/home/components/home-components.module.ts
  ui-ngx/src/app/modules/home/models/datasource/scroll-grid-datasource.ts
  ui-ngx/src/app/modules/home/models/widget-component.models.ts
  ui-ngx/src/app/modules/home/pages/widget/widget-editor.component.html
  ui-ngx/src/app/modules/home/pages/widget/widget-library-routing.module.ts
  ui-ngx/src/app/modules/home/pages/widget/widget-type.component.html
  ui-ngx/src/app/modules/home/pages/widget/widget-type.component.ts
  ui-ngx/src/app/modules/home/pages/widget/widgets-bundle-widgets.component.ts
  ui-ngx/src/app/shared/models/widget.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI, Core
