Repository thingsboard/thingsboard, pull requests merged in 2023-07, with the labels that each got.

#8878 User notification settings by notification type
  ui-ngx/src/app/modules/home/pages/notification/settings/notification-setting-form.component.html
  ui-ngx/src/app/modules/home/pages/notification/settings/notification-setting-form.component.ts
  ui-ngx/src/app/modules/home/pages/notification/settings/notification-settings.component.ts
  ui-ngx/src/app/shared/models/notification.models.ts
Labels: Ignore for release

#8881 fixed saveDeviceWithCredentials api
  application/src/main/java/org/thingsboard/server/controller/DeviceController.java
  application/src/test/java/org/thingsboard/server/controller/DeviceControllerTest.java
  common/data/src/main/java/org/thingsboard/server/common/data/SaveDeviceWithCredentialsRequest.java
  dao/src/main/java/org/thingsboard/server/dao/device/DeviceServiceImpl.java
Labels: Bug, Core

#8879 Update cource Decorators
  ui-ngx/src/app/shared/decorators/coercion.ts
Labels: Bug, UI

#8884 Fixed device transport configuration with SNMP protocol enabled/disabled state
  ui-ngx/src/app/modules/home/pages/device/data/device-transport-configuration.component.ts
  ui-ngx/src/app/modules/home/pages/device/data/snmp-device-transport-configuration.component.ts
Labels: Bug, UI

#8897 Move form table style from data key to form.scss
  ui-ngx/src/app/modules/home/components/widget/config/basic/common/data-key-row.component.html
  ui-ngx/src/app/modules/home/components/widget/config/basic/common/data-key-row.component.scss
  ui-ngx/src/app/modules/home/components/widget/config/basic/common/data-keys-panel.component.html
  ui-ngx/src/app/modules/home/components/widget/config/basic/common/data-keys-panel.component.scss
  ui-ngx/src/form.scss
Labels: enhancement, UI, Ignore for release

#8929 Improvement for entity autocomplete
  ui-ngx/src/app/shared/components/entity/entity-autocomplete.component.ts
Labels: enhancement, UI, Ignore for release

#8916 Added on unit input to show the clear button when hovering the element
  ui-ngx/src/app/shared/components/unit-input.component.html
  ui-ngx/src/form.scss
Labels: enhancement, UI, Ignore for release

#8836 Added ability to test/edit rule node script with selected debug event
  ui-ngx/src/app/core/services/script/node-script-test.service.ts
  ui-ngx/src/app/modules/home/components/entity/entities-table.component.ts
  ui-ngx/src/app/modules/home/components/event/event-table-config.ts
  ui-ngx/src/app/modules/home/components/event/event-table.component.ts
  ui-ngx/src/app/modules/home/models/entity/entity-table-component.models.ts
  ui-ngx/src/app/modules/home/pages/rulechain/rule-node-config.component.ts
  ui-ngx/src/app/modules/home/pages/rulechain/rule-node-details.component.html
  ui-ngx/src/app/modules/home/pages/rulechain/rule-node-details.component.ts
  ui-ngx/src/app/modules/home/pages/rulechain/rulechain-page.component.html
  ui-ngx/src/app/modules/home/pages/rulechain/rulechain-page.component.ts
  ui-ngx/src/app/shared/models/rule-node.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI, Feature

#8906 Fixed user phone display in entities table
  dao/src/main/java/org/thingsboard/server/dao/sql/query/DefaultEntityQueryRepository.java
  dao/src/test/java/org/thingsboard/server/dao/service/EntityServiceTest.java
Labels: Bug, Core

#8898 Resource deletion validation
  application/src/main/java/org/thingsboard/server/service/resource/DefaultTbResourceService.java
  application/src/test/java/org/thingsboard/server/controller/TbResourceControllerTest.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/widget/WidgetTypeService.java
  dao/src/main/java/org/thingsboard/server/dao/resource/BaseResourceService.java
  dao/src/main/java/org/thingsboard/server/dao/service/DataValidator.java
  dao/src/main/java/org/thingsboard/server/dao/service/validator/ResourceDataValidator.java
  dao/src/main/java/org/thingsboard/server/dao/sql/widget/JpaWidgetTypeDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/widget/WidgetTypeRepository.java
  dao/src/main/java/org/thingsboard/server/dao/widget/WidgetTypeDao.java
  dao/src/main/java/org/thingsboard/server/dao/widget/WidgetTypeServiceImpl.java
Labels: enhancement, Core

#8957 Fix for custom translation in inbox notifications table
  ui-ngx/src/app/modules/home/pages/notification/inbox/inbox-table-config.resolver.ts
Labels: Bug, UI

#8951 Fix for notification rules page
  ui-ngx/src/app/modules/home/pages/notification/rule/rule-table-config.resolver.ts
  ui-ngx/src/app/shared/models/notification.models.ts
Labels: Bug, UI

#8904 Added ng-content to js-func conponent
  ui-ngx/src/app/shared/components/js-func.component.html
Labels: enhancement, UI, Ignore for release

#8894 Add option collapse cell actions in mobile view for entities/timeseries/alarm table
  ui-ngx/src/app/modules/home/components/entity/entities-table.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/alarms-table-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/alarms-table-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/entities-table-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/entities-table-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/alarm/alarms-table-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/alarm/alarms-table-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/entities-table-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/entities-table-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/timeseries-table-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/timeseries-table-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/table-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/timeseries-table-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/timeseries-table-widget.component.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI

#8939 Add units models
  ui-ngx/src/app/shared/components/unit-input.component.ts
  ui-ngx/src/app/shared/models/unit.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
  ui-ngx/src/assets/model/units.json
Labels: enhancement, UI, Ignore for release

#8968 Fix for update JSON attribute input widget required time-series data key instead attribute key
  application/src/main/data/json/system/widget_bundles/input_widgets.json
Labels: Bug, UI

#8961 LegendComponent show cursor pointer on hover
  ui-ngx/src/app/modules/home/components/widget/lib/legend.component.scss
Labels: enhancement, UI

#8960 Widget Entities Table: show pointer if row has click action
  ui-ngx/src/app/modules/home/components/widget/lib/alarms-table-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/alarms-table-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/entities-table-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/entities-table-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/timeseries-table-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/timeseries-table-widget.component.ts
Labels: enhancement, UI

#8966 Change field label assign customer
  ui-ngx/src/app/modules/home/components/wizard/device-wizard-dialog.component.html
  ui-ngx/src/assets/locale/locale.constant-ca_ES.json
  ui-ngx/src/assets/locale/locale.constant-cs_CZ.json
  ui-ngx/src/assets/locale/locale.constant-da_DK.json
  ui-ngx/src/assets/locale/locale.constant-en_US.json
  ui-ngx/src/assets/locale/locale.constant-es_ES.json
  ui-ngx/src/assets/locale/locale.constant-fr_FR.json
  ui-ngx/src/assets/locale/locale.constant-ko_KR.json
  ui-ngx/src/assets/locale/locale.constant-sl_SI.json
  ui-ngx/src/assets/locale/locale.constant-tr_TR.json
  ui-ngx/src/assets/locale/locale.constant-zh_CN.json
  ui-ngx/src/assets/locale/locale.constant-zh_TW.json
Labels: enhancement, UI, Ignore for release

#8987 Fixed alarm filter panel
  ui-ngx/src/app/modules/home/components/alarm/alarm-filter-config.component.html
  ui-ngx/src/app/modules/home/components/alarm/alarm-filter-config.component.scss
Labels: Bug, UI

#8997 Add double quotes to highlight 'remove other entities' confirm phrase in version control dialog
  ui-ngx/src/assets/locale/locale.constant-ca_ES.json
  ui-ngx/src/assets/locale/locale.constant-en_US.json
  ui-ngx/src/assets/locale/locale.constant-es_ES.json
  ui-ngx/src/assets/locale/locale.constant-zh_CN.json
  ui-ngx/src/assets/locale/locale.constant-zh_TW.json
Labels: enhancement, UI

#8775 added recalculatePartitions delay for node restarting
  application/src/main/resources/thingsboard.yml
  common/queue/src/main/java/org/thingsboard/server/queue/discovery/ZkDiscoveryService.java
  common/queue/src/test/java/org/thingsboard/server/queue/discovery/ZkDiscoveryServiceTest.java
  msa/vc-executor/src/main/resources/tb-vc-executor.yml
  transport/coap/src/main/resources/tb-coap-transport.yml
  transport/http/src/main/resources/tb-http-transport.yml
  transport/lwm2m/src/main/resources/tb-lwm2m-transport.yml
  transport/mqtt/src/main/resources/tb-mqtt-transport.yml
  transport/snmp/src/main/resources/tb-snmp-transport.yml
Labels: enhancement, Core

#8911 Redesign user menu
  ui-ngx/src/app/core/auth/auth.service.ts
  ui-ngx/src/app/modules/home/components/router-tabs.component.html
  ui-ngx/src/app/modules/home/components/router-tabs.component.ts
  ui-ngx/src/app/modules/home/pages/account/account-routing.module.ts
  ui-ngx/src/app/modules/home/pages/account/account.module.ts
  ui-ngx/src/app/modules/home/pages/home-pages.module.ts
  ui-ngx/src/app/modules/home/pages/profile/profile-routing.module.ts
  ui-ngx/src/app/modules/home/pages/security/security-routing.module.ts
  ui-ngx/src/app/shared/components/user-menu.component.html
  ui-ngx/src/app/shared/components/user-menu.component.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI, Feature

#9015 Enabled test with this message for OUT messages with errors
  ui-ngx/src/app/modules/home/components/event/event-table-config.ts
Labels: enhancement, UI, Ignore for release

#8938 Added check connectivity in device
  application/src/main/java/org/thingsboard/server/config/ThingsboardSecurityConfiguration.java
  application/src/main/java/org/thingsboard/server/controller/ControllerConstants.java
  application/src/main/java/org/thingsboard/server/controller/DeviceConnectivityController.java
  application/src/main/resources/thingsboard.yml
  application/src/test/java/org/thingsboard/server/controller/DeviceConnectivityControllerTest.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/device/DeviceConnectivityService.java
  dao/src/main/java/org/thingsboard/server/dao/device/DeviceConnectivityConfiguration.java
  dao/src/main/java/org/thingsboard/server/dao/device/DeviceConnectivityInfo.java
  dao/src/main/java/org/thingsboard/server/dao/device/DeviceConnectivityServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/util/DeviceConnectivityUtil.java
  ui-ngx/src/app/app.component.ts
  ui-ngx/src/app/core/auth/auth.actions.ts
  ui-ngx/src/app/core/auth/auth.effects.ts
  ui-ngx/src/app/core/auth/auth.reducer.ts
  ui-ngx/src/app/core/auth/auth.selectors.ts
  ui-ngx/src/app/core/http/device.service.ts
  ui-ngx/src/app/core/utils.ts
  ui-ngx/src/app/modules/home/components/wizard/device-wizard-dialog.component.ts
  ui-ngx/src/app/modules/home/pages/device/device-check-connectivity-dialog.component.html
  ui-ngx/src/app/modules/home/pages/device/device-check-connectivity-dialog.component.scss
  ui-ngx/src/app/modules/home/pages/device/device-check-connectivity-dialog.component.ts
  ui-ngx/src/app/modules/home/pages/device/device.component.html
  ui-ngx/src/app/modules/home/pages/device/device.module.ts
  ui-ngx/src/app/modules/home/pages/device/devices-table-config.resolver.ts
  ui-ngx/src/app/shared/models/device.models.ts
  ui-ngx/src/app/shared/models/icon.models.ts
  ui-ngx/src/app/shared/models/user-settings.models.ts
  ui-ngx/src/assets/docker.svg
  ui-ngx/src/assets/linux.svg
  ui-ngx/src/assets/locale/locale.constant-en_US.json
  ui-ngx/src/assets/macos.svg
  ui-ngx/src/assets/windows.svg
  ui-ngx/src/form.scss
  ui-ngx/src/typings/utils.d.ts
Labels: UI, Feature
