Repository thingsboard/thingsboard, pull requests merged in 2023-08, with the labels that each got.

#9018 Refactoring User notification settings
  ui-ngx/src/app/core/services/menu.service.ts
  ui-ngx/src/app/modules/home/menu/side-menu.component.ts
  ui-ngx/src/app/modules/home/pages/account/account-routing.module.ts
  ui-ngx/src/app/modules/home/pages/notification/notification.module.ts
  ui-ngx/src/app/modules/home/pages/notification/settings/notification-settings-routing.modules.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI, Ignore for release

#9020 Refactoring of delete timeseries ui
  ui-ngx/src/app/modules/home/components/attribute/attribute-table.component.html
  ui-ngx/src/app/modules/home/components/attribute/attribute-table.component.ts
  ui-ngx/src/app/modules/home/components/attribute/delete-timeseries-panel.component.html
  ui-ngx/src/app/modules/home/components/attribute/delete-timeseries-panel.component.scss
  ui-ngx/src/app/modules/home/components/attribute/delete-timeseries-panel.component.ts
Labels: enhancement, UI, Ignore for release

#8965 Fixed entity select component for alias dialog component
  ui-ngx/src/app/shared/components/entity/entity-select.component.ts
Labels: Bug, UI

#9034 Fixed resize alarm filter config component
  ui-ngx/src/app/core/services/utils.service.ts
  ui-ngx/src/app/modules/home/components/alarm/alarm-filter-config.component.html
  ui-ngx/src/app/modules/home/components/alarm/alarm-filter-config.component.scss
  ui-ngx/src/app/modules/home/components/alarm/alarm-filter-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/alarms-table-widget.component.ts
Labels: Bug, UI, Ignore for release

#9056 UI event table speedup config (15min default time window), ms in time for events
  ui-ngx/src/app/modules/home/components/event/event-table-config.ts
Labels: enhancement, UI, Core

#9043 Aligned phone input flags container by input field
  ui-ngx/src/app/shared/components/phone-input.component.scss
Labels: enhancement, UI

#9003 Added dialog for creation latest telemetry key value
  ui-ngx/src/app/modules/home/components/attribute/add-attribute-dialog.component.html
  ui-ngx/src/app/modules/home/components/attribute/add-attribute-dialog.component.ts
  ui-ngx/src/app/modules/home/components/attribute/attribute-table.component.html
  ui-ngx/src/app/modules/home/components/attribute/attribute-table.component.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI, Feature

#9060 Fixed layout for clear alarm rule
  ui-ngx/src/app/modules/home/components/profile/alarm/device-profile-alarm.component.scss
Labels: Bug, UI

#9061 updated recalculate_delay
  application/src/main/resources/thingsboard.yml
  common/queue/src/main/java/org/thingsboard/server/queue/discovery/ZkDiscoveryService.java
  msa/vc-executor/src/main/resources/tb-vc-executor.yml
  transport/coap/src/main/resources/tb-coap-transport.yml
  transport/http/src/main/resources/tb-http-transport.yml
  transport/lwm2m/src/main/resources/tb-lwm2m-transport.yml
  transport/mqtt/src/main/resources/tb-mqtt-transport.yml
  transport/snmp/src/main/resources/tb-snmp-transport.yml
Labels: Ignore for release

#9071 Updated default config for math node
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/math/TbMathNodeConfiguration.java
Labels: enhancement, Rule Engine

#9073 fix CoAP over DTLS feature type handling for server-side rpc response
  common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/CoapTransportResource.java
  common/transport/coap/src/test/java/org/thingsboard/server/transport/coap/CoapTransportResourceTest.java
Labels: Bug, Major Transport

#8880 Updated components that using in enrichment/filter rule nodes
  ui-ngx/src/app/modules/home/components/relation/relation-filters.component.html
  ui-ngx/src/app/modules/home/components/relation/relation-filters.component.scss
  ui-ngx/src/app/modules/home/components/widget/config/basic/common/data-key-row.component.html
  ui-ngx/src/app/modules/home/components/widget/config/basic/common/data-keys-panel.component.html
  ui-ngx/src/app/modules/home/pages/rulechain/add-rule-node-dialog.component.scss
  ui-ngx/src/app/modules/home/pages/rulechain/rule-node-details.component.scss
  ui-ngx/src/app/shared/components/entity/entity-subtype-list.component.html
  ui-ngx/src/app/shared/components/entity/entity-subtype-list.component.ts
  ui-ngx/src/app/shared/components/entity/entity-type-list.component.html
  ui-ngx/src/app/shared/components/entity/entity-type-list.component.ts
  ui-ngx/src/app/shared/components/help-popup.component.html
  ui-ngx/src/app/shared/components/help-popup.component.scss
  ui-ngx/src/app/shared/components/help-popup.component.ts
  ui-ngx/src/app/shared/components/relation/relation-type-autocomplete.component.html
  ui-ngx/src/app/shared/components/relation/relation-type-autocomplete.component.ts
  ui-ngx/src/app/shared/components/string-items-list.component.html
  ui-ngx/src/assets/locale/locale.constant-en_US.json
  ui-ngx/src/form.scss
  ui-ngx/src/styles.scss
Labels: enhancement, UI, Rule Engine

#9037 Added selection to alarms table for bulk acknowledgement and clearing
  ui-ngx/src/app/core/http/alarm.service.ts
  ui-ngx/src/app/modules/home/components/alarm/alarm-table-config.ts
  ui-ngx/src/app/modules/home/components/widget/lib/alarms-table-widget.component.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI

#9065 Added internalType field to TbMsg to have the ability to use switch-cases instead of if-return blocks.
  common/data/src/main/java/org/thingsboard/server/common/data/msg/TbMsgType.java
  common/data/src/test/java/org/thingsboard/server/common/data/msg/TbMsgTypeTest.java
  common/message/src/main/java/org/thingsboard/server/common/msg/TbMsg.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/filter/TbMsgTypeSwitchNode.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/filter/TbMsgTypeSwitchNodeTest.java
Labels: enhancement, Rule Engine

#8841 fixed update inactivity timeout attribute
  application/src/main/java/org/thingsboard/server/service/state/DefaultDeviceStateService.java
  application/src/test/java/org/thingsboard/server/service/state/DefaultDeviceStateServiceTest.java
Labels: Bug, Core

#9089 Fixes for Version Control
  application/src/main/java/org/thingsboard/server/service/sync/ie/DefaultEntitiesExportImportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/exporting/impl/BaseEntityExportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/exporting/impl/DashboardExportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/exporting/impl/RuleChainExportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/BaseEntityImportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/DashboardImportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/RuleChainImportService.java
  application/src/main/java/org/thingsboard/server/service/sync/vc/DefaultGitVersionControlQueueService.java
  application/src/main/resources/thingsboard.yml
  application/src/test/java/org/thingsboard/server/service/sync/ie/ExportImportServiceSqlTest.java
  common/util/src/main/java/org/thingsboard/common/util/JacksonUtil.java
  common/version-control/src/main/java/org/thingsboard/server/service/sync/vc/DefaultClusterVersionControlService.java
  msa/vc-executor/src/main/resources/tb-vc-executor.yml
Labels: Bug, Core

#9080 Update flot lib
  ui-ngx/yarn.lock
Labels: enhancement, UI, Ignore for release

#9081 Update device connectivity HTTP/MQTT install for MacOS
  ui-ngx/src/app/modules/home/pages/device/device-check-connectivity-dialog.component.html
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: Bug, Ignore for release

#9021 Improvement search in the platform added ignore space symbols in the start and end search text
  ui-ngx/src/app/modules/home/components/attribute/attribute-table.component.html
  ui-ngx/src/app/modules/home/components/attribute/attribute-table.component.ts
  ui-ngx/src/app/modules/home/components/entity/entities-table.component.html
  ui-ngx/src/app/modules/home/components/entity/entities-table.component.ts
  ui-ngx/src/app/modules/home/components/relation/relation-table.component.html
  ui-ngx/src/app/modules/home/components/relation/relation-table.component.ts
  ui-ngx/src/app/modules/home/components/vc/entity-versions-table.component.html
  ui-ngx/src/app/modules/home/components/vc/entity-versions-table.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/alarms-table-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/alarms-table-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/entities-hierarchy-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/entities-hierarchy-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/entities-table-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/entities-table-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/timeseries-table-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/timeseries-table-widget.component.ts
  ui-ngx/src/app/modules/home/home.component.html
  ui-ngx/src/app/modules/home/home.component.ts
  ui-ngx/src/app/modules/home/pages/rulechain/rulechain-page.component.html
  ui-ngx/src/app/modules/home/pages/rulechain/rulechain-page.component.ts
  ui-ngx/src/app/shared/models/page/page-link.ts
Labels: enhancement, UI

#9096 Rename selector matSuffix in entity-subtype-list.component
  ui-ngx/src/app/shared/components/entity/entity-subtype-list.component.html
Labels: enhancement, UI, Ignore for release

#9100 Rule node UI: redesign filter enrichment nodes
  rule-engine/rule-engine-components/src/main/resources/public/static/rulenode/rulenode-core-config.js
Labels: enhancement, UI, Rule Engine, Ignore for release

#9091 Edge Attribute Request processing - added support of JSON attributes
  application/src/main/java/org/thingsboard/server/service/edge/rpc/sync/DefaultEdgeRequestsService.java
  application/src/test/java/org/thingsboard/server/edge/DeviceEdgeTest.java
Labels: Ignore for release

#9098 Fixed padding for multiple input widget
  ui-ngx/src/app/modules/home/components/widget/lib/multiple-input-widget.component.scss
Labels: enhancement, UI, Ignore for release

#9102 Timeseries table widget columns display fixed columns name
  ui-ngx/src/app/modules/home/components/widget/lib/timeseries-table-widget.component.ts
Labels: Bug, UI, Ignore for release

#9106 Remove Microsoft teams from Notification settings
  ui-ngx/src/app/modules/home/pages/notification/settings/notification-settings.component.ts
Labels: Bug, UI, Ignore for release

#9116 Remove close search fields in entities table when empty
  ui-ngx/src/app/modules/home/components/entity/entities-table.component.ts
Labels: Bug, UI, Ignore for release

#9122 Fix event table rule node event table columns overlap
  ui-ngx/src/app/modules/home/components/event/event-table-config.ts
Labels: enhancement, UI

#9121 Increased reserved space for hidden action cell buttons
  ui-ngx/src/app/modules/home/components/widget/lib/alarms-table-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/entities-table-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/timeseries-table-widget.component.html
Labels: enhancement, UI

#9120 Added missing translation for tenant profile details
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI, Ignore for release

#9001 Added type email for input
  ui-ngx/src/app/modules/home/pages/profile/profile.component.html
  ui-ngx/src/app/modules/home/pages/user/user.component.html
  ui-ngx/src/app/shared/components/contact.component.html
Labels: enhancement, UI

#9117 Update label logic for relation-type-autocomplete
  ui-ngx/src/app/modules/home/components/relation/relation-filters.component.html
  ui-ngx/src/app/shared/components/relation/relation-type-autocomplete.component.html
  ui-ngx/src/app/shared/components/relation/relation-type-autocomplete.component.ts
Labels: Bug, UI, Ignore for release

#9126 Fix for 'remove other entities' popover in version control
  ui-ngx/src/app/modules/home/components/vc/entity-types-version-load.component.ts
Labels: Bug, UI

#8767 Fixed widgets table styles for correct applying row style function
  ui-ngx/src/app/modules/home/components/widget/lib/alarms-table-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/entities-table-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/table-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/timeseries-table-widget.component.html
  ui-ngx/src/styles.scss
Labels: Bug, UI

#9068 Fixed infinite loading for latest widgets with aggregation on change timewindow
  ui-ngx/src/app/core/api/entity-data-subscription.ts
  ui-ngx/src/app/core/api/widget-subscription.ts
  ui-ngx/src/app/shared/models/telemetry/telemetry.models.ts
Labels: Bug, UI

#9125 Fixed showing exit dialog twice on dashboard page
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.ts
Labels: Bug, UI, Ignore for release

#9123 Fix for showing disabled form controls in rule nodes
  ui-ngx/src/app/modules/home/pages/rulechain/add-rule-node-dialog.component.html
  ui-ngx/src/app/modules/home/pages/rulechain/rule-node-config.component.scss
  ui-ngx/src/app/modules/home/pages/rulechain/rule-node-config.component.ts
  ui-ngx/src/app/modules/home/pages/rulechain/rule-node-details.component.html
  ui-ngx/src/app/modules/home/pages/rulechain/rule-node-details.component.ts
  ui-ngx/src/app/modules/home/pages/rulechain/rulechain-page.component.html
  ui-ngx/src/app/shared/models/rule-node.models.ts
Labels: Bug, UI, Rule Engine

#8931 Improvement for Add asset dialog
  ui-ngx/src/app/modules/home/components/profile/asset-profile-autocomplete.component.html
  ui-ngx/src/app/modules/home/components/profile/asset-profile-autocomplete.component.scss
  ui-ngx/src/app/modules/home/components/profile/asset-profile-autocomplete.component.ts
  ui-ngx/src/app/modules/home/components/profile/device-profile-autocomplete.component.html
  ui-ngx/src/app/modules/home/components/profile/device-profile-autocomplete.component.ts
  ui-ngx/src/app/modules/home/components/wizard/device-wizard-dialog.component.ts
  ui-ngx/src/app/modules/home/pages/asset/asset.component.html
  ui-ngx/src/app/modules/home/pages/asset/asset.component.ts
Labels: enhancement, UI

#9136 Fixed show/hide action and style timeseries table widgets
  ui-ngx/src/app/core/utils.ts
  ui-ngx/src/app/modules/home/components/widget/lib/timeseries-table-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/timeseries-table-widget.component.ts
  ui-ngx/src/styles.scss
Labels: Bug, UI, Ignore for release

#9133 Improve device connectivity dialog
  ui-ngx/src/app/modules/home/pages/device/device-check-connectivity-dialog.component.html
  ui-ngx/src/app/modules/home/pages/device/device-check-connectivity-dialog.component.ts
  ui-ngx/src/app/modules/home/pages/device/devices-table-config.resolver.ts
Labels: enhancement, UI, Ignore for release

#9138 Update locale.constant-zh_CN.json
  ui-ngx/src/assets/locale/locale.constant-zh_CN.json
Labels: UI, Ignore for release

#9143 Added reserved space for skipped rows in GPIO panel widgets
  application/src/main/data/json/system/widget_bundles/gpio_widgets.json
Labels: Bug, UI
