Repository thingsboard/thingsboard, pull requests merged in 2023-03, with the labels that each got.

#8163 Feature/alarm rule entity state store
  application/src/main/data/upgrade/3.4.4/schema_update.sql
  application/src/main/java/org/thingsboard/server/service/alarm/rule/DefaultTbAlarmRuleStateService.java
  application/src/main/java/org/thingsboard/server/service/alarm/rule/EntityState.java
  application/src/main/java/org/thingsboard/server/service/alarm/rule/TbAlarmRuleContext.java
  application/src/main/java/org/thingsboard/server/service/alarm/rule/state/PersistedEntityState.java
  application/src/main/java/org/thingsboard/server/service/alarm/rule/store/AlarmRuleEntityStateStore.java
  application/src/main/java/org/thingsboard/server/service/alarm/rule/store/DummyAlarmRuleEntityStateStore.java
  application/src/main/java/org/thingsboard/server/service/alarm/rule/store/RedisAlarmRuleEntityStateStore.java
  application/src/main/java/org/thingsboard/server/service/install/SqlDatabaseUpgradeService.java
  application/src/test/java/org/thingsboard/server/service/alarm/rule/DefaultTbAlarmRuleStateServiceTest.java
  common/cache/src/main/java/org/thingsboard/server/cache/RedisUtil.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/alarm/rule/AlarmRuleEntityStateService.java
  common/data/src/main/java/org/thingsboard/server/common/data/alarm/rule/AlarmRuleEntityState.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/store/TbLwM2mRedisRegistrationStore.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/store/TbRedisLwM2MClientStore.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/store/TbRedisLwM2MModelConfigStore.java
  dao/src/main/java/org/thingsboard/server/dao/alarm/rule/AlarmRuleDao.java
  dao/src/main/java/org/thingsboard/server/dao/alarm/rule/AlarmRuleEntityStateDao.java
  dao/src/main/java/org/thingsboard/server/dao/alarm/rule/BaseAlarmRuleEntityStateService.java
  dao/src/main/java/org/thingsboard/server/dao/model/ModelConstants.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/AlarmRuleEntityStateEntity.java
  dao/src/main/java/org/thingsboard/server/dao/sql/alarm/rule/AlarmRuleEntityStateRepository.java
  dao/src/main/java/org/thingsboard/server/dao/sql/alarm/rule/AlarmRuleRepository.java
  dao/src/main/java/org/thingsboard/server/dao/sql/alarm/rule/JpaAlarmRuleDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/alarm/rule/JpaAlarmRuleEntityStateDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/query/DefaultEntityQueryRepository.java
  dao/src/main/resources/sql/schema-entities.sql
  dao/src/test/java/org/thingsboard/server/dao/service/AbstractServiceTest.java
  dao/src/test/java/org/thingsboard/server/dao/service/BaseAlarmRuleEntityStateServiceTest.java
  dao/src/test/java/org/thingsboard/server/dao/service/BaseEntityServiceTest.java
  dao/src/test/resources/sql/psql/drop-all-tables.sql
Labels: Ignore for release

#8119 alarm rule queues implementations
  application/src/main/resources/thingsboard.yml
  common/queue/src/main/java/org/thingsboard/server/queue/azure/servicebus/TbServiceBusQueueConfigs.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/AwsSqsMonolithQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/AwsSqsTbCoreQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/AwsSqsTbRuleEngineQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/PubSubMonolithQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/PubSubTbCoreQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/PubSubTbRuleEngineQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/RabbitMqMonolithQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/RabbitMqTbCoreQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/RabbitMqTbRuleEngineQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/ServiceBusMonolithQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/ServiceBusTbCoreQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/ServiceBusTbRuleEngineQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/pubsub/TbPubSubSubscriptionSettings.java
  common/queue/src/main/java/org/thingsboard/server/queue/rabbitmq/TbRabbitMqQueueArguments.java
  common/queue/src/main/java/org/thingsboard/server/queue/sqs/TbAwsSqsQueueAttributes.java
Labels: Ignore for release

#8170 UI: Updated ngx-translate-messageformat-compiler for latest value
  ui-ngx/angular.json
  ui-ngx/package.json
  ui-ngx/src/app/core/translate/translate-default-compiler.ts
  ui-ngx/src/assets/locale/locale.constant-ca_ES.json
  ui-ngx/src/assets/locale/locale.constant-cs_CZ.json
  ui-ngx/src/assets/locale/locale.constant-da_DK.json
  ui-ngx/src/assets/locale/locale.constant-de_DE.json
  ui-ngx/src/assets/locale/locale.constant-el_GR.json
  ui-ngx/src/assets/locale/locale.constant-en_US.json
  ui-ngx/src/assets/locale/locale.constant-es_ES.json
  ui-ngx/src/assets/locale/locale.constant-fa_IR.json
  ui-ngx/src/assets/locale/locale.constant-fr_FR.json
  ui-ngx/src/assets/locale/locale.constant-it_IT.json
  ui-ngx/src/assets/locale/locale.constant-ja_JP.json
  ui-ngx/src/assets/locale/locale.constant-ka_GE.json
  ui-ngx/src/assets/locale/locale.constant-ko_KR.json
  ui-ngx/src/assets/locale/locale.constant-lv_LV.json
  ui-ngx/src/assets/locale/locale.constant-pt_BR.json
  ui-ngx/src/assets/locale/locale.constant-ro_RO.json
  ui-ngx/src/assets/locale/locale.constant-ru_RU.json
  ui-ngx/src/assets/locale/locale.constant-sl_SI.json
  ui-ngx/src/assets/locale/locale.constant-tr_TR.json
  ui-ngx/src/assets/locale/locale.constant-uk_UA.json
  ui-ngx/src/assets/locale/locale.constant-zh_CN.json
  ui-ngx/src/assets/locale/locale.constant-zh_TW.json
  ui-ngx/yarn.lock
Labels: UI, Ignore for release

#8203 sendUpdateSharedAttributeToCloudAndValidateDeviceSubscription - timeo…
  application/src/test/java/org/thingsboard/server/edge/BaseDeviceEdgeTest.java
Labels: Ignore for release

#8216 Updated alarm comment deletion logic
  application/src/main/java/org/thingsboard/server/controller/AlarmCommentController.java
  application/src/main/java/org/thingsboard/server/controller/ControllerConstants.java
  application/src/main/java/org/thingsboard/server/service/entitiy/alarm/DefaultTbAlarmCommentService.java
  application/src/main/java/org/thingsboard/server/service/entitiy/alarm/TbAlarmCommentService.java
  application/src/test/java/org/thingsboard/server/controller/BaseAlarmCommentControllerTest.java
  application/src/test/java/org/thingsboard/server/service/entitiy/alarmComment/DefaultTbAlarmCommentServiceTest.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/alarm/AlarmCommentService.java
  dao/src/main/java/org/thingsboard/server/dao/alarm/BaseAlarmCommentService.java
  dao/src/test/java/org/thingsboard/server/dao/service/BaseAlarmCommentServiceTest.java
  rest-client/src/main/java/org/thingsboard/rest/client/RestClient.java
Labels: Ignore for release

#8245 [3.5]fixed upgrade schema update
  application/src/main/data/upgrade/3.4.4/schema_update.sql
  application/src/main/java/org/thingsboard/server/service/install/SqlDatabaseUpgradeService.java
Labels: Ignore for release

#8253 [3.5] added assignee check for alarm
  application/src/main/java/org/thingsboard/server/controller/AlarmController.java
  application/src/main/java/org/thingsboard/server/service/entitiy/alarm/DefaultTbAlarmService.java
  application/src/test/java/org/thingsboard/server/controller/AbstractWebTest.java
  application/src/test/java/org/thingsboard/server/controller/BaseAlarmControllerTest.java
Labels: Ignore for release

#8257 [3.5] fix logic in procedure for drop ts_kv partitions by ttl
  application/src/main/data/upgrade/3.4.4/schema_update.sql
  dao/src/main/java/org/thingsboard/server/dao/sqlts/sql/JpaSqlTimeseriesDao.java
  dao/src/main/resources/sql/schema-ts-psql.sql
Labels: Ignore for release

#8258 Move rule chains menu link in top level
  ui-ngx/src/app/core/services/menu.service.ts
  ui-ngx/src/app/modules/home/pages/features/features-routing.module.ts
  ui-ngx/src/app/modules/home/pages/rulechain/rulechain-routing.module.ts
  ui-ngx/src/app/shared/models/entity-type.models.ts
Labels: UI, Feature, Ignore for release

#8062 Refactoring time window component
  ui-ngx/src/app/shared/components/time/timewindow-panel.component.html
  ui-ngx/src/app/shared/components/time/timewindow-panel.component.scss
  ui-ngx/src/app/shared/components/time/timewindow-panel.component.ts
  ui-ngx/src/app/shared/components/time/timewindow.component.html
  ui-ngx/src/app/shared/components/time/timewindow.component.ts
Labels: Bug, UI

#7780 Refactoring form array
  ui-ngx/src/app/modules/home/components/filter/filter-predicate-list.component.html
  ui-ngx/src/app/modules/home/components/filter/filter-predicate-list.component.ts
  ui-ngx/src/app/modules/home/components/filter/key-filter-list.component.html
  ui-ngx/src/app/modules/home/components/filter/key-filter-list.component.ts
  ui-ngx/src/app/modules/home/components/profile/alarm/create-alarm-rules.component.ts
  ui-ngx/src/app/modules/home/components/profile/alarm/device-profile-alarms.component.html
  ui-ngx/src/app/modules/home/components/profile/alarm/device-profile-alarms.component.ts
  ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-attributes-key-list.component.ts
  ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-bootstrap-config-servers.component.html
  ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-bootstrap-config-servers.component.ts
  ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-observe-attr-telemetry-instances.component.ts
  ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-observe-attr-telemetry-resources.component.ts
  ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-observe-attr-telemetry.component.ts
  ui-ngx/src/app/modules/home/components/profile/device/snmp/snmp-device-profile-communication-config.component.html
  ui-ngx/src/app/modules/home/components/profile/device/snmp/snmp-device-profile-communication-config.component.ts
  ui-ngx/src/app/modules/home/components/profile/device/snmp/snmp-device-profile-mapping.component.html
  ui-ngx/src/app/modules/home/components/profile/device/snmp/snmp-device-profile-mapping.component.ts
  ui-ngx/src/app/modules/home/components/profile/queue/tenant-profile-queues.component.ts
  ui-ngx/src/app/modules/home/components/relation/relation-filters.component.html
  ui-ngx/src/app/modules/home/components/relation/relation-filters.component.ts
  ui-ngx/src/app/shared/components/kv-map.component.ts
Labels: UI

#7823 Fixed different size sort header arrow
  ui-ngx/src/app/modules/home/components/widget/lib/table-widget.models.ts
Labels: Bug, UI

#7926 Exclude specified subtypes from autocomplete widget.
  ui-ngx/src/app/shared/components/entity/entity-autocomplete.component.ts
  ui-ngx/src/app/shared/components/entity/entity-subtype-autocomplete.component.html
  ui-ngx/src/app/shared/components/entity/entity-subtype-autocomplete.component.ts
Labels: UI, Feature

#8017 Add quarter and half year intervals to time window.
  ui-ngx/src/app/shared/models/time/time.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI, Feature

#8057 Leave only lower bould for widget's height in mobile mode.
  ui-ngx/src/app/modules/home/components/widget/widget-config.component.html
  ui-ngx/src/app/modules/home/components/widget/widget-config.component.ts
Labels: UI, Feature

#8071 Add Base64 functions to Utils service.
  ui-ngx/src/app/core/services/utils.service.ts
Labels: UI, Feature

#8118 'Horizontal bar' widget displays incorrectly decimal values that ends with zeros
  ui-ngx/src/app/modules/home/components/widget/lib/digital-gauge.ts
Labels: Bug, UI

#8167 Added hint to the "Password / access token" input (Repository settings)
  ui-ngx/src/app/modules/home/components/vc/repository-settings.component.html
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI, Feature

#8255 Added "delete" icon to the default icon list
  ui-ngx/src/app/core/services/utils.service.ts
Labels: UI, Feature

#7625 Add dashboard filter duplication option
  ui-ngx/src/app/modules/home/components/filter/filters-dialog.component.html
  ui-ngx/src/app/modules/home/components/filter/filters-dialog.component.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI, Feature

#8266 Sparkplug ui
  ui-ngx/src/app/modules/home/components/profile/device/mqtt-device-profile-transport-configuration.component.html
  ui-ngx/src/app/modules/home/components/profile/device/mqtt-device-profile-transport-configuration.component.ts
  ui-ngx/src/app/shared/components/string-items-list.component.html
  ui-ngx/src/app/shared/components/string-items-list.component.ts
Labels: UI, Ignore for release

#8272 Refactoring dashborad-select component
  ui-ngx/src/app/shared/components/dashboard-select.component.ts
Labels: enhancement, UI

#8267 Fix locales for tenan profile field "REST requests for tenant"
  ui-ngx/src/app/modules/home/components/profile/tenant/rate-limits/rate-limits.models.ts
  ui-ngx/src/assets/locale/locale.constant-ca_ES.json
  ui-ngx/src/assets/locale/locale.constant-cs_CZ.json
  ui-ngx/src/assets/locale/locale.constant-da_DK.json
  ui-ngx/src/assets/locale/locale.constant-en_US.json
  ui-ngx/src/assets/locale/locale.constant-es_ES.json
  ui-ngx/src/assets/locale/locale.constant-ko_KR.json
  ui-ngx/src/assets/locale/locale.constant-sl_SI.json
  ui-ngx/src/assets/locale/locale.constant-tr_TR.json
  ui-ngx/src/assets/locale/locale.constant-zh_CN.json
  ui-ngx/src/assets/locale/locale.constant-zh_TW.json
Labels: Bug, UI

#8278 [3.5]minor ui fixes
  ui-ngx/src/app/shared/components/entity/entity-subtype-autocomplete.component.ts
Labels: Ignore for release

#8277 [3.5]fixed system info updates
  application/src/main/java/org/thingsboard/server/service/system/DefaultSystemInfoService.java
  common/queue/src/main/java/org/thingsboard/server/queue/discovery/DefaultTbServiceInfoProvider.java
  common/queue/src/main/java/org/thingsboard/server/queue/discovery/TbServiceInfoProvider.java
  common/queue/src/main/java/org/thingsboard/server/queue/discovery/ZkDiscoveryService.java
Labels: Ignore for release

#8281 [3.5]minor tests fixes
  application/src/main/java/org/thingsboard/server/service/subscription/DefaultTbEntityDataSubscriptionService.java
  application/src/test/java/org/thingsboard/server/controller/BaseHomePageApiTest.java
  application/src/test/java/org/thingsboard/server/service/notification/NotificationApiTest.java
Labels: Ignore for release

#8292 Fixer RP: Optionally update dashboard state when using navigate back API
  ui-ngx/src/app/core/api/widget-api.models.ts
  ui-ngx/src/app/modules/home/components/dashboard-page/states/default-state-controller.component.ts
  ui-ngx/src/app/modules/home/components/dashboard-page/states/entity-state-controller.component.ts
  ui-ngx/src/app/modules/home/components/dashboard-page/states/state-controller.component.ts
Labels: enhancement, UI, Ignore for release

#8072 Optionally update dashboard state when using navigate back API.
  ui-ngx/src/app/modules/home/components/dashboard-page/states/default-state-controller.component.ts
  ui-ngx/src/app/modules/home/components/dashboard-page/states/entity-state-controller.component.ts
  ui-ngx/src/app/modules/home/components/dashboard-page/states/state-controller.component.ts
Labels: enhancement, UI

#8287 API version 3 support has been added to HERE map widget
  application/src/main/data/json/system/widget_bundles/maps.json
  ui-ngx/src/app/modules/home/components/widget/lib/maps/map-models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/maps/providers/here-map.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/map/here-map-provider-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/map/here-map-provider-settings.component.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI, Feature
