Repository thingsboard/thingsboard, pull requests merged in 2023-11, with the labels that each got.

#9457 Device connectivity settings move in UI
  application/src/main/java/org/thingsboard/server/install/ThingsboardInstallService.java
  application/src/main/java/org/thingsboard/server/service/install/DefaultSystemDataLoaderService.java
  application/src/main/java/org/thingsboard/server/service/install/update/DefaultDataUpdateService.java
  application/src/test/java/org/thingsboard/server/controller/DeviceConnectivityControllerTest.java
  application/src/test/java/org/thingsboard/server/controller/DeviceConnectivityControllerWithDefaultPortTest.java
  dao/src/main/java/org/thingsboard/server/dao/device/DeviceConnectivityConfiguration.java
  dao/src/main/java/org/thingsboard/server/dao/device/DeviceConnectivityInfo.java
  dao/src/main/java/org/thingsboard/server/dao/device/DeviceConnectivityServiceImpl.java
  dao/src/test/resources/sql/system-data.sql
  ui-ngx/src/app/modules/home/pages/admin/general-settings.component.html
  ui-ngx/src/app/modules/home/pages/admin/general-settings.component.scss
  ui-ngx/src/app/modules/home/pages/admin/general-settings.component.ts
  ui-ngx/src/app/shared/models/settings.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI, Core

#9539 connectivity upgrade fix
  application/src/main/java/org/thingsboard/server/service/install/update/DefaultDataUpdateService.java
Labels: Ignore for release

#9545 syncEdgeTest fix. testFindTenantWidgetsBundlesByPageLink - cleanup system widgets
  application/src/test/java/org/thingsboard/server/controller/WidgetsBundleControllerTest.java
Labels: Ignore for release

#9410 fixed device active/inactive widgets in home-page
  ui-ngx/src/assets/dashboard/customer_user_home_page.json
  ui-ngx/src/assets/dashboard/tenant_admin_home_page.json
Labels: Bug

#9558 fixed getUsersForAssign if originator was removed
  application/src/main/java/org/thingsboard/server/controller/UserController.java
  application/src/test/java/org/thingsboard/server/controller/UserControllerTest.java
Labels: Bug, Core

#9251 Fix of error not displaying in dashboard force fullscreen mode
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.html
Labels: Bug, UI

#9510 Fix for timeseries charts validation blocks widget adding
  ui-ngx/src/app/modules/home/components/widget/config/datasources.component.ts
Labels: Bug, UI

#9511 Fixed alarm type list width and empty option
  ui-ngx/src/app/modules/home/components/alarm/alarm-filter-config.component.scss
  ui-ngx/src/app/shared/components/entity/entity-subtype-list.component.html
  ui-ngx/src/app/shared/components/entity/entity-subtype-list.component.ts
Labels: enhancement, UI

#9517 Fixed width of alarm rule for device profile dialog
  ui-ngx/src/app/modules/home/components/profile/add-device-profile-dialog.component.scss
Labels: enhancement, UI

#9522 Fixed display column panel in table widgets for scrolling long list columns
  ui-ngx/src/app/modules/home/components/widget/lib/alarm/alarms-table-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/display-columns-panel.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/entity/entities-table-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/timeseries-table-widget.component.ts
  ui-ngx/src/styles.scss
Labels: enhancement, UI

#9533 Fixed alarm table basic settings columns error appearense and anomaly with changeDetection
  ui-ngx/src/app/modules/home/components/widget/config/basic/alarm/alarms-table-basic-config.component.html
  ui-ngx/src/app/shared/components/tb-error.component.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: Bug, UI

#9556 Refactoring event filter panel
  ui-ngx/src/app/modules/home/components/event/event-filter-panel.component.html
  ui-ngx/src/app/modules/home/components/event/event-filter-panel.component.scss
  ui-ngx/src/app/modules/home/components/event/event-table-config.ts
Labels: enhancement, UI

#9567 Fixed updated value in markdown input component and refactoring this component
  ui-ngx/src/app/shared/components/markdown-editor.component.ts
Labels: Bug, UI

#9568 Fixed range list basic settings analog gauge
  ui-ngx/src/app/modules/home/components/widget/config/basic/gauge/analog-gauge-basic-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/gauge/analogue-compass-widget-settings.component.html
Labels: Bug, UI, Ignore for release

#9569 Improved usability of bulk operations in alarm widget table
  ui-ngx/src/app/modules/home/components/alarm/alarm-table-config.ts
  ui-ngx/src/app/modules/home/components/widget/lib/alarm/alarms-table-widget.component.ts
  ui-ngx/src/app/shared/models/alarm.models.ts
Labels: enhancement, UI

#9571 Change dashboard add widget panel width
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.scss
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-widget-select.component.ts
Labels: Bug, UI, Ignore for release

#9503 Fixed version control Widgets/Widget bundles entity list
  ui-ngx/src/app/core/http/entity.service.ts
  ui-ngx/src/app/core/http/widget.service.ts
Labels: Bug, UI

#9581 Added support basic settings form of custom widgets
  ui-ngx/src/app/modules/home/components/public-api.ts
  ui-ngx/src/app/modules/home/components/widget/widget-component.service.ts
Labels: enhancement, UI

#9583 Hide display buttons activation link and resend activation when user activated
  ui-ngx/src/app/modules/home/pages/user/user.component.html
  ui-ngx/src/app/modules/home/pages/user/user.component.ts
Labels: Bug, UI

#9585 fixed query timeout exception
  application/src/main/java/org/thingsboard/server/controller/AuditLogController.java
Labels: enhancement, Core

#9584 Updated rulenode-core-config.js
  rule-engine/rule-engine-components/src/main/resources/public/static/rulenode/rulenode-core-config.js
Labels: Ignore for release

#9582 Added logging in case edge test failed on initial check
  application/src/test/java/org/thingsboard/server/edge/AbstractEdgeTest.java
Labels: Ignore for release

#9586 fixed get lwm2m resources
  application/src/test/java/org/thingsboard/server/controller/TbResourceControllerTest.java
  dao/src/main/java/org/thingsboard/server/dao/sql/resource/TbResourceRepository.java
Labels: Ignore for release

#9595 Fixed updated show value and toltip in liquid level widget
  ui-ngx/src/app/modules/home/components/widget/lib/indicator/liquid-level-widget.component.ts
Labels: Bug, UI, Ignore for release

#9598 Admin Edge Fetcher updates. Resource Edge Processor updates.
  application/src/main/java/org/thingsboard/server/service/edge/EdgeContextComponent.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeSyncCursor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/fetch/AdminSettingsEdgeEventFetcher.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/BaseEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/alarm/AlarmEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/relation/RelationEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/resource/BaseResourceProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/resource/ResourceEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/utils/EdgeVersionUtils.java
  application/src/main/java/org/thingsboard/server/service/queue/DefaultTbClusterService.java
  application/src/main/java/org/thingsboard/server/service/queue/ProtoUtils.java
  application/src/test/java/org/thingsboard/server/controller/EdgeControllerTest.java
  application/src/test/java/org/thingsboard/server/edge/AbstractEdgeTest.java
  application/src/test/java/org/thingsboard/server/edge/AssetEdgeTest.java
  application/src/test/java/org/thingsboard/server/edge/DeviceEdgeTest.java
  application/src/test/java/org/thingsboard/server/edge/ResourceEdgeTest.java
  common/cluster-api/src/main/proto/queue.proto
  common/edge-api/src/main/java/org/thingsboard/edge/rpc/EdgeGrpcClient.java
  common/edge-api/src/main/proto/edge.proto
Labels: Ignore for release

#9601 blackbox improvements
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ThingsBoardDbInstaller.java
Labels: enhancement, Ignore for release

#9592 Fixed value and chart card crash on empty colorProcessor type
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/color-settings-panel.component.ts
  ui-ngx/src/app/shared/models/widget-settings.models.ts
Labels: Bug, UI

#9606 Fixed liquid level widget additional checkup for datasources
  ui-ngx/src/app/modules/home/components/widget/lib/indicator/liquid-level-widget.component.ts
Labels: Bug, UI, Ignore for release

#9609 Added additional z-index to widget no data container
  ui-ngx/src/app/modules/home/components/widget/widget.component.scss
Labels: Bug, UI

#9610 Replacement of capital letters with lowercase letters in the second word in the names of menu items
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI

#9604 Telemetry edge processor: added check for attr/timeseries value size
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/telemetry/TelemetryEdgeProcessor.java
  application/src/test/java/org/thingsboard/server/service/edge/rpc/processor/telemetry/TelemetryEdgeProcessorTest.java
Labels: Ignore for release

#9607 added TbNodeUpgradeUtils && fixed rule node upgrades when config is null or NullNode
  application/src/main/java/org/thingsboard/server/service/install/update/DefaultDataUpdateService.java
  application/src/main/java/org/thingsboard/server/service/rule/DefaultTbRuleChainService.java
  application/src/main/java/org/thingsboard/server/utils/TbNodeUpgradeUtils.java
  application/src/test/java/org/thingsboard/server/utils/TbNodeUpgradeUtilsTest.java
  rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/util/TbNodeUtils.java
Labels: Bug

#9611 EdgeRepository - fixed typo searchText <> textSearch
  dao/src/main/java/org/thingsboard/server/dao/sql/edge/EdgeRepository.java
Labels: Ignore for release

#9612 save timeseries without latest: removed callback for entity view
  application/src/main/java/org/thingsboard/server/service/telemetry/DefaultTelemetrySubscriptionService.java
Labels: Bug

#9600 Improved afterTest method
  application/src/test/java/org/thingsboard/server/controller/AbstractWebTest.java
Labels: Bug

#9632 Save rule chain metadata: validate node configuration only after upgrade
  dao/src/main/java/org/thingsboard/server/dao/rule/BaseRuleChainService.java
  dao/src/main/java/org/thingsboard/server/dao/service/validator/RuleChainDataValidator.java
Labels: Bug, Core

#9643 Fixed uncontrolled focus alarm type list
  ui-ngx/src/app/shared/components/entity/entity-subtype-list.component.ts
Labels: Bug, UI

#9640 Improve flaky test
  application/src/test/java/org/thingsboard/server/service/notification/NotificationApiTest.java
Labels: Ignore for release

#9657 Edge sync test edge stability improvements
  application/src/test/java/org/thingsboard/server/controller/EdgeControllerTest.java
Labels: Ignore for release

#9659 blackbox tests improvements
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ThingsBoardDbInstaller.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/connectivity/MqttClientTest.java
Labels: Ignore for release

#9687 Extended widgetTypes access to customer user authority
  application/src/main/java/org/thingsboard/server/controller/WidgetTypeController.java
  application/src/test/java/org/thingsboard/server/controller/WidgetTypeControllerTest.java
Labels: Bug

#9699 Monitoring service improvements
  monitoring/src/main/java/org/thingsboard/monitoring/config/MonitoringTarget.java
  monitoring/src/main/java/org/thingsboard/monitoring/config/transport/TransportMonitoringConfig.java
  monitoring/src/main/java/org/thingsboard/monitoring/config/transport/TransportMonitoringTarget.java
  monitoring/src/main/java/org/thingsboard/monitoring/data/Latencies.java
  monitoring/src/main/java/org/thingsboard/monitoring/data/Latency.java
  monitoring/src/main/java/org/thingsboard/monitoring/data/notification/HighLatencyNotification.java
  monitoring/src/main/java/org/thingsboard/monitoring/service/BaseHealthChecker.java
  monitoring/src/main/java/org/thingsboard/monitoring/service/BaseMonitoringService.java
  monitoring/src/main/java/org/thingsboard/monitoring/service/MonitoringReporter.java
  monitoring/src/main/java/org/thingsboard/monitoring/service/transport/TransportsMonitoringService.java
  monitoring/src/main/resources/root_rule_chain.json
  monitoring/src/main/resources/tb-monitoring.yml
Labels: Build Scripts

#9712 Edge Requests Service - fetch only first level of relation from cloud…
  application/src/main/java/org/thingsboard/server/service/edge/rpc/sync/DefaultEdgeRequestsService.java
  application/src/test/java/org/thingsboard/server/edge/RelationEdgeTest.java
Labels: Bug, Edge

#9616 Fixed assign device to tenant
  application/src/main/java/org/thingsboard/server/actors/device/DeviceActor.java
  application/src/main/java/org/thingsboard/server/actors/tenant/TenantActor.java
  application/src/main/java/org/thingsboard/server/service/entitiy/DefaultTbNotificationEntityService.java
  application/src/main/java/org/thingsboard/server/service/queue/DefaultTbClusterService.java
  application/src/main/java/org/thingsboard/server/service/queue/ProtoUtils.java
  application/src/test/java/org/thingsboard/server/controller/DeviceControllerTest.java
  common/cluster-api/src/main/java/org/thingsboard/server/cluster/TbClusterService.java
  common/cluster-api/src/main/proto/queue.proto
  common/message/src/main/java/org/thingsboard/server/common/msg/MsgType.java
  common/message/src/main/java/org/thingsboard/server/common/msg/rule/engine/DeviceDeleteMsg.java
Labels: Bug, Core

#9708 added encode/decode time stats and refactoring
  common/cache/src/main/java/org/thingsboard/server/cache/RedisTbTransactionalCache.java
  common/data/src/main/java/org/thingsboard/server/common/data/FstStatsService.java
  common/queue/src/main/java/org/thingsboard/server/queue/util/ProtoWithFSTService.java
  common/stats/src/main/java/org/thingsboard/server/common/stats/FstStatsServiceImpl.java
Labels: Ignore for release

#9727 fixed rule-engine stats
  application/src/main/java/org/thingsboard/server/config/CustomOAuth2AuthorizationRequestResolver.java
  application/src/main/java/org/thingsboard/server/config/TbRuleEngineSecurityConfiguration.java
  application/src/main/java/org/thingsboard/server/service/security/auth/oauth2/HttpCookieOAuth2AuthorizationRequestRepository.java
Labels: Bug

#9733 fixed persistent RPC
  application/src/main/java/org/thingsboard/server/service/queue/ProtoUtils.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/TestRestClient.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/connectivity/MqttClientTest.java
Labels: Bug, Core
