Repository thingsboard/thingsboard, pull requests merged in 2023-04, with the labels that each got.

#8301 [3.5] Edge computing in solution templates
  application/src/main/data/json/edge/rule_chains/edge_root_rule_chain.json
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/BaseEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/relation/BaseRelationProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/telemetry/BaseTelemetryProcessor.java
  application/src/main/java/org/thingsboard/server/service/install/InstallScripts.java
Labels: Feature, Edge

#8308 [3.5]fixed upgrade script
  application/src/main/java/org/thingsboard/server/service/install/DefaultSystemDataLoaderService.java
  application/src/main/java/org/thingsboard/server/service/install/InstallScripts.java
Labels: Ignore for release

#8274 [3.5] Alarm entity that was delivered from the edge is stored with provided ID
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/alarm/BaseAlarmProcessor.java
  application/src/test/java/org/thingsboard/server/edge/BaseAlarmEdgeTest.java
  common/data/src/main/java/org/thingsboard/server/common/data/alarm/AlarmCreateOrUpdateActiveRequest.java
  dao/src/main/java/org/thingsboard/server/dao/sql/alarm/JpaAlarmDao.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/edge/AbstractTbMsgPushNode.java
  ui-ngx/src/app/modules/home/pages/rulechain/rulechains-table-config.resolver.ts
Labels: Bug, Edge

#8300 Update PR template delete add version in templates
  pull_request_template.md
Labels: Ignore for release

#8321 Updated rule node core config
  rule-engine/rule-engine-components/src/main/resources/public/static/rulenode/rulenode-core-config.js
Labels: Ignore for release

#8310 [3.5] fix for incorrect long integers, sent on ws to FE
  dao/src/main/java/org/thingsboard/server/dao/sql/query/EntityDataAdapter.java
  dao/src/test/java/org/thingsboard/server/dao/sql/query/EntityDataAdapterTest.java
Labels: Bug, Core

#8317 [3.5] Edge processor - delete attribute msg is not properly handled for non device type
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/telemetry/BaseTelemetryProcessor.java
  application/src/test/java/org/thingsboard/server/edge/BaseTelemetryEdgeTest.java
Labels: Bug, Ignore for release

#8326 Fixed updated notification when open notifications popover
  ui-ngx/src/app/shared/models/websocket/notification-ws.models.ts
Labels: Bug, UI, Ignore for release

#8328 Flaky test fixes
  application/src/test/java/org/thingsboard/server/controller/BaseEntityQueryControllerTest.java
  application/src/test/java/org/thingsboard/server/controller/BaseHomePageApiTest.java
Labels: Ignore for release

#8333 Change notification template/rule type disabled in edit mode
  ui-ngx/src/app/modules/home/pages/notification/rule/rule-notification-dialog.component.ts
  ui-ngx/src/app/modules/home/pages/notification/template/template-notification-dialog.component.ts
Labels: enhancement, UI, Ignore for release

#8329 Added logging for invalid mqtt ssl certificates
  common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttSslHandlerProvider.java
Labels: enhancement, Ignore for release

#8325 [3.5] Fixed logging of EdgeGrpcSession
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java
Labels: Ignore for release

#8294 Update links for alarm info in widget custom action help
  ui-ngx/src/assets/help/en_US/widget/action/custom_additional_params.md
Labels: enhancement, UI

#8285 Alarm details redesign
  application/src/main/data/json/system/widget_bundles/alarm_widgets.json
  ui-ngx/src/app/modules/home/components/alarm/alarm-assignee-panel.component.html
  ui-ngx/src/app/modules/home/components/alarm/alarm-assignee-panel.component.scss
  ui-ngx/src/app/modules/home/components/alarm/alarm-assignee-panel.component.ts
  ui-ngx/src/app/modules/home/components/alarm/alarm-assignee.component.html
  ui-ngx/src/app/modules/home/components/alarm/alarm-assignee.component.scss
  ui-ngx/src/app/modules/home/components/alarm/alarm-assignee.component.ts
  ui-ngx/src/app/modules/home/components/alarm/alarm-comment-dialog.component.html
  ui-ngx/src/app/modules/home/components/alarm/alarm-comment-dialog.component.ts
  ui-ngx/src/app/modules/home/components/alarm/alarm-comment.component.html
  ui-ngx/src/app/modules/home/components/alarm/alarm-comment.component.scss
  ui-ngx/src/app/modules/home/components/alarm/alarm-comment.component.ts
  ui-ngx/src/app/modules/home/components/alarm/alarm-details-dialog.component.html
  ui-ngx/src/app/modules/home/components/alarm/alarm-details-dialog.component.scss
  ui-ngx/src/app/modules/home/components/alarm/alarm-details-dialog.component.ts
  ui-ngx/src/app/modules/home/components/alarm/alarm-table-config.ts
  ui-ngx/src/app/modules/home/components/alarm/alarm-table.component.scss
  ui-ngx/src/app/modules/home/components/import-export/import-export.models.ts
  ui-ngx/src/app/modules/home/components/import-export/import-export.service.ts
  ui-ngx/src/app/modules/home/components/widget/lib/alarms-table-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/alarm/alarms-table-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/alarm/alarms-table-widget-settings.component.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI, Ignore for release

#6986 [3.5] added ability to create&subscribe custom mqtt attributes topics
  application/src/test/java/org/thingsboard/server/controller/AbstractWebTest.java
  application/src/test/java/org/thingsboard/server/controller/BaseDeviceProfileControllerTest.java
  application/src/test/java/org/thingsboard/server/transport/mqtt/mqttv3/attributes/updates/MqttAttributesUpdatesIntegrationTest.java
  common/data/src/main/java/org/thingsboard/server/common/data/device/profile/MqttDeviceProfileTransportConfiguration.java
  common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttTransportHandler.java
  common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/DeviceSessionCtx.java
  ui-ngx/src/app/modules/home/components/profile/device/mqtt-device-profile-transport-configuration.component.html
  ui-ngx/src/app/modules/home/components/profile/device/mqtt-device-profile-transport-configuration.component.ts
  ui-ngx/src/assets/locale/locale.constant-cs_CZ.json
  ui-ngx/src/assets/locale/locale.constant-en_US.json
  ui-ngx/src/assets/locale/locale.constant-es_ES.json
  ui-ngx/src/assets/locale/locale.constant-fr_FR.json
  ui-ngx/src/assets/locale/locale.constant-ko_KR.json
  ui-ngx/src/assets/locale/locale.constant-sl_SI.json
  ui-ngx/src/assets/locale/locale.constant-tr_TR.json
Labels: Transport

#8327 removed redundant handle exception
  application/src/main/java/org/thingsboard/server/controller/AdminController.java
  application/src/main/java/org/thingsboard/server/controller/AlarmController.java
  application/src/main/java/org/thingsboard/server/controller/AssetController.java
  application/src/main/java/org/thingsboard/server/controller/AssetProfileController.java
  application/src/main/java/org/thingsboard/server/controller/AuditLogController.java
  application/src/main/java/org/thingsboard/server/controller/AuthController.java
  application/src/main/java/org/thingsboard/server/controller/ComponentDescriptorController.java
  application/src/main/java/org/thingsboard/server/controller/CustomerController.java
  application/src/main/java/org/thingsboard/server/controller/DashboardController.java
  application/src/main/java/org/thingsboard/server/controller/DeviceController.java
  application/src/main/java/org/thingsboard/server/controller/DeviceProfileController.java
  application/src/main/java/org/thingsboard/server/controller/EdgeController.java
  application/src/main/java/org/thingsboard/server/controller/EdgeEventController.java
  application/src/main/java/org/thingsboard/server/controller/EntityRelationController.java
  application/src/main/java/org/thingsboard/server/controller/EntityViewController.java
  application/src/main/java/org/thingsboard/server/controller/EventController.java
  application/src/main/java/org/thingsboard/server/controller/Lwm2mController.java
  application/src/main/java/org/thingsboard/server/controller/OAuth2ConfigTemplateController.java
  application/src/main/java/org/thingsboard/server/controller/OAuth2Controller.java
  application/src/main/java/org/thingsboard/server/controller/OtaPackageController.java
  application/src/main/java/org/thingsboard/server/controller/RpcV2Controller.java
  application/src/main/java/org/thingsboard/server/controller/RuleChainController.java
  application/src/main/java/org/thingsboard/server/controller/TbResourceController.java
  application/src/main/java/org/thingsboard/server/controller/TelemetryController.java
  application/src/main/java/org/thingsboard/server/controller/TenantController.java
  application/src/main/java/org/thingsboard/server/controller/TenantProfileController.java
  application/src/main/java/org/thingsboard/server/controller/UserController.java
  application/src/main/java/org/thingsboard/server/controller/WidgetTypeController.java
  application/src/main/java/org/thingsboard/server/controller/WidgetsBundleController.java
Labels: enhancement, Ignore for release

#7857 Improvements for reporting device activity during RPC processing
  common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/client/DefaultCoapClientContext.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/rpc/RpcDownlinkRequestCallbackProxy.java
  common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttTransportHandler.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/TransportService.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/service/DefaultTransportService.java
Labels: enhancement, Feature

#7858 Rest API Call node - Add ability to remove quotes from Body
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/rest/TbHttpClient.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/rest/TbRestApiCallNodeConfiguration.java
Labels: Rule Engine

#8334 Notification system improvements
  application/src/main/data/upgrade/3.4.4/schema_update.sql
  application/src/main/java/org/thingsboard/server/controller/NotificationRuleController.java
  application/src/main/java/org/thingsboard/server/service/notification/rule/DefaultNotificationRuleProcessor.java
  application/src/main/java/org/thingsboard/server/service/notification/rule/cache/DefaultNotificationRulesCache.java
  application/src/main/java/org/thingsboard/server/service/notification/rule/cache/NotificationRulesCache.java
  application/src/main/java/org/thingsboard/server/service/notification/rule/trigger/NewPlatformVersionTriggerProcessor.java
  application/src/main/java/org/thingsboard/server/service/queue/DefaultTbClusterService.java
  application/src/main/java/org/thingsboard/server/service/queue/DefaultTbCoreConsumerService.java
  application/src/main/java/org/thingsboard/server/service/update/DefaultUpdateService.java
  application/src/main/resources/thingsboard.yml
  common/cluster-api/src/main/proto/queue.proto
  common/data/src/main/java/org/thingsboard/server/common/data/CacheConstants.java
  common/data/src/main/java/org/thingsboard/server/common/data/notification/info/NewPlatformVersionNotificationInfo.java
  common/data/src/main/java/org/thingsboard/server/common/data/notification/rule/trigger/NewPlatformVersionNotificationRuleTriggerConfig.java
  common/message/src/main/java/org/thingsboard/server/common/msg/notification/trigger/NewPlatformVersionTrigger.java
  common/queue/src/main/java/org/thingsboard/server/queue/notification/RemoteNotificationRuleProcessor.java
  dao/src/main/java/org/thingsboard/server/dao/notification/DefaultNotificationRuleService.java
  dao/src/main/java/org/thingsboard/server/dao/notification/DefaultNotificationSettingsService.java
  dao/src/main/java/org/thingsboard/server/dao/notification/DefaultNotificationTemplateService.java
  dao/src/main/java/org/thingsboard/server/dao/notification/cache/NotificationRuleCacheValue.java
  dao/src/main/java/org/thingsboard/server/dao/notification/cache/NotificationRuleCaffeineCache.java
  dao/src/main/java/org/thingsboard/server/dao/notification/cache/NotificationRuleRedisCache.java
  dao/src/main/resources/sql/schema-entities.sql
  ui-ngx/src/app/modules/home/pages/notification/rule/rule-notification-dialog.component.html
  ui-ngx/src/app/modules/home/pages/notification/rule/rule-notification-dialog.component.ts
  ui-ngx/src/app/modules/home/pages/notification/template/template-notification-dialog.component.ts
  ui-ngx/src/app/shared/models/notification.models.ts
  ui-ngx/src/assets/help/en_US/notification/new_platform_version.md
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: Ignore for release

#7991 Allow to configure kafkajs `connectionTimeout` property
  msa/js-executor/config/custom-environment-variables.yml
  msa/js-executor/config/default.yml
  msa/js-executor/queue/kafkaTemplate.ts
Labels: Rule Engine

#8340 [3.5] Handle gRPC messages exceeding default max message size
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcService.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java
  application/src/main/resources/thingsboard.yml
  application/src/test/java/org/thingsboard/server/edge/imitator/EdgeImitator.java
  common/edge-api/src/main/java/org/thingsboard/edge/rpc/EdgeGrpcClient.java
  common/edge-api/src/main/java/org/thingsboard/edge/rpc/EdgeRpcClient.java
  common/edge-api/src/main/proto/edge.proto
Labels: Edge

#8335 Devices activity statistics
  application/src/main/java/org/thingsboard/server/service/apiusage/BaseApiUsageState.java
  application/src/main/java/org/thingsboard/server/service/apiusage/DefaultTbApiUsageStateService.java
  application/src/main/java/org/thingsboard/server/service/state/DefaultDeviceStateService.java
  application/src/main/java/org/thingsboard/server/service/telemetry/DefaultTelemetrySubscriptionService.java
  application/src/main/resources/thingsboard.yml
  application/src/test/java/org/thingsboard/server/controller/AbstractWebTest.java
  application/src/test/java/org/thingsboard/server/service/notification/MockNotificationSettingsService.java
  application/src/test/java/org/thingsboard/server/service/state/DefaultDeviceStateServiceTest.java
  application/src/test/java/org/thingsboard/server/service/stats/DevicesStatisticsTest.java
  application/src/test/java/org/thingsboard/server/transport/mqtt/mqttv3/credentials/BasicMqttCredentialsTest.java
  common/cluster-api/src/main/proto/queue.proto
  common/data/src/main/java/org/thingsboard/server/common/data/ApiUsageRecordKey.java
  common/queue/src/main/java/org/thingsboard/server/queue/usagestats/DefaultTbApiUsageReportClient.java
  dao/src/main/java/org/thingsboard/server/dao/usagerecord/ApiUsageStateServiceImpl.java
  msa/vc-executor/src/main/resources/tb-vc-executor.yml
  transport/coap/src/main/resources/tb-coap-transport.yml
  transport/http/src/main/resources/tb-http-transport.yml
  transport/lwm2m/src/main/resources/tb-lwm2m-transport.yml
  transport/mqtt/src/main/resources/tb-mqtt-transport.yml
  transport/snmp/src/main/resources/tb-snmp-transport.yml
Labels: Core

#8344 [3.5] Push edge connect/disconnect events to rule chain
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcService.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/edge/AbstractTbMsgPushNode.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/edge/TbMsgPushToEdgeNodeTest.java
Labels: Edge

#8343 Fixed show email notification preview in big content
  ui-ngx/src/app/modules/home/components/notification/show-notification-popover.component.html
  ui-ngx/src/app/modules/home/pages/notification/sent/sent-notification-dialog.component.scss
  ui-ngx/src/app/shared/components/notification/notification.component.scss
Labels: Bug, UI, Ignore for release

#8342 [3.5] Add SSL option for Kafka queue connection
  application/src/main/resources/thingsboard.yml
  common/queue/src/main/java/org/thingsboard/server/queue/kafka/TbKafkaSettings.java
  msa/vc-executor/src/main/resources/tb-vc-executor.yml
  transport/coap/src/main/resources/tb-coap-transport.yml
  transport/http/src/main/resources/tb-http-transport.yml
  transport/lwm2m/src/main/resources/tb-lwm2m-transport.yml
  transport/mqtt/src/main/resources/tb-mqtt-transport.yml
  transport/snmp/src/main/resources/tb-snmp-transport.yml
Labels: enhancement

#8026 Filter type alias - add possibility to specify multiple types, instead of single one
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/DashboardImportService.java
  application/src/test/java/org/thingsboard/server/controller/BaseEntityQueryControllerTest.java
  application/src/test/java/org/thingsboard/server/controller/BaseEntityViewControllerTest.java
  application/src/test/java/org/thingsboard/server/controller/BaseWebsocketApiTest.java
  application/src/test/java/org/thingsboard/server/transport/mqtt/mqttv3/attributes/AbstractMqttAttributesIntegrationTest.java
  common/data/src/main/java/org/thingsboard/server/common/data/query/AssetTypeFilter.java
  common/data/src/main/java/org/thingsboard/server/common/data/query/DeviceTypeFilter.java
  common/data/src/main/java/org/thingsboard/server/common/data/query/EdgeTypeFilter.java
  common/data/src/main/java/org/thingsboard/server/common/data/query/EntityViewTypeFilter.java
  dao/src/main/java/org/thingsboard/server/dao/sql/query/DefaultEntityQueryRepository.java
  dao/src/test/java/org/thingsboard/server/dao/service/BaseEntityServiceTest.java
  ui-ngx/src/app/core/services/dashboard-utils.service.ts
  ui-ngx/src/app/modules/home/components/entity/entity-filter-view.component.ts
  ui-ngx/src/app/modules/home/components/entity/entity-filter.component.html
  ui-ngx/src/app/modules/home/components/entity/entity-filter.component.ts
  ui-ngx/src/app/shared/models/alias.models.ts
  ui-ngx/src/assets/locale/locale.constant-ca_ES.json
  ui-ngx/src/assets/locale/locale.constant-cs_CZ.json
  ui-ngx/src/assets/locale/locale.constant-de_DE.json
  ui-ngx/src/assets/locale/locale.constant-el_GR.json
  ui-ngx/src/assets/locale/locale.constant-en_US.json
  ui-ngx/src/assets/locale/locale.constant-es_ES.json
  ui-ngx/src/assets/locale/locale.constant-fa_IR.json
  ui-ngx/src/assets/locale/locale.constant-fr_FR.json
  ui-ngx/src/assets/locale/locale.constant-it_IT.json
  ui-ngx/src/assets/locale/locale.constant-ja_JP.json
  ui-ngx/src/assets/locale/locale.constant-ka_GE.json
  ui-ngx/src/assets/locale/locale.constant-ko_KR.json
  ui-ngx/src/assets/locale/locale.constant-lv_LV.json
  ui-ngx/src/assets/locale/locale.constant-pt_BR.json
  ui-ngx/src/assets/locale/locale.constant-ro_RO.json
  ui-ngx/src/assets/locale/locale.constant-ru_RU.json
  ui-ngx/src/assets/locale/locale.constant-sl_SI.json
  ui-ngx/src/assets/locale/locale.constant-tr_TR.json
  ui-ngx/src/assets/locale/locale.constant-uk_UA.json
  ui-ngx/src/assets/locale/locale.constant-zh_CN.json
  ui-ngx/src/assets/locale/locale.constant-zh_TW.json
Labels: Core

#8349 fix vulnerabilities
  application/src/main/java/org/thingsboard/server/service/security/auth/rest/RestAuthenticationDetails.java
  common/data/pom.xml
  pom.xml
Labels: Core

#8350 Deleted redundant @NotNull annotations
  common/script/remote-js-client/src/main/java/org/thingsboard/server/service/script/RemoteJsInvokeService.java
  dao/src/main/java/org/thingsboard/server/dao/sql/alarm/JpaAlarmDao.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/action/TbCopyAttributesToEntityViewNode.java
Labels: Ignore for release

#8348 Originator node
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/filter/TbOriginatorTypeSwitchNode.java
Labels: Ignore for release

#8241 Changed default for wsMsgQueueLimitPerSession
  application/src/main/java/org/thingsboard/server/controller/plugin/TbWebSocketHandler.java
  application/src/main/resources/thingsboard.yml
  dao/src/main/java/org/thingsboard/server/dao/service/validator/TenantProfileDataValidator.java
  ui-ngx/src/app/modules/home/components/profile/tenant/default-tenant-profile-configuration.component.html
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, Core

#7935 X509 certificate provision
  application/src/main/java/org/thingsboard/server/service/device/DeviceProvisionServiceImpl.java
  application/src/main/java/org/thingsboard/server/service/transport/DefaultTransportApiService.java
  application/src/test/java/org/thingsboard/server/service/device/provision/DeviceProvisionServiceTest.java
  application/src/test/java/org/thingsboard/server/service/transport/DefaultTransportApiServiceTest.java
  application/src/test/resources/provision/x509ChainProvisionTest.pem
  common/dao-api/src/main/java/org/thingsboard/server/dao/device/DeviceProvisionService.java
  dao/src/main/java/org/thingsboard/server/dao/service/validator/DeviceProfileDataValidator.java
  ui-ngx/src/assets/help/en_US/device-profile/x509-chain-regex-examples.md
Labels: Major Core

#5311 Feature/funtionality to handle JSON attribute in edit multiple attributes widget
  ui-ngx/src/app/modules/home/components/widget/lib/multiple-input-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/multiple-input-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/input/update-multiple-attributes-key-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/input/update-multiple-attributes-key-settings.component.ts
  ui-ngx/src/app/shared/components/dialog/json-object-edit-dialog.component.html
  ui-ngx/src/app/shared/components/dialog/json-object-edit-dialog.component.ts
  ui-ngx/src/app/shared/shared.module.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI, Feature

#8298 Added label parsing in select entity dialog
  ui-ngx/src/app/modules/home/components/widget/lib/maps/dialogs/select-entity-dialog.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/maps/dialogs/select-entity-dialog.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/maps/leaflet-map.ts
  ui-ngx/src/app/modules/home/components/widget/lib/maps/maps-utils.ts
Labels: enhancement, UI

#8311 Fix disable time interval in timewindow panel
  ui-ngx/src/app/shared/components/time/timeinterval.component.ts
  ui-ngx/src/app/shared/components/time/timewindow-panel.component.ts
Labels: Bug, UI, Ignore for release

#8336 Fix for no users matching assignment user
  ui-ngx/src/app/modules/home/components/alarm/alarm-assignee-panel.component.html
Labels: Bug, UI, Ignore for release

#8357 Typo - fixed startup of edge event clean up service
  application/src/main/java/org/thingsboard/server/service/ttl/EdgeEventsCleanUpService.java
  dao/src/main/java/org/thingsboard/server/dao/sql/edge/JpaBaseEdgeEventDao.java
Labels: Ignore for release

#8346 Improved Keep Alive Functionality between Edge and Cloud to Prevent Data Loss
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcService.java
  application/src/main/resources/thingsboard.yml
  application/src/test/java/org/thingsboard/server/edge/imitator/EdgeImitator.java
  common/edge-api/src/main/java/org/thingsboard/edge/rpc/EdgeGrpcClient.java
Labels: Edge

#8353 Fixed xss vulnerabilities in attributes and telemetry
  application/src/main/java/org/thingsboard/server/controller/TelemetryController.java
  application/src/main/java/org/thingsboard/server/service/security/AccessValidator.java
  application/src/main/resources/thingsboard.yml
  application/src/test/java/org/thingsboard/server/controller/BaseTelemetryControllerTest.java
  application/src/test/java/org/thingsboard/server/controller/sql/TelemetryControllerSqlTest.java
  common/data/src/main/java/org/thingsboard/server/common/data/kv/BasicKvEntry.java
  common/data/src/main/java/org/thingsboard/server/common/data/kv/BasicTsKvEntry.java
  common/data/src/main/java/org/thingsboard/server/common/data/kv/JsonDataEntry.java
  common/data/src/main/java/org/thingsboard/server/common/data/kv/StringDataEntry.java
  dao/src/main/java/org/thingsboard/server/dao/attributes/AttributeUtils.java
  dao/src/main/java/org/thingsboard/server/dao/attributes/BaseAttributesService.java
  dao/src/main/java/org/thingsboard/server/dao/attributes/CachedAttributesService.java
  dao/src/main/java/org/thingsboard/server/dao/timeseries/BaseTimeseriesService.java
  dao/src/main/java/org/thingsboard/server/dao/util/KvUtils.java
  dao/src/test/java/org/thingsboard/server/dao/service/ConstraintValidatorTest.java
Labels: Core

#8356 Notification system improvements
  application/src/main/java/org/thingsboard/server/controller/BaseController.java
  application/src/main/java/org/thingsboard/server/controller/NotificationController.java
  application/src/main/java/org/thingsboard/server/controller/NotificationTargetController.java
  application/src/main/java/org/thingsboard/server/service/apiusage/limits/DefaultRateLimitService.java
  application/src/main/java/org/thingsboard/server/service/apiusage/limits/LimitedApi.java
  application/src/main/java/org/thingsboard/server/service/apiusage/limits/RateLimitService.java
  application/src/main/java/org/thingsboard/server/service/notification/DefaultNotificationCenter.java
  application/src/main/java/org/thingsboard/server/service/notification/NotificationProcessingContext.java
  application/src/main/java/org/thingsboard/server/service/notification/channels/EmailNotificationChannel.java
  application/src/main/java/org/thingsboard/server/service/notification/channels/NotificationChannel.java
  application/src/main/java/org/thingsboard/server/service/notification/channels/SlackNotificationChannel.java
  application/src/main/java/org/thingsboard/server/service/notification/channels/SmsNotificationChannel.java
  application/src/main/java/org/thingsboard/server/service/notification/rule/DefaultNotificationRuleProcessor.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/DefaultEntitiesExportImportService.java
  application/src/main/resources/thingsboard.yml
  application/src/test/java/org/thingsboard/server/service/notification/NotificationApiTest.java
  application/src/test/java/org/thingsboard/server/service/notification/NotificationRuleApiTest.java
  application/src/test/java/org/thingsboard/server/service/notification/NotificationTemplateApiTest.java
  common/data/src/main/java/org/thingsboard/server/common/data/notification/rule/NotificationRule.java
  common/data/src/main/java/org/thingsboard/server/common/data/notification/targets/NotificationTarget.java
  common/data/src/main/java/org/thingsboard/server/common/data/notification/targets/NotificationTargetConfig.java
  common/data/src/main/java/org/thingsboard/server/common/data/notification/targets/NotificationTargetType.java
  common/data/src/main/java/org/thingsboard/server/common/data/notification/template/EmailDeliveryMethodNotificationTemplate.java
  common/data/src/main/java/org/thingsboard/server/common/data/notification/template/NotificationTemplate.java
  common/data/src/main/java/org/thingsboard/server/common/data/notification/template/NotificationText.java
  common/data/src/main/java/org/thingsboard/server/common/data/notification/template/SlackDeliveryMethodNotificationTemplate.java
  common/data/src/main/java/org/thingsboard/server/common/data/notification/template/SmsDeliveryMethodNotificationTemplate.java
  common/data/src/main/java/org/thingsboard/server/common/data/notification/template/WebDeliveryMethodNotificationTemplate.java
  common/data/src/main/java/org/thingsboard/server/common/data/tenant/profile/DefaultTenantProfileConfiguration.java
  common/data/src/main/java/org/thingsboard/server/common/data/validation/Length.java
  common/data/src/main/java/org/thingsboard/server/common/data/validation/NoXss.java
  dao/src/main/java/org/thingsboard/server/dao/notification/DefaultNotificationSettingsService.java
  dao/src/main/java/org/thingsboard/server/dao/service/ConstraintValidator.java
  ui-ngx/src/app/modules/home/components/profile/tenant/default-tenant-profile-configuration.component.html
  ui-ngx/src/app/modules/home/components/profile/tenant/default-tenant-profile-configuration.component.ts
  ui-ngx/src/app/modules/home/components/profile/tenant/rate-limits/rate-limits.models.ts
  ui-ngx/src/app/shared/models/tenant.model.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: Ignore for release

#7906 Add guide for run tests on built UI
  msa/black-box-tests/README.md
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/TestProperties.java
  msa/black-box-tests/src/test/resources/config.properties
Labels: Build Scripts

#8375 Bugfix for Deduplicate and Delay Rule Nodes outgoing messages processing
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/deduplication/TbMsgDeduplicationNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/delay/TbMsgDelayNode.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/action/TbMsgDeduplicationNodeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/transform/TbMsgDeduplicationNodeTest.java
Labels: Bug, Rule Engine

#8369 Added test for detection RestTemplate xml content type issue
  application/src/test/java/org/thingsboard/server/system/RestTemplateConvertersTest.java
Labels: Core, Ignore for release

#8371 revert tskv value noxss validation
  application/src/main/resources/thingsboard.yml
  application/src/test/java/org/thingsboard/server/controller/BaseTelemetryControllerTest.java
  common/data/src/main/java/org/thingsboard/server/common/data/kv/JsonDataEntry.java
  common/data/src/main/java/org/thingsboard/server/common/data/kv/StringDataEntry.java
  dao/src/main/java/org/thingsboard/server/dao/attributes/AttributeUtils.java
  dao/src/main/java/org/thingsboard/server/dao/attributes/BaseAttributesService.java
  dao/src/main/java/org/thingsboard/server/dao/attributes/CachedAttributesService.java
  dao/src/main/java/org/thingsboard/server/dao/timeseries/BaseTimeseriesService.java
  dao/src/main/java/org/thingsboard/server/dao/util/KvUtils.java
  dao/src/test/java/org/thingsboard/server/dao/service/ConstraintValidatorTest.java
Labels: Ignore for release

#8364 Redesign of color picker
  ui-ngx/package.json
  ui-ngx/src/app/shared/components/color-picker/color-picker.component.html
  ui-ngx/src/app/shared/components/color-picker/color-picker.component.scss
  ui-ngx/src/app/shared/components/color-picker/color-picker.component.ts
  ui-ngx/src/app/shared/components/dialog/color-picker-dialog.component.html
  ui-ngx/src/app/shared/components/dialog/color-picker-dialog.component.ts
  ui-ngx/src/app/shared/shared.module.ts
  ui-ngx/yarn.lock
Labels: enhancement, UI

#8376 Fix external id substitution when loading version of dashboard or rule chain
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/BaseEntityImportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/DashboardImportService.java
  application/src/main/java/org/thingsboard/server/service/sync/vc/DefaultEntitiesVersionControlService.java
  application/src/test/java/org/thingsboard/server/service/sync/ie/ExportImportServiceSqlTest.java
  monitoring/src/main/conf/logback.xml
Labels: Bug, Core

#8380 Fix/X509 device provisioning
  dao/src/main/java/org/thingsboard/server/dao/device/DeviceProfileServiceImpl.java
  ui-ngx/src/app/modules/home/components/profile/device-profile-provision-configuration.component.ts
Labels: Ignore for release

#8378 Edge - improved logic of interruption of sending downlink tasks
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcService.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeSessionState.java
Labels: Ignore for release

#8383 Fix color picker input width
  ui-ngx/src/app/shared/components/color-picker/color-picker.component.scss
Labels: Bug, UI, Ignore for release

#8387 Fixed telemetry/attribute update while device bulk import
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/csv/AbstractBulkImportService.java
  application/src/test/java/org/thingsboard/server/controller/BaseDeviceControllerTest.java
Labels: Bug, Core

#8391 features info improvements
  application/src/main/java/org/thingsboard/server/service/system/DefaultSystemInfoService.java
  application/src/test/java/org/thingsboard/server/controller/BaseHomePageApiTest.java
Labels: Ignore for release

#8393 Added init value for MQTT transport configuration in device profile
  ui-ngx/src/app/shared/models/device.models.ts
Labels: Bug, UI, Ignore for release

#8388 Monitoring for LwM2M
  monitoring/pom.xml
  monitoring/src/main/java/org/thingsboard/monitoring/client/Lwm2mClient.java
  monitoring/src/main/java/org/thingsboard/monitoring/config/TransportType.java
  monitoring/src/main/java/org/thingsboard/monitoring/config/service/Lwm2mTransportMonitoringConfig.java
  monitoring/src/main/java/org/thingsboard/monitoring/transport/TransportHealthChecker.java
  monitoring/src/main/java/org/thingsboard/monitoring/transport/TransportMonitoringService.java
  monitoring/src/main/java/org/thingsboard/monitoring/transport/impl/Lwm2mTransportHealthChecker.java
  monitoring/src/main/java/org/thingsboard/monitoring/util/ResourceUtils.java
  monitoring/src/main/resources/lwm2m/device_profile.json
  monitoring/src/main/resources/lwm2m/models/0.xml
  monitoring/src/main/resources/lwm2m/models/1.xml
  monitoring/src/main/resources/lwm2m/models/2.xml
  monitoring/src/main/resources/lwm2m/models/test-model.xml
  monitoring/src/main/resources/lwm2m/resource.json
  monitoring/src/main/resources/tb-monitoring.yml
Labels: Ignore for release

#8392 added log to TenantActor for investigation
  application/src/main/java/org/thingsboard/server/actors/tenant/TenantActor.java
Labels: Ignore for release

#8401 fix deduplication node description
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/deduplication/TbMsgDeduplicationNode.java
Labels: Ignore for release

#8389 Remove usages of findDeviceByIdAsync
  application/src/main/java/org/thingsboard/server/service/device/ClaimDevicesServiceImpl.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/device/BaseDeviceProcessor.java
  application/src/main/java/org/thingsboard/server/service/security/AccessValidator.java
  dao/src/main/java/org/thingsboard/server/dao/device/DeviceServiceImpl.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/action/TbCreateRelationNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/metadata/TbAbstractGetEntityDetailsNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/metadata/TbGetCustomerDetailsNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/metadata/TbGetTenantDetailsNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/util/EntitiesCustomerIdAsyncLoader.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/util/EntitiesFieldsAsyncLoader.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/metadata/AbstractAttributeNodeTest.java
Labels: WIP, Ignore for release

#8400 Home dashboard improvements
  application/src/main/data/json/system/widget_bundles/home_page_widgets.json
  ui-ngx/src/app/modules/home/components/widget/lib/home-page/getting-started-widget.component.html
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI, Ignore for release

#8386 Add tests on delete phone number
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/customerSmoke/CreateCustomerTest.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/tests/customerSmoke/CustomerEditMenuTest.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ui/utils/EntityPrototypes.java
Labels: Build Scripts

#8402 Feature/alarm tenant id active idx
  application/src/main/data/upgrade/3.4.4/schema_update.sql
  dao/src/main/resources/sql/schema-entities-idx.sql
Labels: Ignore for release

#8405 Notification system improvements
  application/src/main/java/org/thingsboard/server/actors/ActorSystemContext.java
  application/src/main/java/org/thingsboard/server/controller/BaseController.java
  application/src/main/java/org/thingsboard/server/service/action/EntityActionService.java
  application/src/main/java/org/thingsboard/server/service/apiusage/DefaultTbApiUsageStateService.java
  application/src/main/java/org/thingsboard/server/service/notification/rule/DefaultNotificationRuleProcessor.java
  application/src/main/java/org/thingsboard/server/service/notification/rule/trigger/EntitiesLimitTriggerProcessor.java
  application/src/main/java/org/thingsboard/server/service/queue/DefaultTbCoreConsumerService.java
  application/src/main/java/org/thingsboard/server/service/telemetry/DefaultAlarmSubscriptionService.java
  application/src/main/java/org/thingsboard/server/service/update/DefaultUpdateService.java
  application/src/test/java/org/thingsboard/server/service/notification/MockNotificationSettingsService.java
  application/src/test/java/org/thingsboard/server/service/notification/NotificationRuleApiTest.java
  common/data/src/main/java/org/thingsboard/server/common/data/notification/rule/trigger/AlarmAssignmentNotificationRuleTriggerConfig.java
  common/data/src/main/java/org/thingsboard/server/common/data/notification/rule/trigger/AlarmCommentNotificationRuleTriggerConfig.java
  common/data/src/main/java/org/thingsboard/server/common/data/notification/rule/trigger/AlarmNotificationRuleTriggerConfig.java
  common/data/src/main/java/org/thingsboard/server/common/data/notification/rule/trigger/ApiUsageLimitNotificationRuleTriggerConfig.java
  common/data/src/main/java/org/thingsboard/server/common/data/notification/rule/trigger/DeviceActivityNotificationRuleTriggerConfig.java
  common/data/src/main/java/org/thingsboard/server/common/data/notification/rule/trigger/EntitiesLimitNotificationRuleTriggerConfig.java
  common/data/src/main/java/org/thingsboard/server/common/data/notification/rule/trigger/EntityActionNotificationRuleTriggerConfig.java
  common/data/src/main/java/org/thingsboard/server/common/data/notification/rule/trigger/RuleEngineComponentLifecycleEventNotificationRuleTriggerConfig.java
  common/message/src/main/java/org/thingsboard/server/common/msg/notification/trigger/EntitiesLimitTrigger.java
  common/queue/src/main/java/org/thingsboard/server/queue/notification/NotificationRuleProcessor.java
  common/queue/src/main/java/org/thingsboard/server/queue/notification/RemoteNotificationRuleProcessor.java
  dao/src/main/java/org/thingsboard/server/dao/notification/DefaultNotificationSettingsService.java
  dao/src/main/java/org/thingsboard/server/dao/notification/DefaultNotifications.java
  dao/src/main/java/org/thingsboard/server/dao/rule/BaseRuleChainService.java
  dao/src/main/java/org/thingsboard/server/dao/usagerecord/DefaultApiLimitService.java
Labels: WIP, Ignore for release

#8406 Fixed assignee cell height not matching row height in alarm entity table
  ui-ngx/src/app/modules/home/components/alarm/alarm-table-config.ts
  ui-ngx/src/app/modules/home/components/alarm/alarm-table.component.scss
Labels: Bug, UI, Ignore for release

#8409 Add help link for calculate delta rule node
  ui-ngx/src/app/shared/models/constants.ts
  ui-ngx/src/app/shared/models/rule-node.models.ts
Labels: enhancement, UI

#8413 Fixed error when call test function in rule node
  ui-ngx/src/app/core/services/script/node-script-test.service.ts
Labels: Bug, UI, Rule Engine

#8398 Added new message types to rule engine
  application/src/main/java/org/thingsboard/server/service/action/EntityActionService.java
  application/src/main/java/org/thingsboard/server/service/entitiy/DefaultTbNotificationEntityService.java
  application/src/main/java/org/thingsboard/server/service/entitiy/alarm/DefaultTbAlarmService.java
  application/src/main/java/org/thingsboard/server/service/notification/rule/trigger/AlarmAssignmentTriggerProcessor.java
  application/src/test/java/org/thingsboard/server/controller/BaseAlarmControllerTest.java
  common/data/src/main/java/org/thingsboard/server/common/data/DataConstants.java
  common/data/src/main/java/org/thingsboard/server/common/data/audit/ActionType.java
  common/data/src/main/java/org/thingsboard/server/common/data/edge/EdgeEventActionType.java
  dao/src/main/java/org/thingsboard/server/dao/audit/AuditLogServiceImpl.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/filter/TbMsgTypeSwitchNode.java
  ui-ngx/src/app/shared/models/audit-log.models.ts
  ui-ngx/src/app/shared/models/rule-node.models.ts
Labels: Rule Engine

#8425 fexed NPE in log node
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/action/TbLogNode.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/action/TbLogNodeTest.java
Labels: Ignore for release

#8404 Feature TBEL function toFlatMap
  common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/TbUtils.java
  common/script/script-api/src/test/java/org/thingsboard/script/api/tbel/TbUtilsTest.java
Labels: Ignore for release

#8414 Feature/singleton rule node
  application/src/main/data/upgrade/3.4.4/schema_update.sql
  application/src/main/java/org/thingsboard/server/actors/ActorSystemContext.java
  application/src/main/java/org/thingsboard/server/actors/ruleChain/RuleNodeActorMessageProcessor.java
  application/src/main/java/org/thingsboard/server/service/component/AnnotationComponentDiscoveryService.java
  common/data/src/main/java/org/thingsboard/server/common/data/plugin/ComponentClusteringMode.java
  common/data/src/main/java/org/thingsboard/server/common/data/plugin/ComponentDescriptor.java
  common/data/src/main/java/org/thingsboard/server/common/data/rule/RuleNode.java
  dao/src/main/java/org/thingsboard/server/dao/model/ModelConstants.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/ComponentDescriptorEntity.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/RuleNodeEntity.java
  dao/src/main/java/org/thingsboard/server/dao/rule/BaseRuleChainService.java
  dao/src/main/java/org/thingsboard/server/dao/service/validator/RuleChainDataValidator.java
  dao/src/main/java/org/thingsboard/server/dao/sql/component/AbstractComponentDescriptorInsertRepository.java
  dao/src/main/java/org/thingsboard/server/dao/sql/component/SqlComponentDescriptorInsertRepository.java
  dao/src/main/resources/sql/schema-entities.sql
  rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/RuleNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/mqtt/TbMqttNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/mqtt/azure/TbAzureIotHubNode.java
  ui-ngx/src/app/modules/home/components/import-export/import-export.service.ts
  ui-ngx/src/app/modules/home/pages/rulechain/rule-node-details.component.html
  ui-ngx/src/app/modules/home/pages/rulechain/rule-node-details.component.scss
  ui-ngx/src/app/modules/home/pages/rulechain/rule-node-details.component.ts
  ui-ngx/src/app/modules/home/pages/rulechain/rulechain-page.component.ts
  ui-ngx/src/app/shared/models/component-descriptor.models.ts
  ui-ngx/src/app/shared/models/rule-chain.models.ts
  ui-ngx/src/app/shared/models/rule-node.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: Rule Engine

#8396 Fixed validation of the TBEL "foreach" loop in the "Script fuction" UI component
  ui-ngx/angular.json
  ui-ngx/src/app/shared/components/dialog/node-script-test-dialog.component.html
  ui-ngx/src/app/shared/components/js-func.component.ts
  ui-ngx/src/app/shared/models/ace/ace.models.ts
  ui-ngx/src/app/shared/models/ace/tbel/mode-tbel.js
  ui-ngx/src/app/shared/models/ace/tbel/worker-tbel.js
Labels: enhancement, UI

#8407 Fixed filters dialog button column width
  ui-ngx/src/app/modules/home/components/filter/filters-dialog.component.html
Labels: Bug, UI, Ignore for release

#8424 Navigation to particular delivery method settings from the "New notification" window
  ui-ngx/src/app/core/http/notification.service.ts
  ui-ngx/src/app/modules/home/components/notification/notification-bell.component.ts
  ui-ngx/src/app/modules/home/pages/notification/sent/sent-notification-dialog.component.html
  ui-ngx/src/app/modules/home/pages/notification/sent/sent-notification-dialog.component.scss
  ui-ngx/src/app/modules/home/pages/notification/sent/sent-notification-dialog.componet.ts
  ui-ngx/src/app/modules/home/pages/notification/template/template-notification-dialog.component.html
  ui-ngx/src/app/modules/home/pages/notification/template/template-notification-dialog.component.scss
  ui-ngx/src/app/shared/components/notification/notification.component.ts
  ui-ngx/src/app/shared/models/notification.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI, Ignore for release

#8419 Added assetProfileService to ServicesMap
  pull_request_template.md
  ui-ngx/src/app/modules/home/models/services.map.ts
Labels: enhancement, UI

#8428 Fix help link for resources
  ui-ngx/src/app/shared/models/constants.ts
  ui-ngx/src/app/shared/models/entity-type.models.ts
Labels: Bug, UI

#8439 Updated rulenode-core-config: added support TBEL linter
  rule-engine/rule-engine-components/src/main/resources/public/static/rulenode/rulenode-core-config.js
Labels: enhancement, Rule Engine, Ignore for release

#8435 Fix invalid removed outdated alarms count in logs
  application/src/main/java/org/thingsboard/server/service/ttl/AlarmsCleanUpService.java
  application/src/test/java/org/thingsboard/server/controller/AbstractWebTest.java
  application/src/test/java/org/thingsboard/server/service/notification/NotificationRuleApiTest.java
  application/src/test/java/org/thingsboard/server/service/ttl/AlarmsCleanUpServiceTest.java
Labels: Bug, Core

#8444 Fixed asset lifecycle message broadcasting in cluster mode
  application/src/main/java/org/thingsboard/server/service/queue/DefaultTbClusterService.java
Labels: Bug, Core
