Repository thingsboard/thingsboard, pull requests merged in 2023-10, with the labels that each got.

#9361 Fix failing tests
  application/src/test/java/org/thingsboard/server/service/notification/AbstractNotificationApiTest.java
  application/src/test/java/org/thingsboard/server/service/notification/NotificationApiTest.java
  application/src/test/java/org/thingsboard/server/service/notification/NotificationRuleApiTest.java
Labels: Ignore for release

#9364 Improvements for tenant deletion
  common/dao-api/src/main/java/org/thingsboard/server/dao/alarm/AlarmService.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/device/DeviceCredentialsService.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/entityview/EntityViewService.java
  dao/src/main/java/org/thingsboard/server/dao/alarm/AlarmDao.java
  dao/src/main/java/org/thingsboard/server/dao/alarm/BaseAlarmService.java
  dao/src/main/java/org/thingsboard/server/dao/asset/BaseAssetService.java
  dao/src/main/java/org/thingsboard/server/dao/dashboard/DashboardDao.java
  dao/src/main/java/org/thingsboard/server/dao/dashboard/DashboardServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/device/DeviceCredentialsDao.java
  dao/src/main/java/org/thingsboard/server/dao/device/DeviceCredentialsServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/device/DeviceServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/entity/AbstractEntityService.java
  dao/src/main/java/org/thingsboard/server/dao/entityview/EntityViewDao.java
  dao/src/main/java/org/thingsboard/server/dao/entityview/EntityViewServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/service/PaginatedRemover.java
  dao/src/main/java/org/thingsboard/server/dao/sql/alarm/EntityAlarmRepository.java
  dao/src/main/java/org/thingsboard/server/dao/sql/alarm/JpaAlarmDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/dashboard/DashboardRepository.java
  dao/src/main/java/org/thingsboard/server/dao/sql/dashboard/JpaDashboardDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/device/DeviceCredentialsRepository.java
  dao/src/main/java/org/thingsboard/server/dao/sql/device/JpaDeviceCredentialsDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/entityview/EntityViewRepository.java
  dao/src/main/java/org/thingsboard/server/dao/sql/entityview/JpaEntityViewDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/user/JpaUserCredentialsDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/user/UserCredentialsRepository.java
  dao/src/main/java/org/thingsboard/server/dao/tenant/TenantServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/user/UserCredentialsDao.java
  dao/src/main/java/org/thingsboard/server/dao/user/UserServiceImpl.java
Labels: Ignore for release

#9393 Command whitespaces hotfix
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-configuration.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-configuration.component.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: Bug, UI

#9402 Fix chart widgets color transparency not working in hex and hsla formats
  ui-ngx/src/app/modules/home/components/widget/lib/flot-widget.ts
Labels: Bug, UI

#9398 Improvement of alarm additional info usability
  ui-ngx/src/app/modules/home/components/profile/alarm/alarm-rule.component.html
  ui-ngx/src/app/modules/home/components/profile/alarm/edit-alarm-details-dialog.component.html
  ui-ngx/src/assets/locale/locale.constant-ca_ES.json
  ui-ngx/src/assets/locale/locale.constant-cs_CZ.json
  ui-ngx/src/assets/locale/locale.constant-da_DK.json
  ui-ngx/src/assets/locale/locale.constant-en_US.json
  ui-ngx/src/assets/locale/locale.constant-es_ES.json
  ui-ngx/src/assets/locale/locale.constant-ko_KR.json
  ui-ngx/src/assets/locale/locale.constant-sl_SI.json
  ui-ngx/src/assets/locale/locale.constant-tr_TR.json
  ui-ngx/src/assets/locale/locale.constant-zh_CN.json
  ui-ngx/src/assets/locale/locale.constant-zh_TW.json
Labels: enhancement, UI

#9391 Enabled all delete strategies for multiple delete timeseries UI
  ui-ngx/src/app/modules/home/components/attribute/attribute-table.component.ts
  ui-ngx/src/app/modules/home/components/attribute/delete-timeseries-panel.component.ts
Labels: enhancement, UI

#9389 Fixed tenant profile dialog
  ui-ngx/src/app/modules/home/components/profile/tenant-profile-dialog.component.html
  ui-ngx/src/app/modules/home/components/profile/tenant-profile-dialog.component.scss
  ui-ngx/src/app/modules/home/components/profile/tenant-profile-dialog.component.ts
  ui-ngx/src/app/modules/home/components/queue/queue-form.component.html
Labels: enhancement, UI

#9387 Fixed tenant profile autocomplete hide edit button and add create new button
  ui-ngx/src/app/modules/home/components/profile/tenant-profile-autocomplete.component.html
Labels: enhancement, UI

#9382 Improvement for notification settings
  ui-ngx/src/app/modules/home/pages/notification/settings/notification-setting-form.component.html
  ui-ngx/src/app/modules/home/pages/notification/settings/notification-setting-form.component.ts
  ui-ngx/src/app/modules/home/pages/notification/settings/notification-settings.component.html
  ui-ngx/src/app/modules/home/pages/notification/settings/notification-settings.component.ts
Labels: enhancement, UI

#9372 Alarm table settings replace alarm source
  ui-ngx/src/app/modules/home/components/widget/config/basic/alarm/alarms-table-basic-config.component.html
Labels: enhancement, UI

#9351 Update es_ES locale to 3.6
  ui-ngx/src/assets/locale/locale.constant-es_ES.json
Labels: UI

#9335 Update locale.constant-de_DE.json
  ui-ngx/src/assets/locale/locale.constant-de_DE.json
Labels: UI

#9332 Fixed dashboard detail button
  ui-ngx/src/app/modules/home/pages/dashboard/dashboard-form.component.html
Labels: Bug, UI

#9331 Fixed translation on change lang
  ui-ngx/src/app/core/auth/auth.service.ts
Labels: Bug, UI

#9322 Updated screenshots for rulenode examples
  ui-ngx/src/assets/help/images/rulenode/examples/customer-attributes-ft.png
  ui-ngx/src/assets/help/images/rulenode/examples/originator-attributes-ft.png
  ui-ngx/src/assets/help/images/rulenode/examples/originator-fields-ft.png
  ui-ngx/src/assets/help/images/rulenode/examples/originator-telemetry-ft-2.png
  ui-ngx/src/assets/help/images/rulenode/examples/originator-telemetry-ft.png
  ui-ngx/src/assets/help/images/rulenode/examples/related-device-attributes-ft.png
  ui-ngx/src/assets/help/images/rulenode/examples/related-entity-data-ft.png
  ui-ngx/src/assets/help/images/rulenode/examples/tenant-attributes-ft.png
Labels: enhancement, UI

#9277 Added default label for entity list
  ui-ngx/src/app/modules/home/components/entity/entity-filter.component.html
Labels: enhancement, UI

#9265 Added client/server/shared attribute to key filter
  ui-ngx/src/app/modules/home/components/filter/key-filter-dialog.component.ts
  ui-ngx/src/app/shared/models/query/query.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI

#9422 DefaultNotificationRuleProcessor - submit to executor sooner
  application/src/main/java/org/thingsboard/server/service/notification/rule/DefaultNotificationRuleProcessor.java
Labels: Ignore for release

#9419 tenant publish event fix: tenant_id instead sys_tenant_id to avoid br…
  dao/src/main/java/org/thingsboard/server/dao/tenant/TenantServiceImpl.java
Labels: Bug

#9318 Api rate limits for TBEL UI
  ui-ngx/src/app/modules/home/components/profile/tenant/default-tenant-profile-configuration.component.html
  ui-ngx/src/app/modules/home/components/profile/tenant/default-tenant-profile-configuration.component.ts
  ui-ngx/src/app/shared/models/api-usage.models.ts
  ui-ngx/src/app/shared/models/tenant.model.ts
  ui-ngx/src/assets/dashboard/api_usage.json
  ui-ngx/src/assets/locale/locale.constant-ca_ES.json
  ui-ngx/src/assets/locale/locale.constant-cs_CZ.json
  ui-ngx/src/assets/locale/locale.constant-da_DK.json
  ui-ngx/src/assets/locale/locale.constant-en_US.json
  ui-ngx/src/assets/locale/locale.constant-es_ES.json
  ui-ngx/src/assets/locale/locale.constant-fr_FR.json
  ui-ngx/src/assets/locale/locale.constant-ko_KR.json
  ui-ngx/src/assets/locale/locale.constant-sl_SI.json
  ui-ngx/src/assets/locale/locale.constant-tr_TR.json
  ui-ngx/src/assets/locale/locale.constant-zh_CN.json
  ui-ngx/src/assets/locale/locale.constant-zh_TW.json
Labels: enhancement, UI

#9441 fixed rule nodes upgrade script
  application/src/main/java/org/thingsboard/server/service/install/update/DefaultDataUpdateService.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/rule/RuleChainService.java
  dao/src/main/java/org/thingsboard/server/dao/rule/BaseRuleChainService.java
  dao/src/main/java/org/thingsboard/server/dao/rule/RuleNodeDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/rule/JpaRuleNodeDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/rule/RuleNodeRepository.java
  dao/src/test/java/org/thingsboard/server/dao/sql/rule/JpaRuleNodeDaoTest.java
Labels: Bug, Build Scripts

#9429 Rule Engine consumer service refactoring
  application/src/main/java/org/thingsboard/server/service/queue/DefaultTbCoreConsumerService.java
  application/src/main/java/org/thingsboard/server/service/queue/DefaultTbRuleEngineConsumerService.java
  application/src/main/java/org/thingsboard/server/service/queue/TbRuleEngineConsumerStats.java
  application/src/main/java/org/thingsboard/server/service/queue/processing/AbstractConsumerService.java
  application/src/main/java/org/thingsboard/server/service/queue/ruleengine/QueueEvent.java
  application/src/main/java/org/thingsboard/server/service/queue/ruleengine/TbQueueConsumerManagerTask.java
  application/src/main/java/org/thingsboard/server/service/queue/ruleengine/TbQueueConsumerTask.java
  application/src/main/java/org/thingsboard/server/service/queue/ruleengine/TbRuleEngineConsumerContext.java
  application/src/main/java/org/thingsboard/server/service/queue/ruleengine/TbRuleEngineQueueConsumerManager.java
  application/src/main/resources/thingsboard.yml
  application/src/test/java/org/thingsboard/server/controller/BaseQueueControllerTest.java
  application/src/test/java/org/thingsboard/server/controller/TenantControllerTest.java
  application/src/test/java/org/thingsboard/server/service/queue/ruleengine/TbRuleEngineQueueConsumerManagerTest.java
  common/cluster-api/src/main/java/org/thingsboard/server/queue/TbQueueConsumer.java
  common/queue/src/main/java/org/thingsboard/server/queue/common/AbstractTbQueueConsumerTemplate.java
  common/queue/src/main/java/org/thingsboard/server/queue/kafka/TbKafkaConsumerTemplate.java
  common/queue/src/main/java/org/thingsboard/server/queue/memory/InMemoryTbQueueConsumer.java
Labels: Ignore for release

#9427 Added breadcrumbs when navigate to editing widgets from the widget bundle
  ui-ngx/src/app/modules/home/pages/widget/widget-library-routing.module.ts
  ui-ngx/src/app/modules/home/pages/widget/widgets-bundle-widgets.component.ts
Labels: enhancement, UI

#9435 Improvement default widget bundle in attributes/timeseries tables
  ui-ngx/src/app/modules/home/components/attribute/attribute-table.component.ts
Labels: enhancement, UI

#9445 Rename widget type to widget
  ui-ngx/src/app/modules/home/components/import-export/import-export.service.ts
  ui-ngx/src/app/modules/home/pages/widget/save-widget-type-as-dialog.component.html
  ui-ngx/src/app/modules/home/pages/widget/widget-type.component.html
  ui-ngx/src/app/modules/home/pages/widget/widget-types-table-config.resolver.ts
  ui-ngx/src/app/modules/home/pages/widget/widgets-bundle-widgets.component.html
  ui-ngx/src/app/shared/models/entity-type.models.ts
  ui-ngx/src/assets/locale/locale.constant-ca_ES.json
  ui-ngx/src/assets/locale/locale.constant-cs_CZ.json
  ui-ngx/src/assets/locale/locale.constant-da_DK.json
  ui-ngx/src/assets/locale/locale.constant-de_DE.json
  ui-ngx/src/assets/locale/locale.constant-el_GR.json
  ui-ngx/src/assets/locale/locale.constant-en_US.json
  ui-ngx/src/assets/locale/locale.constant-es_ES.json
  ui-ngx/src/assets/locale/locale.constant-fa_IR.json
  ui-ngx/src/assets/locale/locale.constant-fr_FR.json
  ui-ngx/src/assets/locale/locale.constant-it_IT.json
  ui-ngx/src/assets/locale/locale.constant-ja_JP.json
  ui-ngx/src/assets/locale/locale.constant-ka_GE.json
  ui-ngx/src/assets/locale/locale.constant-ko_KR.json
  ui-ngx/src/assets/locale/locale.constant-lv_LV.json
  ui-ngx/src/assets/locale/locale.constant-pt_BR.json
  ui-ngx/src/assets/locale/locale.constant-ro_RO.json
  ui-ngx/src/assets/locale/locale.constant-ru_RU.json
  ui-ngx/src/assets/locale/locale.constant-sl_SI.json
  ui-ngx/src/assets/locale/locale.constant-tr_TR.json
  ui-ngx/src/assets/locale/locale.constant-uk_UA.json
  ui-ngx/src/assets/locale/locale.constant-zh_CN.json
  ui-ngx/src/assets/locale/locale.constant-zh_TW.json
Labels: enhancement, UI

#9472 Improved show confirm on exit dialog in widget editor
  ui-ngx/src/app/core/guards/confirm-on-exit.guard.ts
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.ts
  ui-ngx/src/app/modules/home/pages/widget/widget-editor.component.ts
  ui-ngx/src/app/shared/models/window-message.model.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI

#9442 Improvement for font settings panel added settings to disabled and hide line height
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/font-settings-panel.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/font-settings-panel.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/font-settings.component.ts
Labels: enhancement, UI

#9468 Add support select widget bundle when save as widget
  ui-ngx/src/app/modules/home/components/attribute/attribute-table.component.html
  ui-ngx/src/app/modules/home/pages/widget/save-widget-type-as-dialog.component.html
  ui-ngx/src/app/modules/home/pages/widget/save-widget-type-as-dialog.component.ts
  ui-ngx/src/app/modules/home/pages/widget/widget-editor.component.ts
  ui-ngx/src/app/shared/components/widgets-bundle-select.component.html
  ui-ngx/src/app/shared/components/widgets-bundle-select.component.ts
Labels: enhancement, UI

#9448 Fixed position of help icon in custom date config of card widgets
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/date-format-settings-panel.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/date-format-settings-panel.component.scss
Labels: Bug, UI

#9449 Added decibel-milliwatts unit to dictionary
  ui-ngx/src/assets/locale/locale.constant-en_US.json
  ui-ngx/src/assets/metadata/units.json
Labels: enhancement, UI

#9459 Fixed advanced widget setting boarder radius property
  ui-ngx/src/app/modules/home/models/dashboard-component.models.ts
Labels: Bug, UI

#9460 Fixed state chart default legend position not set
  application/src/main/data/json/system/widget_types/state_chart.json
Labels: Bug, UI

#9469 Changed 'Java Script' to 'JavaScript'
  ui-ngx/src/assets/locale/locale.constant-en_US.json
  ui-ngx/src/assets/locale/locale.constant-es_ES.json
  ui-ngx/src/assets/locale/locale.constant-zh_CN.json
Labels: enhancement, UI

#9425 Optimizations for Edge Queue Event Storage and Server Load Reduction
  application/src/main/java/org/thingsboard/server/service/edge/EdgeEventSourcingListener.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/BaseEdgeProcessor.java
  application/src/test/java/org/thingsboard/server/controller/AlarmControllerTest.java
  application/src/test/java/org/thingsboard/server/controller/EdgeControllerTest.java
  application/src/test/java/org/thingsboard/server/controller/EdgeEventControllerTest.java
  application/src/test/java/org/thingsboard/server/edge/AbstractEdgeTest.java
  application/src/test/java/org/thingsboard/server/edge/AlarmEdgeTest.java
  application/src/test/java/org/thingsboard/server/edge/DeviceEdgeTest.java
  application/src/test/java/org/thingsboard/server/edge/UserEdgeTest.java
  dao/src/main/java/org/thingsboard/server/dao/eventsourcing/SaveEntityEvent.java
  dao/src/main/java/org/thingsboard/server/dao/user/UserServiceImpl.java
  ui-ngx/src/app/core/http/entity.service.ts
Labels: Edge, Ignore for release

#9474 Fixed testIsolatedTenantProfile - correct expected number of downlink msgs
  application/src/test/java/org/thingsboard/server/edge/TenantProfileEdgeTest.java
Labels: Ignore for release

#9494 Version control: fix edgeRuleChainId substitution for asset and device profiles
  application/src/main/java/org/thingsboard/server/service/sync/ie/exporting/impl/AssetProfileExportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/exporting/impl/DeviceProfileExportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/AssetProfileImportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/DeviceProfileImportService.java
Labels: Bug, Core

#9491 Fix 'Device created' notification when creating alarm using REST API
  application/src/main/java/org/thingsboard/server/controller/NotificationController.java
  application/src/main/java/org/thingsboard/server/controller/NotificationRuleController.java
  application/src/main/java/org/thingsboard/server/controller/NotificationTargetController.java
  application/src/main/java/org/thingsboard/server/controller/NotificationTemplateController.java
  application/src/main/java/org/thingsboard/server/service/action/EntityActionService.java
  application/src/test/java/org/thingsboard/server/service/notification/NotificationRuleApiTest.java
Labels: Bug, Core

#9515 Increased default value of EDGES_SLEEP_BETWEEN_BATCHES to handle 2G/3G connections
  application/src/main/resources/thingsboard.yml
Labels: Edge, Ignore for release

#9513 Distribute partitions between Rule Engines based only on tenant id
  application/src/test/java/org/thingsboard/server/queue/discovery/HashPartitionServiceTest.java
  common/queue/src/main/java/org/thingsboard/server/queue/discovery/HashPartitionService.java
Labels: Ignore for release

#9437 Added ability to add global prefix for all topics
  application/src/main/java/org/thingsboard/server/service/notification/DefaultNotificationCenter.java
  application/src/main/java/org/thingsboard/server/service/queue/DefaultTbClusterService.java
  application/src/main/java/org/thingsboard/server/service/subscription/DefaultSubscriptionManagerService.java
  application/src/main/java/org/thingsboard/server/service/transport/DefaultTbCoreToTransportService.java
  application/src/main/resources/thingsboard.yml
  application/src/test/java/org/thingsboard/server/queue/discovery/HashPartitionServiceTest.java
  application/src/test/java/org/thingsboard/server/service/queue/DefaultTbClusterServiceTest.java
  common/cluster-api/src/main/java/org/thingsboard/server/cluster/TbClusterService.java
  common/queue/src/main/java/org/thingsboard/server/queue/discovery/HashPartitionService.java
  common/queue/src/main/java/org/thingsboard/server/queue/discovery/TopicService.java
  common/queue/src/main/java/org/thingsboard/server/queue/notification/RemoteNotificationRuleProcessor.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/AwsSqsMonolithQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/AwsSqsTbCoreQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/AwsSqsTbRuleEngineQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/AwsSqsTbVersionControlQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/AwsSqsTransportQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/InMemoryMonolithQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/InMemoryTbTransportQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/KafkaMonolithQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/KafkaTbCoreQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/KafkaTbRuleEngineQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/KafkaTbTransportQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/KafkaTbVersionControlQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/PubSubMonolithQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/PubSubTbCoreQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/PubSubTbRuleEngineQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/PubSubTbVersionControlQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/PubSubTransportQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/RabbitMqMonolithQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/RabbitMqTbCoreQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/RabbitMqTbRuleEngineQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/RabbitMqTbVersionControlQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/RabbitMqTransportQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/ServiceBusMonolithQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/ServiceBusTbCoreQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/ServiceBusTbRuleEngineQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/ServiceBusTbVersionControlQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/ServiceBusTransportQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/settings/TbQueueRemoteJsInvokeSettings.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/service/DefaultTransportService.java
  common/version-control/src/main/java/org/thingsboard/server/service/sync/vc/DefaultClusterVersionControlService.java
  msa/vc-executor/src/main/resources/tb-vc-executor.yml
  transport/coap/src/main/resources/tb-coap-transport.yml
  transport/http/src/main/resources/tb-http-transport.yml
  transport/lwm2m/src/main/resources/tb-lwm2m-transport.yml
  transport/mqtt/src/main/resources/tb-mqtt-transport.yml
  transport/snmp/src/main/resources/tb-snmp-transport.yml
Labels: enhancement

#9456 Feature/level widget
  application/src/main/data/json/system/widget_bundles/liquid_level_tanks.json
  application/src/main/data/json/system/widget_types/horizontal_2_1_elliptical_tank.json
  application/src/main/data/json/system/widget_types/horizontal_capsule_tank.json
  application/src/main/data/json/system/widget_types/horizontal_cylinder_tank.json
  application/src/main/data/json/system/widget_types/horizontal_dish_ends_tank.json
  application/src/main/data/json/system/widget_types/horizontal_ellipse_tank.json
  application/src/main/data/json/system/widget_types/horizontal_oval_tank.json
  application/src/main/data/json/system/widget_types/rectangle_tank.json
  application/src/main/data/json/system/widget_types/vertical_capsule_tank.json
  application/src/main/data/json/system/widget_types/vertical_cylinder_tank.json
  application/src/main/data/json/system/widget_types/vertical_oval_tank.json
  application/src/main/java/org/thingsboard/server/service/install/DefaultSystemDataLoaderService.java
  ui-ngx/src/app/core/http/attribute.service.ts
  ui-ngx/src/app/core/services/resources.service.ts
  ui-ngx/src/app/modules/home/components/widget/config/basic/basic-widget-config.module.ts
  ui-ngx/src/app/modules/home/components/widget/config/basic/indicator/liquid-level-card-basic-config.component.html
  ui-ngx/src/app/modules/home/components/widget/config/basic/indicator/liquid-level-card-basic-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/indicator/liquid-level-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/indicator/liquid-level-widget.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/indicator/liquid-level-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/indicator/liquid-level-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/image-cards-select.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/image-cards-select.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/image-cards-select.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/indicator/liquid-level-card-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/indicator/liquid-level-card-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/widget-settings.module.ts
  ui-ngx/src/app/modules/home/components/widget/widget-components.module.ts
  ui-ngx/src/app/shared/components/string-autocomplete.component.html
  ui-ngx/src/app/shared/components/string-autocomplete.component.scss
  ui-ngx/src/app/shared/components/string-autocomplete.component.ts
  ui-ngx/src/app/shared/components/unit-input.component.html
  ui-ngx/src/app/shared/components/unit-input.component.ts
  ui-ngx/src/app/shared/models/unit.models.ts
  ui-ngx/src/app/shared/models/widget-settings.models.ts
  ui-ngx/src/app/shared/shared.module.ts
  ui-ngx/src/assets/help/en_US/widget/lib/indicator/shape_attribute_fn.md
  ui-ngx/src/assets/locale/locale.constant-en_US.json
  ui-ngx/src/assets/metadata/units.json
  ui-ngx/src/assets/widget/liquid-level/shapes/horizontal-2_1-elliptical.svg
  ui-ngx/src/assets/widget/liquid-level/shapes/horizontal-capsule.svg
  ui-ngx/src/assets/widget/liquid-level/shapes/horizontal-cylinder.svg
  ui-ngx/src/assets/widget/liquid-level/shapes/horizontal-dish-ends.svg
  ui-ngx/src/assets/widget/liquid-level/shapes/horizontal-ellipse.svg
  ui-ngx/src/assets/widget/liquid-level/shapes/horizontal-oval.svg
  ui-ngx/src/assets/widget/liquid-level/shapes/rectangle.svg
  ui-ngx/src/assets/widget/liquid-level/shapes/vertical-capsule.svg
  ui-ngx/src/assets/widget/liquid-level/shapes/vertical-cylinder.svg
  ui-ngx/src/assets/widget/liquid-level/shapes/vertical-oval.svg
  ui-ngx/src/form.scss
  ui-ngx/src/styles.scss
Labels: UI, Feature

#9473 HTML/markdown changes detection on parsing invalid html string
  ui-ngx/src/app/shared/components/markdown.component.ts
Labels: Bug, UI

#9484 Color range setting
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/color-range-list.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/color-range-list.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/color-range-panel.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/color-range-panel.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/color-range-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/color-range-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/color-settings-panel.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/color-settings-panel.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/widget-settings-common.module.ts
Labels: enhancement, UI

#9485 Improvement for gauge widgets settings
  application/src/main/data/json/system/widget_types/compass.json
  application/src/main/data/json/system/widget_types/radial_gauge.json
  application/src/main/data/json/system/widget_types/speed_gauge.json
  application/src/main/data/json/system/widget_types/temperature_radial_gauge.json
  application/src/main/data/json/system/widget_types/thermometer_scale.json
  ui-ngx/src/app/modules/home/components/widget/config/basic/basic-widget-config.module.ts
  ui-ngx/src/app/modules/home/components/widget/config/basic/gauge/analog-gauge-basic-config.component.html
  ui-ngx/src/app/modules/home/components/widget/config/basic/gauge/analog-gauge-basic-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/config/basic/gauge/compass-gauge-basic-config.component.html
  ui-ngx/src/app/modules/home/components/widget/config/basic/gauge/compass-gauge-basic-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/config/basic/gauge/radial-gauge-basic-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/config/basic/gauge/thermometer-scale-gauge-basic-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/font-settings-panel.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/gauge/analogue-compass-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/gauge/analogue-compass-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/gauge/analogue-gauge-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/gauge/analogue-gauge-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/gauge/gauge-highlight.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/gauge/gauge-highlight.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/settings/gauge/gauge-highlight.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/widget-settings.module.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI

#9489 Fixed rule chain selector padding
  ui-ngx/src/app/shared/components/rule-chain/rule-chain-select.component.scss
Labels: Bug, UI

#9500 Improved translations in component
  ui-ngx/src/app/modules/home/components/relation/relation-filters.component.html
  ui-ngx/src/app/shared/components/entity/entity-subtype-list.component.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI

#9501 Add basic settigs for admin table widgets
  application/src/main/data/json/system/widget_types/asset_admin_table.json
  application/src/main/data/json/system/widget_types/device_admin_table.json
Labels: enhancement, UI

#9502 Fixed missing or bad German translations
  ui-ngx/src/assets/locale/locale.constant-de_DE.json
Labels: enhancement, UI

#9185 Edge Synchronization improvement using EdgeId
  application/src/main/java/org/thingsboard/server/service/edge/EdgeEventSourcingListener.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/constructor/rule/AbstractRuleChainMetadataConstructor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/constructor/rule/RuleChainMetadataConstructorV330.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/constructor/rule/RuleChainMetadataConstructorV340.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/fetch/AdminSettingsEdgeEventFetcher.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/BaseEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/alarm/AlarmEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/alarm/BaseAlarmProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/asset/AssetEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/asset/AssetProfileEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/dashboard/DashboardEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/device/BaseDeviceProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/device/DeviceEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/device/DeviceProfileEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/edge/EdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/entityview/EntityViewEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/relation/BaseRelationProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/relation/RelationEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/settings/AdminSettingsEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/telemetry/BaseTelemetryProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/sync/DefaultEdgeRequestsService.java
  application/src/main/java/org/thingsboard/server/service/queue/DefaultTbClusterService.java
  application/src/test/java/org/thingsboard/server/controller/AbstractNotifyEntityTest.java
  application/src/test/java/org/thingsboard/server/edge/DeviceEdgeTest.java
  application/src/test/java/org/thingsboard/server/service/sync/ie/ExportImportServiceSqlTest.java
  common/cluster-api/src/main/java/org/thingsboard/server/cluster/TbClusterService.java
  common/cluster-api/src/main/proto/queue.proto
  common/dao-api/src/main/java/org/thingsboard/server/dao/edge/EdgeSynchronizationManager.java
  dao/src/main/java/org/thingsboard/server/dao/edge/DefaultEdgeSynchronizationManager.java
  dao/src/main/java/org/thingsboard/server/dao/eventsourcing/DeleteEntityEvent.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/rpc/TbSendRPCReplyNode.java
Labels: Edge
