Repository thingsboard/thingsboard, pull requests merged in 2023-06, with the labels that each got.

#8695 added field templatization docs for enrichment rule nodes & added java doc for upgrade method in TbVersionedNode interface
  rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/TbVersionedNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/TbAbstractTransformNode.java
  rule-engine/rule-engine-components/src/main/resources/public/static/rulenode/rulenode-core-config.js
  ui-ngx/src/assets/help/en_US/rulenode/common_node_fields_templatization.md
  ui-ngx/src/assets/help/en_US/rulenode/customer_attributes_node_fields_templatization.md
  ui-ngx/src/assets/help/en_US/rulenode/msg_and_metadata_key_patterns_fn.md
  ui-ngx/src/assets/help/en_US/rulenode/originator_attributes_node_fields_templatization.md
  ui-ngx/src/assets/help/en_US/rulenode/originator_fields_node_fields_templatization.md
  ui-ngx/src/assets/help/en_US/rulenode/originator_telemetry_node_fields_templatization.md
  ui-ngx/src/assets/help/en_US/rulenode/related_device_attributes_node_fields_templatization.md
  ui-ngx/src/assets/help/en_US/rulenode/related_entity_data_node_fields_templatization.md
  ui-ngx/src/assets/help/en_US/rulenode/tenant_attributes_node_fields_templatization.md
  ui-ngx/src/assets/help/images/rulenode/examples/customer-attributes-ft.png
  ui-ngx/src/assets/help/images/rulenode/examples/originator-attributes-ft.png
  ui-ngx/src/assets/help/images/rulenode/examples/originator-fields-ft.png
  ui-ngx/src/assets/help/images/rulenode/examples/originator-telemetry-ft-2.png
  ui-ngx/src/assets/help/images/rulenode/examples/originator-telemetry-ft-3.png
  ui-ngx/src/assets/help/images/rulenode/examples/originator-telemetry-ft.png
  ui-ngx/src/assets/help/images/rulenode/examples/related-device-attributes-ft.png
  ui-ngx/src/assets/help/images/rulenode/examples/related-entity-data-ft-2.png
  ui-ngx/src/assets/help/images/rulenode/examples/related-entity-data-ft.png
  ui-ngx/src/assets/help/images/rulenode/examples/tenant-attributes-ft.png
Labels: WIP, Ignore for release

#8706 Fixes for models in Swagger
  common/data/src/main/java/org/thingsboard/server/common/data/id/NotificationId.java
  common/data/src/main/java/org/thingsboard/server/common/data/id/NotificationRequestId.java
  common/data/src/main/java/org/thingsboard/server/common/data/id/NotificationRuleId.java
  common/data/src/main/java/org/thingsboard/server/common/data/id/NotificationTargetId.java
  common/data/src/main/java/org/thingsboard/server/common/data/id/NotificationTemplateId.java
  common/data/src/main/java/org/thingsboard/server/common/data/id/QueueId.java
Labels: Bug

#8587 Added the option to edit notification templates in the template selector
  ui-ngx/src/app/modules/home/pages/notification/rule/rule-notification-dialog.component.html
  ui-ngx/src/app/modules/home/pages/notification/sent/sent-notification-dialog.component.html
  ui-ngx/src/app/shared/components/notification/template-autocomplete.component.html
  ui-ngx/src/app/shared/components/notification/template-autocomplete.component.ts
Labels: enhancement, UI

#8571 Added columns visibility for Timeseries table
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/timeseries-table-key-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/timeseries-table-key-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/timeseries-table-latest-key-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/timeseries-table-latest-key-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/timeseries-table-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/timeseries-table-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/table-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/timeseries-table-widget.component.ts
Labels: UI, Feature

#8728 fixed azure root ca load
  common/util/src/main/java/org/thingsboard/common/util/AzureIotHubUtil.java
Labels: Ignore for release

#8721 Add ToggleHeaderComponent to the module-map
  ui-ngx/src/app/modules/common/modules-map.ts
Labels: enhancement, UI

#8722 Math function rule node: fixed validation
  rule-engine/rule-engine-components/src/main/resources/public/static/rulenode/rulenode-core-config.js
Labels: Bug, UI, Rule Engine

#8713 RPC queue stuck issue on response handling for undelivered rpc && logging improvements
  application/src/main/java/org/thingsboard/server/actors/device/DeviceActor.java
  application/src/main/java/org/thingsboard/server/actors/device/DeviceActorMessageProcessor.java
  application/src/main/resources/logback.xml
  application/src/test/java/org/thingsboard/server/transport/coap/CoapTestCallback.java
  application/src/test/java/org/thingsboard/server/transport/coap/attributes/AbstractCoapAttributesIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/coap/rpc/AbstractCoapServerSideRpcIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/mqtt/mqttv3/MqttTestCallback.java
  application/src/test/java/org/thingsboard/server/transport/mqtt/mqttv3/MqttTestSubscribeOnTopicCallback.java
  application/src/test/java/org/thingsboard/server/transport/mqtt/mqttv3/attributes/AbstractMqttAttributesIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/mqtt/mqttv3/provision/MqttProvisionJsonDeviceTest.java
  application/src/test/java/org/thingsboard/server/transport/mqtt/mqttv3/provision/MqttProvisionProtoDeviceTest.java
  application/src/test/java/org/thingsboard/server/transport/mqtt/mqttv3/rpc/AbstractMqttServerSideRpcIntegrationTest.java
  application/src/test/resources/logback-test.xml
  common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/client/DefaultCoapClientContext.java
  common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttTransportHandler.java
Labels: Bug, enhancement

#8745 Fixed oauth2 mail server settings
  ui-ngx/src/app/modules/home/pages/admin/mail-server.component.html
  ui-ngx/src/app/modules/home/pages/admin/mail-server.component.ts
Labels: Bug, UI, Ignore for release

#7793 Add "Enable selection mode" settings with touch event for bar/state/line chart-widgets
  application/src/main/data/json/system/widget_bundles/charts.json
  ui-ngx/src/app/modules/home/components/widget/lib/flot-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/flot-widget.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/chart/flot-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/chart/flot-widget-settings.component.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
  ui-ngx/src/typings/jquery.flot.typings.d.ts
Labels: UI, Feature

#8740 Fixed OAuth2 deletion domains/mobile applications/providers settings
  ui-ngx/src/app/modules/home/pages/admin/oauth2-settings.component.html
  ui-ngx/src/app/modules/home/pages/admin/oauth2-settings.component.ts
Labels: Bug, UI

#8784 Fixed 'Notify again' dialog in notification center
  ui-ngx/src/app/modules/home/pages/notification/sent/sent-notification-dialog.componet.ts
Labels: Bug, UI

#8812 Added icon for rule chain selector
  ui-ngx/src/app/shared/components/rule-chain/rule-chain-select.component.html
  ui-ngx/src/app/shared/components/rule-chain/rule-chain-select.component.scss
Labels: enhancement, UI, Ignore for release

#8814 Fixed dashboard state selection in toolbar on mobile view
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-toolbar.component.scss
Labels: Bug, UI

#8821 Added z-index for selected rule node
  ui-ngx/src/app/modules/home/pages/rulechain/rulechain-page.component.scss
Labels: enhancement, UI, Rule Engine

#8826 [3.5.2] Fix prod-2207: display correctly analogue gauge values
  ui-ngx/src/app/modules/home/components/widget/lib/analogue-gauge.models.ts
Labels: Bug, UI

#8828 Fixed width Clear alarm rule section
  ui-ngx/src/app/modules/home/components/profile/alarm/device-profile-alarm.component.scss
Labels: Bug, UI

#8831 Fixed Timeseries table widget display columns without sources
  ui-ngx/src/app/modules/home/components/widget/lib/timeseries-table-widget.component.ts
Labels: Bug, UI, Ignore for release

#8832 Remove specify alarm notification style for cleared alarm notification
  application/src/main/java/org/thingsboard/server/service/notification/rule/trigger/AlarmTriggerProcessor.java
  common/data/src/main/java/org/thingsboard/server/common/data/alarm/Alarm.java
  common/data/src/main/java/org/thingsboard/server/common/data/notification/info/AlarmNotificationInfo.java
  ui-ngx/src/app/shared/components/notification/notification.component.html
  ui-ngx/src/app/shared/components/notification/notification.component.ts
  ui-ngx/src/app/shared/models/notification.models.ts
Labels: enhancement, UI

#8834 Fixed loading widget data for 'previous quarter' and 'previous half year' timewindow intervals
  ui-ngx/src/app/shared/models/time/time.models.ts
Labels: Bug, UI

#8808 HotFix - fixed init of rule chains - init only on APP_INIT msg
  application/src/main/java/org/thingsboard/server/actors/app/AppActor.java
  application/src/main/java/org/thingsboard/server/service/queue/DefaultTbRuleEngineConsumerService.java
  application/src/main/java/org/thingsboard/server/service/queue/processing/AbstractConsumerService.java
  common/message/src/main/java/org/thingsboard/server/common/msg/MsgType.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/profile/TbDeviceProfileNode.java
Labels: Bug, Core

#8830 Edge event table - added sequential ID column to handle properly heavy load and cluster cases
  application/src/main/data/upgrade/3.5.1/schema_update.sql
  application/src/main/java/org/thingsboard/server/controller/EdgeEventController.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcService.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/constructor/AlarmMsgConstructor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/fetch/GeneralEdgeEventFetcher.java
  application/src/main/java/org/thingsboard/server/service/install/update/DefaultDataUpdateService.java
  application/src/test/java/org/thingsboard/server/edge/AbstractEdgeTest.java
  application/src/test/java/org/thingsboard/server/edge/imitator/EdgeImitator.java
  application/src/test/resources/application-test.properties
  common/dao-api/src/main/java/org/thingsboard/server/dao/edge/EdgeEventService.java
  common/data/src/main/java/org/thingsboard/server/common/data/edge/EdgeEvent.java
  dao/src/main/java/org/thingsboard/server/dao/edge/BaseEdgeEventService.java
  dao/src/main/java/org/thingsboard/server/dao/edge/EdgeEventDao.java
  dao/src/main/java/org/thingsboard/server/dao/model/ModelConstants.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/EdgeEventEntity.java
  dao/src/main/java/org/thingsboard/server/dao/sql/edge/EdgeEventRepository.java
  dao/src/main/java/org/thingsboard/server/dao/sql/edge/JpaBaseEdgeEventDao.java
  dao/src/main/resources/sql/schema-entities.sql
  dao/src/test/java/org/thingsboard/server/dao/service/EdgeEventServiceTest.java
  dao/src/test/resources/sql/system-test-psql.sql
Labels: Bug, Edge

#8839 Added cache for resource info
  application/src/main/resources/thingsboard.yml
  common/cache/src/main/java/org/thingsboard/server/cache/resourceInfo/ResourceInfoCacheKey.java
  common/cache/src/main/java/org/thingsboard/server/cache/resourceInfo/ResourceInfoCaffeineCache.java
  common/cache/src/main/java/org/thingsboard/server/cache/resourceInfo/ResourceInfoEvictEvent.java
  common/cache/src/main/java/org/thingsboard/server/cache/resourceInfo/ResourceInfoRedisCache.java
  common/data/src/main/java/org/thingsboard/server/common/data/CacheConstants.java
  dao/src/main/java/org/thingsboard/server/dao/resource/BaseResourceService.java
  dao/src/test/resources/application-test.properties
Labels: Core
