Repository thingsboard/thingsboard, pull requests merged in 2023-12, with the labels that each got.

#9746 fixed flaky test
  application/src/test/java/org/thingsboard/server/controller/DeviceControllerTest.java
Labels: Ignore for release

#9720 Updated postgres image version from 12 to 15
  application/src/main/data/json/edge/install_instructions/docker/instructions.md
  docker/docker-compose.hybrid.yml
  docker/docker-compose.postgres.yml
  msa/tb/docker-cassandra/Dockerfile
Labels: enhancement

#9619 Pubsub executor thread pool size fix
  application/src/main/java/org/thingsboard/server/actors/ActorSystemContext.java
  application/src/main/java/org/thingsboard/server/actors/ruleChain/DefaultTbContext.java
  application/src/main/java/org/thingsboard/server/service/executors/PubSubRuleNodeExecutorProvider.java
  application/src/main/resources/thingsboard.yml
  common/queue/src/main/java/org/thingsboard/server/queue/pubsub/TbPubSubConsumerTemplate.java
  common/queue/src/main/java/org/thingsboard/server/queue/pubsub/TbPubSubProducerTemplate.java
  common/queue/src/main/java/org/thingsboard/server/queue/pubsub/TbPubSubSettings.java
  common/util/src/main/java/org/thingsboard/common/util/ExecutorProvider.java
  msa/vc-executor/src/main/resources/tb-vc-executor.yml
  rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/TbContext.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/gcp/pubsub/TbPubSubNode.java
  transport/coap/src/main/resources/tb-coap-transport.yml
  transport/http/src/main/resources/tb-http-transport.yml
  transport/lwm2m/src/main/resources/tb-lwm2m-transport.yml
  transport/mqtt/src/main/resources/tb-mqtt-transport.yml
  transport/snmp/src/main/resources/tb-snmp-transport.yml
Labels: enhancement

#9738 Moved proto files and converter classes to proto module
  application/src/main/java/org/thingsboard/server/controller/TelemetryController.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/constructor/telemetry/EntityDataMsgConstructor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/telemetry/BaseTelemetryProcessor.java
  application/src/main/java/org/thingsboard/server/service/queue/DefaultTbClusterService.java
  application/src/main/java/org/thingsboard/server/service/queue/DefaultTbCoreConsumerService.java
  application/src/main/java/org/thingsboard/server/service/queue/DefaultTbRuleEngineConsumerService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/csv/AbstractBulkImportService.java
  application/src/test/java/org/thingsboard/server/edge/DeviceEdgeTest.java
  common/cluster-api/pom.xml
  common/pom.xml
  common/proto/pom.xml
  common/proto/src/main/java/org/thingsboard/server/common/adaptor/AdaptorException.java
  common/proto/src/main/java/org/thingsboard/server/common/adaptor/JsonConverter.java
  common/proto/src/main/java/org/thingsboard/server/common/adaptor/JsonConverterConfig.java
  common/proto/src/main/java/org/thingsboard/server/common/adaptor/ProtoConverter.java
  common/proto/src/main/java/org/thingsboard/server/common/util/ProtoUtils.java
  common/proto/src/main/proto/jsinvoke.proto
  common/proto/src/main/proto/queue.proto
  common/proto/src/main/proto/transport.proto
  common/proto/src/test/java/org/thingsboard/server/common/adaptor/JsonConverterTest.java
  common/proto/src/test/java/org/thingsboard/server/common/util/ProtoUtilsTest.java
  common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/CoapTransportResource.java
  common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/adaptors/CoapAdaptorUtils.java
  common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/adaptors/CoapTransportAdaptor.java
  common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/adaptors/JsonCoapAdaptor.java
  common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/adaptors/ProtoCoapAdaptor.java
  common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/callback/GetAttributesSyncSessionCallback.java
  common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/callback/ToServerRpcSyncSessionCallback.java
  common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/client/CoapClientContext.java
  common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/client/DefaultCoapClientContext.java
  common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/efento/CoapEfentoTransportResource.java
  common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/efento/adaptor/EfentoCoapAdaptor.java
  common/transport/http/src/main/java/org/thingsboard/server/transport/http/DeviceApiController.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/adaptors/LwM2MJsonAdaptor.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/adaptors/LwM2MTransportAdaptor.java
  common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttTransportHandler.java
  common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/adaptors/BackwardCompatibilityAdaptor.java
  common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/adaptors/JsonMqttAdaptor.java
  common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/adaptors/MqttTransportAdaptor.java
  common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/adaptors/ProtoMqttAdaptor.java
  common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/AbstractGatewaySessionHandler.java
  common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/GatewaySessionHandler.java
  common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/SparkplugNodeSessionHandler.java
  common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/util/sparkplug/MetricDataType.java
  common/transport/snmp/src/main/java/org/thingsboard/server/transport/snmp/service/SnmpTransportService.java
  pom.xml
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/action/TbCopyAttributesToEntityViewNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/profile/AlarmRuleState.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/profile/DeviceState.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/telemetry/TbMsgAttributesNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/telemetry/TbMsgTimeseriesNode.java
Labels: Ignore for release

#9759 [3.7]tbel Release 1.1.5_
  pom.xml
Labels: Build Scripts

#9764 Fixed mqtt/coap docker connectivity commands (localhost case)
  application/src/test/java/org/thingsboard/server/controller/DeviceConnectivityControllerTest.java
  dao/src/main/java/org/thingsboard/server/dao/device/DeviceConnectivityServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/util/DeviceConnectivityUtil.java
Labels: Bug

#9652 Save attributes node fixes
  application/src/main/data/json/edge/rule_chains/edge_root_rule_chain.json
  application/src/main/data/json/tenant/device_profile/rule_chain_template.json
  application/src/main/data/json/tenant/rule_chains/root_rule_chain.json
  application/src/main/data/upgrade/3.6.1/save_attributes_node_update.sql
  application/src/main/java/org/thingsboard/server/service/install/SqlDatabaseUpgradeService.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/telemetry/TbMsgAttributesNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/telemetry/TbMsgAttributesNodeConfiguration.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/telemetry/TbMsgAttributesNodeConfigurationTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/telemetry/TbMsgAttributesNodeTest.java
Labels: Bug, Rule Engine

#9284 Transformation rule nodes enhancements
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/deduplication/TbMsgDeduplicationNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/mail/TbMsgToEmailNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/mail/TbMsgToEmailNodeConfiguration.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/metadata/TbAbstractNodeWithFetchTo.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/metadata/TbGetOriginatorFieldsConfiguration.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/TbAbstractTransformNodeWithTbMsgSource.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/TbChangeOriginatorNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/TbCopyKeysNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/TbCopyKeysNodeConfiguration.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/TbDeleteKeysNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/TbDeleteKeysNodeConfiguration.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/TbJsonPathNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/TbRenameKeysNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/TbRenameKeysNodeConfiguration.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/TbSplitArrayMsgNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/TbTransformMsgNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/util/EntitiesCustomerIdAsyncLoader.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/mail/TbMsgToEmailNodeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/metadata/TbGetCustomerAttributeNodeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/metadata/TbGetCustomerDetailsNodeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/metadata/TbGetOriginatorFieldsNodeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/metadata/TbGetRelatedAttributeNodeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/metadata/TbGetTenantAttributeNodeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/metadata/TbGetTenantDetailsNodeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/transform/TbCopyKeysNodeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/transform/TbDeleteKeysNodeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/transform/TbRenameKeysNodeTest.java
  ui-ngx/src/assets/help/en_US/rulenode/change_originator_node_fields_templatization.md
  ui-ngx/src/assets/help/en_US/rulenode/common_node_fields_templatization.md
  ui-ngx/src/assets/help/en_US/rulenode/to_email_node_fields_templatization.md
  ui-ngx/src/assets/help/images/rulenode/examples/change-originator-ft-2.png
  ui-ngx/src/assets/help/images/rulenode/examples/change-originator-ft-3.png
  ui-ngx/src/assets/help/images/rulenode/examples/change-originator-ft.png
  ui-ngx/src/assets/help/images/rulenode/examples/to-email-ft.png
Labels: enhancement, Rule Engine

#9768 [3.6.2]Fix_bug_Tbdate_default_tz
  common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/TbDate.java
  common/script/script-api/src/test/java/org/thingsboard/script/api/tbel/TbDateTest.java
  common/util/src/main/java/org/thingsboard/common/util/JacksonUtil.java
Labels: Bug

#9774 Updated design of transformation rules nodes
  rule-engine/rule-engine-components/src/main/resources/public/static/rulenode/rulenode-core-config.js
Labels: enhancement, UI, Rule Engine, Ignore for release

#9748 The Chinese translations of 'inactive' and 'active' are reversed
  ui-ngx/src/assets/locale/locale.constant-zh_CN.json
Labels: UI

#9307 Timewindow config transfer on tab switch
  ui-ngx/src/app/shared/components/time/timewindow-panel.component.html
  ui-ngx/src/app/shared/components/time/timewindow-panel.component.ts
Labels: enhancement, UI

#9553 Dashboard form redesign
  ui-ngx/src/app/modules/home/pages/dashboard/dashboard-form.component.html
  ui-ngx/src/app/modules/home/pages/dashboard/dashboard-form.component.ts
  ui-ngx/src/app/modules/home/pages/dashboard/dashboards-table-config.resolver.ts
  ui-ngx/src/app/shared/models/dashboard.models.ts
Labels: enhancement, UI

#9579 Save status include bundle widget in export
  ui-ngx/src/app/shared/import-export/export-widgets-bundle-dialog.component.ts
  ui-ngx/src/app/shared/import-export/import-export.service.ts
  ui-ngx/src/app/shared/models/user-settings.models.ts
Labels: UI, Feature

#9620 Fixed infinity alarm loading on unresolved data sources
  ui-ngx/src/app/core/api/alarm-data.service.ts
Labels: Bug, UI

#9629 Dashboard alias stacking relation filters
  ui-ngx/src/app/modules/home/components/alias/entity-alias-dialog.component.ts
Labels: enhancement, UI

#9630 Fixed version control message text display behaviour
  ui-ngx/src/app/modules/home/components/vc/version-control.scss
Labels: enhancement, UI

#9642 Add query.models to public-api
  ui-ngx/src/app/modules/home/components/widget/lib/entity/entities-table-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/table-widget.models.ts
  ui-ngx/src/app/shared/models/public-api.ts
  ui-ngx/src/app/shared/models/query/query.models.ts
Labels: enhancement, UI

#9649 Improve added links to entities from setting of entities
  ui-ngx/src/app/modules/home/components/profile/asset-profile-autocomplete.component.html
  ui-ngx/src/app/modules/home/components/profile/asset-profile-autocomplete.component.ts
  ui-ngx/src/app/modules/home/components/profile/device-profile-autocomplete.component.html
  ui-ngx/src/app/modules/home/components/profile/device-profile-autocomplete.component.ts
  ui-ngx/src/app/modules/home/components/rule-chain/rule-chain-autocomplete.component.html
  ui-ngx/src/app/modules/home/components/rule-chain/rule-chain-autocomplete.component.ts
  ui-ngx/src/app/shared/components/dashboard-autocomplete.component.html
  ui-ngx/src/app/shared/components/dashboard-autocomplete.component.ts
  ui-ngx/src/app/shared/components/entity/entity-autocomplete.component.html
  ui-ngx/src/app/shared/components/entity/entity-autocomplete.component.ts
  ui-ngx/src/app/shared/components/ota-package/ota-package-autocomplete.component.html
  ui-ngx/src/app/shared/components/ota-package/ota-package-autocomplete.component.ts
Labels: enhancement, UI

#9650 Added entity links to alarm table originator column
  ui-ngx/src/app/modules/home/components/alarm/alarm-table-config.ts
  ui-ngx/src/app/modules/home/components/entity/entities-table.component.html
  ui-ngx/src/app/modules/home/components/entity/entities-table.component.ts
  ui-ngx/src/app/modules/home/models/entity/entities-table-config.models.ts
Labels: enhancement, UI

#9658 Fixed border radius for basic settings analog gauge widgets
  ui-ngx/src/app/modules/home/components/widget/config/basic/gauge/analog-gauge-basic-config.component.ts
Labels: Bug, UI

#9660 Fixed units for analog gauge widgets
  application/src/main/data/json/system/widget_types/speed_gauge.json
  application/src/main/data/json/system/widget_types/temperature_radial_gauge.json
  application/src/main/data/json/system/widget_types/thermometer_scale.json
Labels: Bug, UI

#9663 Fixed translation key for error of rule engine TTL exceptions days field
  ui-ngx/src/app/modules/home/components/profile/tenant/default-tenant-profile-configuration.component.html
Labels: Bug, UI

#9671 Fixed padding for multiple input widget with group setings
  ui-ngx/src/app/modules/home/components/widget/lib/multiple-input-widget.component.scss
Labels: Bug, UI

#9677 Fixed card widget display only numeric value
  ui-ngx/src/app/modules/home/components/widget/lib/cards/value-card-widget.component.ts
Labels: Bug, UI

#9704 Industrial widgets: Flow rate
  application/src/main/data/json/system/widget_bundles/industial_widgets.json
  application/src/main/data/json/system/widget_types/flow_rate_card.json
  application/src/main/data/json/system/widget_types/flow_rate_card_with_background.json
  application/src/main/data/json/system/widget_types/flow_rate_chart_card.json
  application/src/main/data/json/system/widget_types/flow_rate_chart_card_with_background.json
  application/src/main/data/json/system/widget_types/flow_rate_gauge.json
  application/src/main/data/json/system/widget_types/flow_rate_progress_bar.json
  application/src/main/data/json/system/widget_types/flow_rate_progress_bar_with_background.json
  application/src/main/data/json/system/widget_types/flow_rate_range_chart.json
  application/src/main/data/json/system/widget_types/flow_rate_range_chart_with_background.json
  application/src/main/data/json/system/widget_types/horizontal_flow_rate_card.json
  application/src/main/data/json/system/widget_types/horizontal_flow_rate_card_with_background.json
  application/src/main/data/json/system/widget_types/simple_flow_rate_chart_card.json
  application/src/main/data/json/system/widget_types/simple_flow_rate_chart_card_with_background.json
Labels: UI, Major UI

#9709 Add Dutch (Belgium) locale
  ui-ngx/src/assets/locale/locale.constant-en_US.json
  ui-ngx/src/assets/locale/locale.constant-nl_BE.json
Labels: UI, Feature

#9729 Fixed JSON type attribute in multiple input widget
  ui-ngx/src/app/modules/home/components/widget/lib/multiple-input-widget.component.ts
Labels: Bug, UI

#9747 Fixed mdi and other icons appearing
  ui-ngx/src/app/modules/home/components/alarm/alarm-comment.component.html
  ui-ngx/src/app/modules/home/components/entity/entities-table.component.html
  ui-ngx/src/app/modules/home/components/filter/filter-predicate-value.component.html
  ui-ngx/src/app/modules/home/components/profile/alarm/alarm-duration-predicate-value.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/alarm/alarms-table-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/entity/entities-table-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/timeseries-table-widget.component.html
  ui-ngx/src/app/modules/home/models/entity/entities-table-config.models.ts
  ui-ngx/src/app/modules/home/pages/admin/mail-server.component.html
  ui-ngx/src/app/modules/home/pages/admin/oauth2-settings.component.html
  ui-ngx/src/app/modules/home/pages/notification/rule/rule-table-config.resolver.ts
  ui-ngx/src/app/modules/home/pages/notification/sent/sent-table-config.resolver.ts
  ui-ngx/src/app/modules/home/pages/security/security.component.html
  ui-ngx/src/app/modules/home/pages/user/users-table-config.resolver.ts
  ui-ngx/src/app/shared/components/button/copy-button.component.html
  ui-ngx/src/app/shared/components/button/copy-button.component.ts
Labels: Bug, UI

#9770 Fixed export widget bundle url
  ui-ngx/src/app/core/http/widget.service.ts
Labels: Bug, UI, Ignore for release

#9771 Added Individual Allergy Index (IAI) widgets to air quality bundle
  application/src/main/data/json/system/widget_bundles/air_quality.json
  application/src/main/data/json/system/widget_types/horizontal_individual_allergy_index__iai__card.json
  application/src/main/data/json/system/widget_types/horizontal_individual_allergy_index__iai__card_with_background.json
  application/src/main/data/json/system/widget_types/individual_allergy_index__iai__card.json
  application/src/main/data/json/system/widget_types/individual_allergy_index__iai__card_with_background.json
  application/src/main/data/json/system/widget_types/individual_allergy_index__iai__chart_card.json
  application/src/main/data/json/system/widget_types/individual_allergy_index__iai__chart_card_with_background.json
  application/src/main/data/json/system/widget_types/simple_individual_allergy_index__iai__chart_card.json
  application/src/main/data/json/system/widget_types/simple_individual_allergy_index__iai__chart_card_with_background.json
Labels: UI, Major UI

#9782 Fix image API tests
  application/src/test/java/org/thingsboard/server/controller/ImageControllerTest.java
Labels: Ignore for release

#9796 [3.6.2] TbSqlBlockingQueue failover improvement
  dao/src/main/java/org/thingsboard/server/dao/sql/TbSqlBlockingQueue.java
Labels: enhancement

#9801 Updated config parameter description
  application/src/main/resources/thingsboard.yml
  msa/vc-executor/src/main/resources/tb-vc-executor.yml
  transport/coap/src/main/resources/tb-coap-transport.yml
  transport/http/src/main/resources/tb-http-transport.yml
  transport/lwm2m/src/main/resources/tb-lwm2m-transport.yml
  transport/mqtt/src/main/resources/tb-mqtt-transport.yml
  transport/snmp/src/main/resources/tb-snmp-transport.yml
Labels: Ignore for release

#9776 added new get entity profile names APIs for profile entities(AssetProfile & DeviceProfile)
  application/src/main/java/org/thingsboard/server/controller/AssetController.java
  application/src/main/java/org/thingsboard/server/controller/AssetProfileController.java
  application/src/main/java/org/thingsboard/server/controller/DeviceController.java
  application/src/main/java/org/thingsboard/server/controller/DeviceProfileController.java
  application/src/main/java/org/thingsboard/server/service/install/SqlDatabaseUpgradeService.java
  application/src/test/java/org/thingsboard/server/controller/AssetProfileControllerTest.java
  application/src/test/java/org/thingsboard/server/controller/DeviceProfileControllerTest.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/asset/AssetProfileService.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/asset/AssetService.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/device/DeviceProfileService.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/device/DeviceService.java
  dao/src/main/java/org/thingsboard/server/dao/DaoUtil.java
  dao/src/main/java/org/thingsboard/server/dao/asset/AssetDao.java
  dao/src/main/java/org/thingsboard/server/dao/asset/AssetProfileDao.java
  dao/src/main/java/org/thingsboard/server/dao/asset/AssetProfileServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/asset/BaseAssetService.java
  dao/src/main/java/org/thingsboard/server/dao/device/DeviceDao.java
  dao/src/main/java/org/thingsboard/server/dao/device/DeviceProfileDao.java
  dao/src/main/java/org/thingsboard/server/dao/device/DeviceProfileServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/device/DeviceServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/sql/asset/AssetProfileRepository.java
  dao/src/main/java/org/thingsboard/server/dao/sql/asset/AssetRepository.java
  dao/src/main/java/org/thingsboard/server/dao/sql/asset/JpaAssetDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/asset/JpaAssetProfileDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/device/DeviceProfileRepository.java
  dao/src/main/java/org/thingsboard/server/dao/sql/device/DeviceRepository.java
  dao/src/main/java/org/thingsboard/server/dao/sql/device/JpaDeviceDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/device/JpaDeviceProfileDao.java
  dao/src/main/resources/sql/schema-entities-idx.sql
  dao/src/test/java/org/thingsboard/server/dao/service/AssetProfileServiceTest.java
  dao/src/test/java/org/thingsboard/server/dao/service/DeviceProfileServiceTest.java
  rest-client/src/main/java/org/thingsboard/rest/client/RestClient.java
Labels: Core

#9637 Gateway dashboard updates
  application/src/main/data/json/tenant/dashboards/gateways.json
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-connectors.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-logs.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc.component.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI

#9807 Added milligram per cubic meter unit
  ui-ngx/src/assets/locale/locale.constant-en_US.json
  ui-ngx/src/assets/metadata/units.json
Labels: enhancement, UI

#9808 russian language removed
  ui-ngx/src/assets/locale/locale.constant-en_US.json
  ui-ngx/src/assets/locale/locale.constant-ru_RU.json
Labels: UI

#9813 Battery widget change default level and share color
  application/src/main/data/json/system/widget_types/battery_level.json
  ui-ngx/src/app/modules/home/components/widget/lib/indicator/battery-level-widget.models.ts
Labels: Bug, UI

#9775 Added max length password policy
  application/src/main/java/org/thingsboard/server/exception/ThingsboardCredentialsViolationResponse.java
  application/src/main/java/org/thingsboard/server/exception/ThingsboardErrorResponseHandler.java
  application/src/main/java/org/thingsboard/server/service/security/exception/UserPasswordNotValidException.java
  application/src/main/java/org/thingsboard/server/service/security/system/DefaultSystemSecurityService.java
  application/src/test/java/org/thingsboard/server/controller/AuthControllerTest.java
  common/data/src/main/java/org/thingsboard/server/common/data/exception/ThingsboardErrorCode.java
  common/data/src/main/java/org/thingsboard/server/common/data/security/model/UserPasswordPolicy.java
Labels: enhancement, Feature

#9791 Improvement for security settings
  ui-ngx/src/app/modules/home/pages/admin/security-settings.component.html
  ui-ngx/src/app/modules/home/pages/admin/security-settings.component.ts
  ui-ngx/src/app/modules/home/pages/security/security.component.html
  ui-ngx/src/app/modules/home/pages/security/security.component.ts
  ui-ngx/src/app/modules/login/pages/login/login.component.html
  ui-ngx/src/app/modules/login/pages/login/login.component.ts
  ui-ngx/src/app/shared/models/constants.ts
  ui-ngx/src/app/shared/models/settings.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI, Feature

#9803 [3.6.2] Device connectivity controller test improvements
  application/src/test/java/org/thingsboard/server/controller/DeviceConnectivityControllerTest.java
  dao/src/test/java/org/thingsboard/server/dao/util/DeviceConnectivityUtilTest.java
Labels: Ignore for release

#9818 [3.6.2] TbSqlBlockingQueue does not log an error on InterruptedException because of normal lifecycle
  dao/src/main/java/org/thingsboard/server/dao/sql/TbSqlBlockingQueue.java
Labels: Ignore for release

#9824 Updated upgrade script for 3.6.1 to clean up securitySettings cache
  application/src/main/java/org/thingsboard/server/service/install/update/DefaultCacheCleanupService.java
Labels: Ignore for release

#9817 fixed flaky tests
  application/src/test/java/org/thingsboard/server/transport/coap/CoapTestCallback.java
  pom.xml
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/rest/TbHttpClientTest.java
Labels: Ignore for release

#9832 Added edge_event idx by tenant id and edge id
  application/src/main/data/upgrade/3.6.1/schema_update.sql
  dao/src/main/resources/sql/schema-entities-idx.sql
Labels: Ignore for release

#9804 Edge - fix image feature backward compatibility
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeSyncCursor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/constructor/asset/AssetMsgConstructorV1.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/constructor/dashboard/DashboardMsgConstructorV1.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/constructor/device/DeviceMsgConstructorV1.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/constructor/resource/ResourceMsgConstructorV1.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/constructor/tenant/TenantMsgConstructorV1.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/constructor/widget/WidgetMsgConstructorV1.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/fetch/BaseResourceEdgeEventFetcher.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/fetch/SystemResourcesEdgeEventFetcher.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/fetch/TenantResourcesEdgeEventFetcher.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/resource/ResourceEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/resource/ResourceEdgeProcessorV1.java
  application/src/test/java/org/thingsboard/server/service/edge/rpc/processor/BaseEdgeProcessorTest.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/resource/ImageService.java
  dao/src/main/java/org/thingsboard/server/dao/resource/BaseImageService.java
Labels: Ignore for release

#9831 Moved password policy check before user info rest calls
  application/src/main/java/org/thingsboard/server/controller/AdminController.java
  application/src/main/java/org/thingsboard/server/controller/AuthController.java
  application/src/main/java/org/thingsboard/server/service/security/auth/rest/RestAuthenticationProvider.java
  application/src/main/java/org/thingsboard/server/service/security/exception/UserPasswordNotValidException.java
  application/src/main/java/org/thingsboard/server/service/security/system/DefaultSystemSecurityService.java
  application/src/main/java/org/thingsboard/server/service/security/system/SystemSecurityService.java
Labels: enhancement, Ignore for release

#9844 Added hotfix upgrade for transformation rule nodes with TbMsgSource
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/TbAbstractTransformNodeWithTbMsgSource.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/TbCopyKeysNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/TbDeleteKeysNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/TbRenameKeysNode.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/transform/TbCopyKeysNodeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/transform/TbDeleteKeysNodeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/transform/TbRenameKeysNodeTest.java
Labels: Bug, WIP

#9842 Fixed edge upgrade script - added volumes section
  application/src/main/data/json/edge/instructions/upgrade/docker/upgrade_preparing.md
Labels: Ignore for release

#9849 TbKafkaNode - replace \ and n symbols with new line symbol \n
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/kafka/TbKafkaNode.java
Labels: Ignore for release

#9857 Fixed externalId when import/export entity
  ui-ngx/src/app/shared/import-export/import-export.service.ts
  ui-ngx/src/app/shared/models/base-data.ts
  ui-ngx/src/app/shared/models/tenant.model.ts
  ui-ngx/src/app/shared/models/widget.models.ts
Labels: Bug, UI

#9847 Changed placeholder for the Enter asset profile field
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: Bug, UI

#9840 Widget action dialog fixed name field error overlay
  ui-ngx/src/app/modules/home/components/widget/action/widget-action-dialog.component.html
Labels: Bug, UI

#9839 Liquid level widget remove percent from label for n/a value
  ui-ngx/src/app/modules/home/components/widget/lib/indicator/liquid-level-widget.models.ts
Labels: Bug, UI

#9800 Added ozone level widget (O3) to air quality bundle
  application/src/main/data/json/system/widget_bundles/air_quality.json
  application/src/main/data/json/system/widget_types/horizontal_ozone__o3__card.json
  application/src/main/data/json/system/widget_types/horizontal_ozone__o3__card_with_background.json
  application/src/main/data/json/system/widget_types/ozone__o3__card.json
  application/src/main/data/json/system/widget_types/ozone__o3__card_with_background.json
  application/src/main/data/json/system/widget_types/ozone__o3__chart_card.json
  application/src/main/data/json/system/widget_types/ozone__o3__chart_card_with_background.json
  application/src/main/data/json/system/widget_types/simple_ozone__o3__chart_card.json
  application/src/main/data/json/system/widget_types/simple_ozone__o3__chart_card_with_background.json
Labels: UI, Feature

#9836 Fixed battery level widget fill
  application/src/main/data/json/system/widget_types/battery_level.json
  ui-ngx/src/app/modules/home/components/widget/lib/indicator/battery-level-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/indicator/battery-level-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/indicator/battery-level-widget.models.ts
Labels: Bug, UI

#9825 Fixed backward compatibility for notification settings
  ui-ngx/src/app/modules/home/pages/notification/settings/notification-settings.component.ts
Labels: Bug, UI

#9778 [3.6.2]Fix_bug_tbDate_from_String_without_TZ
  common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/TbDate.java
  common/script/script-api/src/test/java/org/thingsboard/script/api/tbel/TbDateConstructorTest.java
  common/script/script-api/src/test/java/org/thingsboard/script/api/tbel/TbDateTest.java
Labels: Bug

#9838 Added new preview and background images for air quality widgets
  application/src/main/data/json/system/widget_bundles/air_quality.json
  application/src/main/data/json/system/widget_types/carbon_monoxide__co__card.json
  application/src/main/data/json/system/widget_types/carbon_monoxide__co__card_with_background.json
  application/src/main/data/json/system/widget_types/carbon_monoxide__co__chart_card.json
  application/src/main/data/json/system/widget_types/carbon_monoxide__co__chart_card_with_background.json
  application/src/main/data/json/system/widget_types/horizontal_carbon_monoxide__co__card.json
  application/src/main/data/json/system/widget_types/horizontal_carbon_monoxide__co__card_with_background.json
  application/src/main/data/json/system/widget_types/horizontal_individual_allergy_index__iai__card.json
  application/src/main/data/json/system/widget_types/horizontal_individual_allergy_index__iai__card_with_background.json
  application/src/main/data/json/system/widget_types/horizontal_nitrogen_dioxide__no2__card.json
  application/src/main/data/json/system/widget_types/horizontal_nitrogen_dioxide__no2__card_with_background.json
  application/src/main/data/json/system/widget_types/horizontal_ozone__o3__card.json
  application/src/main/data/json/system/widget_types/horizontal_ozone__o3__card_with_background.json
  application/src/main/data/json/system/widget_types/horizontal_sulfur_dioxide__so2__card.json
  application/src/main/data/json/system/widget_types/horizontal_sulfur_dioxide__so2__card_with_background.json
  application/src/main/data/json/system/widget_types/individual_allergy_index__iai__card.json
  application/src/main/data/json/system/widget_types/individual_allergy_index__iai__card_with_background.json
  application/src/main/data/json/system/widget_types/individual_allergy_index__iai__chart_card.json
  application/src/main/data/json/system/widget_types/individual_allergy_index__iai__chart_card_with_background.json
  application/src/main/data/json/system/widget_types/nitrogen_dioxide__no2__card.json
  application/src/main/data/json/system/widget_types/nitrogen_dioxide__no2__card_with_background.json
  application/src/main/data/json/system/widget_types/nitrogen_dioxide__no2__chart_card.json
  application/src/main/data/json/system/widget_types/nitrogen_dioxide__no2__chart_card_with_background.json
  application/src/main/data/json/system/widget_types/ozone__o3__card.json
  application/src/main/data/json/system/widget_types/ozone__o3__card_with_background.json
  application/src/main/data/json/system/widget_types/ozone__o3__chart_card.json
  application/src/main/data/json/system/widget_types/ozone__o3__chart_card_with_background.json
  application/src/main/data/json/system/widget_types/simple_carbon_monoxide__co__chart_card.json
  application/src/main/data/json/system/widget_types/simple_carbon_monoxide__co__chart_card_with_background.json
  application/src/main/data/json/system/widget_types/simple_individual_allergy_index__iai__chart_card.json
  application/src/main/data/json/system/widget_types/simple_individual_allergy_index__iai__chart_card_with_background.json
  application/src/main/data/json/system/widget_types/simple_nitrogen_dioxide__no2__chart_card.json
  application/src/main/data/json/system/widget_types/simple_nitrogen_dioxide__no2__chart_card_with_background.json
  application/src/main/data/json/system/widget_types/simple_ozone__o3__chart_card.json
  application/src/main/data/json/system/widget_types/simple_ozone__o3__chart_card_with_background.json
  application/src/main/data/json/system/widget_types/simple_sulfur_dioxide__so2__chart_card.json
  application/src/main/data/json/system/widget_types/simple_sulfur_dioxide__so2__chart_card_with_background.json
  application/src/main/data/json/system/widget_types/sulfur_dioxide__so2__card.json
  application/src/main/data/json/system/widget_types/sulfur_dioxide__so2__card_with_background.json
  application/src/main/data/json/system/widget_types/sulfur_dioxide__so2__chart_card.json
  application/src/main/data/json/system/widget_types/sulfur_dioxide__so2__chart_card_with_background.json
Labels: enhancement, UI, Ignore for release

#9848 Redesign gateway launch commands dialog
  application/src/main/data/json/tenant/dashboards/gateways.json
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/device-gateway-command.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/device-gateway-command.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/device-gateway-command.component.ts
  ui-ngx/src/app/shared/models/constants.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
  ui-ngx/src/assets/locale/locale.constant-es_ES.json
  ui-ngx/src/assets/locale/locale.constant-zh_CN.json
Labels: enhancement, UI

#9860 Fixed analog gauge infinite loop for major ticks
  ui-ngx/src/app/modules/home/components/widget/lib/analogue-gauge.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/gauge/analogue-gauge-widget-settings.component.ts
Labels: Bug, UI

#9861 Fixed download gateway launch file and refactoring downloads file
  ui-ngx/src/app/core/http/device.service.ts
  ui-ngx/src/app/core/http/image.service.ts
  ui-ngx/src/app/core/http/ota-package.service.ts
  ui-ngx/src/app/core/http/resource.service.ts
  ui-ngx/src/app/core/services/resources.service.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/device-gateway-command.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/device-gateway-command.component.ts
  ui-ngx/src/app/shared/models/device.models.ts
Labels: Bug, UI, Ignore for release

#9863 [3.6.2]Tbel 1 1 5
  pom.xml
Labels: Build Scripts

#9827 Fix VC support for notification recipients
  application/src/main/java/org/thingsboard/server/service/notification/DefaultNotificationSchedulerService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/exporting/impl/NotificationTargetExportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/NotificationTargetImportService.java
Labels: Bug, Core

#9868 Fixed incorrect link to install necessary tool for MQTT in Windows
  ui-ngx/src/app/modules/home/pages/device/device-check-connectivity-dialog.component.html
Labels: Bug, UI

#9865 Fix for chart-card widgets SVG previews showing incorrect resolution
  application/src/main/data/json/system/widget_bundles/air_quality.json
  application/src/main/data/json/system/widget_bundles/industial_widgets.json
  application/src/main/data/json/system/widget_types/carbon_monoxide__co__chart_card.json
  application/src/main/data/json/system/widget_types/carbon_monoxide__co__chart_card_with_background.json
  application/src/main/data/json/system/widget_types/efficiency_chart_card.json
  application/src/main/data/json/system/widget_types/efficiency_chart_card_with_background.json
  application/src/main/data/json/system/widget_types/flow_rate_chart_card.json
  application/src/main/data/json/system/widget_types/flow_rate_chart_card_with_background.json
  application/src/main/data/json/system/widget_types/fluid_pressure_chart_card.json
  application/src/main/data/json/system/widget_types/fluid_pressure_chart_card_with_background.json
  application/src/main/data/json/system/widget_types/individual_allergy_index__iai__chart_card.json
  application/src/main/data/json/system/widget_types/individual_allergy_index__iai__chart_card_with_background.json
  application/src/main/data/json/system/widget_types/nitrogen_dioxide__no2__chart_card.json
  application/src/main/data/json/system/widget_types/nitrogen_dioxide__no2__chart_card_with_background.json
  application/src/main/data/json/system/widget_types/ozone__o3__chart_card.json
  application/src/main/data/json/system/widget_types/ozone__o3__chart_card_with_background.json
  application/src/main/data/json/system/widget_types/power_consumption_chart_card.json
  application/src/main/data/json/system/widget_types/power_consumption_chart_card_with_background.json
  application/src/main/data/json/system/widget_types/pump_vibration_chart_card.json
  application/src/main/data/json/system/widget_types/pump_vibration_chart_card_with_background.json
  application/src/main/data/json/system/widget_types/rotational_speed_chart_card.json
  application/src/main/data/json/system/widget_types/rotational_speed_chart_card_with_background.json
  application/src/main/data/json/system/widget_types/sulfur_dioxide__so2__chart_card.json
  application/src/main/data/json/system/widget_types/sulfur_dioxide__so2__chart_card_with_background.json
Labels: Bug, Ignore for release

#9867 Image gallery improvements
  application/src/main/java/org/thingsboard/server/controller/ImageController.java
  application/src/test/java/org/thingsboard/server/controller/ImageControllerTest.java
  dao/src/main/java/org/thingsboard/server/dao/resource/BaseImageService.java
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: Ignore for release

#9872 Rename default state controller to static
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-settings-dialog.component.html
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-settings-dialog.component.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI

#9881 Fixed incorrect link to install necessary tool for MQTT in Windows
  ui-ngx/src/app/modules/home/pages/device/device-check-connectivity-dialog.component.html
Labels: Bug, UI, Ignore for release

#9882 [3.6.2] test optimization CA_ROOT_CERT_PEM from constant
  application/src/test/java/org/thingsboard/server/controller/DeviceConnectivityControllerTest.java
Labels: Ignore for release

#9890 Updated rulenode-core-config.js
  rule-engine/rule-engine-components/src/main/resources/public/static/rulenode/rulenode-core-config.js
Labels: UI, Ignore for release

#9884 Update Spanish locale
  ui-ngx/src/assets/locale/locale.constant-es_ES.json
Labels: enhancement, UI

#9885 Update Ukrainian translation
  ui-ngx/src/assets/locale/locale.constant-uk_UA.json
Labels: UI

#9889 Fixed device connectivity sysadmin settings disabled inputs values disappearing on save
  ui-ngx/src/app/modules/home/pages/admin/general-settings.component.ts
Labels: Bug, UI

#9891 Updated industrial widgets bundle preview
  application/src/main/data/json/system/widget_bundles/industial_widgets.json
Labels: enhancement, UI, Ignore for release

#9883 Fixed flot widget custom legend
  ui-ngx/src/app/modules/home/components/widget/lib/flot-widget.ts
Labels: Bug, UI

#9901 Set max allow resource size from tenant profile
  application/src/main/java/org/thingsboard/server/controller/ImageController.java
  application/src/main/java/org/thingsboard/server/controller/SystemInfoController.java
  application/src/test/java/org/thingsboard/server/controller/ImageControllerTest.java
  common/data/src/main/java/org/thingsboard/server/common/data/SystemParams.java
  ui-ngx/src/app/core/auth/auth.models.ts
  ui-ngx/src/app/core/auth/auth.reducer.ts
  ui-ngx/src/app/modules/home/components/vc/repository-settings.component.html
  ui-ngx/src/app/modules/home/pages/admin/resource/resources-library.component.html
  ui-ngx/src/app/modules/home/pages/admin/resource/resources-library.component.ts
  ui-ngx/src/app/modules/home/pages/ota-update/ota-update.component.html
  ui-ngx/src/app/shared/components/file-input.component.html
  ui-ngx/src/app/shared/components/file-input.component.scss
  ui-ngx/src/app/shared/components/file-input.component.ts
  ui-ngx/src/app/shared/components/image/upload-image-dialog.component.html
  ui-ngx/src/app/shared/components/image/upload-image-dialog.component.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI, Feature, Core

#9897 Fixes for images version control
  application/src/main/java/org/thingsboard/server/service/sync/ie/exporting/impl/ResourceExportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/ResourceImportService.java
  application/src/main/java/org/thingsboard/server/service/sync/vc/DefaultEntitiesVersionControlService.java
  common/version-control/src/main/java/org/thingsboard/server/service/sync/vc/DefaultClusterVersionControlService.java
  common/version-control/src/main/java/org/thingsboard/server/service/sync/vc/GitRepository.java
  dao/src/main/java/org/thingsboard/server/dao/resource/BaseImageService.java
Labels: Ignore for release

#9902 Added spring multipart parameters to http transport
  transport/http/src/main/resources/tb-http-transport.yml
Labels: Ignore for release

#9900 Version control performance improvements
  application/src/main/java/org/thingsboard/server/controller/BaseController.java
  application/src/main/java/org/thingsboard/server/controller/EntitiesVersionControlController.java
  application/src/main/java/org/thingsboard/server/service/executors/VersionControlExecutor.java
  application/src/main/java/org/thingsboard/server/service/sync/vc/DefaultEntitiesVersionControlService.java
  application/src/main/java/org/thingsboard/server/service/sync/vc/DefaultGitVersionControlQueueService.java
  application/src/main/resources/thingsboard.yml
  common/version-control/src/main/java/org/thingsboard/server/service/sync/vc/DefaultClusterVersionControlService.java
  msa/vc-executor/src/main/resources/tb-vc-executor.yml
Labels: Core

#9911 Fix image's isPublic on import
  application/src/test/java/org/thingsboard/server/controller/ImageControllerTest.java
  common/data/src/main/java/org/thingsboard/server/common/data/ImageExportData.java
Labels: Ignore for release

#9910 Fixed EdgeControllerTest.testSyncEdge
  application/src/test/java/org/thingsboard/server/controller/EdgeControllerTest.java
Labels: Ignore for release
