Repository thingsboard/thingsboard, pull requests merged in 2023-02, with the labels that each got.

#8046 Notification temaplate
  ui-ngx/src/app/modules/home/components/notification/show-notification-popover.component.html
  ui-ngx/src/app/shared/components/notification/notification.component.html
  ui-ngx/src/app/shared/components/notification/notification.component.scss
  ui-ngx/src/app/shared/components/notification/notification.component.ts
  ui-ngx/src/app/shared/models/notification.models.ts
Labels: Ignore for release

#8031 Hotfix device profile url for navigation cards settings
  ui-ngx/src/app/modules/home/components/widget/lib/settings/navigation/navigation-cards-widget-settings.component.ts
Labels: Bug, UI

#8037 Fix loading widget resources, when one of the resources is marked as module
  ui-ngx/src/app/modules/home/components/widget/widget-component.service.ts
Labels: Bug, UI

#8051 [WIP] Added controller methods for saving user settings in UserController
  application/src/main/data/upgrade/3.4.4/schema_update.sql
  application/src/main/java/org/thingsboard/server/controller/BaseController.java
  application/src/main/java/org/thingsboard/server/controller/UserController.java
  application/src/main/resources/thingsboard.yml
  application/src/test/java/org/thingsboard/server/controller/AbstractWebTest.java
  application/src/test/java/org/thingsboard/server/controller/BaseUserControllerTest.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/user/UserSettingsService.java
  common/data/src/main/java/org/thingsboard/server/common/data/CacheConstants.java
  common/data/src/main/java/org/thingsboard/server/common/data/security/UserSettings.java
  dao/pom.xml
  dao/src/main/java/org/thingsboard/server/dao/entity/AbstractCachedService.java
  dao/src/main/java/org/thingsboard/server/dao/model/ModelConstants.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/UserSettingsEntity.java
  dao/src/main/java/org/thingsboard/server/dao/sql/user/JpaUserSettingsDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/user/UserSettingsRepository.java
  dao/src/main/java/org/thingsboard/server/dao/user/UserServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/user/UserSettingsCaffeineCache.java
  dao/src/main/java/org/thingsboard/server/dao/user/UserSettingsDao.java
  dao/src/main/java/org/thingsboard/server/dao/user/UserSettingsEvictEvent.java
  dao/src/main/java/org/thingsboard/server/dao/user/UserSettingsRedisCache.java
  dao/src/main/java/org/thingsboard/server/dao/user/UserSettingsServiceImpl.java
  dao/src/main/resources/sql/schema-entities.sql
  dao/src/test/java/org/thingsboard/server/dao/service/BaseUserServiceTest.java
  dao/src/test/java/org/thingsboard/server/dao/sql/user/JpaUserSettingsDaoTest.java
Labels: Feature, Core

#8068 Ignored unstable integration tests
  application/src/test/java/org/thingsboard/server/controller/BaseAlarmControllerTest.java
  application/src/test/java/org/thingsboard/server/controller/BaseAssetControllerTest.java
  application/src/test/java/org/thingsboard/server/controller/BaseCustomerControllerTest.java
  application/src/test/java/org/thingsboard/server/controller/BaseDeviceControllerTest.java
  application/src/test/java/org/thingsboard/server/controller/BaseDeviceProfileControllerTest.java
  application/src/test/java/org/thingsboard/server/controller/BaseEdgeControllerTest.java
  application/src/test/java/org/thingsboard/server/controller/BaseEntityViewControllerTest.java
  application/src/test/java/org/thingsboard/server/controller/BaseRuleChainControllerTest.java
  application/src/test/java/org/thingsboard/server/controller/BaseUserControllerTest.java
Labels: Ignore for release

#8094 Find users by query
  application/src/main/java/org/thingsboard/server/controller/BaseController.java
  application/src/main/java/org/thingsboard/server/controller/UserController.java
  application/src/test/java/org/thingsboard/server/controller/BaseUserControllerTest.java
  common/data/src/main/java/org/thingsboard/server/common/data/UserEmailInfo.java
Labels: enhancement, Core

#8127 [3.5] Remove EventDeduplicationExecutor
  application/src/main/java/org/thingsboard/server/utils/EventDeduplicationExecutor.java
  application/src/test/java/org/thingsboard/server/util/EventDeduplicationExecutorTest.java
Labels: Ignore for release

#8111 [3.5] Add functionality to support multiple certificate entries in pem file
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/credentials/CertPemCredentials.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/credentials/CertPemCredentialsTest.java
  rule-engine/rule-engine-components/src/test/resources/pem/empty.pem
  rule-engine/rule-engine-components/src/test/resources/pem/tb-cloud-chain.pem
  rule-engine/rule-engine-components/src/test/resources/pem/tb-cloud.pem
Labels: enhancement

#8108 [3.5] bugfix for remove latest telemetry
  dao/src/main/java/org/thingsboard/server/dao/sqlts/SqlTimeseriesLatestDao.java
Labels: Bug
