Repository thingsboard/thingsboard, pull requests merged in 2024-07, with the labels that each got.

#10982 Added no text option for autocomplete
  ui-ngx/src/app/modules/home/pages/widget/widget-type-autocomplete.component.html
  ui-ngx/src/app/modules/home/pages/widget/widget-type-autocomplete.component.ts
  ui-ngx/src/app/shared/components/dashboard-autocomplete.component.html
  ui-ngx/src/app/shared/components/dashboard-autocomplete.component.ts
  ui-ngx/src/app/shared/components/entity/entity-autocomplete.component.html
  ui-ngx/src/app/shared/components/entity/entity-autocomplete.component.ts
  ui-ngx/src/app/shared/components/entity/entity-list.component.html
  ui-ngx/src/app/shared/components/entity/entity-list.component.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI

#10999 Fixed entity table header components disabled create new device/asset profile
  ui-ngx/src/app/modules/home/components/device/device-info-filter.component.html
  ui-ngx/src/app/modules/home/components/wizard/device-wizard-dialog.component.html
  ui-ngx/src/app/modules/home/pages/asset/asset-table-header.component.html
Labels: bug, UI

#11010 Fixed LWM2M device profile transport configuration "object list" form field value persistence on tab switch
  ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-object-list.component.ts
Labels: bug, UI

#11035 Fixed disappearing of device profile transport config form on tab switch if it is invalid
  ui-ngx/src/app/modules/home/components/profile/device/coap-device-profile-transport-configuration.component.ts
  ui-ngx/src/app/modules/home/components/profile/device/device-profile-transport-configuration.component.ts
  ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-device-profile-transport-configuration.component.ts
  ui-ngx/src/app/modules/home/components/profile/device/mqtt-device-profile-transport-configuration.component.ts
  ui-ngx/src/app/modules/home/components/profile/device/snmp/snmp-device-profile-transport-configuration.component.ts
Labels: bug, UI

#11100 Disabled filtering of attributes with empty string values for attribute table
  ui-ngx/src/app/modules/home/components/attribute/attribute-table.component.html
  ui-ngx/src/app/modules/home/models/datasource/attribute-datasource.ts
Labels: bug, UI

#11124 Fixed UI build
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-configuration.component.html
Labels: UI, Ignore for release

#11084 Improvements for version control
  application/src/main/java/org/thingsboard/server/controller/AdminController.java
  application/src/main/java/org/thingsboard/server/service/queue/DefaultTbClusterService.java
  application/src/main/java/org/thingsboard/server/service/sync/vc/DefaultEntitiesVersionControlService.java
  application/src/main/java/org/thingsboard/server/service/sync/vc/DefaultGitVersionControlQueueService.java
  application/src/main/java/org/thingsboard/server/service/sync/vc/EntitiesVersionControlService.java
  application/src/test/java/org/thingsboard/server/controller/AbstractWebTest.java
  application/src/test/java/org/thingsboard/server/service/sync/ie/BaseExportImportServiceTest.java
  application/src/test/java/org/thingsboard/server/service/sync/ie/ExportImportServiceSqlTest.java
  application/src/test/java/org/thingsboard/server/service/sync/vc/VersionControlTest.java
  common/data/src/main/java/org/thingsboard/server/common/data/sync/vc/RepositorySettings.java
  common/proto/src/main/java/org/thingsboard/server/common/util/ProtoUtils.java
  common/proto/src/main/proto/queue.proto
  common/version-control/src/main/java/org/thingsboard/server/service/sync/vc/DefaultClusterVersionControlService.java
  common/version-control/src/main/java/org/thingsboard/server/service/sync/vc/DefaultGitRepositoryService.java
  common/version-control/src/main/java/org/thingsboard/server/service/sync/vc/GitRepository.java
Labels: Core

#11134 Proper error message when deleting dashboard referenced by asset profile
  application/src/main/java/org/thingsboard/server/controller/BaseController.java
  application/src/test/java/org/thingsboard/server/controller/DashboardControllerTest.java
  dao/src/main/java/org/thingsboard/server/dao/dashboard/DashboardServiceImpl.java
Labels: Ignore for release

#11152 Use Main queue if supplied queueName is empty
  application/src/test/java/org/thingsboard/server/controller/TenantControllerTest.java
  common/queue/src/main/java/org/thingsboard/server/queue/discovery/HashPartitionService.java
Labels: Ignore for release

#11139 [Edge] Proxy for grpc client
  application/src/main/java/org/thingsboard/server/actors/tenant/TenantActor.java
  application/src/main/java/org/thingsboard/server/controller/EdgeController.java
  application/src/main/java/org/thingsboard/server/controller/EdgeEventController.java
  application/src/main/java/org/thingsboard/server/service/edge/instructions/DefaultEdgeUpgradeInstructionsService.java
  application/src/main/java/org/thingsboard/server/service/edge/instructions/EdgeInstallInstructionsService.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcService.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/constructor/telemetry/EntityDataMsgConstructor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/constructor/tenant/TenantMsgConstructorV2.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/device/DeviceProcessor.java
  common/edge-api/src/main/java/org/thingsboard/edge/rpc/EdgeGrpcClient.java
Labels: Edge

#11151 send resourse change/delete events only for lwm2m
  application/src/main/java/org/thingsboard/server/service/queue/DefaultTbClusterService.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/service/DefaultTransportService.java
Labels: Ignore for release

#11105 fix_bug_tbel_Operations_ADD_ SUB
  pom.xml
Labels: bug

#11016 AWS lambda node
  ui-ngx/src/app/shared/models/constants.ts
  ui-ngx/src/app/shared/models/rule-node.models.ts
Labels: UI, Rule Engine

#11055 Added support unicode symbols in chart legend/tooltip
  ui-ngx/src/app/modules/home/components/widget/config/basic/chart/time-series-chart-basic-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/chart/bar-chart-with-labels-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/chart/range-chart-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/chart/time-series-chart-state.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/chart/time-series-chart-tooltip.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/chart/time-series-chart-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/chart/time-series-chart.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/chart/time-series-chart.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/chart/time-series-chart-widget-settings.component.ts
Labels: enhancement, UI

#11138 Notification widget
  application/src/main/data/json/system/widget_bundles/cards.json
  application/src/main/data/json/system/widget_types/unread_notifications.json
  ui-ngx/src/app/modules/home/components/notification/show-notification-popover.component.html
  ui-ngx/src/app/modules/home/components/notification/show-notification-popover.component.scss
  ui-ngx/src/app/modules/home/components/notification/show-notification-popover.component.ts
  ui-ngx/src/app/modules/home/components/widget/config/basic/basic-widget-config.module.ts
  ui-ngx/src/app/modules/home/components/widget/config/basic/cards/unread-notification-basic-config.component.html
  ui-ngx/src/app/modules/home/components/widget/config/basic/cards/unread-notification-basic-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/cards/notification-type-filter-panel.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/cards/notification-type-filter-panel.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/cards/notification-type-filter-panel.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/cards/unread-notification-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/cards/unread-notification-widget.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/cards/unread-notification-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/cards/unread-notification-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/unread-notification-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/unread-notification-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/widget-settings.module.ts
  ui-ngx/src/app/modules/home/components/widget/widget-components.module.ts
  ui-ngx/src/app/modules/home/components/widget/widget-container.component.html
  ui-ngx/src/app/shared/components/notification/notification.component.html
  ui-ngx/src/app/shared/components/notification/notification.component.ts
  ui-ngx/src/app/shared/models/telemetry/telemetry.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
  ui-ngx/src/assets/notification-bell.svg
Labels: UI, feature

#11165 Update rule node core config
  rule-engine/rule-engine-components/src/main/resources/public/static/rulenode/rulenode-core-config.js
Labels: UI, Rule Engine, Ignore for release

#11169 Fixed Min/Max value on gradient panel
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/gradient.component.ts
Labels: bug, UI

#11012 Removed unnecessary parameters for MQTT Connector
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc-connector-templates.component.html
  ui-ngx/src/app/modules/home/components/widget/widget-components.module.ts
  ui-ngx/src/app/shared/pipe/key-value-not-empty.pipe.ts
Labels: enhancement, UI

#11114 Show device tabs only with existing devices
  application/src/main/data/json/tenant/dashboards/gateways.json
Labels: enhancement, UI

#11149 Added connector name in connector logs
  application/src/main/data/json/tenant/dashboards/gateways.json
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-logs.component.ts
Labels: enhancement, UI

#9724 Notifications widget
  application/src/main/java/org/thingsboard/server/service/notification/DefaultNotificationCenter.java
  application/src/main/java/org/thingsboard/server/service/subscription/TbSubscription.java
  application/src/main/java/org/thingsboard/server/service/ws/notification/DefaultNotificationCommandsHandler.java
  application/src/main/java/org/thingsboard/server/service/ws/notification/cmd/NotificationsSubCmd.java
  application/src/main/java/org/thingsboard/server/service/ws/notification/cmd/UnreadNotificationsUpdate.java
  application/src/main/java/org/thingsboard/server/service/ws/notification/sub/NotificationUpdate.java
  application/src/main/java/org/thingsboard/server/service/ws/notification/sub/NotificationsCountSubscription.java
  application/src/main/java/org/thingsboard/server/service/ws/notification/sub/NotificationsSubscription.java
  application/src/test/java/org/thingsboard/server/service/notification/AbstractNotificationApiTest.java
  application/src/test/java/org/thingsboard/server/service/notification/NotificationApiTest.java
  application/src/test/java/org/thingsboard/server/service/notification/NotificationApiWsClient.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/notification/NotificationService.java
  common/data/src/main/java/org/thingsboard/server/common/data/notification/NotificationType.java
  dao/src/main/java/org/thingsboard/server/dao/notification/DefaultNotificationService.java
  dao/src/main/java/org/thingsboard/server/dao/notification/NotificationDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/notification/JpaNotificationDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/notification/NotificationRepository.java
Labels: Ignore for release

#11172 hotfix for calculate delta node: fixed false positive tests & fixed NPE
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/metadata/CalculateDeltaNode.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/metadata/CalculateDeltaNodeTest.java
Labels: bug, Rule Engine

#11175 Fix Edge Oauth2 validation
  application/src/main/java/org/thingsboard/server/service/edge/EdgeEventSourcingListener.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/fetch/OAuth2EdgeEventFetcher.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/oauth2/OAuth2EdgeProcessor.java
Labels: Ignore for release

#11176 [SWAGGER-UI] added ability to change swagger group name (definition)
  application/src/main/java/org/thingsboard/server/config/SwaggerConfiguration.java
  application/src/main/resources/thingsboard.yml
Labels: enhancement, Core

#11156 Fix startup error when Swagger is disabled
  application/src/main/java/org/thingsboard/server/config/SwaggerConfiguration.java
Labels: bug, Core

#11129 TBEL: new methods
  common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/TbUtils.java
  common/script/script-api/src/test/java/org/thingsboard/script/api/tbel/TbUtilsTest.java
Labels: Tbel

#11192 [Rest API Call node] fixed adding body condition and content-type creation
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/rest/TbHttpClient.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/rest/TbRestApiCallNodeTest.java
Labels: bug

#11196 JpaAlarmDao debug log added
  common/data/src/main/java/org/thingsboard/server/common/data/alarm/AlarmCreateOrUpdateActiveRequest.java
  common/data/src/main/java/org/thingsboard/server/common/data/alarm/AlarmUpdateRequest.java
  dao/src/main/java/org/thingsboard/server/dao/sql/alarm/JpaAlarmDao.java
Labels: Ignore for release

#11195 Fix OAuth2EdgeTest
  application/src/test/java/org/thingsboard/server/edge/NotificationEdgeTest.java
  application/src/test/java/org/thingsboard/server/edge/OAuth2EdgeTest.java
Labels: Ignore for release

#11223 Handle properly DELETE cases for ASSET/DEVICE to push ENTITY_DELETED event into correct rule chain
  application/src/main/java/org/thingsboard/server/service/queue/DefaultTbClusterService.java
  application/src/test/java/org/thingsboard/server/service/queue/DefaultTbClusterServiceTest.java
Labels: bug

#11207 Redis - disable caching in case maxSize is 0
  common/cache/src/main/java/org/thingsboard/server/cache/CacheSpecsMap.java
  common/cache/src/main/java/org/thingsboard/server/cache/RedisTbTransactionalCache.java
  common/cache/src/main/java/org/thingsboard/server/cache/TbTransactionalCache.java
  common/cache/src/test/java/org/thingsboard/server/cache/CacheSpecsMapTest.java
  dao/src/test/java/org/thingsboard/server/dao/cache/RedisTbTransactionalCacheTest.java
  dao/src/test/java/org/thingsboard/server/dao/service/AlarmServiceTest.java
Labels: enhancement, Core

#11242 Fix entities deletion task reprocessing
  application/src/main/java/org/thingsboard/server/actors/ruleChain/RuleEngineComponentActor.java
  dao/src/main/java/org/thingsboard/server/dao/resource/BaseResourceService.java
  dao/src/main/java/org/thingsboard/server/dao/rule/BaseRuleChainService.java
Labels: Ignore for release

#11168 Fixed hidden by default chart series not rendering on unhide
  ui-ngx/src/app/modules/home/components/widget/lib/chart/time-series-chart-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/chart/time-series-chart.ts
Labels: bug, UI

#11182 Fixed notify again validation after deleted recipient
  ui-ngx/src/app/shared/components/entity/entity-list.component.ts
Labels: bug, UI

#11184 Fixed String input widgets
  application/src/main/data/json/system/widget_types/update_server_string_attribute.json
  application/src/main/data/json/system/widget_types/update_shared_string_attribute.json
  application/src/main/data/json/system/widget_types/update_string_timeseries.json
  ui-ngx/src/app/core/services/utils.service.ts
Labels: bug, UI

#11202 Fixed invalid tooltip in chart fill settings
  ui-ngx/src/app/modules/home/components/widget/config/basic/chart/bar-chart-with-labels-basic-config.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/chart/bar-chart-with-labels-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/chart/chart-bar-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/chart/chart-fill-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/chart/chart-fill-settings.component.ts
Labels: bug, UI

#11233 Prevent action on preview/edit mode for notification widget
  ui-ngx/src/app/modules/home/components/widget/lib/cards/unread-notification-widget.component.ts
Labels: enhancement, UI, Ignore for release

#11255 TBEL: added some float methods
  common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/TbUtils.java
  common/script/script-api/src/test/java/org/thingsboard/script/api/tbel/TbUtilsTest.java
Labels: enhancement, Tbel

#11269 TBEL: added parameter length to methods parseBytesToNumber
  common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/TbUtils.java
  common/script/script-api/src/test/java/org/thingsboard/script/api/tbel/TbUtilsTest.java
Labels: Ignore for release, Tbel

#11283 TBEL: new version tbel and added test hexToBytes
  common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/TbUtils.java
  common/script/script-api/src/test/java/org/thingsboard/script/api/tbel/TbUtilsTest.java
  pom.xml
Labels: Tbel

#11198 Made title read only on LwM2M resources
  ui-ngx/src/app/modules/home/pages/admin/resource/resources-library.component.html
  ui-ngx/src/app/modules/home/pages/admin/resource/resources-library.component.ts
Labels: enhancement, UI

#11203 Fixed user menu duplication on customer home/default dashboard
  ui-ngx/src/app/core/auth/auth.service.ts
Labels: bug, UI

#11206 Power layouts for 'Power button' widget
  ui-ngx/src/app/modules/home/components/widget/lib/rpc/power-button-widget.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
  ui-ngx/src/assets/widget/power-button/default-icon-layout.svg
  ui-ngx/src/assets/widget/power-button/outlined-icon-layout.svg
  ui-ngx/src/assets/widget/power-button/simplified-icon-layout.svg
Labels: enhancement, UI

#11228 Fixed device profile create/update form validation
  ui-ngx/src/app/modules/home/components/profile/add-device-profile-dialog.component.html
  ui-ngx/src/app/modules/home/components/profile/device-profile.component.html
  ui-ngx/src/app/modules/home/components/profile/device/coap-device-profile-transport-configuration.component.ts
  ui-ngx/src/app/modules/home/components/profile/device/default-device-profile-configuration.component.ts
  ui-ngx/src/app/modules/home/components/profile/device/default-device-profile-transport-configuration.component.ts
  ui-ngx/src/app/modules/home/components/profile/device/device-profile-configuration.component.html
  ui-ngx/src/app/modules/home/components/profile/device/device-profile-configuration.component.ts
  ui-ngx/src/app/modules/home/components/profile/device/device-profile-transport-configuration.component.html
  ui-ngx/src/app/modules/home/components/profile/device/device-profile-transport-configuration.component.ts
  ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-device-profile-transport-configuration.component.ts
  ui-ngx/src/app/modules/home/components/profile/device/mqtt-device-profile-transport-configuration.component.ts
  ui-ngx/src/app/modules/home/components/profile/device/snmp/snmp-device-profile-transport-configuration.component.ts
  ui-ngx/src/app/modules/home/pages/device-profile/device-profile-tabs.component.html
Labels: bug, UI, Ignore for release

#11238 Fix 'Home dasboards' widget
  ui-ngx/src/app/modules/home/components/widget/lib/home-page/recent-dashboards-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/home-page/recent-dashboards-widget.component.ts
Labels: bug, UI

#11267 Validation min max value for digital gauge settings
  ui-ngx/src/app/modules/home/components/widget/config/basic/gauge/digital-simple-gauge-basic-config.component.html
  ui-ngx/src/app/modules/home/components/widget/config/basic/gauge/digital-simple-gauge-basic-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/gauge/digital-gauge-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/gauge/digital-gauge-widget-settings.component.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI, Ignore for release

#11272 Fixed overlapping dialog window by autocomplete list
  ui-ngx/src/app/modules/home/components/profile/asset-profile-autocomplete.component.ts
  ui-ngx/src/app/modules/home/components/profile/device-profile-autocomplete.component.ts
Labels: bug, UI

#11277 Improvements and bug fix for notification widget
  application/src/main/data/json/system/widget_types/unread_notifications.json
  ui-ngx/src/app/modules/home/components/widget/config/basic/cards/unread-notification-basic-config.component.html
  ui-ngx/src/app/modules/home/components/widget/config/basic/cards/unread-notification-basic-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/cards/unread-notification-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/cards/unread-notification-widget.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/cards/unread-notification-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/cards/unread-notification-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/unread-notification-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/unread-notification-widget-settings.component.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI, Ignore for release

#11282 Fix documentation link
  ui-ngx/src/assets/help/en_US/rulenode/common_node_fields_templatization.md
Labels: bug, UI

#11288 Fixed Editing Resource title for JS module Resource
  ui-ngx/src/app/modules/home/pages/admin/resource/resources-library.component.html
  ui-ngx/src/app/modules/home/pages/admin/resource/resources-library.component.ts
Labels: bug, UI

#11290 Fixed Device Profile LwM2M Server information collapsed state view
  ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-device-config-server.component.html
Labels: bug, UI

#11209 Removed persisted data on creation of new Connector in RPC configuration
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc.component.ts
Labels: bug, UI

#11219 Fixed updating credentials in gateway dashboard
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-configuration.component.ts
Labels: bug, UI

#11241 Removed table Add Connector button from page on no connectors displayed
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-connectors.component.html
Labels: bug, UI

#11285 Fixed Connector Form state after connector with basic config removal
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-connectors.component.ts
Labels: bug, UI, Ignore for release

#11174 OPC-UA Data mapping crushing on creating empty connector fix
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/mapping-table/mapping-table.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/dialog/mapping-dialog.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-widget.models.ts
Labels: bug, UI

#11185 Added 'With Response' to MQTT templates and removed Response Time
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc-connector.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc-connector.component.ts
  ui-ngx/src/app/shared/pipe/key-value-not-empty.pipe.ts
Labels: bug, UI

#11186 Fixed spacing in OPC-UA server tab
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/server-config/server-config.component.html
Labels: bug, UI, Ignore for release

#11188 Added ability to open statistics settings from statistics state on Gateway dashboard
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-statistics.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-statistics.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-statistics.component.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI

#11189 Added emmition of default values on Connector with basic config creation
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/broker-config-control/broker-config-control.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/mqtt-basic-config/mqtt-basic-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/workers-config-control/workers-config-control.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/dialog/add-connector-dialog.component.ts
Labels: bug, UI, Ignore for release

#11197 Added view update for Connectors on switching active connector
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/broker-config-control/broker-config-control.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/security-config/security-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/server-config/server-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/workers-config-control/workers-config-control.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-connectors.component.ts
Labels: bug, UI

#11296 TBEL: added parseBytesIntToFloat, parseBytesLongToDouble, byteArrayToExecutionArrayList
  common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/TbUtils.java
  common/script/script-api/src/test/java/org/thingsboard/script/api/tbel/TbUtilsTest.java
Labels: Ignore for release

#11318 Fix script compile error (ScriptCPUAbuseException) with Nashorn sandbox
  application/src/test/java/org/thingsboard/server/service/script/NashornJsInvokeServiceTest.java
  pom.xml
Labels: bug, Rule Engine

#11265 HTTP API: validate payload size
  application/src/main/java/org/thingsboard/server/config/RequestSizeFilter.java
  application/src/main/java/org/thingsboard/server/config/ThingsboardSecurityConfiguration.java
  application/src/main/java/org/thingsboard/server/controller/RpcV2Controller.java
  application/src/main/java/org/thingsboard/server/exception/ThingsboardErrorResponseHandler.java
  application/src/main/resources/thingsboard.yml
  application/src/test/java/org/thingsboard/server/controller/RpcControllerTest.java
  application/src/test/java/org/thingsboard/server/system/BaseHttpDeviceApiTest.java
  common/message/src/main/java/org/thingsboard/server/common/msg/tools/MaxPayloadSizeExceededException.java
  common/transport/http/src/main/java/org/thingsboard/server/transport/http/DeviceApiController.java
  transport/http/src/main/resources/tb-http-transport.yml
Labels: enhancement, Transport

#11323 TBEL: added padStart, padEnd, parseByteToBinaryArray, parseBytesToBinaryArray, parseLongToBinaryArray
  common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/TbUtils.java
  common/script/script-api/src/test/java/org/thingsboard/script/api/tbel/TbUtilsTest.java
Labels: Ignore for release

#11322 added TbRuleEngineStrategyTest
  application/src/test/java/org/thingsboard/server/service/queue/ruleengine/TbRuleEngineStrategyTest.java
Labels: Ignore for release
