Repository thingsboard/thingsboard, pull requests merged in 2024-10, with the labels that each got.

#11773 Fixed pulse counter telemetry calculation
  common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/efento/CoapEfentoTransportResource.java
  common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/efento/utils/CoapEfentoUtils.java
  common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/efento/utils/PulseCounterType.java
  common/transport/coap/src/test/java/org/thingsboard/server/transport/coap/efento/CoapEfentoTransportResourceTest.java
Labels: Ignore for release

#11786 Added logging for CoapEfentoTransportResource
  common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/efento/CoapEfentoTransportResource.java
Labels: Ignore for release

#11763 Fixed pattern animation for chrome 127
  ui-ngx/src/app/modules/home/components/widget/lib/scada/scada-symbol.models.ts
Labels: bug, UI, Ignore for release

#11783 Updated material-icons.json metadate
  ui-ngx/generate-icon-metadata.js
  ui-ngx/package.json
  ui-ngx/src/app/shared/models/icon.models.ts
  ui-ngx/src/assets/metadata/material-icons.json
Labels: enhancement, UI

#11787 Gateway fixes and added support for newer Gateway versions
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/abstract/gateway-connector-version-processor.abstract.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-slave-config/modbus-slave-config.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/security-config/security-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/dialog/add-connector-dialog.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-connectors.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-connectors.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/pipes/gateway-help-link.pipe.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/pipes/latest-version-config.pipe.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/utils/gateway-connector-version-mapping.util.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/utils/opc-version-mapping.util.ts
  ui-ngx/src/app/modules/home/components/widget/widget-components.module.ts
  ui-ngx/src/assets/help/en_US/widget/lib/gateway/attributes_timeseries_expressions_fn.md
  ui-ngx/src/assets/locale/locale.constant-en_US.json
  ui-ngx/src/assets/metadata/connector-default-configs/modbus.json
Labels: bug, enhancement, UI, Ignore for release

#11795 Fixed edit and disabled oauth client settings scope
  ui-ngx/src/app/modules/home/pages/admin/oauth2/clients/client.component.html
  ui-ngx/src/app/modules/home/pages/admin/oauth2/clients/client.component.ts
Labels: bug, UI, Ignore for release

#11797 Drop max Hikari pool size to 4 for dedicated datasource
  application/src/main/resources/thingsboard.yml
Labels: Ignore for release

#11798 Fixed the inability to edit resource type in resource library when created resource
  ui-ngx/src/app/modules/home/pages/admin/resource/resources-library.component.ts
Labels: bug, UI, Ignore for release

#11805 Updated leaflet to 1.9.12
  ui-ngx/package.json
  ui-ngx/src/app/modules/home/components/widget/lib/maps/common-maps-utils.ts
  ui-ngx/src/app/modules/home/components/widget/lib/maps/leaflet-map.ts
  ui-ngx/src/app/modules/home/components/widget/lib/maps/map-models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/maps/map-widget.interface.ts
  ui-ngx/src/app/modules/home/components/widget/lib/maps/map-widget2.ts
  ui-ngx/src/app/modules/home/components/widget/lib/maps/maps-utils.ts
  ui-ngx/src/app/modules/home/components/widget/lib/maps/markers.ts
  ui-ngx/src/app/modules/home/components/widget/lib/maps/providers/google-map.ts
  ui-ngx/src/app/modules/home/components/widget/lib/maps/providers/here-map.ts
  ui-ngx/src/app/modules/home/components/widget/lib/maps/providers/image-map.ts
  ui-ngx/src/app/modules/home/components/widget/lib/maps/providers/openstreet-map.ts
  ui-ngx/src/app/modules/home/components/widget/lib/maps/providers/tencent-map.ts
  ui-ngx/yarn.lock
Labels: enhancement, UI, Ignore for release

#11780 Fixed cropped "qr mobile app" widget title on tenant home page
  ui-ngx/src/assets/dashboard/tenant_admin_home_page.json
Labels: bug, UI

#11823 Fixed not updated group interval in history time windows
  ui-ngx/src/app/shared/components/time/timewindow-config-dialog.component.html
  ui-ngx/src/app/shared/components/time/timewindow-config-dialog.component.ts
  ui-ngx/src/app/shared/components/time/timewindow-panel.component.html
Labels: bug, UI

#11830 Fixed accumulative pulse counter total value calculation
  common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/efento/CoapEfentoTransportResource.java
  common/transport/coap/src/test/java/org/thingsboard/server/transport/coap/efento/CoapEfentoTransportResourceTest.java
Labels: bug

#11845 tbel: version 1.2.4
  pom.xml
Labels: Tbel

#11820 fixed IndexOutOfBoundsException during saving old latestTs
  dao/src/main/java/org/thingsboard/server/dao/AbstractVersionedInsertRepository.java
  dao/src/test/java/org/thingsboard/server/dao/sqlts/SqlTimeseriesLatestDaoTest.java
Labels: bug

#11849 Improve Git repository init
  common/version-control/src/main/java/org/thingsboard/server/service/sync/vc/DefaultGitRepositoryService.java
  common/version-control/src/main/java/org/thingsboard/server/service/sync/vc/GitRepository.java
Labels: Ignore for release

#11857 Fix overlapping widgets when changing layout columns count
  ui-ngx/src/app/core/services/dashboard-utils.service.ts
Labels: bug, UI

#11858 Remove flex layout in gateway widgets
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/configuration/advanced/gateway-advanced-configuration.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/configuration/basic/gateway-basic-configuration.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/mapping-data-keys-panel/mapping-data-keys-panel.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/mapping-table/mapping-table.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-basic-config/modbus-basic-config.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-data-keys-panel/modbus-data-keys-panel.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-master-table/modbus-master-table.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-security-config/modbus-security-config.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-slave-config/modbus-slave-config.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-slave-dialog/modbus-slave-dialog.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-values/modbus-values.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/mqtt/broker-config-control/broker-config-control.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/mqtt/workers-config-control/workers-config-control.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/opc/opc-server-config/opc-server-config.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/report-strategy/report-strategy.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/rpc-parameters/modbus-rpc-parameters/modbus-rpc-parameters.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/rpc-parameters/opc-rpc-parameters/opc-rpc-parameters.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/type-value-panel/type-value-panel.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/dialog/add-connector-dialog.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/dialog/mapping-dialog.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-connectors.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-form.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-form.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-logs.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-remote-configuration-dialog.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc-connector-template-dialog.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc-connector-templates.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc-connector.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-statistics.component.html
  ui-ngx/tailwind.config.js
Labels: enhancement, UI, Ignore for release

#11862 Remove flex layout in map widgets settings
  ui-ngx/src/app/modules/home/components/widget/lib/settings/map/circle-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/map/common-map-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/map/datasources-key-autocomplete.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/map/google-map-provider-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/map/here-map-provider-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/map/image-map-provider-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/map/map-editor-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/map/map-provider-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/map/map-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/map/marker-clustering-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/map/markers-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/map/openstreet-map-provider-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/map/polygon-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/map/route-map-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/map/tencent-map-provider-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/map/trip-animation-common-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/map/trip-animation-marker-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/map/trip-animation-path-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/map/trip-animation-point-settings.component.html
Labels: enhancement, UI, Ignore for release

#11854 Lwm2m fix bug
  application/src/test/java/org/thingsboard/server/transport/lwm2m/client/LwM2MTestClient.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/client/LwM2mTemperatureSensor.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/AbstractRpcLwM2MIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationReadCollectedValueTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationReadTest.java
Labels: Ignore for release

#11846 Fix bug coap tests
  application/src/test/java/org/thingsboard/server/transport/coap/rpc/AbstractCoapServerSideRpcIntegrationTest.java
Labels: Ignore for release

#11843 Hide mail sender error details
  application/src/main/java/org/thingsboard/server/controller/AdminController.java
  application/src/main/java/org/thingsboard/server/controller/AuthController.java
  application/src/main/java/org/thingsboard/server/controller/BaseController.java
  application/src/main/java/org/thingsboard/server/controller/UserController.java
  application/src/main/java/org/thingsboard/server/service/entitiy/user/DefaultUserService.java
  application/src/main/java/org/thingsboard/server/service/mail/DefaultMailService.java
  application/src/main/java/org/thingsboard/server/service/security/auth/mfa/provider/impl/EmailTwoFaProvider.java
Labels: Ignore for release

#11671 Remove security-related info from user's additional info
  application/src/main/data/upgrade/3.8.1/schema_update.sql
  application/src/main/java/org/thingsboard/server/controller/BaseController.java
  application/src/main/java/org/thingsboard/server/controller/UserController.java
  application/src/main/java/org/thingsboard/server/service/edge/EdgeEventSourcingListener.java
  application/src/main/java/org/thingsboard/server/service/security/system/DefaultSystemSecurityService.java
  application/src/test/java/org/thingsboard/server/controller/AuthControllerTest.java
  application/src/test/java/org/thingsboard/server/controller/TwoFactorAuthTest.java
  application/src/test/java/org/thingsboard/server/controller/UserControllerTest.java
  application/src/test/java/org/thingsboard/server/edge/UserEdgeTest.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/user/UserService.java
  common/data/src/main/java/org/thingsboard/server/common/data/security/UserCredentials.java
  dao/src/main/java/org/thingsboard/server/dao/model/ModelConstants.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/UserCredentialsEntity.java
  dao/src/main/java/org/thingsboard/server/dao/sql/user/JpaUserCredentialsDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/user/UserCredentialsRepository.java
  dao/src/main/java/org/thingsboard/server/dao/user/UserCredentialsDao.java
  dao/src/main/java/org/thingsboard/server/dao/user/UserServiceImpl.java
  dao/src/main/resources/sql/schema-entities.sql
Labels: enhancement, Core

#11877 automaticaly set schema version based on app version
  application/src/main/java/org/thingsboard/server/install/ThingsboardInstallService.java
  application/src/main/java/org/thingsboard/server/service/install/EntityDatabaseSchemaService.java
  application/src/main/java/org/thingsboard/server/service/install/SqlEntityDatabaseSchemaService.java
  application/src/main/java/org/thingsboard/server/service/install/SqlTsDatabaseSchemaService.java
  dao/src/main/resources/sql/schema-entities.sql
Labels: Ignore for release

#11892 Updated postgres from 15 to 16
  application/src/main/data/json/edge/instructions/install/centos/instructions.md
  application/src/main/data/json/edge/instructions/install/docker/instructions.md
  application/src/main/data/json/edge/instructions/install/ubuntu/instructions.md
  application/src/main/data/json/edge/instructions/upgrade/docker/upgrade_db.md
  docker/docker-compose.hybrid.yml
  docker/docker-compose.postgres.yml
  msa/tb/docker-cassandra/Dockerfile
Labels: enhancement

#11815 Updated modules map for gateway extension migration
  ui-ngx/src/app/modules/common/modules-map.ts
  ui-ngx/src/app/shared/components/public-api.ts
  ui-ngx/src/app/shared/pipe/public-api.ts
Labels: UI, Ignore for release

#11944 fix_bug_test_coap_processTwoWayRpcTest
  application/src/test/java/org/thingsboard/server/transport/coap/rpc/AbstractCoapServerSideRpcIntegrationTest.java
Labels: bug

#11896 Lwm2m_write_obj_19
  application/src/test/java/org/thingsboard/server/transport/lwm2m/AbstractLwM2MIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/client/LwM2MTestClient.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/client/LwM2mBinaryAppDataContainer.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/ota/sql/Ota5LwM2MIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/ota/sql/Ota9LwM2MIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/AbstractRpcLwM2MIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2MIntegrationObserveCompositeTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationCreateTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationDeleteTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationDiscoverTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationDiscoverWriteAttributesTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationExecuteTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationObserveTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationReadCollectedValueTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationReadTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationWriteCborTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationWriteTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/security/AbstractSecurityLwM2MIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/security/cid/AbstractSecurityLwM2MIntegrationDtlsCidLengthTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/security/diffPort/AbstractLwM2MIntegrationDiffPortTest.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/downlink/DefaultLwM2mDownlinkMsgHandler.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/rpc/DefaultLwM2MRpcRequestHandler.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/utils/LwM2MTransportUtil.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/utils/LwM2mValueConverterImpl.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/service/DefaultTransportService.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/util/JsonUtils.java
Labels: Transport

#11948 Sync with Git: ignore if no changes
  application/src/main/java/org/thingsboard/server/service/entitiy/dashboard/DashboardSyncService.java
  application/src/main/java/org/thingsboard/server/service/install/InstallScripts.java
  application/src/main/java/org/thingsboard/server/service/sync/DefaultGitSyncService.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/resource/ResourceService.java
  common/version-control/src/main/java/org/thingsboard/server/service/sync/vc/GitRepository.java
  dao/src/main/java/org/thingsboard/server/dao/resource/BaseResourceService.java
Labels: Ignore for release

#11878 Fixed originator telemetry node
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/metadata/TbGetTelemetryNode.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/metadata/TbGetTelemetryNodeTest.java
Labels: bug, Rule Engine

#11949 Don't create gateways dashboard for new tenants; process images for system dashboard resource
  application/src/main/data/json/tenant/dashboards/gateways.json
  application/src/main/java/org/thingsboard/server/service/entitiy/dashboard/DashboardSyncService.java
  application/src/main/java/org/thingsboard/server/service/install/InstallScripts.java
  application/src/test/java/org/thingsboard/server/service/install/InstallScriptsTest.java
  dao/src/main/java/org/thingsboard/server/dao/resource/BaseResourceService.java
Labels: Ignore for release

#11969 tbel_fix_bug_validate_decimal
  common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/TbUtils.java
  common/script/script-api/src/test/java/org/thingsboard/script/api/tbel/TbUtilsTest.java
Labels: bug, Tbel

#11893 activity_Failed to send message to core
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/service/DefaultTransportService.java
Labels: Ignore for release
