Repository thingsboard/thingsboard, pull requests merged in 2024-12, with the labels that each got.

#12157 Fixed mobile layout configuration response
  application/src/main/java/org/thingsboard/server/controller/MobileAppController.java
  dao/src/main/java/org/thingsboard/server/dao/mobile/MobileAppBundleServiceImpl.java
Labels: bug, Ignore for release

#12147 Debug settings changed approach to object (ControlValueAccessor) and refactoring
  ui-ngx/src/app/modules/home/components/debug-config/debug-config-button.component.html
  ui-ngx/src/app/modules/home/components/debug-config/debug-config-button.component.scss
  ui-ngx/src/app/modules/home/components/debug-config/debug-config-button.component.ts
  ui-ngx/src/app/modules/home/components/debug-config/debug-config-panel.component.ts
  ui-ngx/src/app/modules/home/components/debug-settings/debug-settings-button.component.html
  ui-ngx/src/app/modules/home/components/debug-settings/debug-settings-button.component.ts
  ui-ngx/src/app/modules/home/components/debug-settings/debug-settings-panel.component.html
  ui-ngx/src/app/modules/home/components/debug-settings/debug-settings-panel.component.ts
  ui-ngx/src/app/modules/home/components/event/event-table-config.ts
  ui-ngx/src/app/modules/home/components/profile/tenant/default-tenant-profile-configuration.component.html
  ui-ngx/src/app/modules/home/components/profile/tenant/default-tenant-profile-configuration.component.ts
  ui-ngx/src/app/modules/home/pages/rulechain/rule-node-details.component.html
  ui-ngx/src/app/modules/home/pages/rulechain/rule-node-details.component.ts
  ui-ngx/src/app/modules/home/pages/rulechain/rulechain-page.component.ts
  ui-ngx/src/app/modules/home/pages/rulechain/rulechain.module.ts
  ui-ngx/src/app/shared/import-export/import-export.service.ts
  ui-ngx/src/app/shared/models/entity.models.ts
  ui-ngx/src/app/shared/models/rule-node.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI, Ignore for release

#12133 Upgrade version and product validation, upgrade refactoring
  application/src/main/data/upgrade/3.5.0/schema_update.sql
  application/src/main/data/upgrade/3.5.1/schema_update.sql
  application/src/main/data/upgrade/3.6.0/schema_update.sql
  application/src/main/data/upgrade/3.6.1/save_attributes_node_update.sql
  application/src/main/data/upgrade/3.6.1/schema_update.sql
  application/src/main/data/upgrade/3.6.2/schema_update.sql
  application/src/main/data/upgrade/3.6.3/schema_update.sql
  application/src/main/data/upgrade/3.6.4/schema_update.sql
  application/src/main/data/upgrade/3.7.0/schema_update.sql
  application/src/main/data/upgrade/basic/schema_update.sql
  application/src/main/java/org/thingsboard/server/install/ThingsboardInstallService.java
  application/src/main/java/org/thingsboard/server/service/install/AbstractSqlTsDatabaseUpgradeService.java
  application/src/main/java/org/thingsboard/server/service/install/DatabaseEntitiesUpgradeService.java
  application/src/main/java/org/thingsboard/server/service/install/DatabaseSchemaSettingsService.java
  application/src/main/java/org/thingsboard/server/service/install/DatabaseTsUpgradeService.java
  application/src/main/java/org/thingsboard/server/service/install/DefaultDatabaseSchemaSettingsService.java
  application/src/main/java/org/thingsboard/server/service/install/EntityDatabaseSchemaService.java
  application/src/main/java/org/thingsboard/server/service/install/SqlDatabaseUpgradeService.java
  application/src/main/java/org/thingsboard/server/service/install/SqlEntityDatabaseSchemaService.java
  application/src/main/java/org/thingsboard/server/service/install/SqlTsDatabaseUpgradeService.java
  application/src/main/java/org/thingsboard/server/service/install/TimescaleTsDatabaseUpgradeService.java
  application/src/main/java/org/thingsboard/server/service/install/update/CacheCleanupService.java
  application/src/main/java/org/thingsboard/server/service/install/update/DataUpdateService.java
  application/src/main/java/org/thingsboard/server/service/install/update/DefaultCacheCleanupService.java
  application/src/main/java/org/thingsboard/server/service/install/update/DefaultDataUpdateService.java
  dao/src/main/resources/sql/schema-entities.sql
Labels: enhancement

#12161 Updated rulenode-core-config.js (save to custom table)
  rule-engine/rule-engine-components/src/main/resources/public/static/rulenode/rulenode-core-config.js
Labels: UI, Rule Engine, Ignore for release

#12024 js-executor: added request body on debug level
  msa/js-executor/api/jsInvokeMessageProcessor.ts
Labels: Ignore for release

#11675 hashcode caching for immutable objects
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/tenant/TenantEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/queue/DefaultTbCoreConsumerService.java
  application/src/main/java/org/thingsboard/server/service/queue/DefaultTbRuleEngineConsumerService.java
  application/src/main/java/org/thingsboard/server/service/subscription/TbSubscription.java
  common/data/src/main/java/org/thingsboard/server/common/data/DeviceIdInfo.java
  common/data/src/main/java/org/thingsboard/server/common/data/DeviceProfileInfo.java
  common/data/src/main/java/org/thingsboard/server/common/data/asset/AssetProfileInfo.java
  common/data/src/main/java/org/thingsboard/server/common/data/id/EntityIdFactory.java
  common/data/src/main/java/org/thingsboard/server/common/data/id/TenantId.java
  common/data/src/main/java/org/thingsboard/server/common/data/id/UUIDBased.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/store/util/LwM2MClientSerDes.java
  common/version-control/src/main/java/org/thingsboard/server/service/sync/vc/VersionControlRequestCtx.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/OAuth2ClientEntity.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/QueueEntity.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/QueueStatsEntity.java
  dao/src/main/java/org/thingsboard/server/dao/tenant/TenantServiceImpl.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/util/TenantIdLoader.java
Labels: enhancement

#12114 Refactoring SCADA symbols
  application/src/main/data/json/system/scada_symbols/bottom-flow-meter.svg
  application/src/main/data/json/system/scada_symbols/centrifugal-pump.svg
  application/src/main/data/json/system/scada_symbols/control-panel-hp.svg
  application/src/main/data/json/system/scada_symbols/cylindrical-tank.svg
  application/src/main/data/json/system/scada_symbols/dynamic-horizontal-scale-hp.svg
  application/src/main/data/json/system/scada_symbols/dynamic-vertical-scale-hp.svg
  application/src/main/data/json/system/scada_symbols/elevated-tank.svg
  application/src/main/data/json/system/scada_symbols/filter-hp.svg
  application/src/main/data/json/system/scada_symbols/heat-pump-hp.svg
  application/src/main/data/json/system/scada_symbols/horizontal-inline-flow-meter.svg
  application/src/main/data/json/system/scada_symbols/horizontal-tank-hp.svg
  application/src/main/data/json/system/scada_symbols/horizontal-tank.svg
  application/src/main/data/json/system/scada_symbols/horizontal-valve-hp.svg
  application/src/main/data/json/system/scada_symbols/large-cylindrical-tank.svg
  application/src/main/data/json/system/scada_symbols/large-stand-cylindrical-tank.svg
  application/src/main/data/json/system/scada_symbols/large-stand-vertical-tank.svg
  application/src/main/data/json/system/scada_symbols/large-vertical-tank.svg
  application/src/main/data/json/system/scada_symbols/left-analog-water-level-meter.svg
  application/src/main/data/json/system/scada_symbols/left-flow-meter.svg
  application/src/main/data/json/system/scada_symbols/left-heat-pump.svg
  application/src/main/data/json/system/scada_symbols/left-motor-pump.svg
  application/src/main/data/json/system/scada_symbols/long-vertical-connector-hp.svg
  application/src/main/data/json/system/scada_symbols/pool-hp.svg
  application/src/main/data/json/system/scada_symbols/pump-hp.svg
  application/src/main/data/json/system/scada_symbols/right-analog-water-level-meter.svg
  application/src/main/data/json/system/scada_symbols/right-flow-meter.svg
  application/src/main/data/json/system/scada_symbols/right-heat-pump.svg
  application/src/main/data/json/system/scada_symbols/right-motor-pump.svg
  application/src/main/data/json/system/scada_symbols/sand-filter-hp.svg
  application/src/main/data/json/system/scada_symbols/short-vertical-tank-hp.svg
  application/src/main/data/json/system/scada_symbols/simple-horizontal-scale-hp.svg
  application/src/main/data/json/system/scada_symbols/simple-vertical-scale-hp.svg
  application/src/main/data/json/system/scada_symbols/small-cylindrical-tank.svg
  application/src/main/data/json/system/scada_symbols/small-left-motor-pump.svg
  application/src/main/data/json/system/scada_symbols/small-right-motor-pump.svg
  application/src/main/data/json/system/scada_symbols/small-spherical-tank.svg
  application/src/main/data/json/system/scada_symbols/spherical-tank.svg
  application/src/main/data/json/system/scada_symbols/stand-cylindrical-tank.svg
  application/src/main/data/json/system/scada_symbols/stand-horizontal-tank.svg
  application/src/main/data/json/system/scada_symbols/stand-vertical-short-tank.svg
  application/src/main/data/json/system/scada_symbols/stand-vertical-tank.svg
  application/src/main/data/json/system/scada_symbols/top-flow-meter.svg
  application/src/main/data/json/system/scada_symbols/vertical-inline-flow-meter.svg
  application/src/main/data/json/system/scada_symbols/vertical-short-tank.svg
  application/src/main/data/json/system/scada_symbols/vertical-tank-hp.svg
  application/src/main/data/json/system/scada_symbols/vertical-tank.svg
  application/src/main/data/json/system/scada_symbols/vertical-valve-hp.svg
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: bug, UI, Ignore for release

#11244 Update template.service
  packaging/java/scripts/control/template.service
Labels: Build Scripts

#11647 Custom OAuth 2.0: Add NONE auth method needed for some auth servers like Django
  dao/src/main/java/org/thingsboard/server/dao/oauth2/HybridClientRegistrationRepository.java
  ui-ngx/src/app/shared/models/oauth2.models.ts
Labels: enhancement, Core

#12117 Fixed incorrect show long number in attribute card
  application/src/main/data/json/system/widget_types/attributes_card.json
  ui-ngx/src/app/core/utils.ts
Labels: bug, UI

#12118 Improvement validation message on JWT security settings
  ui-ngx/src/app/modules/home/pages/admin/security-settings.component.html
  ui-ngx/src/app/modules/home/pages/admin/security-settings.component.ts
  ui-ngx/src/assets/locale/locale.constant-ar_AE.json
  ui-ngx/src/assets/locale/locale.constant-en_US.json
  ui-ngx/src/assets/locale/locale.constant-es_ES.json
  ui-ngx/src/assets/locale/locale.constant-lt_LT.json
  ui-ngx/src/assets/locale/locale.constant-nl_BE.json
  ui-ngx/src/assets/locale/locale.constant-pl_PL.json
  ui-ngx/src/assets/locale/locale.constant-zh_CN.json
Labels: enhancement, UI

#12163 Improvements for Housekeeping service
  application/src/main/java/org/thingsboard/server/service/housekeeper/HousekeeperService.java
  application/src/main/java/org/thingsboard/server/service/housekeeper/processor/HousekeeperTaskProcessor.java
  application/src/main/java/org/thingsboard/server/service/housekeeper/processor/LatestTsDeletionTaskProcessor.java
  application/src/main/java/org/thingsboard/server/service/housekeeper/processor/TsHistoryDeletionTaskProcessor.java
  application/src/test/java/org/thingsboard/server/service/housekeeper/HousekeeperServiceTest.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/util/SemaphoreWithTbMsgQueue.java
Labels: enhancement, Core

#12162 rc
  application/src/main/java/org/thingsboard/server/service/housekeeper/HousekeeperService.java
  application/src/main/java/org/thingsboard/server/service/housekeeper/processor/HousekeeperTaskProcessor.java
  application/src/main/java/org/thingsboard/server/service/housekeeper/processor/LatestTsDeletionTaskProcessor.java
  application/src/main/java/org/thingsboard/server/service/housekeeper/processor/TsHistoryDeletionTaskProcessor.java
  application/src/test/java/org/thingsboard/server/service/housekeeper/HousekeeperServiceTest.java
  msa/js-executor/api/jsInvokeMessageProcessor.ts
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/util/SemaphoreWithTbMsgQueue.java
Labels: WIP

#12142 Two-segment button widget
  application/src/main/data/json/system/widget_bundles/buttons.json
  application/src/main/data/json/system/widget_bundles/control_widgets.json
  application/src/main/data/json/system/widget_types/two_segment_button.json
  ui-ngx/src/app/modules/home/components/widget/config/basic/basic-widget-config.module.ts
  ui-ngx/src/app/modules/home/components/widget/config/basic/button/segmented-button-basic-config.component.html
  ui-ngx/src/app/modules/home/components/widget/config/basic/button/segmented-button-basic-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/button/segmented-button-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/button/two-segment-button-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/button/two-segment-button-widget.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/button/two-segment-button-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/button/segmented-button-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/button/segmented-button-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/button/widget-button-toggle-custom-style-panel.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/button/widget-button-toggle-custom-style-panel.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/button/widget-button-toggle-custom-style-panel.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/button/widget-button-toggle-custom-style.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/button/widget-button-toggle-custom-style.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/button/widget-button-toggle-custom-style.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/widget-settings-common.module.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/widget-settings.module.ts
  ui-ngx/src/app/modules/home/components/widget/widget-components.module.ts
  ui-ngx/src/app/shared/components/button/widget-button-toggle.component.html
  ui-ngx/src/app/shared/components/button/widget-button-toggle.component.scss
  ui-ngx/src/app/shared/components/button/widget-button-toggle.component.ts
  ui-ngx/src/app/shared/shared.module.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
  ui-ngx/src/assets/widget/segmented-button/rounded-layout.svg
  ui-ngx/src/assets/widget/segmented-button/squared-layout.svg
Labels: UI, feature

#12177 Added show helps for bacnet connector basic config
  ui-ngx/src/assets/help/en_US/widget/lib/gateway/bacnet-device-name-field-expression_fn.md
  ui-ngx/src/assets/help/en_US/widget/lib/gateway/bacnet-device-profile-name-expression_fn.md
Labels: enhancement, UI, Ignore for release

#12179 Warning/Critical state animation for HP SCADA
  application/src/main/data/json/system/scada_symbols/filter-hp.svg
  application/src/main/data/json/system/scada_symbols/heat-pump-hp.svg
  application/src/main/data/json/system/scada_symbols/horizontal-tank-hp.svg
  application/src/main/data/json/system/scada_symbols/horizontal-valve-hp.svg
  application/src/main/data/json/system/scada_symbols/pool-hp.svg
  application/src/main/data/json/system/scada_symbols/pump-hp.svg
  application/src/main/data/json/system/scada_symbols/sand-filter-hp.svg
  application/src/main/data/json/system/scada_symbols/short-vertical-tank-hp.svg
  application/src/main/data/json/system/scada_symbols/vertical-tank-hp.svg
  application/src/main/data/json/system/scada_symbols/vertical-valve-hp.svg
  application/src/main/data/json/system/widget_bundles/general_high_performance_scada_symbols.json
  application/src/main/data/json/system/widget_bundles/high_performance_scada_fluid_system.json
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI, Ignore for release

#12166 Fix multiple vulnerabilities
  pom.xml
Labels: enhancement, Core

#12182 Fixed Two segment button widget disable event on edit mode
  ui-ngx/src/app/modules/home/components/widget/lib/button/two-segment-button-widget.component.html
Labels: bug, UI, Ignore for release

#12186 Added JavaScript library details audit logs and version control
  ui-ngx/src/app/modules/home/components/vc/entity-version-create.component.html
  ui-ngx/src/app/modules/home/components/vc/entity-version-create.component.ts
  ui-ngx/src/app/modules/home/pages/admin/admin.module.ts
  ui-ngx/src/app/modules/home/pages/admin/resource/js-library-table-config.resolver.ts
  ui-ngx/src/app/modules/home/pages/admin/resource/resource-tabs.component.html
  ui-ngx/src/app/modules/home/pages/admin/resource/resource-tabs.component.ts
  ui-ngx/src/app/shared/models/vc.models.ts
Labels: enhancement, UI, Ignore for release

#11937 Remove all queue types except Kafka
  application/src/main/resources/thingsboard.yml
  common/queue/pom.xml
  common/queue/src/main/java/org/thingsboard/server/queue/RuleEngineTbQueueAdminFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/azure/servicebus/TbServiceBusAdmin.java
  common/queue/src/main/java/org/thingsboard/server/queue/azure/servicebus/TbServiceBusConsumerTemplate.java
  common/queue/src/main/java/org/thingsboard/server/queue/azure/servicebus/TbServiceBusProducerTemplate.java
  common/queue/src/main/java/org/thingsboard/server/queue/azure/servicebus/TbServiceBusQueueConfigs.java
  common/queue/src/main/java/org/thingsboard/server/queue/azure/servicebus/TbServiceBusSettings.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/AwsSqsMonolithQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/AwsSqsTbCoreQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/AwsSqsTbRuleEngineQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/AwsSqsTbVersionControlQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/AwsSqsTransportQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/PubSubMonolithQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/PubSubTbCoreQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/PubSubTbRuleEngineQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/PubSubTbVersionControlQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/PubSubTransportQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/RabbitMqMonolithQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/RabbitMqTbCoreQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/RabbitMqTbRuleEngineQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/RabbitMqTbVersionControlQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/RabbitMqTransportQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/ServiceBusMonolithQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/ServiceBusTbCoreQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/ServiceBusTbRuleEngineQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/ServiceBusTbVersionControlQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/ServiceBusTransportQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/pubsub/TbPubSubAdmin.java
  common/queue/src/main/java/org/thingsboard/server/queue/pubsub/TbPubSubConsumerTemplate.java
  common/queue/src/main/java/org/thingsboard/server/queue/pubsub/TbPubSubProducerTemplate.java
  common/queue/src/main/java/org/thingsboard/server/queue/pubsub/TbPubSubSettings.java
  common/queue/src/main/java/org/thingsboard/server/queue/pubsub/TbPubSubSubscriptionSettings.java
  common/queue/src/main/java/org/thingsboard/server/queue/rabbitmq/TbRabbitMqAdmin.java
  common/queue/src/main/java/org/thingsboard/server/queue/rabbitmq/TbRabbitMqConsumerTemplate.java
  common/queue/src/main/java/org/thingsboard/server/queue/rabbitmq/TbRabbitMqProducerTemplate.java
  common/queue/src/main/java/org/thingsboard/server/queue/rabbitmq/TbRabbitMqQueueArguments.java
  common/queue/src/main/java/org/thingsboard/server/queue/rabbitmq/TbRabbitMqSettings.java
  common/queue/src/main/java/org/thingsboard/server/queue/sqs/AwsSqsTbQueueMsgMetadata.java
  common/queue/src/main/java/org/thingsboard/server/queue/sqs/TbAwsSqsAdmin.java
  common/queue/src/main/java/org/thingsboard/server/queue/sqs/TbAwsSqsConsumerTemplate.java
  common/queue/src/main/java/org/thingsboard/server/queue/sqs/TbAwsSqsProducerTemplate.java
  common/queue/src/main/java/org/thingsboard/server/queue/sqs/TbAwsSqsQueueAttributes.java
  common/queue/src/main/java/org/thingsboard/server/queue/sqs/TbAwsSqsSettings.java
  common/queue/src/test/java/org/thingsboard/server/queue/rabbitmq/TbRabbitMqConsumerTemplateTest.java
  msa/js-executor/config/custom-environment-variables.yml
  msa/js-executor/config/default.yml
  msa/js-executor/queue/awsSqsTemplate.ts
  msa/js-executor/queue/kafkaTemplate.ts
  msa/js-executor/queue/pubSubTemplate.ts
  msa/js-executor/queue/rabbitmqTemplate.ts
  msa/js-executor/queue/serviceBusTemplate.ts
  msa/js-executor/server.ts
  msa/vc-executor/src/main/resources/tb-vc-executor.yml
  pom.xml
  transport/coap/src/main/resources/tb-coap-transport.yml
  transport/http/src/main/resources/tb-http-transport.yml
  transport/lwm2m/src/main/resources/tb-lwm2m-transport.yml
  transport/mqtt/src/main/resources/tb-mqtt-transport.yml
  transport/snmp/src/main/resources/tb-snmp-transport.yml
Labels: Major Core

#12174 Dashboard/widget resources export - process whole config
  application/src/main/java/org/thingsboard/server/service/install/update/ResourcesUpdater.java
  application/src/main/java/org/thingsboard/server/service/resource/DefaultTbResourceService.java
  application/src/test/java/org/thingsboard/server/controller/DashboardControllerTest.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/resource/ResourceService.java
  common/data/src/main/java/org/thingsboard/server/common/data/widget/WidgetType.java
  dao/src/main/java/org/thingsboard/server/dao/dashboard/DashboardServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/resource/BaseResourceService.java
  dao/src/main/java/org/thingsboard/server/dao/widget/WidgetTypeServiceImpl.java
Labels: Ignore for release

#12184 tbel_add_bitwise_boolean
  pom.xml
Labels: Tbel

#12211 Fixed qr code settings migration for disabled android/ios configuration #3075
  application/src/main/data/upgrade/basic/schema_update.sql
  dao/src/main/resources/sql/schema-entities.sql
Labels: Ignore for release

#12215 Fix edge events migration
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcService.java
Labels: Ignore for release

#12198 Fixed double open dialog when edit mobile bundle
  ui-ngx/src/app/modules/home/pages/mobile/bundes/mobile-bundle-table-config.resolve.ts
Labels: bug, UI, Ignore for release

#12200 Fixed for value less than min and more than max
  application/src/main/data/json/system/scada_symbols/dynamic-horizontal-scale-hp.svg
  application/src/main/data/json/system/scada_symbols/dynamic-vertical-scale-hp.svg
  application/src/main/data/json/system/scada_symbols/simple-horizontal-scale-hp.svg
  application/src/main/data/json/system/scada_symbols/simple-vertical-scale-hp.svg
Labels: bug, UI, Ignore for release

#12207 Fixed hide menu export dashboard after select option
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.ts
Labels: bug, UI, Ignore for release

#12209 Fixed mobile center translate, validation and editor
  ui-ngx/src/app/modules/home/pages/mobile/applications/mobile-app.component.ts
  ui-ngx/src/app/modules/home/pages/mobile/bundes/layout/mobile-layout.component.ts
  ui-ngx/src/app/modules/home/pages/mobile/bundes/layout/mobile-page-item-row.component.ts
  ui-ngx/src/app/modules/home/pages/mobile/common/editor-panel.component.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: bug, UI, Ignore for release

#12210 Fixed load background in image map
  ui-ngx/src/app/modules/home/components/widget/lib/maps/providers/image-map.ts
Labels: bug, UI, Ignore for release

#12212 Debug Settings fixes
  ui-ngx/src/app/core/services/item-buffer.service.ts
  ui-ngx/src/app/modules/home/components/debug-settings/debug-settings-button.component.html
  ui-ngx/src/app/modules/home/components/debug-settings/debug-settings-button.component.ts
  ui-ngx/src/app/modules/home/components/debug-settings/debug-settings-panel.component.html
  ui-ngx/src/app/modules/home/components/debug-settings/debug-settings-panel.component.ts
  ui-ngx/src/app/modules/home/pages/rulechain/rulechain-page.component.html
  ui-ngx/src/app/modules/home/pages/rulechain/rulechain-page.component.ts
  ui-ngx/src/app/shared/pipe/milliseconds-to-time-string.pipe.ts
  ui-ngx/src/assets/locale/locale.constant-ar_AE.json
  ui-ngx/src/assets/locale/locale.constant-ca_ES.json
  ui-ngx/src/assets/locale/locale.constant-cs_CZ.json
  ui-ngx/src/assets/locale/locale.constant-da_DK.json
  ui-ngx/src/assets/locale/locale.constant-el_GR.json
  ui-ngx/src/assets/locale/locale.constant-en_US.json
  ui-ngx/src/assets/locale/locale.constant-es_ES.json
  ui-ngx/src/assets/locale/locale.constant-ka_GE.json
  ui-ngx/src/assets/locale/locale.constant-ko_KR.json
  ui-ngx/src/assets/locale/locale.constant-lt_LT.json
  ui-ngx/src/assets/locale/locale.constant-lv_LV.json
  ui-ngx/src/assets/locale/locale.constant-nl_BE.json
  ui-ngx/src/assets/locale/locale.constant-pl_PL.json
  ui-ngx/src/assets/locale/locale.constant-pt_BR.json
  ui-ngx/src/assets/locale/locale.constant-ro_RO.json
  ui-ngx/src/assets/locale/locale.constant-sl_SI.json
  ui-ngx/src/assets/locale/locale.constant-tr_TR.json
  ui-ngx/src/assets/locale/locale.constant-uk_UA.json
  ui-ngx/src/assets/locale/locale.constant-zh_CN.json
  ui-ngx/src/assets/locale/locale.constant-zh_TW.json
Labels: bug, UI, Ignore for release

#12213 Share echarts-widget.models
  ui-ngx/src/app/modules/home/components/public-api.ts
Labels: enhancement, UI

#12214 Fixed relative urls in send email notification
  ui-ngx/src/app/modules/home/pages/notification/template/configuration/notification-template-configuration.component.ts
Labels: bug, UI

#12216 Fixed dynamic sources for filters list
  ui-ngx/src/app/modules/home/components/filter/filter-predicate-list.component.html
  ui-ngx/src/app/modules/home/components/filter/filter-predicate-value.component.html
  ui-ngx/tailwind.config.js
Labels: bug, UI, Ignore for release

#12217 Adjusted audit logs dialog codeblock height
  ui-ngx/src/app/modules/home/components/audit-log/audit-log-details-dialog.component.ts
Labels: bug, UI

#12229 Fixes for system notification type
  application/src/main/java/org/thingsboard/server/service/notification/DefaultNotificationCenter.java
Labels: Ignore for release

#12208 Fixed error toast when editing device details
  ui-ngx/src/app/shared/components/ota-package/ota-package-autocomplete.component.ts
Labels: bug, UI

#12219 Rollback hide axis to original behaviour
  ui-ngx/src/app/modules/home/components/widget/lib/chart/time-series-chart-widget.component.ts
Labels: UI, Ignore for release

#12221 Fixed scroll on progress bar for usage info widget
  ui-ngx/src/app/modules/home/components/widget/lib/home-page/usage-info-widget.component.scss
Labels: bug, UI, Ignore for release

#12222 Fixed tenant profile default configuration
  ui-ngx/src/app/modules/home/components/profile/tenant/default-tenant-profile-configuration.component.ts
  ui-ngx/src/app/shared/models/tenant.model.ts
Labels: bug, UI

#12226 Debug Settings minor refactoring
  ui-ngx/src/app/modules/home/components/entity/debug/entity-debug-settings-button.component.html
  ui-ngx/src/app/modules/home/components/entity/debug/entity-debug-settings-button.component.ts
  ui-ngx/src/app/modules/home/components/entity/debug/entity-debug-settings-panel.component.html
  ui-ngx/src/app/modules/home/components/entity/debug/entity-debug-settings-panel.component.ts
  ui-ngx/src/app/modules/home/pages/rulechain/rule-node-details.component.html
  ui-ngx/src/app/modules/home/pages/rulechain/rulechain-page.component.ts
  ui-ngx/src/app/modules/home/pages/rulechain/rulechain.module.ts
  ui-ngx/src/app/shared/models/entity.models.ts
  ui-ngx/src/app/shared/models/rule-node.models.ts
Labels: enhancement, UI, Ignore for release

#12227 Gateway MQTT md files update
  ui-ngx/src/assets/help/en_US/widget/lib/gateway/mqtt-bytes-expression_fn.md
  ui-ngx/src/assets/help/en_US/widget/lib/gateway/mqtt-expression_fn.md
  ui-ngx/src/assets/help/en_US/widget/lib/gateway/mqtt-json-expression_fn.md
  ui-ngx/src/assets/help/en_US/widget/lib/gateway/mqtt-json-key-expression_fn.md
Labels: enhancement, UI, Ignore for release

#12233 Fixed adaptive dashboard grid when moving widget
  ui-ngx/src/app/modules/home/components/dashboard/dashboard.component.ts
Labels: bug, UI

#12235 Fixed updated mobile layout and show mobile edit panel
  ui-ngx/src/app/modules/home/pages/mobile/bundes/layout/mobile-page-item-row.component.ts
  ui-ngx/src/app/modules/home/pages/mobile/common/editor-panel.component.scss
  ui-ngx/src/app/modules/home/pages/mobile/common/editor-panel.component.ts
Labels: bug, UI, Ignore for release

#12232 Fixed incorrect copy widget in dashboard
  ui-ngx/src/app/core/services/dashboard-utils.service.ts
  ui-ngx/src/app/modules/home/components/dashboard/dashboard.component.ts
  ui-ngx/src/app/modules/home/models/dashboard-component.models.ts
Labels: bug, UI

#12202 removed FROM_VERSION check from upgrade scripts
  docker/docker-upgrade-tb.sh
  msa/tb-node/docker/start-tb-node.sh
  msa/tb/docker/upgrade-tb.sh
  packaging/java/scripts/install/upgrade.sh
  packaging/java/scripts/install/upgrade_dev_db.sh
  packaging/java/scripts/windows/upgrade.bat
Labels: Ignore for release

#12258 Fixed mobile redirect if ios is disabled in properties
  application/src/main/java/org/thingsboard/server/controller/QrCodeSettingsController.java
Labels: bug, Ignore for release

#12248 Added domain validation
  dao/src/main/java/org/thingsboard/server/dao/domain/DomainServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/service/DataValidator.java
  dao/src/main/java/org/thingsboard/server/dao/service/validator/DomainDataValidator.java
  dao/src/test/java/org/thingsboard/server/dao/service/DomainServiceTest.java
Labels: enhancement, Ignore for release

#12255 Timewindow: fix applying default grouping interval
  ui-ngx/src/app/shared/components/time/timewindow-config-dialog.component.html
  ui-ngx/src/app/shared/components/time/timewindow-config-dialog.component.ts
  ui-ngx/src/app/shared/components/time/timewindow-panel.component.ts
Labels: bug, UI, Ignore for release

#12259 Fixed truncateWithTooltip directive behavior on different mouse events
  ui-ngx/src/app/shared/directives/truncate-with-tooltip.directive.ts
Labels: bug, UI

#12268 Fixed incorrect apply timewindows after cancel edit dashboard
  ui-ngx/src/app/modules/home/components/widget/widget-container.component.html
  ui-ngx/src/app/modules/home/components/widget/widget.component.ts
Labels: bug, UI

#12292 Fix user info
  application/src/main/java/org/thingsboard/server/controller/BaseController.java
  application/src/test/java/org/thingsboard/server/controller/AuthControllerTest.java
  ui-ngx/src/app/modules/home/pages/user/user.component.html
  ui-ngx/src/app/modules/home/pages/user/user.component.ts
  ui-ngx/src/app/shared/models/user.model.ts
Labels: bug, UI, Core, Ignore for release

#12293 Increase default edge-related thread pool sizes
  application/src/main/resources/thingsboard.yml
Labels: Ignore for release

#12283 added git-commit-id-maven-plugin for the application to expose the git information under actuator/info
  application/pom.xml
  pom.xml
Labels: Build Scripts, Ignore for release

#12304 VC: show error when push is rejected
  common/version-control/src/main/java/org/thingsboard/server/service/sync/vc/GitRepository.java
Labels: Core

#12247 Fixed background settings popover collapses
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/background-settings-panel.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/background-settings.component.ts
Labels: bug, UI

#12298 Hierarcy widget fires select node action too many times fix
  ui-ngx/src/app/shared/components/nav-tree.component.ts
Labels: bug, UI

#12308 Fix image getting broken after exporting entity
  application/src/main/java/org/thingsboard/server/controller/AssetProfileController.java
  application/src/main/java/org/thingsboard/server/controller/DeviceProfileController.java
  application/src/main/java/org/thingsboard/server/controller/WidgetsBundleController.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/exporting/impl/AssetProfileExportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/exporting/impl/DefaultEntityExportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/exporting/impl/DeviceProfileExportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/exporting/impl/WidgetsBundleExportService.java
  application/src/test/java/org/thingsboard/server/controller/ImageControllerTest.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/resource/ImageService.java
  dao/src/main/java/org/thingsboard/server/dao/resource/BaseImageService.java
Labels: bug, Core

#12297 Telemetry service refactoring
  application/src/main/java/org/thingsboard/server/controller/TelemetryController.java
  application/src/main/java/org/thingsboard/server/service/apiusage/DefaultTbApiUsageStateService.java
  application/src/main/java/org/thingsboard/server/service/device/ClaimDevicesServiceImpl.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcService.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/telemetry/BaseTelemetryProcessor.java
  application/src/main/java/org/thingsboard/server/service/entitiy/entityview/DefaultTbEntityViewService.java
  application/src/main/java/org/thingsboard/server/service/ota/DefaultOtaPackageStateService.java
  application/src/main/java/org/thingsboard/server/service/state/DefaultDeviceStateService.java
  application/src/main/java/org/thingsboard/server/service/stats/DefaultRuleEngineStatisticsService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/csv/AbstractBulkImportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/BaseEntityImportService.java
  application/src/main/java/org/thingsboard/server/service/system/DefaultSystemInfoService.java
  application/src/main/java/org/thingsboard/server/service/telemetry/DefaultTelemetrySubscriptionService.java
  application/src/main/java/org/thingsboard/server/service/telemetry/InternalTelemetryService.java
  application/src/test/java/org/thingsboard/server/controller/WebsocketApiTest.java
  application/src/test/java/org/thingsboard/server/service/state/DefaultDeviceStateServiceTest.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/attributes/AttributesService.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/timeseries/TimeseriesService.java
  dao/src/main/java/org/thingsboard/server/dao/attributes/BaseAttributesService.java
  dao/src/main/java/org/thingsboard/server/dao/attributes/CachedAttributesService.java
  dao/src/main/java/org/thingsboard/server/dao/timeseries/BaseTimeseriesService.java
  rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/AttributesDeleteRequest.java
  rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/AttributesSaveRequest.java
  rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/RuleEngineTelemetryService.java
  rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/TimeseriesDeleteRequest.java
  rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/TimeseriesSaveRequest.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/action/TbCopyAttributesToEntityViewNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/math/TbMathNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/telemetry/TbMsgAttributesNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/telemetry/TbMsgDeleteAttributesNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/telemetry/TbMsgTimeseriesNode.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/action/TbCopyAttributesToEntityViewNodeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/math/TbMathNodeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/telemetry/TbMsgAttributesNodeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/telemetry/TbMsgDeleteAttributesNodeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/telemetry/TbMsgTimeseriesNodeTest.java
Labels: Core

#12305 Updated constraint name to valid one
  application/src/main/data/upgrade/basic/schema_update.sql
  dao/src/main/java/org/thingsboard/server/dao/domain/DomainServiceImpl.java
Labels: Ignore for release

#12321 Fix duplicate alarm notification when clear rule is met
  application/src/main/java/org/thingsboard/server/service/notification/rule/DefaultNotificationRuleProcessor.java
  application/src/main/java/org/thingsboard/server/service/notification/rule/trigger/AlarmTriggerProcessor.java
  application/src/test/java/org/thingsboard/server/service/notification/NotificationRuleApiTest.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/notification/NotificationRequestService.java
  dao/src/main/java/org/thingsboard/server/dao/notification/DefaultNotificationRequestService.java
  dao/src/main/java/org/thingsboard/server/dao/notification/NotificationRequestDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/notification/JpaNotificationRequestDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/notification/NotificationRequestRepository.java
Labels: bug, Core

#12326 EdgeGrpcSession - fixed abort of sync process in case high priority message notification
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java
Labels: Ignore for release

#12275 Fixed color for HP SCADA filter
  application/src/main/data/json/system/scada_symbols/filter-hp.svg
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: bug, UI

#12291 Fixed the missing add buttons in the notification center on mobile
  ui-ngx/src/app/modules/home/components/entity/entities-table.component.html
  ui-ngx/src/app/modules/home/models/entity/entities-table-config.models.ts
  ui-ngx/src/app/modules/home/pages/mobile/applications/mobile-app-table-config.resolver.ts
  ui-ngx/src/app/modules/home/pages/mobile/applications/mobile-app-table-header.component.html
  ui-ngx/src/app/modules/home/pages/mobile/applications/mobile-app-table-header.component.scss
  ui-ngx/src/app/modules/home/pages/mobile/applications/mobile-app-table-header.component.ts
  ui-ngx/src/app/modules/home/pages/mobile/bundes/mobile-bundle-table-config.resolve.ts
  ui-ngx/src/app/modules/home/pages/mobile/bundes/mobile-bundle-table-header.component.html
  ui-ngx/src/app/modules/home/pages/mobile/bundes/mobile-bundle-table-header.component.scss
  ui-ngx/src/app/modules/home/pages/mobile/bundes/mobile-bundle-table-header.component.ts
  ui-ngx/src/app/modules/home/pages/notification/notification.module.ts
  ui-ngx/src/app/modules/home/pages/notification/recipient/recipient-table-config.resolver.ts
  ui-ngx/src/app/modules/home/pages/notification/recipient/recipient-table-header.component.html
  ui-ngx/src/app/modules/home/pages/notification/recipient/recipient-table-header.component.scss
  ui-ngx/src/app/modules/home/pages/notification/recipient/recipient-table-header.component.ts
  ui-ngx/src/app/modules/home/pages/notification/rule/rule-table-config.resolver.ts
  ui-ngx/src/app/modules/home/pages/notification/rule/rule-table-header.component.html
  ui-ngx/src/app/modules/home/pages/notification/rule/rule-table-header.component.scss
  ui-ngx/src/app/modules/home/pages/notification/rule/rule-table-header.component.ts
  ui-ngx/src/app/modules/home/pages/notification/template/template-table-config.resolver.ts
  ui-ngx/src/app/modules/home/pages/notification/template/template-table-header.component.html
  ui-ngx/src/app/modules/home/pages/notification/template/template-table-header.component.scss
  ui-ngx/src/app/modules/home/pages/notification/template/template-table-header.component.ts
  ui-ngx/src/app/shared/models/entity-type.models.ts
Labels: bug, UI

#12313 Improved translation in platform
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/custom-action-pretty-resources-tabs.component.html
  ui-ngx/src/app/modules/home/pages/widget/widget-editor.component.html
  ui-ngx/src/app/shared/components/entity/entity-autocomplete.component.ts
  ui-ngx/src/assets/locale/locale.constant-ar_AE.json
  ui-ngx/src/assets/locale/locale.constant-ca_ES.json
  ui-ngx/src/assets/locale/locale.constant-cs_CZ.json
  ui-ngx/src/assets/locale/locale.constant-da_DK.json
  ui-ngx/src/assets/locale/locale.constant-en_US.json
  ui-ngx/src/assets/locale/locale.constant-es_ES.json
  ui-ngx/src/assets/locale/locale.constant-ko_KR.json
  ui-ngx/src/assets/locale/locale.constant-lt_LT.json
  ui-ngx/src/assets/locale/locale.constant-nl_BE.json
  ui-ngx/src/assets/locale/locale.constant-pl_PL.json
  ui-ngx/src/assets/locale/locale.constant-pt_BR.json
  ui-ngx/src/assets/locale/locale.constant-sl_SI.json
  ui-ngx/src/assets/locale/locale.constant-zh_CN.json
  ui-ngx/src/assets/locale/locale.constant-zh_TW.json
Labels: enhancement, UI, Ignore for release

#12314 JS Resource Module example minor symbol correction
  ui-ngx/src/assets/help/en_US/resource/js-resource-module_fn.md
Labels: bug, UI, Ignore for release

#12319 Enhance help links and improve help button display
  ui-ngx/src/app/modules/home/pages/admin/oauth2/clients/client-table-header.component.html
  ui-ngx/src/app/modules/home/pages/admin/oauth2/clients/client-table-header.component.ts
  ui-ngx/src/app/modules/home/pages/admin/oauth2/clients/clients-table-config.resolver.ts
  ui-ngx/src/app/modules/home/pages/admin/oauth2/domains/domain-table-config.resolver.ts
  ui-ngx/src/app/modules/home/pages/admin/oauth2/domains/domain-table-header.component.html
  ui-ngx/src/app/modules/home/pages/admin/oauth2/domains/domain-table-header.component.ts
  ui-ngx/src/app/shared/models/constants.ts
  ui-ngx/src/app/shared/models/entity-type.models.ts
Labels: enhancement, UI

#12322 Fixed send empty OAuth2 mobile clients data
  ui-ngx/src/app/core/http/mobile-app.service.ts
Labels: bug, UI, Ignore for release

#12324 Timewindow: fixed applying grouping interval on closing configuration dialog
  ui-ngx/src/app/shared/components/time/timewindow-config-dialog.component.html
  ui-ngx/src/app/shared/components/time/timewindow-panel.component.ts
Labels: bug, UI

#12318 Migrating ESLint config to flat format
  ui-ngx/.eslintrc.json
  ui-ngx/eslint.config.mjs
  ui-ngx/package.json
  ui-ngx/yarn.lock
Labels: enhancement, UI, Ignore for release

#12329 Fixed deletion of JS module in function and added validation for alias name in JS module
  ui-ngx/src/app/shared/components/js-func-module-row.component.html
  ui-ngx/src/app/shared/components/js-func-module-row.component.ts
  ui-ngx/src/app/shared/components/js-func-modules.component.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: bug, enhancement, UI, Ignore for release

#12315 Added offline backups for Gateways
  application/src/main/data/json/system/widget_types/gateway_configuration.json
  application/src/main/data/json/system/widget_types/gateway_configuration__single_device_.json
  application/src/main/data/json/system/widget_types/gateway_connectors.json
  application/src/main/data/json/system/widget_types/gateway_custom_statistics.json
  application/src/main/data/json/system/widget_types/gateway_general_chart_statistics.json
  application/src/main/data/json/system/widget_types/gateway_general_configuration.json
  application/src/main/data/json/system/widget_types/gateway_logs.json
  application/src/main/data/json/system/widget_types/gateway_status.json
  application/src/main/data/json/system/widget_types/service_rpc.json
  application/src/main/data/resources/dashboards/gateways_dashboard.json
  application/src/main/data/resources/js_modules/gateway-management-extension.js
Labels: enhancement, UI

#12332 Usage of special HTML chars in mardown fix
  ui-ngx/src/app/shared/models/js-function.models.ts
Labels: enhancement, UI, Ignore for release

#12336 Fixed incorrect merging of default SCADA symbol settings with user-defined settings
  ui-ngx/src/app/modules/home/components/widget/lib/scada/scada-symbol.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/scada/scada-symbol-object-settings.component.ts
Labels: bug, UI, Ignore for release

#12339 Improved browser compatibility coverage for better platform functionality across various browsers
  ui-ngx/.browserslistrc
Labels: enhancement, UI, Build Scripts

#12340 Improvement configuration eslint.config.mjs
  ui-ngx/eslint.config.mjs
Labels: enhancement, UI, Ignore for release

#12342 Fixed case when seqId started new cycle. Improved edge trace/debug logging
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcService.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/KafkaEdgeGrpcSession.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/fetch/GeneralEdgeEventFetcher.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/sync/DefaultEdgeRequestsService.java
  dao/src/main/java/org/thingsboard/server/dao/sql/edge/JpaBaseEdgeEventDao.java
Labels: Ignore for release

#12355 fix_ bug_lwm2m_flaky_test
  application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationObserveTest.java
Labels: bug, Ignore for release

#12354 Fixed incorrect auto-conversion of inserted links in TinyMCE editor
  ui-ngx/src/app/modules/home/pages/mobile/common/editor-panel.component.ts
  ui-ngx/src/app/modules/home/pages/notification/template/configuration/notification-template-configuration.component.ts
Labels: bug, UI, Ignore for release

#12356 Updated rulenode-core-config.js
  rule-engine/rule-engine-components/src/main/resources/public/static/rulenode/rulenode-core-config.js
Labels: UI, Ignore for release

#12359 Ignore unconfigured delivery method for system notification type
  application/src/main/java/org/thingsboard/server/service/notification/DefaultNotificationCenter.java
Labels: Ignore for release

#12360 Ignore version from tb_schema_settings when from_version property is specified
  application/src/main/java/org/thingsboard/server/install/ThingsboardInstallService.java
  application/src/main/java/org/thingsboard/server/service/install/DefaultDatabaseSchemaSettingsService.java
Labels: Ignore for release

#12361 Temporary disabled relatedEdges due to issue with scan method
  application/src/main/resources/thingsboard.yml
Labels: Ignore for release

#12203 tbel_tests_doc_bitwise_operations
  application/src/test/java/org/thingsboard/server/service/script/TbelInvokeDocsIoTest.java
Labels: Tbel
