Repository thingsboard/thingsboard, pull requests merged in 2024-09, with the labels that each got.

#11498 DefaultTbLocalSubscriptionService WS single lock refactored by tenantId; TbEntityLocalSubsInfo performance optimizations for remove subscription
  application/src/main/java/org/thingsboard/server/service/subscription/DefaultSubscriptionManagerService.java
  application/src/main/java/org/thingsboard/server/service/subscription/DefaultTbLocalSubscriptionService.java
  application/src/main/java/org/thingsboard/server/service/subscription/TbAbstractDataSubCtx.java
  application/src/main/java/org/thingsboard/server/service/subscription/TbAbstractSubCtx.java
  application/src/main/java/org/thingsboard/server/service/subscription/TbAlarmDataSubCtx.java
  application/src/main/java/org/thingsboard/server/service/subscription/TbEntityDataSubCtx.java
  application/src/main/java/org/thingsboard/server/service/subscription/TbEntityLocalSubsInfo.java
  application/src/main/java/org/thingsboard/server/service/subscription/TbLocalSubscriptionService.java
  application/src/main/java/org/thingsboard/server/service/subscription/TbSubscription.java
  application/src/main/java/org/thingsboard/server/service/subscription/TbSubscriptionUtils.java
  application/src/main/java/org/thingsboard/server/service/subscription/TbSubscriptionsInfo.java
  application/src/main/java/org/thingsboard/server/service/ws/DefaultWebSocketService.java
  application/src/main/java/org/thingsboard/server/service/ws/WebSocketService.java
  application/src/main/java/org/thingsboard/server/service/ws/WebSocketSessionRef.java
  application/src/main/java/org/thingsboard/server/service/ws/notification/DefaultNotificationCommandsHandler.java
  application/src/main/java/org/thingsboard/server/service/ws/notification/sub/NotificationsCountSubscription.java
  application/src/main/java/org/thingsboard/server/service/ws/notification/sub/NotificationsSubscription.java
  common/proto/src/main/proto/queue.proto
Labels: enhancement

#11388 DefaultTbLocalSubscriptionService WS single lock refactored by tenantId; TbEntityLocalSubsInfo performance optimizations for remove subscription
  application/src/main/java/org/thingsboard/server/service/subscription/DefaultTbLocalSubscriptionService.java
  application/src/main/java/org/thingsboard/server/service/subscription/TbAlarmsSubscription.java
  application/src/main/java/org/thingsboard/server/service/subscription/TbAttributeSubscription.java
  application/src/main/java/org/thingsboard/server/service/subscription/TbEntityLocalSubsInfo.java
  application/src/main/java/org/thingsboard/server/service/subscription/TbSubscription.java
  application/src/main/java/org/thingsboard/server/service/subscription/TbSubscriptionUtils.java
  application/src/main/java/org/thingsboard/server/service/subscription/TbSubscriptionsInfo.java
  application/src/main/java/org/thingsboard/server/service/subscription/TbTimeSeriesSubscription.java
  application/src/main/java/org/thingsboard/server/service/ws/notification/sub/AbstractNotificationSubscription.java
  application/src/main/java/org/thingsboard/server/service/ws/notification/sub/NotificationsCountSubscription.java
  application/src/main/java/org/thingsboard/server/service/ws/notification/sub/NotificationsSubscription.java
Labels: enhancement, WIP

#11159 Generator node: improvements
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/debug/TbMsgGeneratorNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/debug/TbMsgGeneratorNodeConfiguration.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/debug/TbMsgGeneratorNodeTest.java
Labels: enhancement, Rule Engine

#11496 Versioning for rule chain metadata
  application/src/test/java/org/thingsboard/server/controller/DeviceControllerTest.java
  application/src/test/java/org/thingsboard/server/controller/RuleChainControllerTest.java
  common/data/src/main/java/org/thingsboard/server/common/data/exception/EntityVersionMismatchException.java
  common/data/src/main/java/org/thingsboard/server/common/data/rule/RuleChainMetaData.java
  common/data/src/main/java/org/thingsboard/server/common/data/sync/ie/RuleChainExportData.java
  dao/src/main/java/org/thingsboard/server/dao/rule/BaseRuleChainService.java
  dao/src/main/java/org/thingsboard/server/dao/sql/JpaAbstractDao.java
  dao/src/test/java/org/thingsboard/server/dao/sql/device/JpaDeviceDaoTest.java
  ui-ngx/src/app/modules/home/pages/rulechain/rulechain-page.component.ts
  ui-ngx/src/app/shared/components/dialog/entity-conflict-dialog/entity-conflict-dialog.component.html
  ui-ngx/src/app/shared/components/dialog/entity-conflict-dialog/entity-conflict-dialog.component.ts
  ui-ngx/src/app/shared/import-export/import-export.service.ts
  ui-ngx/src/app/shared/models/rule-chain.models.ts
Labels: enhancement, UI, Core, Ignore for release

#11564 merge with hotfix/3.7
  application/src/main/java/org/thingsboard/server/service/subscription/DefaultSubscriptionManagerService.java
  application/src/main/java/org/thingsboard/server/service/subscription/DefaultTbLocalSubscriptionService.java
  application/src/main/java/org/thingsboard/server/service/subscription/TbAbstractDataSubCtx.java
  application/src/main/java/org/thingsboard/server/service/subscription/TbAbstractSubCtx.java
  application/src/main/java/org/thingsboard/server/service/subscription/TbAlarmDataSubCtx.java
  application/src/main/java/org/thingsboard/server/service/subscription/TbEntityDataSubCtx.java
  application/src/main/java/org/thingsboard/server/service/subscription/TbEntityLocalSubsInfo.java
  application/src/main/java/org/thingsboard/server/service/subscription/TbLocalSubscriptionService.java
  application/src/main/java/org/thingsboard/server/service/subscription/TbSubscriptionUtils.java
  application/src/main/java/org/thingsboard/server/service/ws/DefaultWebSocketService.java
  application/src/main/java/org/thingsboard/server/service/ws/WebSocketService.java
  application/src/main/java/org/thingsboard/server/service/ws/WebSocketSessionRef.java
  application/src/main/java/org/thingsboard/server/service/ws/notification/DefaultNotificationCommandsHandler.java
  common/proto/src/main/proto/queue.proto
Labels: Ignore for release

#11220 Improvement for generator node
  ui-ngx/src/app/shared/components/entity/entity-select.component.html
  ui-ngx/src/app/shared/components/entity/entity-select.component.ts
  ui-ngx/src/app/shared/components/entity/entity-type-select.component.ts
  ui-ngx/src/app/shared/components/js-func.component.html
  ui-ngx/src/app/shared/components/script-lang.component.html
  ui-ngx/src/app/shared/components/script-lang.component.scss
  ui-ngx/src/app/shared/components/script-lang.component.ts
Labels: enhancement, UI, Ignore for release

#11457 Fixed SYNC issue with redundant name fields in server and broker config
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/broker-config-control/broker-config-control.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/opc-server-config/opc-server-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-connectors.component.ts
  ui-ngx/src/assets/metadata/connector-default-configs/mqtt.json
  ui-ngx/src/assets/metadata/connector-default-configs/opcua.json
Labels: bug, UI, Ignore for release

#11473 Added trace log level
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-widget.models.ts
Labels: enhancement, UI, Ignore for release

#11504 Improved move all widget action: fixed overlap widget and add support dashboard layout
  ui-ngx/src/app/core/services/dashboard-utils.service.ts
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.ts
Labels: bug, UI, Ignore for release

#11511 Fixed infinite load when select divided layout
  ui-ngx/src/app/core/services/dashboard-utils.service.ts
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.ts
  ui-ngx/src/app/modules/home/components/dashboard-page/layout/dashboard-layout.component.ts
  ui-ngx/src/app/modules/home/components/dashboard-page/layout/layout.models.ts
  ui-ngx/src/app/modules/home/components/dashboard-page/layout/select-dashboard-breakpoint.component.ts
Labels: bug, UI, Ignore for release

#11512 Improved style for select dashboard breakpoint
  ui-ngx/src/app/modules/home/components/dashboard-page/layout/add-new-breakpoint-dialog.component.html
  ui-ngx/src/app/modules/home/components/dashboard-page/layout/select-dashboard-breakpoint.component.html
Labels: enhancement, UI, Ignore for release

#11514 Fixed incorrect min-width for dashboard layout in preview mode at specific breakpoints
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.ts
Labels: bug, UI, Ignore for release

#11527 Recent dashboards widget - apply custom translation for dashboard titles
  ui-ngx/src/app/modules/home/components/widget/lib/home-page/recent-dashboards-widget.component.html
  ui-ngx/src/app/shared/components/dashboard-autocomplete.component.html
Labels: bug, UI

#11528 Oauth2 UI improvements
  ui-ngx/src/app/core/http/entity.service.ts
  ui-ngx/src/app/modules/home/pages/admin/oauth2/clients/client.component.html
  ui-ngx/src/app/modules/home/pages/admin/oauth2/clients/client.component.ts
  ui-ngx/src/app/modules/home/pages/admin/oauth2/clients/clients-table-config.resolver.ts
  ui-ngx/src/app/modules/home/pages/admin/oauth2/domains/domain-table-config.resolver.ts
  ui-ngx/src/app/modules/home/pages/admin/oauth2/mobile-apps/mobile-app-table-config.resolver.ts
  ui-ngx/src/app/modules/home/pages/admin/oauth2/mobile-apps/mobile-app.component.html
  ui-ngx/src/app/modules/home/pages/admin/oauth2/mobile-apps/mobile-app.component.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: bug, enhancement, UI, Ignore for release

#11541 Fixed multiple input widget not updated dynamically selector after change and save value
  ui-ngx/src/app/modules/home/components/widget/lib/multiple-input-widget.component.html
Labels: bug, UI

#11543 Add country autocomplete
  ui-ngx/src/app/modules/home/components/entity/contact-based.component.ts
  ui-ngx/src/app/modules/home/models/contact.models.ts
  ui-ngx/src/app/modules/home/pages/customer/customer.component.ts
  ui-ngx/src/app/modules/home/pages/tenant/tenant.component.ts
  ui-ngx/src/app/shared/components/contact.component.html
  ui-ngx/src/app/shared/components/contact.component.ts
  ui-ngx/src/app/shared/components/country-autocomplete.component.html
  ui-ngx/src/app/shared/components/country-autocomplete.component.ts
  ui-ngx/src/app/shared/models/country.models.ts
  ui-ngx/src/app/shared/shared.module.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI, Ignore for release

#10251 UI: sync country list & add flags to tb-contact country selector & search country
  ui-ngx/src/app/modules/home/models/contact.models.ts
  ui-ngx/src/app/shared/components/contact.component.html
  ui-ngx/src/app/shared/components/contact.component.ts
  ui-ngx/src/app/shared/models/country.models.ts
Labels: enhancement, UI

#11548 Image service: default image sub-type value added to requests
  ui-ngx/src/app/core/http/image.service.ts
  ui-ngx/src/app/shared/components/image/image-gallery.component.ts
  ui-ngx/src/app/shared/components/image/images-datasource.ts
Labels: enhancement, UI, Ignore for release

#11509 Fixed error tooltip for 'Minimum layout width' in layout configuration
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-settings-dialog.component.html
Labels: bug, UI, Ignore for release

#11542 Fix entity table widgets to correctly process entity type for "show cell button action" function
  ui-ngx/src/app/modules/home/components/widget/lib/entity/entities-table-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/table-widget.models.ts
Labels: enhancement, UI

#11572 Fix last activity not being reported when activity reporting period ends
  common/queue/src/main/java/org/thingsboard/server/queue/scheduler/DefaultSchedulerComponent.java
  common/queue/src/test/java/org/thingsboard/server/queue/scheduler/DefaultSchedulerComponentTest.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/activity/AbstractActivityManager.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/activity/strategy/FirstAndLastEventActivityStrategy.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/activity/strategy/FirstEventActivityStrategy.java
Labels: bug, Core

#11520 Aws lambda node: added validation on init
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/aws/lambda/TbAwsLambdaNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/aws/lambda/TbAwsLambdaNodeConfiguration.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/aws/lambda/TbAwsLambdaNodeTest.java
Labels: Ignore for release

#11536 Fixed incorrect display of device state
  application/src/main/java/org/thingsboard/server/service/state/DefaultDeviceStateService.java
  application/src/test/java/org/thingsboard/server/service/state/DefaultDeviceStateServiceTest.java
Labels: bug, Core

#11569 Rollback to the old oauth2 clients api
  application/src/main/java/org/thingsboard/server/controller/OAuth2Controller.java
  ui-ngx/src/app/core/auth/auth.service.ts
Labels: Ignore for release

#11565 Mqtt node: added validation for client id
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/mqtt/TbMqttNode.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/mqtt/TbMqttNodeTest.java
Labels: Ignore for release

#11500 REST API call node: max response size parameter added
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/rest/TbHttpClient.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/rest/TbRestApiCallNodeConfiguration.java
Labels: enhancement, Rule Engine

#11551 tbel: refactoring, tbUtils to docs
  common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/TbUtils.java
  common/script/script-api/src/test/java/org/thingsboard/script/api/tbel/TbUtilsTest.java
Labels: Ignore for release

#11526 Tbel fix bug map key value
  pom.xml
Labels: bug, Tbel

#11524 Bug fix for stand filter SCADA symbol
  application/src/main/data/json/system/scada_symbols/stand-filter.svg
Labels: UI, Ignore for release

#11550 SCADA symbol Leak sensor and water stop
  application/src/main/data/json/system/scada_symbols/leak-sensor.svg
  application/src/main/data/json/system/scada_symbols/waterstop.svg
  application/src/main/data/json/system/widget_bundles/scada_water_system_symbols.json
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI, Ignore for release

#11532 Water meter SCADA symbols
  application/src/main/data/json/system/scada_symbols/left-analog-water-level-meter.svg
  application/src/main/data/json/system/scada_symbols/right-analog-water-level-meter.svg
  application/src/main/data/json/system/widget_bundles/scada_water_system_symbols.json
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI, Ignore for release

#11580 Fixed credentials check if simple client factory is used and fixed checks for system proxy properties in TbHttpClient
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/rest/TbHttpClient.java
Labels: bug

#11579 Added sorting by title for oauth2 clients
  application/src/test/java/org/thingsboard/server/controller/DomainControllerTest.java
  application/src/test/java/org/thingsboard/server/controller/MobileAppControllerTest.java
  dao/src/main/java/org/thingsboard/server/dao/domain/DomainServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/mobile/MobileAppServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/oauth2/OAuth2ClientServiceImpl.java
  ui-ngx/src/app/modules/home/pages/admin/oauth2/clients/clients-table-config.resolver.ts
Labels: Ignore for release

#11450 added support of getServiceConfiguration RPC
  application/src/test/java/org/thingsboard/server/transport/mqtt/mqttv3/rpc/MqttClientSideRpcIntegrationTest.java
  common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttTransportContext.java
  common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttTransportHandler.java
  common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/limits/GatewaySessionLimits.java
  common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/limits/SessionLimits.java
  common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/DeviceSessionCtx.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/session/DeviceAwareSessionContext.java
Labels: feature

#10901 Fixed creation of profiles with name "default" and existing default renamed profile
  dao/src/main/java/org/thingsboard/server/dao/asset/AssetProfileServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/device/DeviceProfileServiceImpl.java
  dao/src/test/java/org/thingsboard/server/dao/service/AssetProfileServiceTest.java
  dao/src/test/java/org/thingsboard/server/dao/service/DeviceProfileServiceTest.java
Labels: bug

#11560 Added Event and Audit Logs services to services map.
  ui-ngx/src/app/modules/home/models/services.map.ts
Labels: UI

#9327 #9328 Making it possible to use CompletableFuture
  common/queue/src/test/java/org/thingsboard/server/queue/rabbitmq/TbRabbitMqConsumerTemplateTest.java
  netty-mqtt/src/main/java/org/thingsboard/mqtt/MqttHandler.java
Labels: Transport

#11604 Refactor SCADA editor highlighting to support Safari on iOS versions 16.3 and below
  ui-ngx/src/app/modules/home/pages/scada-symbol/metadata-components/scada-symbol-metadata-tag-function-panel.component.html
  ui-ngx/src/app/modules/home/pages/scada-symbol/metadata-components/scada-symbol-metadata-tag-function-panel.component.ts
  ui-ngx/src/app/modules/home/pages/scada-symbol/metadata-components/scada-symbol-metadata.component.html
  ui-ngx/src/app/modules/home/pages/scada-symbol/metadata-components/scada-symbol-metadata.component.ts
  ui-ngx/src/app/modules/home/pages/scada-symbol/scada-symbol-editor.models.ts
  ui-ngx/src/app/shared/components/js-func.component.ts
  ui-ngx/src/app/shared/models/ace/ace.models.ts
Labels: enhancement, UI, Ignore for release

#11578 TTL for password reset and user activation links UI
  ui-ngx/src/app/core/http/user.service.ts
  ui-ngx/src/app/modules/home/pages/user/activation-link-dialog.component.html
  ui-ngx/src/app/modules/home/pages/user/activation-link-dialog.component.ts
  ui-ngx/src/app/modules/home/pages/user/add-user-dialog.component.ts
  ui-ngx/src/app/modules/home/pages/user/users-table-config.resolver.ts
  ui-ngx/src/app/modules/login/login-routing.module.ts
  ui-ngx/src/app/modules/login/login.module.ts
  ui-ngx/src/app/modules/login/pages/login/link-expired.component.html
  ui-ngx/src/app/modules/login/pages/login/link-expired.component.scss
  ui-ngx/src/app/modules/login/pages/login/link-expired.component.ts
  ui-ngx/src/app/shared/models/user.model.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI, feature

#11587 Fix saving dashboard timewindow configuration
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.ts
Labels: bug, UI, Ignore for release

#11590 Improved show error in layout settings
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-settings-dialog.component.html
Labels: enhancement, UI, Ignore for release

#11592 Fixed default credentials for created Gateway
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/configuration/basic/gateway-basic-configuration.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/configuration/gateway-configuration.component.ts
Labels: enhancement, UI, Ignore for release

#11599 Update rulenode config
  rule-engine/rule-engine-components/src/main/resources/public/static/rulenode/rulenode-core-config.js
Labels: UI, Rule Engine, Ignore for release

#11484 Filters are not applying to state if it is opened in dialog window or popover
  ui-ngx/src/app/core/api/alias-controller.ts
  ui-ngx/src/app/core/api/widget-api.models.ts
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.ts
Labels: bug, UI

#11600 Fixed click action for water level symbols
  application/src/main/data/json/system/scada_symbols/left-analog-water-level-meter.svg
  application/src/main/data/json/system/scada_symbols/right-analog-water-level-meter.svg
Labels: bug, UI, Ignore for release

#11608 added description to the rabbitmq max_poll_messages property
  application/src/main/resources/thingsboard.yml
Labels: Ignore for release

#11603 Update scada bundle and add images
  application/src/main/data/json/system/widget_bundles/scada_fluid_system.json
  application/src/main/data/json/system/widget_bundles/scada_symbols.json
  application/src/main/data/json/system/widget_bundles/scada_water_system_symbols.json
  application/src/main/data/json/system/widget_types/scada_symbol.json
Labels: enhancement, UI, Ignore for release

#11271 TTL for password reset and user activation links
  application/src/main/data/upgrade/3.7.0/schema_update.sql
  application/src/main/java/org/thingsboard/server/controller/AdminController.java
  application/src/main/java/org/thingsboard/server/controller/AuthController.java
  application/src/main/java/org/thingsboard/server/controller/BaseController.java
  application/src/main/java/org/thingsboard/server/controller/ImageController.java
  application/src/main/java/org/thingsboard/server/controller/MobileApplicationController.java
  application/src/main/java/org/thingsboard/server/controller/UserController.java
  application/src/main/java/org/thingsboard/server/service/entitiy/user/DefaultUserService.java
  application/src/main/java/org/thingsboard/server/service/entitiy/user/TbUserService.java
  application/src/main/java/org/thingsboard/server/service/install/update/DefaultCacheCleanupService.java
  application/src/main/java/org/thingsboard/server/service/mail/DefaultMailService.java
  application/src/main/java/org/thingsboard/server/service/mobile/secret/MobileAppSecretServiceImpl.java
  application/src/main/java/org/thingsboard/server/service/security/auth/rest/RestAuthenticationProvider.java
  application/src/main/java/org/thingsboard/server/service/security/system/DefaultSystemSecurityService.java
  application/src/main/java/org/thingsboard/server/service/security/system/SystemSecurityService.java
  application/src/main/resources/templates/activation.ftl
  application/src/main/resources/templates/reset.password.ftl
  application/src/test/java/org/thingsboard/server/controller/AbstractWebTest.java
  application/src/test/java/org/thingsboard/server/controller/AuthControllerTest.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/user/UserService.java
  common/data/src/main/java/org/thingsboard/server/common/data/UserActivationLink.java
  common/data/src/main/java/org/thingsboard/server/common/data/security/UserCredentials.java
  common/data/src/main/java/org/thingsboard/server/common/data/security/model/SecuritySettings.java
  dao/src/main/java/org/thingsboard/server/dao/model/ModelConstants.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/UserCredentialsEntity.java
  dao/src/main/java/org/thingsboard/server/dao/settings/DefaultSecuritySettingsService.java
  dao/src/main/java/org/thingsboard/server/dao/settings/SecuritySettingsService.java
  dao/src/main/java/org/thingsboard/server/dao/user/UserServiceImpl.java
  dao/src/main/resources/sql/schema-entities.sql
  dao/src/test/java/org/thingsboard/server/dao/sql/user/JpaUserCredentialsDaoTest.java
  rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/MailService.java
  ui-ngx/src/app/core/http/user.service.ts
  ui-ngx/src/app/modules/home/pages/admin/security-settings.component.html
  ui-ngx/src/app/modules/home/pages/admin/security-settings.component.ts
  ui-ngx/src/app/modules/home/pages/user/activation-link-dialog.component.html
  ui-ngx/src/app/modules/home/pages/user/activation-link-dialog.component.ts
  ui-ngx/src/app/modules/home/pages/user/add-user-dialog.component.ts
  ui-ngx/src/app/modules/home/pages/user/users-table-config.resolver.ts
  ui-ngx/src/app/modules/login/login-routing.module.ts
  ui-ngx/src/app/modules/login/login.module.ts
  ui-ngx/src/app/modules/login/pages/login/link-expired.component.html
  ui-ngx/src/app/modules/login/pages/login/link-expired.component.scss
  ui-ngx/src/app/modules/login/pages/login/link-expired.component.ts
  ui-ngx/src/app/shared/models/settings.models.ts
  ui-ngx/src/app/shared/models/user.model.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: Core

#11606 DashboardEdgeTest - fixed err msg related to incorrect image format
  application/src/test/java/org/thingsboard/server/edge/DashboardEdgeTest.java
Labels: Ignore for release

#11588 Fixed issue with Edge Root Rule Chain cache for related edges
  application/src/main/java/org/thingsboard/server/service/edge/EdgeEventSourcingListener.java
  application/src/main/java/org/thingsboard/server/service/edge/RelatedEdgesSourcingListener.java
  application/src/test/java/org/thingsboard/server/edge/AbstractEdgeTest.java
  application/src/test/java/org/thingsboard/server/edge/RuleChainEdgeTest.java
  dao/src/main/java/org/thingsboard/server/dao/edge/BaseRelatedEdgesService.java
  dao/src/main/java/org/thingsboard/server/dao/rule/BaseRuleChainService.java
Labels: Ignore for release

#11613 Revert close connection header hotfix
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/rest/TbHttpClient.java
Labels: Ignore for release

#10100 fix: fixed the error that the file could not be found after packing
  application/src/main/java/org/thingsboard/server/service/mail/DefaultTbMailConfigTemplateService.java
  common/util/src/main/java/org/thingsboard/common/util/JacksonUtil.java
Labels: bug, unconfirmed

#11320 [Widgets] - Adding card-padding setting
  ui-ngx/src/app/modules/home/components/widget/config/basic/cards/value-card-basic-config.component.html
  ui-ngx/src/app/modules/home/components/widget/config/basic/cards/value-card-basic-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/config/basic/indicator/status-widget-basic-config.component.html
  ui-ngx/src/app/modules/home/components/widget/config/basic/indicator/status-widget-basic-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/config/basic/rpc/single-switch-basic-config.component.html
  ui-ngx/src/app/modules/home/components/widget/config/basic/rpc/single-switch-basic-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/config/basic/weather/wind-speed-direction-basic-config.component.html
  ui-ngx/src/app/modules/home/components/widget/config/basic/weather/wind-speed-direction-basic-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/cards/value-card-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/cards/value-card-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/cards/value-card-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/indicator/status-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/indicator/status-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/indicator/status-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/rpc/single-switch-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/rpc/single-switch-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/rpc/single-switch-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/value-card-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/value-card-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/control/single-switch-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/control/single-switch-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/indicator/status-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/indicator/status-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/weather/wind-speed-direction-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/weather/wind-speed-direction-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/weather/wind-speed-direction-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/weather/wind-speed-direction-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/weather/wind-speed-direction-widget.models.ts
Labels: enhancement, UI

#11626 fixed concurrent modification during printStats
  application/src/main/java/org/thingsboard/server/service/subscription/DefaultTbEntityDataSubscriptionService.java
  application/src/main/java/org/thingsboard/server/service/subscription/DefaultTbLocalSubscriptionService.java
Labels: bug, Ignore for release

#11629 Added platform type to system info
  application/src/main/java/org/thingsboard/server/controller/SystemInfoController.java
Labels: Ignore for release

#11640 Fixed behavior for vertical ball value SCADA
  application/src/main/data/json/system/scada_symbols/vertical-ball-valve.svg
Labels: UI, Ignore for release

#11634 Fixed otaPackage api call in accordance with documentation
  ui-ngx/src/app/core/http/ota-package.service.ts
Labels: bug, UI

#11632 Made Resource details page read only for LwM2M resources
  ui-ngx/src/app/modules/home/pages/admin/resource/resources-library-table-config.resolve.ts
  ui-ngx/src/app/modules/home/pages/admin/resource/resources-library.component.html
  ui-ngx/src/app/modules/home/pages/admin/resource/resources-library.component.ts
Labels: enhancement, UI, Ignore for release

#11625 Change link for entity view documentation
  ui-ngx/src/app/shared/models/constants.ts
Labels: bug, UI

#11341 Added ability to provision gateway devices using device provisioning feature
  application/src/main/java/org/thingsboard/server/service/transport/DefaultTransportApiService.java
  application/src/test/java/org/thingsboard/server/service/device/provision/DeviceProvisionServiceTest.java
  application/src/test/java/org/thingsboard/server/transport/coap/provision/CoapProvisionJsonDeviceTest.java
  application/src/test/java/org/thingsboard/server/transport/coap/provision/CoapProvisionProtoDeviceTest.java
  application/src/test/java/org/thingsboard/server/transport/mqtt/mqttv3/provision/MqttProvisionJsonDeviceTest.java
  application/src/test/java/org/thingsboard/server/transport/mqtt/mqttv3/provision/MqttProvisionProtoDeviceTest.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/device/provision/ProvisionRequest.java
  common/proto/src/main/java/org/thingsboard/server/common/adaptor/JsonConverter.java
  common/proto/src/main/proto/queue.proto
  dao/src/main/java/org/thingsboard/server/dao/device/DeviceServiceImpl.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/connectivity/HttpClientTest.java
Labels: Transport

#11583 Notification center: migrate from Office 365 Connectors to Microsoft Teams Workflows
  application/src/main/java/org/thingsboard/server/service/notification/channels/MicrosoftTeamsNotificationChannel.java
  application/src/main/java/org/thingsboard/server/service/notification/channels/TeamsAdaptiveCard.java
  application/src/main/java/org/thingsboard/server/service/notification/channels/TeamsMessageCard.java
  application/src/test/java/org/thingsboard/server/service/notification/NotificationApiTest.java
  common/data/src/main/java/org/thingsboard/server/common/data/notification/targets/MicrosoftTeamsNotificationTargetConfig.java
  dao/src/main/java/org/thingsboard/server/dao/util/ImageUtils.java
  ui-ngx/src/app/modules/home/pages/notification/recipient/recipient-notification-dialog.component.html
  ui-ngx/src/app/modules/home/pages/notification/recipient/recipient-notification-dialog.component.ts
  ui-ngx/src/app/shared/models/notification.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: Core

#11618 Added ability to configure max connections for TbHttpClient
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/rest/TbHttpClient.java
Labels: enhancement, Rule Engine

#11140 Delay node: improvements
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/delay/TbMsgDelayNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/delay/TbMsgDelayNodeConfiguration.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/delay/TbMsgDelayNodeTest.java
Labels: enhancement, Rule Engine

#11641 Gateway Connector Modbus fixes and adjustments
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/abstract/modbus-version-processor.abstract.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-basic-config/modbus-basic-config.abstract.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-basic-config/modbus-basic-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-basic-config/modbus-legacy-basic-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-data-keys-panel/modbus-data-keys-panel.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-data-keys-panel/modbus-data-keys-panel.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-slave-config/modbus-slave-config.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-slave-config/modbus-slave-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-slave-dialog/modbus-slave-dialog.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-slave-dialog/modbus-slave-dialog.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-values/modbus-values.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/dialog/mapping-dialog.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-connectors.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/utils/modbus-version-mapping.util.ts
Labels: bug, UI, Ignore for release

#11653 Disable WS subscriptions rate limits by default
  application/src/main/java/org/thingsboard/server/service/subscription/DefaultTbLocalSubscriptionService.java
  application/src/main/resources/thingsboard.yml
Labels: Ignore for release

#11660 fixed NPE in RuleNodeActorMessageProcessor
  application/src/main/java/org/thingsboard/server/actors/ruleChain/RuleNodeActorMessageProcessor.java
  common/actor/src/main/java/org/thingsboard/server/actors/TbActorMailbox.java
Labels: bug, Ignore for release

#11655 Added upgrade script for device profile node
  application/src/main/java/org/thingsboard/server/service/install/SqlDatabaseUpgradeService.java
Labels: Ignore for release

#11661 fixed NPE in subscription service after restart
  application/src/main/java/org/thingsboard/server/service/subscription/DefaultTbLocalSubscriptionService.java
Labels: bug

#11607 [MQTT transport] Gateway latency metrics
  application/src/main/resources/thingsboard.yml
  application/src/test/java/org/thingsboard/server/transport/mqtt/mqttv3/telemetry/timeseries/AbstractMqttTimeseriesIntegrationTest.java
  common/message/src/main/java/org/thingsboard/server/common/msg/gateway/metrics/GatewayMetadata.java
  common/proto/src/main/java/org/thingsboard/server/common/adaptor/JsonConverter.java
  common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttTransportContext.java
  common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttTransportHandler.java
  common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttTransportService.java
  common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/TbMqttTransportComponent.java
  common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/gateway/GatewayMetricsService.java
  common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/gateway/metrics/GatewayMetricsState.java
  common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/AbstractGatewaySessionHandler.java
  common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/GatewaySessionHandler.java
  transport/mqtt/src/main/resources/tb-mqtt-transport.yml
Labels: feature, Transport

#11617 EdgeGrpcSession: fix typo in comment
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java
Labels: Ignore for release

#11667 fixed concurrent modification in TopicService
  common/queue/src/main/java/org/thingsboard/server/queue/discovery/TopicService.java
Labels: bug, Ignore for release

#11666 Housekeeper: performance improvements for alarms unassigning
  application/src/main/java/org/thingsboard/server/service/entitiy/alarm/DefaultTbAlarmService.java
  application/src/main/java/org/thingsboard/server/service/entitiy/alarm/TbAlarmService.java
  application/src/main/java/org/thingsboard/server/service/housekeeper/processor/AlarmsUnassignTaskProcessor.java
  application/src/test/java/org/thingsboard/server/service/entitiy/alarm/DefaultTbAlarmServiceTest.java
  application/src/test/java/org/thingsboard/server/service/housekeeper/HousekeeperServiceTest.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/alarm/AlarmService.java
  common/data/src/main/java/org/thingsboard/server/common/data/housekeeper/AlarmsUnassignHousekeeperTask.java
  dao/src/main/java/org/thingsboard/server/dao/alarm/AlarmDao.java
  dao/src/main/java/org/thingsboard/server/dao/alarm/BaseAlarmService.java
  dao/src/main/java/org/thingsboard/server/dao/sql/alarm/AlarmRepository.java
  dao/src/main/java/org/thingsboard/server/dao/sql/alarm/JpaAlarmDao.java
Labels: enhancement, Core

#11679 fixed concurrent modification in TbSubscriptionsInfo
  application/src/main/java/org/thingsboard/server/service/subscription/TbSubscriptionsInfo.java
  application/src/test/java/org/thingsboard/server/service/subscription/DefaultTbLocalSubscriptionServiceTest.java
Labels: bug

#11672 [Rule Engine] fixed RuleEngine OOM
  application/src/main/java/org/thingsboard/server/actors/ruleChain/RuleChainManagerActor.java
  application/src/main/java/org/thingsboard/server/actors/shared/RuleChainErrorActor.java
  application/src/test/java/org/thingsboard/server/actors/tenant/TenantActorTest.java
Labels: bug, Rule Engine

#11087 Originator telemetry node: added tests
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/metadata/FetchMode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/metadata/TbGetTelemetryNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/metadata/TbGetTelemetryNodeConfiguration.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/metadata/TbGetTelemetryNodeTest.java
Labels: Ignore for release

#11682 Fixed incorrect show widgets in layout
  ui-ngx/src/app/modules/home/components/dashboard/dashboard.component.html
  ui-ngx/src/app/modules/home/components/dashboard/dashboard.component.ts
  ui-ngx/src/app/modules/home/models/dashboard-component.models.ts
Labels: bug, UI, Ignore for release

#11707 Fixed incorrect show widgets in layout when active edit mode
  ui-ngx/src/app/modules/home/components/dashboard/dashboard.component.ts
  ui-ngx/src/app/modules/home/models/dashboard-component.models.ts
Labels: bug, UI, Ignore for release

#11702 TbRestApiCallNode - added upgrade step to add maxInMemoryBufferSizeInKb config
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/rest/TbRestApiCallNode.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/rest/TbRestApiCallNodeTest.java
Labels: Ignore for release

#11645 Adjust styles for outlined input with floating label for iOS
  ui-ngx/src/form.scss
Labels: bug, UI, Ignore for release

#11650 Fixed country autocomplete blocking tenant creation
  ui-ngx/src/app/shared/components/contact.component.html
  ui-ngx/src/app/shared/components/country-autocomplete.component.ts
Labels: bug, UI

#11654 Fixed 'add tenant' button on sys-admin home page not readable with German language
  ui-ngx/src/assets/dashboard/sys_admin_home_page.json
Labels: bug, UI

#11656 Gateway UI improvements and minor bug fixes
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/abstract/mqtt-version-processor.abstract.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/configuration/advanced/gateway-advanced-configuration.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/configuration/basic/gateway-basic-configuration.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/configuration/gateway-configuration.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/configuration/models/gateway-configuration.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/mapping-table/mapping-table.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/opc/opc-server-config/opc-server-config.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-connectors.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/utils/opc-version-mapping.util.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: bug, UI, Ignore for release

#11663 Added posibility to configure modifier type
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-data-keys-panel/modbus-data-keys-panel.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-data-keys-panel/modbus-data-keys-panel.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-widget.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI, feature, Ignore for release

#11664 OAuth 2 UI improvements, code cleanup
  ui-ngx/src/app/modules/home/pages/admin/oauth2/clients/client-dialog.component.ts
  ui-ngx/src/app/modules/home/pages/admin/oauth2/clients/client.component.ts
  ui-ngx/src/app/modules/home/pages/admin/oauth2/clients/clients-table-config.resolver.ts
  ui-ngx/src/app/modules/home/pages/admin/oauth2/domains/domain-table-config.resolver.ts
  ui-ngx/src/app/modules/home/pages/admin/oauth2/domains/domain.component.html
  ui-ngx/src/app/modules/home/pages/admin/oauth2/domains/domain.component.ts
  ui-ngx/src/app/modules/home/pages/admin/oauth2/mobile-apps/mobile-app-table-config.resolver.ts
  ui-ngx/src/app/modules/home/pages/admin/oauth2/mobile-apps/mobile-app.component.html
  ui-ngx/src/app/modules/home/pages/admin/oauth2/mobile-apps/mobile-app.component.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: bug, UI, Ignore for release

#11668 Update rule node config
  rule-engine/rule-engine-components/src/main/resources/public/static/rulenode/rulenode-core-config.js
Labels: UI, Rule Engine, Ignore for release

#11687 Fixed race conditional when show login error dialog
  ui-ngx/src/app/core/auth/auth.service.ts
Labels: bug, UI

#11704 Version Conflict Fixes
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.html
  ui-ngx/src/app/shared/components/dialog/entity-conflict-dialog/entity-conflict-dialog.component.html
  ui-ngx/src/app/shared/components/dialog/entity-conflict-dialog/entity-conflict-dialog.component.ts
  ui-ngx/src/app/shared/import-export/import-export.service.ts
Labels: bug, UI, Ignore for release

#11709 Fixed alarm assignee and comments for deleted user
  ui-ngx/src/app/core/services/utils.service.ts
  ui-ngx/src/app/modules/home/components/alarm/alarm-assignee-panel.component.ts
  ui-ngx/src/app/modules/home/components/alarm/alarm-assignee-select-panel.component.ts
  ui-ngx/src/app/modules/home/components/alarm/alarm-assignee.component.html
  ui-ngx/src/app/modules/home/components/alarm/alarm-assignee.component.ts
  ui-ngx/src/app/modules/home/components/alarm/alarm-comment.component.html
  ui-ngx/src/app/modules/home/components/alarm/alarm-comment.component.scss
  ui-ngx/src/app/modules/home/components/alarm/alarm-comment.component.ts
  ui-ngx/src/app/modules/home/components/alarm/alarm-table-config.ts
  ui-ngx/src/app/modules/home/components/widget/lib/alarm/alarms-table-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/alarm/alarms-table-widget.component.ts
  ui-ngx/src/app/shared/models/alarm.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
  ui-ngx/src/styles.scss
Labels: bug, UI

#11729 jackson.version 2.17.2
  pom.xml
Labels: enhancement, Ignore for release

#11678 Fixed next button for notify again dialog
  ui-ngx/src/app/shared/components/entity/entity-list.component.ts
Labels: bug, UI, Ignore for release

#11725 Refactored logic: Customer - Version Conflict - Export
  ui-ngx/src/app/shared/import-export/import-export.service.ts
Labels: enhancement, UI, Ignore for release

#11726 Removed unused style class
  ui-ngx/src/styles.scss
Labels: enhancement, UI, Ignore for release

#11727 Fixed coping of instances when deleting LWM2M objects
  ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-device-profile-transport-configuration.component.ts
Labels: bug, UI

#11730 Fixed select widget in touch screen
  ui-ngx/src/app/modules/home/components/widget/widget-container.component.ts
Labels: bug, UI, Ignore for release

#11731 Fixed translation with pluralization for Dutch Belgium language
  ui-ngx/src/assets/locale/locale.constant-lt_LT.json
  ui-ngx/src/assets/locale/locale.constant-nl_BE.json
  ui-ngx/src/assets/locale/locale.constant-pl_PL.json
Labels: bug, UI

#11718 RPC templates update for MQTT, MODBUS, OPC-UA
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/rpc-parameters/modbus-rpc-parameters/modbus-rpc-parameters.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/rpc-parameters/modbus-rpc-parameters/modbus-rpc-parameters.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/rpc-parameters/modbus-rpc-parameters/modbus-rpc-parameters.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/rpc-parameters/mqtt-rpc-parameters/mqtt-rpc-parameters.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/rpc-parameters/mqtt-rpc-parameters/mqtt-rpc-parameters.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/rpc-parameters/mqtt-rpc-parameters/mqtt-rpc-parameters.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/rpc-parameters/opc-rpc-parameters/opc-rpc-parameters.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/rpc-parameters/opc-rpc-parameters/opc-rpc-parameters.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/rpc-parameters/opc-rpc-parameters/opc-rpc-parameters.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/type-value-panel/type-value-panel.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/type-value-panel/type-value-panel.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc-connector-templates.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc-connector-templates.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc-connector-templates.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc-connector.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc-connector.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/pipes/rpc-template-array-view.pipe.ts
  ui-ngx/src/app/modules/home/components/widget/widget-components.module.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: bug, UI

#11740 Fixed cropped "qr mobile app" widget title on tenant home page
  ui-ngx/src/assets/dashboard/tenant_admin_home_page.json
Labels: bug, UI

#11736 Fixed text color of table widgets not applying to action cell buttons
  ui-ngx/src/app/modules/home/components/widget/lib/table-widget.models.ts
Labels: bug, UI

#11744 Gateway Fixes
  application/src/main/data/json/system/widget_types/gateway_connectors.json
  application/src/main/data/json/tenant/dashboards/gateways.json
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/abstract/gateway-connector-basic-config.abstract.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/abstract/gateway-connector-version-processor.abstract.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/abstract/opc-version-processor.abstract.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/configuration/basic/gateway-basic-configuration.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/configuration/basic/gateway-basic-configuration.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/configuration/gateway-configuration.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/configuration/models/gateway-configuration.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/mapping-data-keys-panel/mapping-data-keys-panel.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-master-table/modbus-master-table.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-slave-dialog/modbus-slave-dialog.abstract.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-slave-dialog/modbus-slave-dialog.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/mqtt/basic-config/mqtt-basic-config.abstract.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/mqtt/basic-config/mqtt-basic-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/mqtt/basic-config/mqtt-legacy-basic-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/type-value-panel/type-value-panel.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-connectors.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-connectors.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/utils/opc-version-mapping.util.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
  ui-ngx/src/assets/metadata/connector-default-configs/modbus.json
Labels: bug, UI, Ignore for release

#11748 Fixed layout settings translate
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI, Ignore for release

#11749 Fixed device credentials on discard/cancel conflict
  ui-ngx/src/app/modules/home/pages/device/device-credentials-dialog.component.ts
Labels: bug, UI, Ignore for release

#11753 Fixed quick update of value in gauge widget during animation
  ui-ngx/src/app/modules/home/components/widget/lib/analogue-gauge.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/digital-gauge.ts
Labels: bug, UI

#11644 Check default and home dashboard exists when GET /auth/user
  application/src/main/java/org/thingsboard/server/controller/AuthController.java
  application/src/main/java/org/thingsboard/server/controller/BaseController.java
  application/src/main/java/org/thingsboard/server/controller/CustomerController.java
  application/src/main/java/org/thingsboard/server/controller/TenantController.java
  application/src/main/java/org/thingsboard/server/controller/UserController.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/dashboard/DashboardService.java
  dao/src/main/java/org/thingsboard/server/dao/dashboard/DashboardServiceImpl.java
Labels: bug, Ignore for release

#11758 Gateway fixes
  application/src/main/data/json/tenant/dashboards/gateways.json
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/configuration/gateway-configuration.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-data-keys-panel/modbus-data-keys-panel.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-data-keys-panel/modbus-data-keys-panel.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-master-table/modbus-master-table.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-slave-dialog/modbus-slave-dialog.abstract.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-slave-dialog/modbus-slave-dialog.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/report-strategy/report-strategy.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-connectors.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-connectors.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-widget.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: bug, UI, Ignore for release

#11770 Fixed incorrect parsing of the CSS units 'rem' and 'vmin'
  ui-ngx/src/app/shared/models/widget-settings.models.ts
Labels: bug, UI

#11771 Renamed 'Webhook URL' to 'Workflow URL' for the new connector API in Microsoft Teams notification recipient
  ui-ngx/src/app/modules/home/pages/notification/recipient/recipient-notification-dialog.component.html
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: bug, UI, Ignore for release

#11772 Timewindow redesign fixes
  ui-ngx/src/app/shared/components/time/datapoints-limit.component.scss
  ui-ngx/src/app/shared/components/time/timewindow-config-dialog.component.html
  ui-ngx/src/app/shared/components/time/timewindow-panel.component.html
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI, Ignore for release
