Repository thingsboard/thingsboard, pull requests merged in 2024-05, with the labels that each got.

#10687 AuditLogControllerTest fix
  application/src/test/java/org/thingsboard/server/controller/AuditLogControllerTest.java
Labels: Ignore for release

#10680 Improvement translate loader and types
  ui-ngx/src/app/core/core.module.ts
  ui-ngx/src/app/core/settings/settings.utils.ts
  ui-ngx/src/app/core/translate/translate-default-loader.ts
Labels: enhancement, UI, Ignore for release

#10615 Swagger does not work on Tb Demo
  msa/tb-node/docker/Dockerfile
Labels: Ignore for release

#10682 fixed mail sender
  pom.xml
Labels: Ignore for release

#10685 JUnit5 migration in transport.
  transport/coap/pom.xml
  transport/http/pom.xml
  transport/lwm2m/pom.xml
  transport/mqtt/pom.xml
Labels: Ignore for release

#10688 VC: resolve existing default entity when loading version
  application/src/main/java/org/thingsboard/server/service/sync/ie/exporting/DefaultExportableEntitiesService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/exporting/ExportableEntitiesService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/BaseEntityImportService.java
  application/src/test/java/org/thingsboard/server/service/sync/ie/ExportImportServiceSqlTest.java
  common/data/src/main/java/org/thingsboard/server/common/data/DeviceProfile.java
  common/data/src/main/java/org/thingsboard/server/common/data/HasDefaultOption.java
  common/data/src/main/java/org/thingsboard/server/common/data/asset/AssetProfile.java
  common/data/src/main/java/org/thingsboard/server/common/data/rule/RuleChain.java
  dao/src/main/java/org/thingsboard/server/dao/ExportableEntityDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/asset/JpaAssetProfileDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/device/JpaDeviceProfileDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/rule/JpaRuleChainDao.java
Labels: Core

#10674 fix with security matchers
  application/src/main/java/org/thingsboard/server/config/ThingsboardSecurityConfiguration.java
  application/src/test/java/org/thingsboard/server/controller/AuthControllerTest.java
Labels: Ignore for release

#10698 Updated rulenode-core-config.js
  rule-engine/rule-engine-components/src/main/resources/public/static/rulenode/rulenode-core-config.js
Labels: UI, Rule Engine, Ignore for release

#9576 Fixed alarm widget table selection and text search prevents editing widget
  application/src/main/data/json/system/widget_types/alarms_table.json
  ui-ngx/src/app/modules/home/components/widget/lib/alarm/alarms-table-widget.component.ts
Labels: bug, UI

#9624 Added ability to display dashboard right layout first in mobile view
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.html
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.ts
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-settings-dialog.component.html
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-settings-dialog.component.ts
  ui-ngx/src/app/modules/home/components/dashboard-page/layout/manage-dashboard-layouts-dialog.component.ts
  ui-ngx/src/app/shared/models/dashboard.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI, feature

#10295 Fixed the create connector message
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-connectors.component.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI

#10308 Parsing unicode in legend
  ui-ngx/src/app/modules/home/components/widget/lib/legend.component.html
Labels: bug, UI

#10348 Fixed key filter dialog when constant key type and boolean value type selected saving null if not touched, added clear of value on value type changed
  ui-ngx/src/app/modules/home/components/filter/key-filter-dialog.component.ts
Labels: bug, UI

#10430 Update pl_PL locale
  ui-ngx/src/assets/locale/locale.constant-pl_PL.json
Labels: enhancement, UI

#10489 Fixed timeseries chart widget threshold settings styles
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/chart/time-series-chart-threshold-settings-panel.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/chart/time-series-chart-threshold-settings-panel.component.scss
Labels: enhancement, UI

#10579 [Custom Translation] Add support for custom translations of alarm originator on the alarms page
  ui-ngx/src/app/modules/home/components/alarm/alarm-table-config.ts
Labels: bug, UI

#10610 Removed deprecated composite operation support from Lwm2m device profile settings
  ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-device-profile-transport-configuration.component.html
  ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-device-profile-transport-configuration.component.ts
  ui-ngx/src/assets/locale/locale.constant-ca_ES.json
  ui-ngx/src/assets/locale/locale.constant-cs_CZ.json
  ui-ngx/src/assets/locale/locale.constant-en_US.json
  ui-ngx/src/assets/locale/locale.constant-es_ES.json
  ui-ngx/src/assets/locale/locale.constant-nl_BE.json
  ui-ngx/src/assets/locale/locale.constant-pl_PL.json
  ui-ngx/src/assets/locale/locale.constant-tr_TR.json
  ui-ngx/src/assets/locale/locale.constant-zh_CN.json
  ui-ngx/src/assets/locale/locale.constant-zh_TW.json
Labels: enhancement, UI

#10701 math node flaky test fixed
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/math/TbMathNodeTest.java
Labels: Ignore for release

#10694 Fixed schema_update.sql for case when attribute_kv is empty
  application/src/main/data/upgrade/3.6.4/schema_update.sql
Labels: Ignore for release

#10703 Always send back block num
  common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/OtaPackageTransportResource.java
Labels: Transport

#10714 fixed events ordering during tenant creation
  dao/src/main/java/org/thingsboard/server/dao/tenant/TenantServiceImpl.java
Labels: Ignore for release

#10418 Fixed widgets in search mode not editable
  application/src/main/data/json/system/widget_types/asset_admin_table.json
  application/src/main/data/json/system/widget_types/device_admin_table.json
  application/src/main/data/json/system/widget_types/entities_hierarchy.json
  application/src/main/data/json/system/widget_types/entities_table.json
  application/src/main/data/json/system/widget_types/timeseries_table.json
  ui-ngx/src/app/modules/home/components/widget/lib/entity/entities-hierarchy-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/entity/entities-table-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/timeseries-table-widget.component.ts
Labels: enhancement, UI

#10719 Fix for notification deduplication service
  common/queue/src/main/java/org/thingsboard/server/queue/notification/DefaultNotificationDeduplicationService.java
Labels: Ignore for release

#10704 updated log entry for adding customer_title_unq_key if doesn't exist
  application/src/main/java/org/thingsboard/server/service/install/SqlAbstractDatabaseSchemaService.java
  application/src/main/java/org/thingsboard/server/service/install/SqlEntityDatabaseSchemaService.java
Labels: Ignore for release

#10723 Fix "Failed to process timeseries history deletion" when deleting tenant
  application/src/test/java/org/thingsboard/server/service/queue/ruleengine/TbRuleEngineQueueConsumerManagerTest.java
  common/cache/src/main/java/org/thingsboard/server/cache/limits/DefaultRateLimitService.java
  common/cache/src/main/java/org/thingsboard/server/cache/limits/RateLimitService.java
  dao/src/main/java/org/thingsboard/server/dao/util/AbstractBufferedRateExecutor.java
Labels: Ignore for release

#10727 Commons logging excluded
  pom.xml
Labels: Ignore for release

#10665 Updated asset search query to include "label", "type" and customer "title" into search
  dao/src/main/java/org/thingsboard/server/dao/sql/asset/AssetRepository.java
  dao/src/test/java/org/thingsboard/server/dao/sql/asset/JpaAssetDaoTest.java
Labels: enhancement, Core

#10730 Rule Chain node: added ability to transfer msg to originator's default rule chain
  application/src/main/java/org/thingsboard/server/service/install/update/DefaultDataUpdateService.java
  common/data/src/main/java/org/thingsboard/server/common/data/tenant/profile/DefaultTenantProfileConfiguration.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/flow/TbRuleChainInputNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/flow/TbRuleChainInputNodeConfiguration.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/flow/TbRuleChainInputNodeTest.java
Labels: enhancement

#10740 Fix for Incorrect HTML tag handling in markdown widgets
  ui-ngx/src/app/core/services/dynamic-component-factory.service.ts
Labels: bug, UI

#10741 Fix finding of attribute keys by entity id and scope
  dao/src/main/java/org/thingsboard/server/dao/sql/attributes/AttributeKvRepository.java
  dao/src/main/java/org/thingsboard/server/dao/sql/attributes/JpaAttributeDao.java
  dao/src/test/java/org/thingsboard/server/dao/service/attributes/BaseAttributesServiceTest.java
Labels: Ignore for release

#10742 Fix maxRuleNodeExecutionsPerMessage (failed test TenantProfileEdgeTest.testTenantProfiles)
  common/data/src/main/java/org/thingsboard/server/common/data/tenant/profile/DefaultTenantProfileConfiguration.java
Labels: Ignore for release

#10528 Fix for aggregation in entities table widget
  ui-ngx/src/app/core/api/data-aggregator.ts
  ui-ngx/src/app/shared/models/time/time.models.ts
Labels: bug, UI

#10731 LwM2M: default object version
  application/src/main/java/org/thingsboard/server/service/device/DeviceBulkImportService.java
  common/data/src/main/java/org/thingsboard/server/common/data/device/profile/lwm2m/OtherConfiguration.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mServerListener.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mVersionedModelProvider.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mClient.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mClientContextImpl.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/ota/DefaultLwM2MOtaUpdateService.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/store/util/LwM2MClientSerDes.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/uplink/DefaultLwM2mUplinkMsgHandler.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/uplink/LwM2mUplinkMsgHandler.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/utils/LwM2MTransportUtil.java
  monitoring/src/main/resources/lwm2m/device_profile.json
  monitoring/src/main/resources/lwm2m/models/test-model.xml
  monitoring/src/main/resources/lwm2m/resource.json
Labels: Transport

#10716 LwM2M: default object version
  application/src/main/java/org/thingsboard/server/service/device/DeviceBulkImportService.java
  common/data/src/main/java/org/thingsboard/server/common/data/device/profile/lwm2m/OtherConfiguration.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mServerListener.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mVersionedModelProvider.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mClient.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mClientContextImpl.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/ota/DefaultLwM2MOtaUpdateService.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/store/util/LwM2MClientSerDes.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/uplink/DefaultLwM2mUplinkMsgHandler.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/uplink/LwM2mUplinkMsgHandler.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/utils/LwM2MTransportUtil.java
  monitoring/src/main/resources/lwm2m/device_profile.json
  monitoring/src/main/resources/lwm2m/models/test-model.xml
  monitoring/src/main/resources/lwm2m/resource.json
  ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-device-profile-transport-configuration.component.html
  ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-device-profile-transport-configuration.component.ts
  ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-profile-config.models.ts
  ui-ngx/src/assets/locale/locale.constant-ar_AE.json
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: Transport

#10744 fix_bug_LwM2MClientSerDes_test
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mClient.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/store/util/LwM2MClientSerDes.java
Labels: Ignore for release

#10746 fix_bug_setSupportedClientObjects_root
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mClient.java
Labels: Ignore for release

#10743 Fix NPE in DeviceProfile node because currentAlarm field has ID equals to null
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/profile/AlarmState.java
Labels: bug

#10736 Junit 4 to 5 migration in application (Mockito extension)
  application/src/test/java/org/thingsboard/server/queue/discovery/HashPartitionServiceTest.java
  application/src/test/java/org/thingsboard/server/service/apiusage/DefaultTbApiUsageStateServiceTest.java
  application/src/test/java/org/thingsboard/server/service/edge/rpc/constructor/RuleChainMsgConstructorTest.java
  application/src/test/java/org/thingsboard/server/service/limits/RateLimitServiceTest.java
  application/src/test/java/org/thingsboard/server/service/queue/ruleengine/TbRuleEngineQueueConsumerManagerTest.java
  application/src/test/java/org/thingsboard/server/service/sms/smpp/SmppSmsSenderTest.java
Labels: Ignore for release

#10755 fix_bug: if setSupportedClientObjectsis is not supported LwM2m.Version
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mClient.java
  monitoring/src/main/java/org/thingsboard/monitoring/service/transport/TransportHealthChecker.java
Labels: Ignore for release

#10758 Jwt token factory refactored due to PE
  application/src/main/java/org/thingsboard/server/service/security/model/token/JwtTokenFactory.java
Labels: Ignore for release

#10732 Added login audit log when user is activated
  application/src/main/java/org/thingsboard/server/controller/AuthController.java
  application/src/test/java/org/thingsboard/server/controller/AuditLogControllerTest.java
  application/src/test/java/org/thingsboard/server/controller/TwoFactorAuthTest.java
Labels: enhancement, Core

#10686 JUnit5 migration in msa.
  msa/black-box-tests/pom.xml
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/AbstractLwm2mClientTest.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/connectivity/lwm2m/LwM2MTestClient.java
  msa/vc-executor/pom.xml
  pom.xml
Labels: Ignore for release

#10750 fixed swagger allowable values
  application/src/main/java/org/thingsboard/server/controller/ComponentDescriptorController.java
  application/src/main/java/org/thingsboard/server/controller/CustomerController.java
  application/src/main/java/org/thingsboard/server/controller/EntityViewController.java
  application/src/main/java/org/thingsboard/server/controller/NotificationController.java
  application/src/main/java/org/thingsboard/server/controller/OAuth2Controller.java
  application/src/main/java/org/thingsboard/server/controller/OtaPackageController.java
  common/data/src/main/java/org/thingsboard/server/common/data/audit/AuditLog.java
  common/data/src/main/java/org/thingsboard/server/common/data/event/DebugEventFilter.java
  common/data/src/main/java/org/thingsboard/server/common/data/event/LifeCycleEventFilter.java
  common/data/src/main/java/org/thingsboard/server/common/data/event/RuleNodeDebugEventFilter.java
  common/data/src/main/java/org/thingsboard/server/common/data/plugin/ComponentDescriptor.java
  common/data/src/main/java/org/thingsboard/server/common/data/security/DeviceCredentials.java
  common/data/src/main/java/org/thingsboard/server/common/data/sms/config/SmppSmsProviderConfiguration.java
Labels: Ignore for release

#10729 Fixed paste hex color with prefix
  ui-ngx/src/app/shared/components/color-picker/hex-input.component.ts
Labels: enhancement, UI, Ignore for release

#10787 Added more logs to DefaultTbApiUsageStateService
  application/src/main/java/org/thingsboard/server/service/apiusage/BaseApiUsageState.java
  application/src/main/java/org/thingsboard/server/service/apiusage/DefaultTbApiUsageStateService.java
Labels: Ignore for release

#10796 Include bundle widget checkbox enabled by default
  ui-ngx/src/app/shared/import-export/export-widgets-bundle-dialog.component.ts
Labels: enhancement, UI

#10806 Add SSL support for Kafka queue connection in JS executor
  msa/js-executor/api/utils.ts
  msa/js-executor/config/custom-environment-variables.yml
  msa/js-executor/config/default.yml
  msa/js-executor/queue/kafkaTemplate.ts
Labels: enhancement, Core

#10831 fixed race condition during adding new gateway connector with default config
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/dialog/add-connector-dialog.component.ts
Labels: Ignore for release

#10836 added upgrade for the gateway rate limits
  application/src/main/java/org/thingsboard/server/service/install/update/DefaultDataUpdateService.java
Labels: Ignore for release

#10813 Startup performance improvements
  application/src/main/java/org/thingsboard/server/ThingsboardServerApplication.java
  common/queue/src/main/java/org/thingsboard/server/queue/kafka/TbKafkaAdmin.java
  common/queue/src/main/java/org/thingsboard/server/queue/kafka/TbKafkaConsumerStatsService.java
  common/queue/src/main/java/org/thingsboard/server/queue/kafka/TbKafkaSettings.java
  dao/src/main/java/org/thingsboard/server/dao/JpaDaoConfig.java
  dao/src/main/java/org/thingsboard/server/dao/SqlTimeseriesDaoConfig.java
  dao/src/main/java/org/thingsboard/server/dao/SqlTsDaoConfig.java
  dao/src/main/java/org/thingsboard/server/dao/SqlTsLatestDaoConfig.java
  dao/src/main/java/org/thingsboard/server/dao/TimescaleDaoConfig.java
  dao/src/main/java/org/thingsboard/server/dao/TimescaleTsLatestDaoConfig.java
  dao/src/test/java/org/thingsboard/server/dao/service/EntityDaoRegistryTest.java
Labels: enhancement, Core, Rule Engine

#10815 Queue option to duplicate msgs to all partitions
  application/src/main/java/org/thingsboard/server/actors/ActorSystemContext.java
  application/src/main/java/org/thingsboard/server/actors/ruleChain/RuleChainActorMessageProcessor.java
  application/src/main/java/org/thingsboard/server/service/queue/DefaultTbClusterService.java
  application/src/main/java/org/thingsboard/server/service/transport/DefaultTransportApiService.java
  application/src/test/java/org/thingsboard/server/controller/BaseQueueControllerTest.java
  application/src/test/java/org/thingsboard/server/service/housekeeper/HousekeeperServiceTest.java
  application/src/test/java/org/thingsboard/server/service/queue/DefaultTbClusterServiceTest.java
  common/data/src/main/java/org/thingsboard/server/common/data/queue/Queue.java
  common/message/src/main/java/org/thingsboard/server/common/msg/TbMsg.java
  common/message/src/main/proto/tbmsg.proto
  common/proto/src/main/proto/queue.proto
  common/queue/src/main/java/org/thingsboard/server/queue/common/TbRuleEngineProducerService.java
  common/queue/src/main/java/org/thingsboard/server/queue/discovery/HashPartitionService.java
  common/queue/src/main/java/org/thingsboard/server/queue/discovery/PartitionService.java
  common/queue/src/main/java/org/thingsboard/server/queue/discovery/QueueRoutingInfo.java
  common/queue/src/main/java/org/thingsboard/server/queue/kafka/TbKafkaConsumerStatsService.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/service/DefaultTransportService.java
  ui-ngx/src/app/modules/home/components/profile/queue/tenant-profile-queues.component.ts
  ui-ngx/src/app/modules/home/components/profile/tenant-profile.component.ts
  ui-ngx/src/app/modules/home/components/queue/queue-form.component.html
  ui-ngx/src/app/modules/home/components/queue/queue-form.component.ts
  ui-ngx/src/app/shared/models/queue.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: Ignore for release

#10757 Kafka Confluent compatibility out of the box: segment.bytes:52428800
  application/src/main/resources/thingsboard.yml
  common/queue/src/test/java/org/thingsboard/server/queue/util/PropertyUtilsTest.java
  msa/js-executor/config/default.yml
  msa/vc-executor/src/main/resources/tb-vc-executor.yml
  transport/coap/src/main/resources/tb-coap-transport.yml
  transport/http/src/main/resources/tb-http-transport.yml
  transport/lwm2m/src/main/resources/tb-lwm2m-transport.yml
  transport/mqtt/src/main/resources/tb-mqtt-transport.yml
  transport/snmp/src/main/resources/tb-snmp-transport.yml
Labels: enhancement

#10500 Pattern support for widget title on widget export
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.ts
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.models.ts
  ui-ngx/src/app/modules/home/components/dashboard-page/layout/dashboard-layout.component.ts
  ui-ngx/src/app/modules/home/components/dashboard/dashboard.component.ts
  ui-ngx/src/app/modules/home/models/dashboard-component.models.ts
  ui-ngx/src/app/shared/import-export/import-export.service.ts
Labels: enhancement, UI

#10756 Added hint for Time series chart for comparison series
  ui-ngx/src/app/modules/home/components/widget/config/basic/chart/time-series-chart-basic-config.component.html
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI

#10820 Fixed widget action dialog column index field blocks save
  ui-ngx/src/app/modules/home/components/widget/action/widget-action-dialog.component.ts
Labels: bug, UI, Ignore for release

#10846 Update locale.constant-de_DE.json
  ui-ngx/src/assets/locale/locale.constant-de_DE.json
Labels: UI

#10844 fix bug lwm2m Content Format M14
  application/src/test/java/org/thingsboard/server/transport/lwm2m/AbstractLwM2MIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/client/LwM2MTestClient.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/AbstractRpcLwM2MIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationWriteCborTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationWriteTest.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mClient.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/downlink/DefaultLwM2mDownlinkMsgHandler.java
Labels: Ignore for release

#9830 [Feature Request] - Add "NOT" option in relation queries
  application/src/test/java/org/thingsboard/server/controller/EntityQueryControllerTest.java
  common/data/src/main/java/org/thingsboard/server/common/data/query/RelationsQueryFilter.java
  common/data/src/main/java/org/thingsboard/server/common/data/relation/RelationEntityTypeFilter.java
  dao/src/main/java/org/thingsboard/server/dao/sql/query/DefaultEntityQueryRepository.java
  ui-ngx/src/app/modules/home/components/entity/entity-filter.component.html
  ui-ngx/src/app/modules/home/components/entity/entity-filter.component.ts
  ui-ngx/src/app/modules/home/components/relation/relation-filters.component.ts
  ui-ngx/src/app/shared/models/alias.models.ts
  ui-ngx/src/app/shared/models/relation.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI, feature, WIP, Core

#10856 clear all WS sessionsMap when stopping the application
  application/src/main/java/org/thingsboard/server/controller/plugin/TbWebSocketHandler.java
Labels: Ignore for release

#10734 Added MQTT Disconnect messages from server with reason codes
  application/src/main/java/org/thingsboard/server/actors/device/DeviceActorMessageProcessor.java
  application/src/main/resources/thingsboard.yml
  common/proto/src/main/java/org/thingsboard/server/common/adaptor/JsonConverter.java
  common/proto/src/main/proto/queue.proto
  common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttTransportContext.java
  common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttTransportHandler.java
  common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/adaptors/BackwardCompatibilityAdaptor.java
  common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/adaptors/JsonMqttAdaptor.java
  common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/adaptors/MqttTransportAdaptor.java
  common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/adaptors/ProtoMqttAdaptor.java
  common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/AbstractGatewaySessionHandler.java
  common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/util/ReturnCode.java
  common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/util/ReturnCodeResolver.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/AbstractContainerTest.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/connectivity/MqttClientTest.java
  netty-mqtt/src/main/java/org/thingsboard/mqtt/MqttChannelHandler.java
  netty-mqtt/src/main/java/org/thingsboard/mqtt/MqttClientCallback.java
  netty-mqtt/src/main/java/org/thingsboard/mqtt/MqttClientImpl.java
  transport/mqtt/src/main/resources/tb-mqtt-transport.yml
Labels: enhancement

#10859 [Check connectivity] Fixed mqtt basic credentials connectivity command
  application/src/test/java/org/thingsboard/server/controller/DeviceConnectivityControllerTest.java
  dao/src/main/java/org/thingsboard/server/dao/util/DeviceConnectivityUtil.java
Labels: bug

#10860 fixed alarm rule with future ts
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/profile/AlarmState.java
Labels: bug

#10876 Rule nodes upgrade: moved try-catch into loop over versioned node types
  application/src/main/java/org/thingsboard/server/service/install/update/DefaultDataUpdateService.java
Labels: Ignore for release

#10884 Fix token sessionId calculation
  application/src/main/java/org/thingsboard/server/controller/AuthController.java
  application/src/main/java/org/thingsboard/server/service/security/model/SecurityUser.java
  application/src/main/java/org/thingsboard/server/service/security/model/token/JwtTokenFactory.java
  application/src/test/java/org/thingsboard/server/service/security/auth/JwtTokenFactoryTest.java
  common/data/src/main/java/org/thingsboard/server/common/data/BaseDataWithAdditionalInfo.java
  common/data/src/main/java/org/thingsboard/server/common/data/security/model/JwtPair.java
Labels: Ignore for release

#10881 [Mobile App] added upgrade script for update mobile secretApp
  application/src/main/java/org/thingsboard/server/install/ThingsboardInstallService.java
  application/src/main/java/org/thingsboard/server/service/install/DefaultSystemDataLoaderService.java
  application/src/main/java/org/thingsboard/server/service/install/SystemDataLoaderService.java
  application/src/main/java/org/thingsboard/server/service/security/auth/jwt/settings/DefaultJwtSettingsService.java
  ui-ngx/src/app/modules/home/pages/admin/oauth2-settings.component.html
  ui-ngx/src/app/modules/home/pages/admin/oauth2-settings.component.ts
  ui-ngx/src/app/modules/home/pages/admin/security-settings.component.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: Ignore for release

#10816 [Documentation] - Added "docPlatformPrefix" to URLs
  ui-ngx/src/app/core/services/help.service.ts
  ui-ngx/src/app/shared/models/constants.ts
  ui-ngx/src/assets/help/en_US/rulenode/clear_alarm_node_script_fn.md
  ui-ngx/src/assets/help/en_US/rulenode/common_node_fields_templatization.md
  ui-ngx/src/assets/help/en_US/rulenode/common_node_script_args.md
  ui-ngx/src/assets/help/en_US/rulenode/create_alarm_node_script_fn.md
  ui-ngx/src/assets/help/en_US/rulenode/filter_node_script_fn.md
  ui-ngx/src/assets/help/en_US/rulenode/log_node_script_fn.md
  ui-ngx/src/assets/help/en_US/rulenode/switch_node_script_fn.md
  ui-ngx/src/assets/help/en_US/rulenode/tbel/clear_alarm_node_script_fn.md
  ui-ngx/src/assets/help/en_US/rulenode/tbel/common_node_script_args.md
  ui-ngx/src/assets/help/en_US/rulenode/tbel/create_alarm_node_script_fn.md
  ui-ngx/src/assets/help/en_US/rulenode/tbel/filter_node_script_fn.md
  ui-ngx/src/assets/help/en_US/rulenode/tbel/generator_node_script_fn.md
  ui-ngx/src/assets/help/en_US/rulenode/tbel/log_node_script_fn.md
  ui-ngx/src/assets/help/en_US/rulenode/tbel/switch_node_script_fn.md
  ui-ngx/src/assets/help/en_US/rulenode/tbel/transformation_node_script_fn.md
  ui-ngx/src/assets/help/en_US/rulenode/transformation_node_script_fn.md
  ui-ngx/src/assets/help/en_US/widget/action/mobile_process_qr_code_fn.md
  ui-ngx/src/assets/help/en_US/widget/editor/examples/rpc_widget.md
  ui-ngx/src/assets/help/en_US/widget/editor/widget_js_fn.md
  ui-ngx/src/assets/help/en_US/widget/editor/widget_js_subscription_object.md
  ui-ngx/src/assets/help/en_US/widget/lib/markdown/markdown_text_fn.md
  ui-ngx/src/assets/help/en_US/widget/lib/qrcode/qrcode_text_fn.md
Labels: enhancement, UI

#10838 [QR-code widget] - Styles improvements, added label limit
  application/src/main/data/json/system/widget_types/mobile_app_qr_code.json
  application/src/main/java/org/thingsboard/server/controller/MobileApplicationController.java
  common/data/src/main/java/org/thingsboard/server/common/data/mobile/BadgeStyle.java
  common/data/src/main/java/org/thingsboard/server/common/data/mobile/QRCodeConfig.java
  dao/src/main/java/org/thingsboard/server/dao/mobile/BaseMobileAppSettingsService.java
  ui-ngx/src/app/core/auth/auth.actions.ts
  ui-ngx/src/app/core/auth/auth.reducer.ts
  ui-ngx/src/app/modules/home/components/widget/config/basic/basic-widget-config.module.ts
  ui-ngx/src/app/modules/home/components/widget/config/basic/cards/mobile-app-qr-code-basic-config.component.html
  ui-ngx/src/app/modules/home/components/widget/config/basic/cards/mobile-app-qr-code-basic-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/cards/mobile-app-qr-code-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/mobile-app-qrcode-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/mobile-app-qrcode-widget.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/mobile-app-qrcode-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/mobile-app-qr-code-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/mobile-app-qr-code-widget-settings.component.ts
  ui-ngx/src/app/modules/home/pages/admin/mobile-app-settings.component.html
  ui-ngx/src/app/modules/home/pages/admin/mobile-app-settings.component.ts
  ui-ngx/src/app/modules/home/pages/home-links/home-links-routing.module.ts
  ui-ngx/src/app/shared/models/mobile-app.models.ts
  ui-ngx/src/assets/android-ios-stores-badges/android_store_en_black_badge.svg
  ui-ngx/src/assets/android-ios-stores-badges/ios_store_en_black_badge.svg
  ui-ngx/src/assets/android-ios-stores-badges/ios_store_en_white_badge.svg
  ui-ngx/src/assets/dashboard/sys_admin_home_page.json
  ui-ngx/src/assets/dashboard/tenant_admin_home_page.json
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI, Ignore for release

#10855 Fixed hotkey event for search field on rule chain page
  ui-ngx/src/app/modules/home/pages/rulechain/rulechain-page.component.ts
Labels: bug, UI

#10863 Update translate from timeseries/time-series to time series
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI

#10885 Fixed cell click action not multiple
  application/src/main/data/json/system/widget_types/alarms_table.json
  application/src/main/data/json/system/widget_types/asset_admin_table.json
  application/src/main/data/json/system/widget_types/device_admin_table.json
  application/src/main/data/json/system/widget_types/entities_table.json
Labels: bug, UI, Ignore for release

#10893 Fixed popover close button hidden under dashboard toolbar
  ui-ngx/src/app/shared/components/popover.component.scss
Labels: bug, UI

#10894 Fixed Color picker centering color copy for dialog
  ui-ngx/src/app/shared/components/color-picker/color-picker.component.scss
Labels: bug, UI

#10898 [Gateway dashboard]: Updated image for gateway dashboard
  application/src/main/data/json/tenant/dashboards/gateways.json
Labels: enhancement, UI, Ignore for release

#10907 [TimeWindow] - For Realtime alarm data query
  ui-ngx/src/app/core/api/alarm-data-subscription.ts
Labels: Ignore for release

#10897 fixed device profile proto deserialization
  common/proto/src/main/java/org/thingsboard/server/common/util/ProtoUtils.java
Labels: Ignore for release
