Repository thingsboard/thingsboard, pull requests merged in 2024-01, with the labels that each got.

#9926 Fix isolated queues creation
  application/src/main/java/org/thingsboard/server/service/security/auth/oauth2/AbstractOAuth2ClientMapper.java
Labels: Ignore for release

#9915 TbAwsSqsProducerTemplate fix
  application/src/main/resources/thingsboard.yml
  common/queue/src/main/java/org/thingsboard/server/queue/sqs/TbAwsSqsAdmin.java
  common/queue/src/main/java/org/thingsboard/server/queue/sqs/TbAwsSqsProducerTemplate.java
  common/queue/src/main/java/org/thingsboard/server/queue/sqs/TbAwsSqsSettings.java
  msa/vc-executor/src/main/resources/tb-vc-executor.yml
  transport/coap/src/main/resources/tb-coap-transport.yml
  transport/http/src/main/resources/tb-http-transport.yml
  transport/lwm2m/src/main/resources/tb-lwm2m-transport.yml
  transport/mqtt/src/main/resources/tb-mqtt-transport.yml
  transport/snmp/src/main/resources/tb-snmp-transport.yml
Labels: Bug

#9928 Fix invalid entities limit notification
  application/src/main/java/org/thingsboard/server/service/notification/rule/trigger/EntitiesLimitTriggerProcessor.java
Labels: Ignore for release

#9924 Optimize rule nodes ids search in the upgrade process
  application/src/main/data/upgrade/3.6.2/schema_update.sql
  application/src/main/java/org/thingsboard/server/install/ThingsboardInstallService.java
  application/src/main/java/org/thingsboard/server/service/install/SqlDatabaseUpgradeService.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/rule/RuleChainService.java
  dao/src/main/java/org/thingsboard/server/dao/service/Validator.java
  dao/src/main/java/org/thingsboard/server/dao/sql/rule/RuleNodeRepository.java
  dao/src/main/resources/sql/schema-entities-idx.sql
Labels: enhancement, Build Scripts

#9941 Fixed validation JSON form in custom widgets
  ui-ngx/src/app/modules/home/components/widget/config/widget-settings.component.ts
Labels: Bug, UI

#9828 moved queueName from rule-node config to rule-node
  application/src/main/data/upgrade/3.6.2/schema_update.sql
  application/src/main/java/org/thingsboard/server/actors/ruleChain/DefaultTbContext.java
  application/src/main/java/org/thingsboard/server/service/component/AnnotationComponentDiscoveryService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/RuleChainImportService.java
  application/src/main/java/org/thingsboard/server/utils/TbNodeUpgradeUtils.java
  common/data/src/main/java/org/thingsboard/server/common/data/DataConstants.java
  common/data/src/main/java/org/thingsboard/server/common/data/plugin/ComponentDescriptor.java
  common/data/src/main/java/org/thingsboard/server/common/data/rule/RuleNode.java
  dao/src/main/java/org/thingsboard/server/dao/model/ModelConstants.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/ComponentDescriptorEntity.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/RuleNodeEntity.java
  dao/src/main/java/org/thingsboard/server/dao/sql/component/AbstractComponentDescriptorInsertRepository.java
  dao/src/main/java/org/thingsboard/server/dao/sql/component/SqlComponentDescriptorInsertRepository.java
  dao/src/main/resources/sql/schema-entities.sql
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ContainerTestSuite.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/TestProperties.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/TestRestClient.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/rule/node/MqttNodeTest.java
  msa/black-box-tests/src/test/resources/MqttRuleNodeTestMetadata.json
  msa/black-box-tests/src/test/resources/docker-compose.mosquitto.yml
  msa/black-box-tests/src/test/resources/mosquitto/mosquitto.conf
  rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/RuleNode.java
  rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/TbContext.java
  rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/util/TbNodeUtils.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/debug/TbMsgGeneratorNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/debug/TbMsgGeneratorNodeConfiguration.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/deduplication/TbMsgDeduplicationNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/deduplication/TbMsgDeduplicationNodeConfiguration.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/flow/TbCheckpointNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/flow/TbCheckpointNodeConfiguration.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/AbstractRuleNodeUpgradeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/debug/TbMsgGeneratorNodeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/flow/TbCheckpointNodeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/telemetry/TbMsgAttributesNodeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/transform/TbMsgDeduplicationNodeTest.java
Labels: enhancement

#9957 set default device conncectivity params from yml during install
  application/src/main/java/org/thingsboard/server/service/install/DefaultSystemDataLoaderService.java
  dao/src/main/java/org/thingsboard/server/dao/device/DeviceConnectivityConfiguration.java
Labels: enhancement, Core

#9963 Fix asset relations deletion
  dao/src/main/java/org/thingsboard/server/dao/asset/BaseAssetService.java
  dao/src/test/java/org/thingsboard/server/dao/service/AssetServiceTest.java
Labels: Bug, Core

#9965 Added missing WidgetTypeController & WidgetsBundleController APIs to RestClient
  application/src/main/java/org/thingsboard/server/controller/WidgetTypeController.java
  rest-client/src/main/java/org/thingsboard/rest/client/RestClient.java
Labels: enhancement, RestClient

#9980 Activity managers for integrations and transports: configurable activity reporting granularity and strategies
  application/src/main/java/org/thingsboard/server/service/state/DefaultDeviceStateService.java
  application/src/main/resources/thingsboard.yml
  common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/client/DefaultCoapClientContext.java
  common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttTransportHandler.java
  common/transport/snmp/src/main/java/org/thingsboard/server/transport/snmp/service/SnmpTransportService.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/TransportService.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/activity/AbstractActivityManager.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/activity/ActivityManager.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/activity/ActivityReportCallback.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/activity/ActivityState.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/activity/strategy/ActivityStrategy.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/activity/strategy/ActivityStrategyType.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/activity/strategy/AllEventsActivityStrategy.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/activity/strategy/FirstAndLastEventActivityStrategy.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/activity/strategy/FirstEventActivityStrategy.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/activity/strategy/LastEventActivityStrategy.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/service/DefaultTransportService.java
  common/transport/transport-api/src/test/java/org/thingsboard/server/common/transport/activity/strategy/ActivityStrategyTypeTest.java
  common/transport/transport-api/src/test/java/org/thingsboard/server/common/transport/activity/strategy/AllEventsActivityStrategyTest.java
  common/transport/transport-api/src/test/java/org/thingsboard/server/common/transport/activity/strategy/FirstAndLastEventActivityStrategyTest.java
  common/transport/transport-api/src/test/java/org/thingsboard/server/common/transport/activity/strategy/FirstEventActivityStrategyTest.java
  common/transport/transport-api/src/test/java/org/thingsboard/server/common/transport/activity/strategy/LastEventActivityStrategyTest.java
  common/transport/transport-api/src/test/java/org/thingsboard/server/common/transport/service/TransportActivityManagerTest.java
Labels: Core

#9987 Last activity time granularity
  application/src/main/java/org/thingsboard/server/service/state/DefaultDeviceStateService.java
  application/src/main/resources/thingsboard.yml
  common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/client/DefaultCoapClientContext.java
  common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttTransportHandler.java
  common/transport/snmp/src/main/java/org/thingsboard/server/transport/snmp/service/SnmpTransportService.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/TransportService.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/activity/AbstractActivityManager.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/activity/ActivityManager.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/activity/ActivityReportCallback.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/activity/ActivityState.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/activity/strategy/ActivityStrategy.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/activity/strategy/ActivityStrategyType.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/activity/strategy/AllEventsActivityStrategy.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/activity/strategy/FirstAndLastEventActivityStrategy.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/activity/strategy/FirstEventActivityStrategy.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/activity/strategy/LastEventActivityStrategy.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/service/DefaultTransportService.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/service/TransportActivityManager.java
  common/transport/transport-api/src/test/java/org/thingsboard/server/common/transport/activity/strategy/ActivityStrategyTypeTest.java
  common/transport/transport-api/src/test/java/org/thingsboard/server/common/transport/activity/strategy/AllEventsActivityStrategyTest.java
  common/transport/transport-api/src/test/java/org/thingsboard/server/common/transport/activity/strategy/FirstAndLastEventActivityStrategyTest.java
  common/transport/transport-api/src/test/java/org/thingsboard/server/common/transport/activity/strategy/FirstEventActivityStrategyTest.java
  common/transport/transport-api/src/test/java/org/thingsboard/server/common/transport/activity/strategy/LastEventActivityStrategyTest.java
  common/transport/transport-api/src/test/java/org/thingsboard/server/common/transport/service/TransportActivityManagerTest.java
Labels: Core

#9992 fixed unnecessary device actor init on rule-engine
  application/src/main/java/org/thingsboard/server/actors/tenant/TenantActor.java
  application/src/test/java/org/thingsboard/server/actors/tenant/TenantActorTest.java
Labels: Bug

#10008 Synchronized DEFAULT_INACTIVITY_TIMEOUT and TB_TRANSPORT_SESSIONS_INACTIVITY_TIMEOUT default env values
  application/src/main/resources/thingsboard.yml
  transport/coap/src/main/resources/tb-coap-transport.yml
  transport/http/src/main/resources/tb-http-transport.yml
  transport/lwm2m/src/main/resources/tb-lwm2m-transport.yml
  transport/mqtt/src/main/resources/tb-mqtt-transport.yml
  transport/snmp/src/main/resources/tb-snmp-transport.yml
Labels: Docs enhancement

#10016 Fixed not updated image preview when updated image
  ui-ngx/src/app/shared/components/image/image-dialog.component.ts
Labels: Bug, UI

#9869 Fixed stateId autocomplete and added improvements for widget action dialog
  ui-ngx/src/app/modules/home/components/widget/action/widget-action-dialog.component.html
  ui-ngx/src/app/modules/home/components/widget/action/widget-action-dialog.component.ts
Labels: Bug, UI

#9904 Update Ukrainian translation
  ui-ngx/src/assets/locale/locale.constant-en_US.json
  ui-ngx/src/assets/locale/locale.constant-uk_UA.json
Labels: UI

#9914 Tenant profile dialog refactoring translate
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI

#10055 Extended error handling from ThingsboardException to Exception
  application/src/main/java/org/thingsboard/server/service/mail/DefaultMailService.java
Labels: enhancement

#9935 Added getAssetProfileNames and getDeviceProfileNames APIs
  ui-ngx/src/app/core/http/asset-profile.service.ts
  ui-ngx/src/app/core/http/device-profile.service.ts
  ui-ngx/src/app/core/http/entity.service.ts
  ui-ngx/src/app/shared/components/entity/entity-subtype-autocomplete.component.ts
  ui-ngx/src/app/shared/components/entity/entity-subtype-list.component.ts
  ui-ngx/src/app/shared/components/entity/entity-subtype-select.component.ts
Labels: enhancement, UI

#9936 Fixed sysadmin general settings for Firefox
  ui-ngx/src/app/modules/home/pages/admin/general-settings.component.html
Labels: Bug, UI

#9948 Fixed not properly displaying of copy-code button
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/device-gateway-command.component.scss
  ui-ngx/src/app/modules/home/pages/device/device-check-connectivity-dialog.component.scss
Labels: Bug, UI

#9991 Disabled originartor column details page links in alarms table for entities that can not have alarm
  ui-ngx/src/app/core/utils.ts
  ui-ngx/src/app/modules/home/components/entity/entities-table.component.html
Labels: Bug, UI

#10012 Fixed default column visibility for timeseries table widget
  ui-ngx/src/app/modules/home/components/widget/lib/timeseries-table-widget.component.ts
Labels: Bug, UI

#10014 Fixed console error on deleting data key
  ui-ngx/src/app/modules/home/components/widget/config/basic/common/data-keys-panel.component.ts
Labels: Bug, UI

#10059 Update rule core config
  rule-engine/rule-engine-components/src/main/resources/public/static/rulenode/rulenode-core-config.js
Labels: UI, Rule Engine, Ignore for release

#10075 fixed stack overflow error
  application/src/main/java/org/thingsboard/server/service/sync/vc/DefaultEntitiesVersionControlService.java
  application/src/main/java/org/thingsboard/server/service/telemetry/DefaultTelemetrySubscriptionService.java
  dao/src/main/java/org/thingsboard/server/dao/attributes/CachedAttributesService.java
Labels: Ignore for release

#10093 Error handling for PartitionChangeEvent listeners
  application/src/main/java/org/thingsboard/server/service/subscription/DefaultSubscriptionManagerService.java
  common/queue/src/main/java/org/thingsboard/server/queue/discovery/HashPartitionService.java
  common/queue/src/main/java/org/thingsboard/server/queue/discovery/TbApplicationEventListener.java
  common/version-control/src/main/java/org/thingsboard/server/service/sync/vc/DefaultClusterVersionControlService.java
Labels: bug

#10083 Performance improvements for entities saving
  application/src/main/java/org/thingsboard/server/controller/BaseController.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/audit/AuditLogService.java
  dao/src/main/java/org/thingsboard/server/dao/alarm/AlarmCommentDao.java
  dao/src/main/java/org/thingsboard/server/dao/alarm/BaseAlarmCommentService.java
  dao/src/main/java/org/thingsboard/server/dao/audit/AuditLogDao.java
  dao/src/main/java/org/thingsboard/server/dao/audit/AuditLogServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/audit/DummyAuditLogServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/audit/sink/ElasticsearchAuditLogSink.java
  dao/src/main/java/org/thingsboard/server/dao/sql/JpaAbstractDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/JpaPartitionedAbstractDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/alarm/JpaAlarmCommentDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/audit/JpaAuditLogDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/edge/JpaBaseEdgeEventDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/notification/JpaNotificationDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/ota/JpaOtaPackageInfoDao.java
  dao/src/test/java/org/thingsboard/server/dao/sql/alarm/JpaAlarmCommentDaoTest.java
Labels: Core
