Repository thingsboard/thingsboard, pull requests merged in 2024-11, with the labels that each got.

#11985 Switch to angular esbuild
  ui-ngx/angular.json
  ui-ngx/esbuild/tb-esbuild-plugins.ts
  ui-ngx/extra-webpack.config.js
  ui-ngx/package.json
  ui-ngx/patches/@angular+build+18.2.10.patch
  ui-ngx/patches/jquery.terminal+2.43.1.patch
  ui-ngx/src/app/core/utils.ts
  ui-ngx/src/app/modules/common/modules-map.ts
  ui-ngx/src/app/modules/home/components/vc/entity-version-diff.component.ts
  ui-ngx/src/app/modules/home/components/widget/dialog/custom-dialog.component.ts
  ui-ngx/src/app/modules/home/components/widget/dynamic-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/mobile-app-qrcode-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/qrcode-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/custom-action.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/map/map-provider-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/map/map-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/map/trip-animation-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/widget-component.service.ts
  ui-ngx/src/app/modules/home/components/widget/widget.component.ts
  ui-ngx/src/app/modules/home/models/widget-component.models.ts
  ui-ngx/src/app/modules/home/pages/security/authentication-dialog/backup-code-auth-dialog.component.ts
  ui-ngx/src/app/modules/home/pages/security/authentication-dialog/totp-auth-dialog.component.ts
  ui-ngx/src/app/shared/components/json-form/json-form.component.ts
  ui-ngx/src/app/shared/components/json-form/react/json-form-ace-editor.tsx
  ui-ngx/src/app/shared/components/json-form/react/json-form-schema-form.tsx
  ui-ngx/src/app/shared/components/page.component.ts
  ui-ngx/src/app/shared/decorators/public-api.ts
  ui-ngx/src/app/shared/decorators/tb-inject.ts
  ui-ngx/src/app/shared/models/ace/ace.models.ts
  ui-ngx/src/app/shared/models/beautify.models.ts
  ui-ngx/src/main.ts
  ui-ngx/src/styles.scss
  ui-ngx/src/tsconfig.app.json
  ui-ngx/src/typings/rawloader.typings.d.ts
  ui-ngx/tsconfig.json
  ui-ngx/yarn.lock
Labels: UI, Major UI

#11756 Disabled "Named entity expected" for html editor
  ui-ngx/src/app/shared/components/html.component.ts
Labels: bug, UI

#11781 Microsoft Teams notification preview improvements
  ui-ngx/src/app/modules/home/pages/notification/sent/sent-notification-dialog.component.html
  ui-ngx/src/app/modules/home/pages/notification/sent/sent-notification-dialog.component.scss
  ui-ngx/src/app/shared/models/notification.models.ts
Labels: bug, UI

#11848 Added md help files for socket basic config implementation
  ui-ngx/src/assets/help/en_US/widget/lib/gateway/address-filter_fn.md
  ui-ngx/src/assets/help/en_US/widget/lib/gateway/attribute-name-expression_fn.md
  ui-ngx/src/assets/help/en_US/widget/lib/gateway/byte_fn.md
  ui-ngx/src/assets/help/en_US/widget/lib/gateway/request-expression_fn.md
Labels: UI, Ignore for release

#11881 SCADA broken and extra long pipe
  application/src/main/data/json/system/scada_symbols/extra-long-horizontal-pipe.svg
  application/src/main/data/json/system/scada_symbols/extra-long-vertical-pipe.svg
  application/src/main/data/json/system/scada_symbols/horizontal-broken-pipe.svg
  application/src/main/data/json/system/scada_symbols/long-horizontal-broken-pipe.svg
  application/src/main/data/json/system/scada_symbols/long-vertical-broken-pipe.svg
  application/src/main/data/json/system/scada_symbols/vertical-broken-pipe.svg
  application/src/main/data/json/system/widget_bundles/scada_fluid_system.json
Labels: UI, feature

#11911 SCADA conicals and small cylindrical tank
  application/src/main/data/json/system/scada_symbols/conical-tank.svg
  application/src/main/data/json/system/scada_symbols/large-conical-tank.svg
  application/src/main/data/json/system/scada_symbols/small-cylindrical-tank.svg
  application/src/main/data/json/system/widget_bundles/scada_fluid_system.json
Labels: UI, feature

#11912 Fixed scale property for spherical and horizontal tanks
  application/src/main/data/json/system/scada_symbols/horizontal-tank.svg
  application/src/main/data/json/system/scada_symbols/small-spherical-tank.svg
  application/src/main/data/json/system/scada_symbols/spherical-tank.svg
  application/src/main/data/json/system/scada_symbols/stand-horizontal-tank.svg
Labels: UI, feature

#11915 Fixed dialog deletion title of entity with long name
  ui-ngx/src/app/shared/components/dialog/confirm-dialog.component.html
Labels: enhancement, UI

#11956 Fixed dialog container content scrolling after Angular update
  ui-ngx/src/styles.scss
Labels: bug, UI, Ignore for release

#11975 Fixed entity select
  ui-ngx/src/app/shared/components/entity/entity-select.component.ts
Labels: bug, UI

#11976 Added trim spaces for alarm comments
  ui-ngx/src/app/modules/home/components/alarm/alarm-comment.component.html
  ui-ngx/src/app/modules/home/components/alarm/alarm-comment.component.ts
Labels: bug, UI

#11984 Added launch command translation for Gateway
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: bug, UI, Ignore for release

#11818 Update locale.constant-zh_CN.json
  ui-ngx/src/assets/locale/locale.constant-zh_CN.json
Labels: UI, Ignore for release

#11813 Update locale.constant-zh_CN.json
  ui-ngx/src/assets/locale/locale.constant-zh_CN.json
Labels: UI

#11986 Changed gateway icon
  ui-ngx/src/app/core/services/menu.models.ts
  ui-ngx/src/app/shared/models/icon.models.ts
  ui-ngx/src/assets/metadata/material-icons.json
Labels: enhancement, UI, Ignore for release

#11990 Updated to latest Angular version and clear dependencies
  ui-ngx/package.json
  ui-ngx/patches/@angular+build+18.2.11.patch
  ui-ngx/patches/@angular+core+18.2.10.patch
  ui-ngx/yarn.lock
Labels: UI, Ignore for release

#11982 Queue providers deprecation
  application/src/main/java/org/thingsboard/server/service/update/DeprecationService.java
  application/src/main/resources/thingsboard.yml
  dao/src/main/java/org/thingsboard/server/dao/notification/DefaultNotifications.java
  msa/vc-executor/src/main/resources/tb-vc-executor.yml
  transport/coap/src/main/resources/tb-coap-transport.yml
  transport/http/src/main/resources/tb-http-transport.yml
  transport/lwm2m/src/main/resources/tb-lwm2m-transport.yml
  transport/mqtt/src/main/resources/tb-mqtt-transport.yml
  transport/snmp/src/main/resources/tb-snmp-transport.yml
Labels: Ignore for release

#11913 used enqueue for input node to avoid latency issue
  application/src/main/java/org/thingsboard/server/actors/ruleChain/DefaultTbContext.java
  application/src/test/java/org/thingsboard/server/rules/flow/AbstractRuleEngineFlowIntegrationTest.java
Labels: bug

#11898 Fixed remote shell request spam on exit
  application/src/main/data/json/system/widget_types/rpc_remote_shell.json
Labels: bug, UI

#11981 Updated autocomplete for AssetService
  ui-ngx/src/app/shared/models/ace/service-completion.models.ts
Labels: enhancement, UI

#11992 Fix of the action bug
  ui-ngx/src/app/modules/home/components/widget/widget-container.component.html
Labels: bug, UI

#12007 Added rulechains description column
  ui-ngx/src/app/modules/home/pages/rulechain/rulechains-table-config.resolver.ts
Labels: enhancement, UI

#12010 Added fallback for non-entity conflicts
  ui-ngx/src/app/core/interceptors/entity-conflict.interceptor.ts
  ui-ngx/src/app/shared/components/dialog/entity-conflict-dialog/entity-conflict-dialog.component.ts
  ui-ngx/src/app/shared/import-export/import-export.service.ts
  ui-ngx/src/app/shared/models/entity.models.ts
Labels: bug, UI

#12011 Updated link styles after updated Angular
  ui-ngx/src/styles.scss
Labels: bug, UI, Ignore for release

#11952 Adding outline appearance to the country autocomplete
  ui-ngx/src/app/shared/components/country-autocomplete.component.html
  ui-ngx/src/app/shared/components/country-autocomplete.component.ts
Labels: UI, Ignore for release

#11996 Fixed RPC debug terminal widget force focus
  ui-ngx/src/app/modules/home/components/widget/widget-container.component.ts
Labels: bug, UI

#12029 Fix update of OAuth details when switching between clients in the OAuth 2.0 clients table
  ui-ngx/src/app/modules/home/pages/admin/oauth2/clients/client.component.ts
Labels: bug, UI

#12031 Flex Layout migration fixes
  ui-ngx/src/app/modules/home/components/alarm/alarm-filter-config.component.html
  ui-ngx/src/app/modules/home/components/filter/filter-predicate-value.component.html
  ui-ngx/src/app/modules/home/pages/customer/customer.component.html
Labels: bug, UI, Ignore for release

#12017 fixed flaky tests
  dao/src/test/java/org/thingsboard/server/dao/service/timeseries/sql/LatestTimeseriesPerformanceTest.java
Labels: Ignore for release

#12065 Updated rulenode-core-config.js
  rule-engine/rule-engine-components/src/main/resources/public/static/rulenode/rulenode-core-config.js
Labels: UI, Ignore for release

#12033 Fixed сhart widget not apply hidden datakey by default
  ui-ngx/src/app/modules/home/components/widget/lib/chart/time-series-chart-widget.component.ts
Labels: bug, UI

#12062 System notification type; improvements for notification center
  application/src/main/java/org/thingsboard/server/controller/BaseController.java
  application/src/main/java/org/thingsboard/server/controller/NotificationController.java
  application/src/main/java/org/thingsboard/server/controller/NotificationTargetController.java
  application/src/main/java/org/thingsboard/server/service/notification/DefaultNotificationCenter.java
  application/src/test/java/org/thingsboard/server/controller/AbstractWebTest.java
  application/src/test/java/org/thingsboard/server/edge/NotificationEdgeTest.java
  application/src/test/java/org/thingsboard/server/service/notification/AbstractNotificationApiTest.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/notification/NotificationSettingsService.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/notification/NotificationTemplateService.java
  common/data/src/main/java/org/thingsboard/server/common/data/notification/NotificationType.java
  dao/src/main/java/org/thingsboard/server/dao/notification/DefaultNotificationSettingsService.java
  dao/src/main/java/org/thingsboard/server/dao/notification/DefaultNotificationTargetService.java
  dao/src/main/java/org/thingsboard/server/dao/notification/DefaultNotificationTemplateService.java
  dao/src/main/java/org/thingsboard/server/dao/notification/NotificationTemplateDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/notification/JpaNotificationTemplateDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/notification/NotificationTemplateRepository.java
  rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/NotificationCenter.java
Labels: Ignore for release

#12074 Fixed 'Update location timeseries' widget
  application/src/main/data/json/system/widget_types/update_location_timeseries.json
Labels: bug, UI, Ignore for release

#12075 Fixed Scroll and pagination buttons are absent, SCADA/Image table
  ui-ngx/src/app/shared/components/image/image-gallery.component.html
Labels: bug, UI, Ignore for release

#12077 Update document 'lang' attribute based on user language preference
  ui-ngx/src/app/core/settings/settings.effects.ts
  ui-ngx/src/app/core/settings/settings.utils.ts
Labels: enhancement, UI

#12078 Fixed high-perfomance SCADA symbols
  application/src/main/data/json/system/scada_symbols/dynamic-horizontal-scale-hp.svg
  application/src/main/data/json/system/scada_symbols/dynamic-vertical-scale-hp.svg
  application/src/main/data/json/system/scada_symbols/filter-hp.svg
  application/src/main/data/json/system/scada_symbols/heat-pump-hp.svg
  application/src/main/data/json/system/scada_symbols/horizontal-tank-hp.svg
  application/src/main/data/json/system/scada_symbols/horizontal-valve-hp.svg
  application/src/main/data/json/system/scada_symbols/long-horizontal-connector-hp.svg
  application/src/main/data/json/system/scada_symbols/pool-hp.svg
  application/src/main/data/json/system/scada_symbols/sand-filter-hp.svg
  application/src/main/data/json/system/scada_symbols/sand-filter.svg
  application/src/main/data/json/system/scada_symbols/short-vertical-tank-hp.svg
  application/src/main/data/json/system/scada_symbols/simple-horizontal-scale-hp.svg
  application/src/main/data/json/system/scada_symbols/vertical-scale-hp.svg
  application/src/main/data/json/system/scada_symbols/vertical-tank-hp.svg
  application/src/main/data/json/system/scada_symbols/vertical-valve-hp.svg
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: bug, UI, Ignore for release

#12080 Fixed broken link and add link for rule node
  ui-ngx/src/app/shared/models/constants.ts
  ui-ngx/src/app/shared/models/rule-node.models.ts
Labels: bug, enhancement, UI

#12089 Fixed close mobile bundle dialog without add/edit
  ui-ngx/src/app/modules/home/pages/mobile/bundes/mobile-bundle-table-config.resolve.ts
Labels: bug, UI, Ignore for release

#12084 Entity Data Query optimisation - entityFilter.isFetchLastLevelOnly() to hit index and avoid sequential scan
  dao/src/main/java/org/thingsboard/server/dao/sql/query/DefaultEntityQueryRepository.java
Labels: Major Core

#12090 fixed flaky tests
  dao/src/test/java/org/thingsboard/server/dao/service/timeseries/sql/LatestTimeseriesPerformanceTest.java
Labels: Ignore for release

#12083 Added md file for Gateway Report strategy
  ui-ngx/src/assets/help/en_US/widget/lib/gateway/address-filter_fn.md
  ui-ngx/src/assets/help/en_US/widget/lib/gateway/report-strategy_fn.md
Labels: enhancement, UI, Ignore for release

#12093 Add new behavior "get alarm status"
  application/src/main/java/org/thingsboard/server/service/subscription/TbAlarmStatusSubCtx.java
  application/src/main/java/org/thingsboard/server/service/subscription/TbAlarmStatusSubscription.java
  application/src/main/java/org/thingsboard/server/service/ws/WsCommandsWrapper.java
  ui-ngx/src/app/core/ws/telemetry-websocket.service.ts
  ui-ngx/src/app/modules/home/components/widget/lib/action/action-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/button/action-button-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/button/command-button-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/button/toggle-button-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/indicator/status-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/rpc/power-button-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/rpc/single-switch-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/rpc/slider-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/scada/scada-symbol.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/get-value-action-settings-panel.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/get-value-action-settings-panel.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/get-value-action-settings.component.ts
  ui-ngx/src/app/shared/models/action-widget-settings.models.ts
  ui-ngx/src/app/shared/models/telemetry/telemetry.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI, feature

#12099 Synchronize languages naming between CE and PE versions
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI

#12100 Fixed show color in signal strength widget when low signal
  ui-ngx/src/app/modules/home/components/widget/lib/indicator/signal-strength-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/indicator/signal-strength-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/indicator/signal-strength-widget-settings.component.ts
Labels: bug, UI

#12101 Fixed audit log and event content dialogs sizing
  ui-ngx/src/app/modules/home/components/audit-log/audit-log-details-dialog.component.ts
  ui-ngx/src/app/modules/home/components/event/event-content-dialog.component.ts
Labels: bug, UI, Ignore for release

#11980 Fixed sizing for codeblocks
  ui-ngx/src/app/modules/home/components/widget/lib/home-page/getting-started-widget.component.scss
  ui-ngx/src/app/shared/components/markdown.component.scss
Labels: bug, UI, WIP, Ignore for release

#12105 Fixed add small widget in mobile layout dashboard
  ui-ngx/src/app/modules/home/models/dashboard-component.models.ts
Labels: bug, UI

#12119 Fixed oauth2 authorization for apps of version 1.3.0 and less
  application/src/main/java/org/thingsboard/server/config/CustomOAuth2AuthorizationRequestResolver.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/oauth2/OAuth2ClientService.java
  dao/src/main/java/org/thingsboard/server/dao/oauth2/OAuth2ClientDao.java
  dao/src/main/java/org/thingsboard/server/dao/oauth2/OAuth2ClientServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/sql/oauth2/JpaOAuth2ClientDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/oauth2/OAuth2ClientRepository.java
Labels: bug, Ignore for release

#12132 Updated mobile app deletion logic
  application/src/main/data/upgrade/3.8.1/schema_update.sql
  application/src/main/java/org/thingsboard/server/controller/MobileAppController.java
  common/data/src/main/java/org/thingsboard/server/common/data/mobile/LoginMobileInfo.java
  common/data/src/main/java/org/thingsboard/server/common/data/mobile/UserMobileInfo.java
  dao/src/main/java/org/thingsboard/server/dao/mobile/MobileAppServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/sql/oauth2/JpaOAuth2ClientDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/oauth2/OAuth2ClientRepository.java
  dao/src/main/resources/sql/schema-entities.sql
Labels: enhancement, Ignore for release

#12149 Increased TBEL script compilation timeout
  common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/DefaultTbelInvokeService.java
Labels: Rule Engine

#12120 Fixed incorrect show mail notification preview
  ui-ngx/src/app/modules/home/pages/notification/sent/sent-notification-dialog.component.html
  ui-ngx/src/app/modules/home/pages/notification/sent/sent-notification-dialog.component.scss
  ui-ngx/src/app/modules/home/pages/notification/sent/sent-notification-dialog.componet.ts
Labels: bug, UI

#12121 Fixed wrong example in TBEL round number
  ui-ngx/src/assets/help/en_US/rulenode/tbel/generator_node_script_fn.md
Labels: bug, UI, Tbel

#12123 Add support custom translate for entity description columns
  ui-ngx/src/app/modules/home/pages/asset-profile/asset-profiles-table-config.resolver.ts
  ui-ngx/src/app/modules/home/pages/device-profile/device-profiles-table-config.resolver.ts
  ui-ngx/src/app/modules/home/pages/notification/recipient/recipient-table-config.resolver.ts
  ui-ngx/src/app/modules/home/pages/notification/rule/rule-table-config.resolver.ts
  ui-ngx/src/app/modules/home/pages/rulechain/rulechains-table-config.resolver.ts
  ui-ngx/src/app/modules/home/pages/tenant-profile/tenant-profiles-table-config.resolver.ts
Labels: enhancement, UI

#12124 Fixed highlighting when disabled toggle-selected
  ui-ngx/src/app/modules/home/pages/admin/mail-server.component.html
  ui-ngx/src/app/modules/home/pages/admin/mail-server.component.scss
  ui-ngx/src/app/modules/home/pages/notification/inbox/inbox-table-header.component.html
  ui-ngx/src/app/modules/home/pages/notification/inbox/inbox-table-header.component.scss
  ui-ngx/src/app/modules/home/pages/notification/inbox/inbox-table-header.component.ts
  ui-ngx/src/app/modules/home/pages/notification/rule/rule-notification-dialog.component.html
  ui-ngx/src/app/modules/home/pages/notification/rule/rule-notification-dialog.component.scss
  ui-ngx/src/app/shared/components/script-lang.component.scss
  ui-ngx/src/app/shared/components/toggle-header.component.scss
Labels: bug, UI, Ignore for release

#12127 Show SCADA symbols svg in preview mode
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-widget-select.component.html
Labels: enhancement, UI

#12139 Fixed and imporvements mobile center
  ui-ngx/src/app/modules/home/pages/mobile/applications/mobile-app-table-config.resolver.ts
  ui-ngx/src/app/modules/home/pages/mobile/applications/mobile-app.component.html
  ui-ngx/src/app/modules/home/pages/mobile/applications/mobile-app.component.ts
  ui-ngx/src/app/modules/home/pages/mobile/applications/remove-app-dialog.component.html
  ui-ngx/src/app/modules/home/pages/mobile/applications/remove-app-dialog.component.ts
  ui-ngx/src/app/modules/home/pages/mobile/bundes/layout/custom-mobile-page.component.ts
  ui-ngx/src/app/modules/home/pages/mobile/bundes/mobile-app-configuration-dialog.component.html
  ui-ngx/src/app/modules/home/pages/mobile/bundes/mobile-app-configuration-dialog.component.scss
  ui-ngx/src/app/modules/home/pages/mobile/bundes/mobile-app-configuration-dialog.component.ts
  ui-ngx/src/app/modules/home/pages/mobile/bundes/mobile-bundle-table-config.resolve.ts
  ui-ngx/src/app/modules/home/pages/mobile/common/editor-panel.component.html
  ui-ngx/src/app/modules/home/pages/mobile/common/editor-panel.component.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: bug, enhancement, UI, Ignore for release

#12146 Fixed "no signal" logical in signal strength widgets
  ui-ngx/src/app/modules/home/components/widget/lib/indicator/signal-strength-widget.component.ts
Labels: bug, UI, Ignore for release

#12150 Add edit alias from dasource widgets
  ui-ngx/src/app/modules/home/components/alias/entity-alias-select.component.html
  ui-ngx/src/app/modules/home/components/alias/entity-alias-select.component.models.ts
  ui-ngx/src/app/modules/home/components/alias/entity-alias-select.component.ts
  ui-ngx/src/app/modules/home/components/widget/config/data-keys.component.html
  ui-ngx/src/app/modules/home/components/widget/config/data-keys.component.ts
  ui-ngx/src/app/modules/home/components/widget/widget-config.component.ts
Labels: UI, feature
