Repository thingsboard/thingsboard, pull requests merged in 2024-08, with the labels that each got.

#10646 Created AWS Lambda node
  pom.xml
  rule-engine/rule-engine-components/pom.xml
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/aws/lambda/TbAwsLambdaNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/aws/lambda/TbAwsLambdaNodeConfiguration.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/aws/lambda/TbAwsLambdaNodeTest.java
  ui-ngx/src/assets/help/en_US/rulenode/node-templatization-doc.md
Labels: Rule Engine

#11048 Async transport API requests processing
  application/src/main/java/org/thingsboard/server/service/transport/DefaultTransportApiService.java
Labels: Transport

#11181 Timeseries node: change name
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/telemetry/TbMsgTimeseriesNode.java
Labels: Ignore for release

#11340 Update rule node core config
  rule-engine/rule-engine-components/src/main/resources/public/static/rulenode/rulenode-core-config.js
Labels: UI, Rule Engine, Ignore for release

#11329 TBEL: added parseBinaryArrayToInt
  common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/TbUtils.java
  common/script/script-api/src/test/java/org/thingsboard/script/api/tbel/TbUtilsTest.java
Labels: Ignore for release

#11335 Shaded MappingJackson2XmlHttpMessageConverter class
  application/src/main/java/org/springframework/http/converter/xml/MappingJackson2XmlHttpMessageConverter.java
  application/src/test/java/org/thingsboard/server/system/RestTemplateConvertersTest.java
  pom.xml
Labels: Ignore for release

#11326 Fixed issue with opening dashboards in the mobile app on iOS
  ui-ngx/src/app/core/services/mobile.service.ts
Labels: bug, UI

#11331 Added missing audit log action type and improved audit log table handler translation
  ui-ngx/src/app/modules/home/components/audit-log/audit-log-table-config.ts
  ui-ngx/src/app/shared/models/audit-log.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: bug, UI

#11294 Removed Unexpected Tooltips from toolbar on Edit Connectors Tables
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/mapping-table/mapping-table.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-master-table/modbus-master-table.component.html
Labels: bug, UI, Ignore for release

#11297 Added Connector tables Row Action buttons descriptions tooltips
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/mapping-table/mapping-table.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-master-table/modbus-master-table.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-master-table/modbus-master-table.component.ts
Labels: enhancement, UI, Ignore for release

#11304 Fixed Modbus Slave Config Values visibility
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-values/modbus-values.component.scss
Labels: bug, UI, Ignore for release

#11307 Updated Form for Modbus RPC templates
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-data-keys-panel/modbus-data-keys-panel.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-data-keys-panel/modbus-data-keys-panel.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-rpc-parameters/modbus-rpc-parameters.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-rpc-parameters/modbus-rpc-parameters.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc-connector.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc-connector.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/widget-components.module.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI, Ignore for release

#11319 Reworked validation of Modbus tabs
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-basic-config/modbus-basic-config.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-basic-config/modbus-basic-config.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-basic-config/modbus-basic-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-master-table/modbus-master-table.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-slave-config/modbus-slave-config.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-slave-config/modbus-slave-config.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-slave-config/modbus-slave-config.component.ts
Labels: bug, UI, Ignore for release

#11321 Fixed saving validation on creating empty OPC connector
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/broker-config-control/broker-config-control.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/opc-server-config/opc-server-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-widget.models.ts
Labels: bug, UI, Ignore for release

#11347 Edge: Enhanced Credential Handling and Sync Improvements
  application/src/main/java/org/thingsboard/server/controller/EdgeController.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcService.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeSyncCursor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/BaseEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/device/DeviceEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/rule/RuleChainEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/user/UserEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/sync/DefaultEdgeRequestsService.java
  application/src/test/java/org/thingsboard/server/controller/EdgeControllerTest.java
  application/src/test/java/org/thingsboard/server/edge/AbstractEdgeTest.java
  application/src/test/java/org/thingsboard/server/edge/DeviceEdgeTest.java
  application/src/test/java/org/thingsboard/server/edge/RuleChainEdgeTest.java
  application/src/test/java/org/thingsboard/server/edge/TelemetryEdgeTest.java
  application/src/test/java/org/thingsboard/server/edge/UserEdgeTest.java
  application/src/test/java/org/thingsboard/server/service/edge/rpc/processor/device/AbstractDeviceProcessorTest.java
  common/data/src/main/java/org/thingsboard/server/common/data/edge/EdgeEventActionType.java
  common/message/src/main/java/org/thingsboard/server/common/msg/edge/FromEdgeSyncResponse.java
  common/proto/src/main/java/org/thingsboard/server/common/util/ProtoUtils.java
  common/proto/src/main/proto/queue.proto
  common/proto/src/test/java/org/thingsboard/server/common/util/ProtoUtilsTest.java
Labels: Ignore for release

#11295 Efento: new measurement types
  common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/efento/CoapEfentoTransportResource.java
  common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/efento/utils/CoapEfentoUtils.java
  common/transport/coap/src/main/proto/efento/proto_config.proto
  common/transport/coap/src/main/proto/efento/proto_device_info.proto
  common/transport/coap/src/main/proto/efento/proto_measurement_types.proto
  common/transport/coap/src/main/proto/efento/proto_measurements.proto
  common/transport/coap/src/main/proto/efento/proto_rule.proto
  common/transport/coap/src/test/java/org/thingsboard/server/transport/coap/efento/CoapEfentTransportResourceTest.java
Labels: feature, Core

#11027 PubSub node: added tests
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/gcp/pubsub/TbPubSubNode.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/gcp/pubsub/TbPubSubNodeTest.java
Labels: Ignore for release

#11037 Kafka node: added tests
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/kafka/TbKafkaNode.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/kafka/TbKafkaNodeTest.java
Labels: Ignore for release

#11093 Related device attributes node: added tests
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/metadata/TbGetAttributesNodeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/metadata/TbGetDeviceAttrNodeTest.java
Labels: Ignore for release

#10958 Mqtt and Azure iot hub nodes: added tests
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/mqtt/TbMqttNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/mqtt/azure/TbAzureIotHubNode.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/mqtt/TbMqttNodeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/mqtt/azure/TbAzureIotHubNodeTest.java
Labels: Ignore for release

#11381 Efento new types: added tests
  common/transport/coap/src/test/java/org/thingsboard/server/transport/coap/efento/CoapEfentTransportResourceTest.java
Labels: Ignore for release

#11360 Swagger: replaced text timeseries/time-series to time series
  application/src/main/java/org/thingsboard/server/controller/ControllerConstants.java
  application/src/main/java/org/thingsboard/server/controller/DeviceProfileController.java
  application/src/main/java/org/thingsboard/server/controller/TelemetryController.java
  common/transport/http/src/main/java/org/thingsboard/server/transport/http/DeviceApiController.java
Labels: Ignore for release

#10961 Rule engine memory optimizations
  application/src/main/java/org/thingsboard/server/actors/shared/ComponentMsgProcessor.java
  application/src/main/java/org/thingsboard/server/actors/stats/StatsPersistTick.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/action/TbLogNode.java
Labels: enhancement

#11393 Hide details panel/page tabs if no additional tabs present
  ui-ngx/src/app/modules/home/components/entity/entity-details-panel.component.ts
Labels: enhancement, UI

#11400 Notification widget rename header button name
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI, Ignore for release

#11401 Notification widget rename basic settings appearance
  ui-ngx/src/app/modules/home/components/widget/config/basic/cards/unread-notification-basic-config.component.html
Labels: enhancement, UI, Ignore for release

#11404 Update rule node config
  rule-engine/rule-engine-components/src/main/resources/public/static/rulenode/rulenode-core-config.js
Labels: UI, Rule Engine, Ignore for release

#11403 Gateway Improvements
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-basic-config/modbus-basic-config.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-data-keys-panel/modbus-data-keys-panel.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-security-config/modbus-security-config.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-security-config/modbus-security-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-slave-config/modbus-slave-config.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-slave-config/modbus-slave-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-slave-dialog/modbus-slave-dialog.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-slave-dialog/modbus-slave-dialog.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-slave-dialog/modbus-slave-dialog.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/opc-server-config/opc-server-config.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/opc-server-config/opc-server-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/type-value-panel/type-value-panel.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/type-value-panel/type-value-panel.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/type-value-panel/type-value-panel.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/dialog/add-connector-dialog.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-connectors.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-connectors.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/widget-components.module.ts
  ui-ngx/src/app/shared/directives/truncate-with-tooltip.directive.ts
  ui-ngx/src/assets/help/en_US/widget/lib/gateway/modbus-functions-data-types_fn.md
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI, Ignore for release

#11370 Added posibility of discrete value pick in OPC value type keys
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/type-value-panel/type-value-panel.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/type-value-panel/type-value-panel.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/type-value-panel/type-value-panel.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/widget-components.module.ts
  ui-ngx/src/app/shared/directives/truncate-with-tooltip.directive.ts
Labels: enhancement, UI

#11387 Gateway Modbus Connector added UI adjustments, helplinks and hints
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-basic-config/modbus-basic-config.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-data-keys-panel/modbus-data-keys-panel.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-security-config/modbus-security-config.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-security-config/modbus-security-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-slave-config/modbus-slave-config.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-slave-config/modbus-slave-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-slave-dialog/modbus-slave-dialog.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-slave-dialog/modbus-slave-dialog.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-slave-dialog/modbus-slave-dialog.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/dialog/add-connector-dialog.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-widget.models.ts
  ui-ngx/src/assets/help/en_US/widget/lib/gateway/modbus-functions-data-types_fn.md
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI, Ignore for release

#11389 Fixed Duplicate Name validation on Adding new Connector
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/dialog/add-connector-dialog.component.ts
Labels: bug, UI, Ignore for release

#11394 Fixed Issue of viewing Out of Sync Connector
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-connectors.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-widget.models.ts
  ui-ngx/src/app/shared/models/telemetry/telemetry.models.ts
Labels: bug, UI, Ignore for release

#11368 Dedicated datasource for events and audit logs
  application/src/main/resources/thingsboard.yml
  application/src/test/java/org/thingsboard/server/controller/AuditLogControllerTest.java
  application/src/test/java/org/thingsboard/server/controller/AuditLogControllerTest_DedicatedEventsDataSource.java
  dao/src/main/java/org/thingsboard/server/dao/TimescaleTsLatestDaoConfig.java
  dao/src/main/java/org/thingsboard/server/dao/audit/AuditLogServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/config/DedicatedEventsDataSource.java
  dao/src/main/java/org/thingsboard/server/dao/config/DedicatedEventsJpaDaoConfig.java
  dao/src/main/java/org/thingsboard/server/dao/config/DefaultDataSource.java
  dao/src/main/java/org/thingsboard/server/dao/config/DefaultDedicatedJpaDaoConfig.java
  dao/src/main/java/org/thingsboard/server/dao/config/JpaDaoConfig.java
  dao/src/main/java/org/thingsboard/server/dao/config/SqlTsDaoConfig.java
  dao/src/main/java/org/thingsboard/server/dao/config/SqlTsLatestDaoConfig.java
  dao/src/main/java/org/thingsboard/server/dao/config/TimescaleDaoConfig.java
  dao/src/main/java/org/thingsboard/server/dao/config/TimescaleTsLatestDaoConfig.java
  dao/src/main/java/org/thingsboard/server/dao/event/EventDao.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/AuditLogEntity.java
  dao/src/main/java/org/thingsboard/server/dao/sql/JpaAbstractDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/audit/DedicatedJpaAuditLogDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/audit/JpaAuditLogDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/event/DedicatedEventInsertRepository.java
  dao/src/main/java/org/thingsboard/server/dao/sql/event/DedicatedJpaEventDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/event/EventInsertRepository.java
  dao/src/main/java/org/thingsboard/server/dao/sql/event/JpaBaseEventDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/event/SqlEventCleanupRepository.java
  dao/src/main/java/org/thingsboard/server/dao/sqlts/insert/sql/DedicatedEventsSqlPartitioningRepository.java
  dao/src/main/java/org/thingsboard/server/dao/sqlts/insert/sql/SqlPartitioningRepository.java
  dao/src/test/java/org/thingsboard/server/dao/AbstractDaoServiceTest.java
  dao/src/test/java/org/thingsboard/server/dao/AbstractJpaDaoTest.java
  dao/src/test/java/org/thingsboard/server/dao/PostgreSqlInitializer.java
  dao/src/test/java/org/thingsboard/server/dao/service/event/sql/EventServiceSqlTest_DedicatedEventsDataSource.java
Labels: Core, Rule Engine

#11430 Dashboard layout and widget reference
  ui-ngx/src/app/core/services/dashboard-utils.service.ts
  ui-ngx/src/app/core/services/item-buffer.service.ts
  ui-ngx/src/app/modules/home/components/dashboard-page/add-widget-dialog.component.html
  ui-ngx/src/app/modules/home/components/dashboard-page/add-widget-dialog.component.ts
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.html
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.scss
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.ts
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.models.ts
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-settings-dialog.component.html
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-settings-dialog.component.ts
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-toolbar.component.scss
  ui-ngx/src/app/modules/home/components/dashboard-page/edit-widget.component.html
  ui-ngx/src/app/modules/home/components/dashboard-page/edit-widget.component.ts
  ui-ngx/src/app/modules/home/components/dashboard-page/layout/add-new-breakpoint-dialog.component.html
  ui-ngx/src/app/modules/home/components/dashboard-page/layout/add-new-breakpoint-dialog.component.ts
  ui-ngx/src/app/modules/home/components/dashboard-page/layout/dashboard-layout.component.html
  ui-ngx/src/app/modules/home/components/dashboard-page/layout/dashboard-layout.component.ts
  ui-ngx/src/app/modules/home/components/dashboard-page/layout/layout.models.ts
  ui-ngx/src/app/modules/home/components/dashboard-page/layout/manage-dashboard-layouts-dialog.component.html
  ui-ngx/src/app/modules/home/components/dashboard-page/layout/manage-dashboard-layouts-dialog.component.scss
  ui-ngx/src/app/modules/home/components/dashboard-page/layout/manage-dashboard-layouts-dialog.component.ts
  ui-ngx/src/app/modules/home/components/dashboard-page/layout/select-dashboard-breakpoint.component.html
  ui-ngx/src/app/modules/home/components/dashboard-page/layout/select-dashboard-breakpoint.component.scss
  ui-ngx/src/app/modules/home/components/dashboard-page/layout/select-dashboard-breakpoint.component.ts
  ui-ngx/src/app/modules/home/components/dashboard/dashboard.component.html
  ui-ngx/src/app/modules/home/components/dashboard/dashboard.component.ts
  ui-ngx/src/app/modules/home/components/home-components.module.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/mapping-table/mapping-table.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-data-keys-panel/modbus-data-keys-panel.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-security-config/modbus-security-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-slave-config/modbus-slave-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/modbus/modbus-slave-dialog/modbus-slave-dialog.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/opc-server-config/opc-server-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/workers-config-control/workers-config-control.component.ts
  ui-ngx/src/app/modules/home/components/widget/widget-components.module.ts
  ui-ngx/src/app/modules/home/components/widget/widget-config.component.html
  ui-ngx/src/app/modules/home/components/widget/widget-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/widget-container.component.scss
  ui-ngx/src/app/modules/home/components/widget/widget-container.component.ts
  ui-ngx/src/app/modules/home/models/dashboard-component.models.ts
  ui-ngx/src/app/modules/home/models/widget-component.models.ts
  ui-ngx/src/app/shared/directives/truncate-with-tooltip.directive.ts
  ui-ngx/src/app/shared/import-export/import-export.service.ts
  ui-ngx/src/app/shared/models/dashboard.models.ts
  ui-ngx/src/app/shared/shared.module.ts
  ui-ngx/src/assets/locale/locale.constant-ar_AE.json
  ui-ngx/src/assets/locale/locale.constant-ca_ES.json
  ui-ngx/src/assets/locale/locale.constant-cs_CZ.json
  ui-ngx/src/assets/locale/locale.constant-en_US.json
  ui-ngx/src/assets/locale/locale.constant-es_ES.json
  ui-ngx/src/assets/locale/locale.constant-fr_FR.json
  ui-ngx/src/assets/locale/locale.constant-lt_LT.json
  ui-ngx/src/assets/locale/locale.constant-nl_BE.json
  ui-ngx/src/assets/locale/locale.constant-pl_PL.json
  ui-ngx/src/assets/locale/locale.constant-tr_TR.json
  ui-ngx/src/assets/locale/locale.constant-zh_CN.json
  ui-ngx/src/assets/locale/locale.constant-zh_TW.json
  ui-ngx/src/styles.scss
Labels: Major UI

#11427 Added Max payload size in bytes and Min packet size to send
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/opc-server-config/opc-server-config.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/opc-server-config/opc-server-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-configuration.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-configuration.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-widget.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
  ui-ngx/src/assets/metadata/connector-default-configs/opcua.json
  ui-ngx/src/assets/metadata/connector-default-configs/opcua_asyncio.json
Labels: UI, feature

#11439 Fixed delete widget in layout and improved dashboard layout types
  ui-ngx/src/app/core/services/dashboard-utils.service.ts
  ui-ngx/src/app/core/services/item-buffer.service.ts
  ui-ngx/src/app/modules/home/components/dashboard-page/layout/manage-dashboard-layouts-dialog.component.ts
  ui-ngx/src/app/modules/home/components/dashboard-page/layout/select-dashboard-breakpoint.component.ts
  ui-ngx/src/app/shared/import-export/import-export.service.ts
  ui-ngx/src/app/shared/models/dashboard.models.ts
Labels: bug, UI, Ignore for release

#11441 Fixed adaptive manage layout dialog
  ui-ngx/src/app/modules/home/components/dashboard-page/layout/add-new-breakpoint-dialog.component.html
  ui-ngx/src/app/modules/home/components/dashboard-page/layout/manage-dashboard-layouts-dialog.component.html
  ui-ngx/src/app/modules/home/components/dashboard-page/layout/manage-dashboard-layouts-dialog.component.scss
Labels: bug, UI, Ignore for release

#11337 Fixed updating target after deleted recipient
  ui-ngx/src/app/modules/home/pages/notification/sent/sent-notification-dialog.component.html
  ui-ngx/src/app/shared/components/entity/entity-list.component.ts
Labels: bug, UI, Ignore for release

#11426 Version Conflict dialog fixes
  ui-ngx/src/app/core/http/widget.service.ts
  ui-ngx/src/app/core/interceptors/entity-conflict.interceptor.ts
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.ts
  ui-ngx/src/app/modules/home/components/entity/entities-table.component.ts
  ui-ngx/src/app/modules/home/components/entity/entity-details-panel.component.ts
  ui-ngx/src/app/modules/home/components/widget/widget-component.service.ts
  ui-ngx/src/app/modules/home/models/widget-component.models.ts
  ui-ngx/src/app/modules/home/pages/widget/widget-editor.component.ts
  ui-ngx/src/app/shared/components/dialog/entity-conflict-dialog/entity-conflict-dialog.component.html
  ui-ngx/src/app/shared/components/dialog/entity-conflict-dialog/entity-conflict-dialog.component.scss
  ui-ngx/src/app/shared/components/dialog/entity-conflict-dialog/entity-conflict-dialog.component.ts
  ui-ngx/src/app/shared/import-export/export-widgets-bundle-dialog.component.html
  ui-ngx/src/app/shared/import-export/export-widgets-bundle-dialog.component.ts
  ui-ngx/src/app/shared/import-export/import-export.service.ts
  ui-ngx/src/app/shared/models/widget.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI, Ignore for release

#11419 Fix unrecognized Kafka config 'session.timeout.ms'
  common/queue/src/main/java/org/thingsboard/server/queue/kafka/TbKafkaSettings.java
  common/queue/src/test/java/org/thingsboard/server/queue/kafka/TbKafkaSettingsTest.java
Labels: bug

#11425 Fix Swagger issues when reverse proxy is used
  application/src/main/resources/thingsboard.yml
  msa/tb-node/docker/Dockerfile
Labels: bug, Core

#11422 [Swagger Documentation] Fixed description
  application/src/main/java/org/thingsboard/server/controller/AdminController.java
  common/data/src/main/java/org/thingsboard/server/common/data/objects/AttributesEntityView.java
  common/data/src/main/java/org/thingsboard/server/common/data/objects/TelemetryEntityView.java
Labels: Ignore for release

#11121 Change originator node: added tests
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/OriginatorSource.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/TbChangeOriginatorNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/TbChangeOriginatorNodeConfiguration.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/util/EntitiesByNameAndTypeLoader.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/transform/TbChangeOriginatorNodeTest.java
Labels: Ignore for release

#11351 Flow type rule nodes: added tests
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/flow/TbAckNodeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/flow/TbCheckpointNodeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/flow/TbRuleChainInputNodeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/flow/TbRuleChainOutputNodeTest.java
Labels: Ignore for release

#11458 Fix getOrFetchFromDB for versioned transactional cache
  common/cache/src/main/java/org/thingsboard/server/cache/TbTransactionalCache.java
Labels: Ignore for release

#11468 VC: fix error message when using https url with private key authentication
  common/version-control/src/main/java/org/thingsboard/server/service/sync/vc/GitRepository.java
Labels: Ignore for release

#11459 Fixed queries for get/count devices without OTA
  common/dao-api/src/main/java/org/thingsboard/server/dao/device/DeviceService.java
  common/data/src/main/java/org/thingsboard/server/common/data/HasOtaPackage.java
  dao/src/main/java/org/thingsboard/server/dao/device/DeviceServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/sql/device/DeviceRepository.java
  dao/src/main/java/org/thingsboard/server/dao/sql/device/JpaDeviceDao.java
  dao/src/test/java/org/thingsboard/server/dao/service/DeviceServiceTest.java
Labels: bug

#11466 Fix entity's version incremented twice
  dao/src/main/java/org/thingsboard/server/dao/model/sql/DeviceProfileEntity.java
  dao/src/main/java/org/thingsboard/server/dao/sql/JpaAbstractDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/JpaPartitionedAbstractDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/asset/JpaAssetProfileDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/device/JpaDeviceProfileDao.java
Labels: Ignore for release

#11469 Ignore unknown notification recipient groups
  application/src/main/java/org/thingsboard/server/controller/NotificationController.java
  application/src/main/java/org/thingsboard/server/service/notification/DefaultNotificationCenter.java
Labels: enhancement

#11471 Fixed issue with not saving Widget on Widget editing
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.ts
Labels: bug, UI, Ignore for release

#11510 lwm2m: fix bug send From Client CollectedValue
  application/src/test/java/org/thingsboard/server/transport/lwm2m/client/LwM2MTestClient.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/client/LwM2mTemperatureSensor.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationReadTest.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mServerListener.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/uplink/DefaultLwM2mUplinkMsgHandler.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/uplink/LwM2mUplinkMsgHandler.java
Labels: Transport

#11421 Fix null entityId in audit log when alarm is deleted
  application/src/main/java/org/thingsboard/server/service/entitiy/alarm/DefaultTbAlarmService.java
  application/src/test/java/org/thingsboard/server/controller/AlarmControllerTest.java
  application/src/test/java/org/thingsboard/server/service/entitiy/alarm/DefaultTbAlarmServiceTest.java
  common/data/src/main/java/org/thingsboard/server/common/data/audit/ActionType.java
  common/data/src/test/java/org/thingsboard/server/common/data/audit/ActionTypeTest.java
  dao/src/main/java/org/thingsboard/server/dao/audit/AuditLogServiceImpl.java
  dao/src/test/java/org/thingsboard/server/dao/audit/AuditLogServiceImplTest.java
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: bug

#11522 Added UI part of RuleChain Editor Version Conflict
  ui-ngx/src/app/modules/home/pages/rulechain/rulechain-page.component.ts
  ui-ngx/src/app/shared/components/dialog/entity-conflict-dialog/entity-conflict-dialog.component.html
  ui-ngx/src/app/shared/components/dialog/entity-conflict-dialog/entity-conflict-dialog.component.ts
  ui-ngx/src/app/shared/import-export/import-export.service.ts
  ui-ngx/src/app/shared/models/rule-chain.models.ts
Labels: enhancement, UI, Ignore for release

#11330 Payload size filter for all requests
  application/src/main/java/org/thingsboard/server/config/RequestSizeFilter.java
  application/src/main/java/org/thingsboard/server/config/ThingsboardSecurityConfiguration.java
  application/src/main/resources/thingsboard.yml
  application/src/test/java/org/thingsboard/server/controller/ImageControllerTest.java
  application/src/test/java/org/thingsboard/server/controller/RpcControllerTest.java
  application/src/test/java/org/thingsboard/server/system/BaseHttpDeviceApiTest.java
  common/message/src/main/java/org/thingsboard/server/common/msg/tools/MaxPayloadSizeExceededException.java
  common/transport/http/pom.xml
  common/transport/http/src/main/java/org/thingsboard/server/transport/http/DeviceApiController.java
  common/transport/http/src/main/java/org/thingsboard/server/transport/http/config/PayloadSizeFilter.java
  common/transport/http/src/main/java/org/thingsboard/server/transport/http/config/TransportSecurityConfiguration.java
  transport/http/src/main/resources/tb-http-transport.yml
Labels: enhancement, Core, Transport
