Repository thingsboard/thingsboard, pull requests merged in 2024-03, with the labels that each got.

#10271 Fix JWT settings updating for Rule Engines
  application/src/main/java/org/thingsboard/server/controller/AdminController.java
  application/src/main/java/org/thingsboard/server/service/queue/DefaultTbCoreConsumerService.java
  application/src/main/java/org/thingsboard/server/service/queue/DefaultTbRuleEngineConsumerService.java
  application/src/main/java/org/thingsboard/server/service/queue/processing/AbstractConsumerService.java
  application/src/main/java/org/thingsboard/server/service/security/auth/jwt/settings/DefaultJwtSettingsService.java
  application/src/test/java/org/thingsboard/server/service/security/auth/JwtTokenFactoryTest.java
Labels: Ignore for release

#10294 fixed lwm2m uplink executor lock
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/uplink/DefaultLwM2mUplinkMsgHandler.java
Labels: bug

#10230 Add rate limits for edge uplink message
  application/src/main/java/org/thingsboard/server/service/edge/EdgeContextComponent.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java
  application/src/test/java/org/thingsboard/server/service/limits/RateLimitServiceTest.java
  common/data/src/main/java/org/thingsboard/server/common/data/limit/LimitedApi.java
  common/data/src/main/java/org/thingsboard/server/common/data/tenant/profile/DefaultTenantProfileConfiguration.java
  ui-ngx/src/app/modules/home/components/profile/tenant/default-tenant-profile-configuration.component.html
  ui-ngx/src/app/modules/home/components/profile/tenant/default-tenant-profile-configuration.component.ts
  ui-ngx/src/app/modules/home/components/profile/tenant/rate-limits/rate-limits.models.ts
  ui-ngx/src/app/shared/models/limited-api.models.ts
  ui-ngx/src/assets/help/en_US/notification/rate_limits.md
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: Ignore for release

#10276 Added fixed width for embed image dialog
  ui-ngx/src/app/shared/components/image/embed-image-dialog.component.scss
Labels: bug, UI

#10279 Fixed applying min/max y-axis parameters in flot chart
  ui-ngx/src/app/modules/home/components/widget/lib/flot-widget.ts
Labels: bug, UI

#10287 Fixed RPC terminals not retrieving device name
  application/src/main/data/json/system/widget_types/persistent_rpc_table.json
  application/src/main/data/json/system/widget_types/rpc_debug_terminal.json
  application/src/main/data/json/system/widget_types/rpc_remote_shell.json
Labels: bug, UI, Ignore for release

#10293 Fixed incorrect cache when open preview public image
  ui-ngx/src/app/shared/components/image/image-dialog.component.ts
Labels: bug, UI, Ignore for release

#10309 fixed lwm2m client deserialization
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/store/util/LwM2MClientSerDes.java
  common/transport/lwm2m/src/test/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mClientTest.java
  common/transport/lwm2m/src/test/java/org/thingsboard/server/transport/lwm2m/server/store/util/LwM2MClientSerDesTest.java
  common/transport/lwm2m/src/test/org/thingsboard/server/transport/lwm2m/server/store/util/LwM2MClientSerDesTest.java
  common/transport/lwm2m/src/test/resources/15.xml
  common/transport/lwm2m/src/test/resources/17.xml
Labels: bug, Core, Transport

#10307 Fix mobile notification sending failures
  application/src/main/java/org/thingsboard/server/service/notification/DefaultNotificationCenter.java
  application/src/main/java/org/thingsboard/server/service/notification/channels/MobileAppNotificationChannel.java
  application/src/test/java/org/thingsboard/server/service/notification/AbstractNotificationApiTest.java
  application/src/test/java/org/thingsboard/server/service/notification/NotificationApiTest.java
  application/src/test/java/org/thingsboard/server/service/notification/NotificationRuleApiTest.java
  common/data/src/main/java/org/thingsboard/server/common/data/notification/NotificationRequestStats.java
Labels: Ignore for release

#10321 Fix git repository initialization after repo directory deletion
  common/version-control/src/main/java/org/thingsboard/server/service/sync/vc/DefaultGitRepositoryService.java
Labels: Core

#10302 Changed type of ThingsboardErrorResponse timestamp from Date to long
  application/src/main/java/org/thingsboard/server/exception/ThingsboardErrorResponse.java
  application/src/main/java/org/thingsboard/server/exception/ThingsboardErrorResponseHandler.java
Labels: Core

#10324 Add icon to configure mobile app notification
  ui-ngx/src/app/modules/home/pages/notification/template/configuration/notification-template-configuration.component.html
  ui-ngx/src/app/modules/home/pages/notification/template/configuration/notification-template-configuration.component.ts
Labels: enhancement, UI, Ignore for release

#10316 Refactoring widgetActionTypes
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/widget-action.component.ts
  ui-ngx/src/app/shared/models/widget.models.ts
Labels: enhancement, UI, Ignore for release

#10337 Latest ts and attribute async improvement
  dao/src/main/java/org/thingsboard/server/dao/attributes/CachedAttributesService.java
  dao/src/main/java/org/thingsboard/server/dao/service/Validator.java
  dao/src/main/java/org/thingsboard/server/dao/sqlts/SqlTimeseriesLatestDao.java
  dao/src/main/java/org/thingsboard/server/dao/timeseries/BaseTimeseriesService.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/metadata/TbAbstractGetAttributesNode.java
Labels: enhancement

#10326 Improvement API usage dashboard
  ui-ngx/src/assets/dashboard/api_usage.json
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI

#10334 Fixed not edit action source
  ui-ngx/src/app/modules/home/components/widget/action/widget-action-dialog.component.ts
Labels: bug, UI, Ignore for release

#10311 Fixed TLS Factory error when no password set in configuration
  common/util/src/main/java/org/thingsboard/common/util/SslUtil.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/credentials/CertPemCredentials.java
Labels: bug, Rule Engine

#10368 Automatically close default dialogs (Alert/Confirm/Error) on route change
  ui-ngx/src/app/core/services/dialog.service.ts
  ui-ngx/src/app/shared/components/dialog/alert-dialog.component.ts
  ui-ngx/src/app/shared/components/dialog/confirm-dialog.component.ts
  ui-ngx/src/app/shared/components/dialog/error-alert-dialog.component.ts
Labels: enhancement, UI

#10380 Add callback executor for device state service
  application/src/main/java/org/thingsboard/server/service/state/DefaultDeviceStateService.java
Labels: Ignore for release

#10379 Add APNS config for push notification in mobile phone
  application/src/main/java/org/thingsboard/server/service/notification/provider/DefaultFirebaseService.java
Labels: Ignore for release

#10370 Added sorting to 'Originator' column for alarm table
  ui-ngx/src/app/modules/home/models/entity/entities-table-config.models.ts
Labels: bug, UI

#10374 Fixed expand notification delivery template when editing
  ui-ngx/src/app/modules/home/pages/notification/template/configuration/notification-template-configuration.component.html
  ui-ngx/src/app/modules/home/pages/notification/template/configuration/notification-template-configuration.component.ts
Labels: bug, UI, Ignore for release

#10039 Refactoring / delete rpc native query
  application/src/main/java/org/thingsboard/server/service/ttl/rpc/RpcCleanUpService.java
  dao/src/main/java/org/thingsboard/server/dao/rpc/RpcDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/rpc/JpaRpcDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/rpc/RpcRepository.java
  dao/src/test/java/org/thingsboard/server/dao/sql/rpc/JpaRpcDaoTest.java
  dao/src/test/resources/logback.xml
Labels: Core

#10385 fixed NPE related to the entity service registry initialization
  dao/src/main/java/org/thingsboard/server/dao/entity/BaseEntityService.java
  dao/src/main/java/org/thingsboard/server/dao/entity/DefaultEntityServiceRegistry.java
Labels: bug, Core

#10394 Ignore partition change event for deleted queues
  application/src/main/java/org/thingsboard/server/service/queue/DefaultTbRuleEngineConsumerService.java
Labels: Ignore for release

#10366 Oauth2 mail refresh token check is being executed only for active not expired token
  application/src/main/java/org/thingsboard/server/service/mail/RefreshTokenExpCheckService.java
Labels: bug, Core

#10443 Switch to SpringDoc OpenAPI 3.1.0
  application/pom.xml
  application/src/main/java/org/thingsboard/server/config/SwaggerConfiguration.java
  application/src/main/java/org/thingsboard/server/config/WebConfig.java
  application/src/main/java/org/thingsboard/server/controller/AdminController.java
  application/src/main/java/org/thingsboard/server/controller/AlarmCommentController.java
  application/src/main/java/org/thingsboard/server/controller/AlarmController.java
  application/src/main/java/org/thingsboard/server/controller/AssetController.java
  application/src/main/java/org/thingsboard/server/controller/AssetProfileController.java
  application/src/main/java/org/thingsboard/server/controller/AuditLogController.java
  application/src/main/java/org/thingsboard/server/controller/CustomerController.java
  application/src/main/java/org/thingsboard/server/controller/DashboardController.java
  application/src/main/java/org/thingsboard/server/controller/DeviceController.java
  application/src/main/java/org/thingsboard/server/controller/DeviceProfileController.java
  application/src/main/java/org/thingsboard/server/controller/EdgeController.java
  application/src/main/java/org/thingsboard/server/controller/EdgeEventController.java
  application/src/main/java/org/thingsboard/server/controller/EntityRelationController.java
  application/src/main/java/org/thingsboard/server/controller/EntityViewController.java
  application/src/main/java/org/thingsboard/server/controller/EventController.java
  application/src/main/java/org/thingsboard/server/controller/Lwm2mController.java
  application/src/main/java/org/thingsboard/server/controller/OtaPackageController.java
  application/src/main/java/org/thingsboard/server/controller/RuleChainController.java
  application/src/main/java/org/thingsboard/server/controller/TbResourceController.java
  application/src/main/java/org/thingsboard/server/controller/TelemetryController.java
  application/src/main/resources/thingsboard.yml
  common/data/src/main/java/org/thingsboard/server/common/data/alarm/AlarmComment.java
  common/data/src/main/java/org/thingsboard/server/common/data/id/EntityId.java
  common/data/src/main/java/org/thingsboard/server/common/data/id/UserId.java
  common/transport/http/src/main/java/org/thingsboard/server/transport/http/DeviceApiController.java
  dao/src/test/java/org/thingsboard/server/dao/sql/alarm/JpaAlarmCommentDaoTest.java
  pom.xml
Labels: Core

#10446 Fixed draggeble marker and not draw new poligon in map widgets
  ui-ngx/package.json
  ui-ngx/yarn.lock
Labels: bug, UI

#10437 Check alarm status node: log severity reduced for "Failed to parse alarm" for known runtime exceptions
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/filter/TbCheckAlarmStatusNode.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/filter/TbCheckAlarmStatusNodeTest.java
  rule-engine/rule-engine-components/src/test/resources/logback-test.xml
Labels: enhancement

#10449 Fixed not opened image gallery when used multiple-gallery-image-input.component.ts
  ui-ngx/src/app/shared/components/image/multiple-gallery-image-input.component.html
  ui-ngx/src/app/shared/components/image/multiple-gallery-image-input.component.ts
Labels: bug, UI

#10330 fixed resolving placeholder in Operation notes
  application/src/main/java/org/thingsboard/server/controller/NotificationTemplateController.java
  application/src/main/java/org/thingsboard/server/controller/TwoFactorAuthConfigController.java
Labels: Ignore for release

#10459 Fixed battery level widget for safari and firefox
  ui-ngx/src/app/modules/home/components/widget/lib/indicator/battery-level-widget.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/indicator/battery-level-widget.component.ts
Labels: bug, UI

#10417 Added global queue prefix for pubsub queue factory
  common/queue/src/main/java/org/thingsboard/server/queue/provider/PubSubMonolithQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/PubSubTbCoreQueueFactory.java
Labels: bug, Core

#10473 Update bar chart with labels and range chart widgets according to current time series widgets family
  ui-ngx/src/app/modules/home/components/widget/config/basic/chart/bar-chart-with-labels-basic-config.component.html
  ui-ngx/src/app/modules/home/components/widget/config/basic/chart/bar-chart-with-labels-basic-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/config/basic/chart/range-chart-basic-config.component.html
  ui-ngx/src/app/modules/home/components/widget/config/basic/chart/range-chart-basic-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/chart/bar-chart-with-labels-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/chart/bar-chart-with-labels-widget.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/chart/bar-chart-with-labels-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/chart/bar-chart-with-labels-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/chart/echarts-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/chart/range-chart-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/chart/range-chart-widget.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/chart/range-chart-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/chart/range-chart-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/chart/time-series-chart-bar.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/chart/time-series-chart.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/chart/time-series-chart.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/chart/bar-chart-with-labels-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/chart/bar-chart-with-labels-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/chart/range-chart-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/chart/range-chart-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/chart/time-series-chart-bar-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/chart/time-series-chart-bar-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/chart/time-series-chart-line-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/chart/time-series-chart-line-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/chart/time-series-chart-axis-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/chart/time-series-chart-axis-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/chart/time-series-chart-fill-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/chart/time-series-chart-fill-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/chart/time-series-chart-threshold-row.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/chart/time-series-chart-threshold-row.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/chart/time-series-chart-threshold-settings-panel.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/chart/time-series-chart-threshold-settings-panel.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/chart/time-series-chart-threshold-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/chart/time-series-chart-threshold-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/chart/time-series-chart-thresholds-panel.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/chart/time-series-chart-thresholds-panel.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/chart/time-series-no-aggregation-bar-width-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/chart/time-series-no-aggregation-bar-width-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/widget-settings-common.module.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/widget-settings.module.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
  ui-ngx/src/assets/locale/locale.constant-pl_PL.json
  ui-ngx/src/assets/locale/locale.constant-zh_CN.json
Labels: UI, Major UI
