Repository thingsboard/thingsboard, pull requests merged in 2024-04, with the labels that each got.

#10436 [3.7] Http Transport log optimization
  common/transport/http/src/main/java/org/thingsboard/server/transport/http/DeviceApiController.java
  common/transport/http/src/test/java/org/thingsboard/server/transport/http/DeviceApiControllerTest.java
  common/transport/http/src/test/resources/logback-test.xml
Labels: enhancement

#10471 Yaml config for max size of telemetry message sent to Edge
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/BaseEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/telemetry/TelemetryEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/tenant/TenantEdgeProcessor.java
  application/src/main/resources/thingsboard.yml
  application/src/test/java/org/thingsboard/server/service/edge/rpc/processor/BaseEdgeProcessorTest.java
  application/src/test/java/org/thingsboard/server/service/edge/rpc/processor/telemetry/TelemetryEdgeProcessorTest.java
  common/proto/src/main/java/org/thingsboard/server/common/util/ProtoUtils.java
Labels: enhancement, Edge

#10377 VC restore: optional rollback on error to vastly increase performance
  application/src/main/java/org/thingsboard/server/service/sync/ie/DefaultEntitiesExportImportService.java
  application/src/main/java/org/thingsboard/server/service/sync/vc/DefaultEntitiesVersionControlService.java
  application/src/main/java/org/thingsboard/server/service/sync/vc/data/EntitiesImportCtx.java
  common/data/src/main/java/org/thingsboard/server/common/data/sync/vc/request/load/EntityTypeVersionLoadRequest.java
  ui-ngx/src/app/modules/home/components/vc/complex-version-load.component.html
  ui-ngx/src/app/modules/home/components/vc/complex-version-load.component.ts
  ui-ngx/src/app/shared/models/vc.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, Core

#10455 Do not delete propagated alarms while asset deletion
  application/src/main/java/org/thingsboard/server/service/entitiy/AbstractTbEntityService.java
  application/src/main/java/org/thingsboard/server/service/entitiy/asset/DefaultTbAssetService.java
  application/src/main/java/org/thingsboard/server/service/entitiy/device/DefaultTbDeviceService.java
  application/src/test/java/org/thingsboard/server/controller/AssetControllerTest.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/alarm/AlarmService.java
  dao/src/main/java/org/thingsboard/server/dao/alarm/AlarmDao.java
  dao/src/main/java/org/thingsboard/server/dao/alarm/BaseAlarmService.java
  dao/src/main/java/org/thingsboard/server/dao/sql/alarm/AlarmRepository.java
  dao/src/main/java/org/thingsboard/server/dao/sql/alarm/JpaAlarmDao.java
Labels: bug, Core

#10453 Added default sorting by id for PageLink
  common/data/src/main/java/org/thingsboard/server/common/data/page/PageLink.java
  common/data/src/main/java/org/thingsboard/server/common/data/page/TimePageLink.java
  dao/src/main/java/org/thingsboard/server/dao/DaoUtil.java
  dao/src/main/java/org/thingsboard/server/dao/sql/alarm/JpaAlarmDao.java
  dao/src/test/java/org/thingsboard/server/dao/sql/widget/JpaWidgetTypeDaoTest.java
Labels: bug, Core

#10145 Entity for queue statistics
  application/src/main/data/json/demo/dashboards/rule_engine_statistics.json
  application/src/main/data/upgrade/3.6.3/schema_update.sql
  application/src/main/java/org/thingsboard/server/actors/ActorSystemContext.java
  application/src/main/java/org/thingsboard/server/actors/ruleChain/DefaultTbContext.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/asset/AssetEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/entitiy/asset/DefaultTbAssetService.java
  application/src/main/java/org/thingsboard/server/service/entitiy/asset/profile/DefaultTbAssetProfileService.java
  application/src/main/java/org/thingsboard/server/service/stats/DefaultRuleEngineStatisticsService.java
  application/src/test/java/org/thingsboard/server/controller/AssetControllerTest.java
  application/src/test/java/org/thingsboard/server/controller/BaseQueueControllerTest.java
  application/src/test/java/org/thingsboard/server/controller/EntityQueryControllerTest.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/queue/QueueStatsService.java
  common/data/src/main/java/org/thingsboard/server/common/data/EntityType.java
  common/data/src/main/java/org/thingsboard/server/common/data/id/EntityIdFactory.java
  common/data/src/main/java/org/thingsboard/server/common/data/id/QueueStatsId.java
  common/data/src/main/java/org/thingsboard/server/common/data/queue/QueueStats.java
  common/proto/src/main/proto/queue.proto
  dao/src/main/java/org/thingsboard/server/dao/asset/BaseAssetService.java
  dao/src/main/java/org/thingsboard/server/dao/model/ModelConstants.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/QueueStatsEntity.java
  dao/src/main/java/org/thingsboard/server/dao/queue/BaseQueueStatsService.java
  dao/src/main/java/org/thingsboard/server/dao/queue/QueueStatsDao.java
  dao/src/main/java/org/thingsboard/server/dao/service/validator/AssetDataValidator.java
  dao/src/main/java/org/thingsboard/server/dao/service/validator/QueueStatsDataValidator.java
  dao/src/main/java/org/thingsboard/server/dao/sql/asset/AssetRepository.java
  dao/src/main/java/org/thingsboard/server/dao/sql/asset/JpaAssetDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/query/DefaultEntityQueryRepository.java
  dao/src/main/java/org/thingsboard/server/dao/sql/query/EntityKeyMapping.java
  dao/src/main/java/org/thingsboard/server/dao/sql/queue/JpaQueueStatsDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/queue/QueueStatsRepository.java
  dao/src/main/java/org/thingsboard/server/dao/tenant/TenantServiceImpl.java
  dao/src/main/resources/sql/schema-entities.sql
  dao/src/test/java/org/thingsboard/server/dao/service/QueueStatsServiceTest.java
  rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/TbContext.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/util/TenantIdLoader.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/util/TenantIdLoaderTest.java
  ui-ngx/src/app/core/http/entity.service.ts
  ui-ngx/src/app/modules/home/components/profile/asset-profile.component.html
  ui-ngx/src/app/modules/home/components/profile/asset-profile.component.ts
  ui-ngx/src/app/modules/home/pages/asset-profile/asset-profiles-table-config.resolver.ts
  ui-ngx/src/app/shared/models/asset.models.ts
  ui-ngx/src/app/shared/models/entity-type.models.ts
  ui-ngx/src/app/shared/models/entity.models.ts
  ui-ngx/src/app/shared/models/query/query.models.ts
  ui-ngx/src/assets/dashboard/api_usage.json
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, Core

#10490 Add 3.7.0 version to edge.proto
  common/edge-api/src/main/proto/edge.proto
Labels: Ignore for release

#10416 Fix KvProtoUtils order for matching KeyValueType and DataType
  application/src/main/java/org/thingsboard/server/actors/device/DeviceActorMessageProcessor.java
  application/src/main/java/org/thingsboard/server/service/queue/DefaultTbCoreConsumerService.java
  application/src/main/java/org/thingsboard/server/service/subscription/TbSubscriptionUtils.java
  application/src/test/java/org/thingsboard/server/utils/TbSubscriptionUtilsTest.java
  common/proto/src/main/java/org/thingsboard/server/common/util/KvProtoUtil.java
  common/proto/src/test/java/org/thingsboard/server/common/util/KvProtoUtilTest.java
Labels: bug, Core

#10493 Critical dependency vulnerabilities fix
  msa/js-executor/package.json
  msa/js-executor/yarn.lock
  pom.xml
Labels: enhancement

#10332 [3.7] Validator performance optimization
  application/src/main/java/org/thingsboard/server/controller/BaseController.java
  application/src/main/java/org/thingsboard/server/service/resource/DefaultTbResourceService.java
  common/data/src/main/java/org/thingsboard/server/common/data/id/UUIDBased.java
  dao/src/main/java/org/thingsboard/server/dao/alarm/BaseAlarmCommentService.java
  dao/src/main/java/org/thingsboard/server/dao/alarm/BaseAlarmService.java
  dao/src/main/java/org/thingsboard/server/dao/asset/AssetProfileServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/asset/BaseAssetService.java
  dao/src/main/java/org/thingsboard/server/dao/attributes/AttributeUtils.java
  dao/src/main/java/org/thingsboard/server/dao/attributes/BaseAttributesService.java
  dao/src/main/java/org/thingsboard/server/dao/attributes/CachedAttributesService.java
  dao/src/main/java/org/thingsboard/server/dao/audit/AuditLogServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/customer/CustomerServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/dashboard/DashboardServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/device/DeviceConnectivityServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/device/DeviceCredentialsServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/device/DeviceProfileServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/device/DeviceServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/edge/EdgeServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/entity/BaseEntityService.java
  dao/src/main/java/org/thingsboard/server/dao/entityview/EntityViewServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/oauth2/OAuth2ConfigTemplateServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/oauth2/OAuth2ServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/ota/BaseOtaPackageService.java
  dao/src/main/java/org/thingsboard/server/dao/queue/BaseQueueStatsService.java
  dao/src/main/java/org/thingsboard/server/dao/relation/BaseRelationService.java
  dao/src/main/java/org/thingsboard/server/dao/resource/BaseImageService.java
  dao/src/main/java/org/thingsboard/server/dao/resource/BaseResourceService.java
  dao/src/main/java/org/thingsboard/server/dao/rpc/BaseRpcService.java
  dao/src/main/java/org/thingsboard/server/dao/rule/BaseRuleChainService.java
  dao/src/main/java/org/thingsboard/server/dao/service/Validator.java
  dao/src/main/java/org/thingsboard/server/dao/settings/AdminSettingsServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/tenant/TenantProfileServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/tenant/TenantServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/usagerecord/ApiUsageStateServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/user/UserServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/user/UserSettingsServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/widget/WidgetTypeServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/widget/WidgetsBundleServiceImpl.java
  dao/src/test/java/org/thingsboard/server/dao/service/ValidatorTest.java
Labels: enhancement

#10452 Nashorn js executor sandbox memory limit
  application/src/main/resources/thingsboard.yml
  application/src/test/java/org/thingsboard/server/service/script/NashornJsInvokeServiceTest.java
  application/src/test/resources/logback-test.xml
  common/script/script-api/src/main/java/org/thingsboard/script/api/AbstractScriptInvokeService.java
  common/script/script-api/src/main/java/org/thingsboard/script/api/js/NashornJsInvokeService.java
  pom.xml
Labels: enhancement

#9930 HAproxy rate and connection limits (images api included)
  docker/haproxy/config/blocklist.txt
  docker/haproxy/config/haproxy.cfg
  docker/haproxy/config/trustlist.txt
Labels: enhancement, Core

#10462 fix_bug_lwm2m_coap_californium_3_11_0
  application/src/test/java/org/thingsboard/server/transport/coap/attributes/updates/CoapAttributesUpdatesIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/coap/attributes/updates/CoapAttributesUpdatesJsonIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/coap/attributes/updates/CoapAttributesUpdatesProtoIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/coap/client/CoapClientIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/coap/rpc/CoapServerSideRpcDefaultIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/coap/rpc/CoapServerSideRpcJsonIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/coap/rpc/CoapServerSideRpcProtoIntegrationTest.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mClient.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/store/util/LwM2MClientSerDes.java
  common/transport/lwm2m/src/test/java/org/thingsboard/server/transport/lwm2m/bootstrap/LwM2MTransportBootstrapServiceTest.java
  common/transport/lwm2m/src/test/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mClientTest.java
  common/transport/lwm2m/src/test/java/org/thingsboard/server/transport/lwm2m/server/store/util/LwM2MClientSerDesTest.java
  pom.xml
  transport/lwm2m/src/main/java/org/eclipse/leshan/server/observation/ObservationServiceImpl.java
Labels: bug

#10512 Californium 3.11; tests fixes
  application/src/test/java/org/thingsboard/server/transport/coap/attributes/updates/CoapAttributesUpdatesIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/coap/attributes/updates/CoapAttributesUpdatesJsonIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/coap/attributes/updates/CoapAttributesUpdatesProtoIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/coap/client/CoapClientIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/coap/rpc/CoapServerSideRpcDefaultIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/coap/rpc/CoapServerSideRpcJsonIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/coap/rpc/CoapServerSideRpcProtoIntegrationTest.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mClient.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/store/util/LwM2MClientSerDes.java
  common/transport/lwm2m/src/test/java/org/thingsboard/server/transport/lwm2m/bootstrap/LwM2MTransportBootstrapServiceTest.java
  common/transport/lwm2m/src/test/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mClientTest.java
  common/transport/lwm2m/src/test/java/org/thingsboard/server/transport/lwm2m/server/store/util/LwM2MClientSerDesTest.java
  pom.xml
  transport/lwm2m/src/main/java/org/eclipse/leshan/server/observation/ObservationServiceImpl.java
Labels: Transport

#10515 Attribute scope was missed for rule engine message metadata
  application/src/main/java/org/thingsboard/server/service/action/EntityActionService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/csv/AbstractBulkImportService.java
  dao/src/main/java/org/thingsboard/server/dao/audit/AuditLogServiceImpl.java
Labels: Ignore for release

#10420 Improvements for mobile notifications
  application/src/main/data/upgrade/3.6.3/schema_update.sql
  application/src/main/java/org/thingsboard/server/controller/NotificationController.java
  application/src/main/java/org/thingsboard/server/service/notification/DefaultNotificationCenter.java
  application/src/main/java/org/thingsboard/server/service/notification/channels/MobileAppNotificationChannel.java
  application/src/main/java/org/thingsboard/server/service/notification/provider/DefaultFirebaseService.java
  application/src/main/java/org/thingsboard/server/service/ws/notification/DefaultNotificationCommandsHandler.java
  application/src/test/java/org/thingsboard/server/service/notification/AbstractNotificationApiTest.java
  application/src/test/java/org/thingsboard/server/service/notification/NotificationApiTest.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/notification/NotificationService.java
  common/data/src/main/java/org/thingsboard/server/common/data/notification/Notification.java
  common/util/src/main/java/org/thingsboard/common/util/JacksonUtil.java
  dao/src/main/java/org/thingsboard/server/dao/model/ModelConstants.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/NotificationEntity.java
  dao/src/main/java/org/thingsboard/server/dao/notification/DefaultNotificationService.java
  dao/src/main/java/org/thingsboard/server/dao/notification/NotificationDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/notification/JpaNotificationDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/notification/NotificationRepository.java
  dao/src/main/resources/sql/schema-entities-idx.sql
  dao/src/main/resources/sql/schema-entities.sql
  rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/NotificationCenter.java
  rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/notification/FirebaseService.java
Labels: Core

#10349 MQTT node: added ability to send string without quotes.
  common/util/src/main/java/org/thingsboard/common/util/JacksonUtil.java
  common/util/src/test/java/org/thingsboard/common/util/JacksonUtilTest.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/mqtt/TbMqttNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/mqtt/TbMqttNodeConfiguration.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/rest/TbHttpClient.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/mqtt/TbMqttNodeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/rest/TbHttpClientTest.java
Labels: enhancement, Rule Engine

#10300 Added property to ignore delta in output messages if it is zero
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/metadata/CalculateDeltaNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/metadata/CalculateDeltaNodeConfiguration.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/metadata/CalculateDeltaNodeTest.java
Labels: enhancement, Rule Engine

#10355 Changed the logic to be able to find the last IN event despite its order in the debug records.
  application/src/main/java/org/thingsboard/server/controller/RuleChainController.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/event/EventService.java
  dao/src/main/java/org/thingsboard/server/dao/event/BaseEventService.java
  dao/src/main/java/org/thingsboard/server/dao/event/EventDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/event/JpaBaseEventDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/event/RuleNodeDebugEventRepository.java
  dao/src/test/java/org/thingsboard/server/dao/service/AbstractServiceTest.java
  dao/src/test/java/org/thingsboard/server/dao/service/event/BaseEventServiceTest.java
  dao/src/test/java/org/thingsboard/server/dao/sql/event/JpaBaseEventDaoTest.java
Labels: enhancement, Rule Engine

#10532 Create alarm node tests: refactor existing and add new
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/action/TbCreateAlarmNode.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/action/TbAlarmNodeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/action/TbClearAlarmNodeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/action/TbCreateAlarmNodeTest.java
Labels: enhancement, Rule Engine

#10535 State chart widget
  application/src/main/data/json/system/widget_bundles/charts.json
  application/src/main/data/json/system/widget_types/state_chart.json
  application/src/main/data/json/system/widget_types/state_chart_deprecated.json
  ui-ngx/src/app/core/api/data-aggregator.ts
  ui-ngx/src/app/core/api/widget-api.models.ts
  ui-ngx/src/app/modules/home/components/widget/config/basic/chart/time-series-chart-basic-config.component.html
  ui-ngx/src/app/modules/home/components/widget/config/basic/chart/time-series-chart-basic-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/chart/echarts-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/chart/time-series-chart-state.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/chart/time-series-chart.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/chart/time-series-chart.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/chart/time-series-chart-key-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/chart/time-series-chart-key-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/chart/time-series-chart-line-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/chart/time-series-chart-line-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/chart/time-series-chart-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/chart/time-series-chart-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/chart/time-series-chart-axis-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/chart/time-series-chart-axis-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/chart/time-series-chart-state-row.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/chart/time-series-chart-state-row.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/chart/time-series-chart-state-row.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/chart/time-series-chart-states-panel.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/chart/time-series-chart-states-panel.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/chart/time-series-chart-states-panel.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/widget-settings-common.module.ts
  ui-ngx/src/assets/help/en_US/widget/lib/chart/ticks_generator_fn.md
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI, feature

#10540 Set edge client version to 3.6.4
  common/edge-api/src/main/java/org/thingsboard/edge/rpc/EdgeGrpcClient.java
  common/edge-api/src/main/proto/edge.proto
Labels: Ignore for release

#10533 fix_bug_lwm2m tests dif Port
  application/src/test/java/org/thingsboard/server/transport/lwm2m/security/diffPort/AbstractLwM2MIntegrationDiffPortTest.java
  application/src/test/resources/logback-test.xml
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/store/TbInMemoryRegistrationStore.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/store/TbLwM2mRedisRegistrationStore.java
Labels: bug

#10530 Lwm2m msa tests
  docker/docker-compose.yml
  docker/tb-lwm2m-transport.env
  msa/black-box-tests/pom.xml
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/AbstractLwm2mClientTest.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/TestRestClient.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/connectivity/Lwm2mClientNoSecTest.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/connectivity/Lwm2mClientPskTest.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/connectivity/lwm2m/FwLwM2MDevice.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/connectivity/lwm2m/LwM2MTestClient.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/connectivity/lwm2m/LwM2mValueConverterImpl.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/connectivity/lwm2m/Lwm2mTestHelper.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/connectivity/lwm2m/SimpleLwM2MDevice.java
  msa/black-box-tests/src/test/resources/lwm2m-registry/0.xml
  msa/black-box-tests/src/test/resources/lwm2m-registry/1.xml
  msa/black-box-tests/src/test/resources/lwm2m-registry/2.xml
  msa/black-box-tests/src/test/resources/lwm2m-registry/3.xml
  msa/black-box-tests/src/test/resources/lwm2m-registry/5.xml
  msa/black-box-tests/src/test/resources/tb-transports/lwm2m/conf/logback.xml
  msa/tb/README.md
  msa/tb/docker-cassandra/Dockerfile
  msa/tb/docker-postgres/Dockerfile
Labels: Ignore for release

#10582 tbel_encodeDecodeUri_java_as_mdn
  common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/TbUtils.java
  common/script/script-api/src/test/java/org/thingsboard/script/api/tbel/TbUtilsTest.java
Labels: Build Scripts

#10592 Added details description of edge params
  application/src/main/resources/thingsboard.yml
Labels: Ignore for release

#10599 fix_bug_lwm2m_API_getLwm2mObjects
  ui-ngx/src/app/core/http/device-profile.service.ts
Labels: bug, UI

#10269 Added Arabic locale
  ui-ngx/src/assets/locale/locale.constant-ar_AR.json
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI

#10608 Improved detect and set translation platform language
  ui-ngx/package.json
  ui-ngx/src/app/app.component.ts
  ui-ngx/src/app/core/auth/auth.service.ts
  ui-ngx/src/app/core/core.module.ts
  ui-ngx/src/app/core/services/resources.service.ts
  ui-ngx/src/app/core/settings/settings.effects.ts
  ui-ngx/src/app/core/settings/settings.utils.ts
  ui-ngx/src/app/core/translate/translate-default-loader.ts
  ui-ngx/src/app/core/utils.ts
  ui-ngx/src/app/modules/login/pages/login/login.component.html
  ui-ngx/src/app/shared/components/json-content.component.html
  ui-ngx/src/app/shared/components/json-content.component.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
  ui-ngx/yarn.lock
Labels: enhancement, UI, Ignore for release

#10497 Devices activity, connected through the gateway fix
  common/data/src/main/java/org/thingsboard/server/common/data/DataConstants.java
  common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttTransportHandler.java
  common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/AbstractGatewaySessionHandler.java
  common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/GatewaySessionHandler.java
  common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/session/SparkplugNodeSessionHandler.java
  common/transport/mqtt/src/test/java/org/thingsboard/server/transport/mqtt/session/GatewaySessionHandlerTest.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/service/DefaultTransportService.java
Labels: Transport

#10613 fix_bug_redis_decode
  application/src/test/java/org/thingsboard/server/transport/lwm2m/client/LwM2MTestClient.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/store/TbLwM2mRedisRegistrationStore.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/store/TbLwM2mRedisSecurityStore.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/connectivity/lwm2m/LwM2MTestClient.java
Labels: bug

#10618 fix bug_lwm2m_redis_add_ logs
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/store/TbLwM2mRedisSecurityStore.java
Labels: bug

#10623 Improved detect auth user in load
  ui-ngx/src/app/app.component.ts
  ui-ngx/src/app/core/auth/auth.selectors.ts
  ui-ngx/src/app/core/auth/auth.service.ts
  ui-ngx/src/app/shared/components/json-content.component.ts
Labels: UI, Ignore for release

#10612 Limit notification request errors stats
  application/src/test/java/org/thingsboard/server/service/notification/NotificationApiTest.java
  application/src/test/java/org/thingsboard/server/service/notification/NotificationApiWsClient.java
  common/data/src/main/java/org/thingsboard/server/common/data/notification/NotificationRequestStats.java
  ui-ngx/src/app/modules/home/pages/notification/sent/sent-table-config.resolver.ts
  ui-ngx/src/app/shared/models/notification.models.ts
Labels: Ignore for release

#10635 Deleted "required" from tenant email swagger schema
  common/data/src/main/java/org/thingsboard/server/common/data/Tenant.java
Labels: Docs enhancement

#10634 JUnit5 migration in rule-engine-components
  rule-engine/rule-engine-components/pom.xml
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/action/TbCreateRelationNodeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/action/TbDeviceStateNodeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/credentials/CertPemCredentialsTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/edge/TbMsgPushToEdgeNodeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/filter/TbJsFilterNodeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/filter/TbJsSwitchNodeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/geo/GeoUtilTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/math/TbMathArgumentValueTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/metadata/TbGetAttributesNodeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/metadata/TbGetDeviceAttrNodeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/metadata/TbGetTelemetryNodeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/profile/AlarmStateTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/profile/DeviceStateTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/profile/TbDeviceProfileNodeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/rest/TbRestApiCallNodeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/rpc/TbSendRPCReplyNodeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/transform/TbChangeOriginatorNodeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/transform/TbTransformMsgNodeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/util/TenantIdLoaderTest.java
  rule-engine/rule-engine-components/src/test/resources/junit-platform.properties
Labels: enhancement

#10636 docker images upgraded
  dao/src/test/java/org/thingsboard/server/dao/AbstractRedisContainer.java
  docker/docker-compose.hybrid.yml
  docker/docker-compose.kafka.yml
  docker/docker-compose.redis-cluster.yml
  docker/docker-compose.redis-sentinel.yml
  docker/docker-compose.redis.yml
  docker/docker-compose.yml
  msa/black-box-tests/src/test/resources/docker-compose.redis-ssl.yml
Labels: enhancement

#10641 Change locale code ar_AR to ar_AE
  ui-ngx/src/assets/locale/locale.constant-ar_AE.json
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI, Ignore for release

#10651 coap.dtls.connection_id_length added default null value to tolerate yaml inconsistency case
  common/coap-server/src/main/java/org/thingsboard/server/coapserver/TbCoapDtlsSettings.java
Labels: Ignore for release

#10662 Added tests for EntityService
  dao/src/test/java/org/thingsboard/server/dao/service/EntityServiceTest.java
Labels: Ignore for release

#10670 deprecated ISO_DATETIME_TIME_ZONE_FORMAT replaced with ISO_8601_EXTENDED_DATETIME_TIME_ZONE_FORMAT
  dao/src/test/java/org/thingsboard/server/dao/service/event/BaseEventServiceTest.java
  dao/src/test/java/org/thingsboard/server/dao/timeseries/CassandraBaseTimeseriesDaoPartitioningDaysAlwaysExistsTest.java
  dao/src/test/java/org/thingsboard/server/dao/timeseries/CassandraBaseTimeseriesDaoPartitioningHoursAlwaysExistsTest.java
  dao/src/test/java/org/thingsboard/server/dao/timeseries/CassandraBaseTimeseriesDaoPartitioningIndefiniteAlwaysExistsTest.java
  dao/src/test/java/org/thingsboard/server/dao/timeseries/CassandraBaseTimeseriesDaoPartitioningMinutesAlwaysExistsTest.java
  dao/src/test/java/org/thingsboard/server/dao/timeseries/CassandraBaseTimeseriesDaoPartitioningMonthsAlwaysExistsTest.java
  dao/src/test/java/org/thingsboard/server/dao/timeseries/CassandraBaseTimeseriesDaoPartitioningYearsAlwaysExistsTest.java
Labels: Ignore for release

#10672 manage ElasticsearchRestClientHealthIndicator HealthCheck (default is disabled)
  application/src/main/resources/thingsboard.yml
Labels: Ignore for release

#10676 TbCoapDtlsSettingsTest
  common/coap-server/pom.xml
  common/coap-server/src/main/java/org/thingsboard/server/coapserver/TbCoapDtlsSettings.java
  common/coap-server/src/test/java/org/thingsboard/server/coapserver/TbCoapDtlsSettingsTest.java
Labels: Ignore for release

#10454 Added ownerName ENTITY_FIELD to EntityDataQuery
  application/src/test/java/org/thingsboard/server/controller/EntityQueryControllerTest.java
  dao/src/main/java/org/thingsboard/server/dao/sql/query/DefaultEntityQueryRepository.java
  dao/src/main/java/org/thingsboard/server/dao/sql/query/EntityKeyMapping.java
  ui-ngx/src/app/core/http/entity.service.ts
  ui-ngx/src/app/shared/models/entity.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: feature, Core

#10679 Improve mobile notifications stability
  application/src/main/java/org/thingsboard/server/service/notification/channels/MobileAppNotificationChannel.java
Labels: Core

#10681 Fix flaky test testBulkImportDeviceWithUpdateFalse
  application/src/test/java/org/thingsboard/server/controller/DeviceControllerTest.java
Labels: Ignore for release
