Repository thingsboard/thingsboard, pull requests merged in 2024-02, with the labels that each got.

#10105 GitHub workflow license-header-format.yml
  .github/workflows/license-header-format.yml
Labels: Build Scripts

#10097 coap: msa tests
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/AbstractCoapClientTest.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/TestCoapClient.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/TestCoapClientCallback.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/connectivity/CoapClientTest.java
Labels: bug

#10095 Californium_3_11_0_and_PR_2215
  application/src/test/java/org/thingsboard/server/transport/coap/attributes/AbstractCoapAttributesIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/coap/attributes/updates/CoapAttributesUpdatesIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/coap/attributes/updates/CoapAttributesUpdatesJsonIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/coap/attributes/updates/CoapAttributesUpdatesProtoIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/coap/client/CoapClientIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/coap/rpc/AbstractCoapServerSideRpcIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/coap/rpc/CoapServerSideRpcDefaultIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/coap/rpc/CoapServerSideRpcJsonIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/coap/rpc/CoapServerSideRpcProtoIntegrationTest.java
  common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/CoapTransportResource.java
  common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/callback/CoapResponseCallback.java
  common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/callback/CoapResponseCodeCallback.java
  common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/client/DefaultCoapClientContext.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/AbstractCoapClientTest.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/TestCoapClient.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/TestCoapClientCallback.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/connectivity/CoapClientTest.java
  pom.xml
Labels: Core

#10118 Make saveRuleChainMetaData @Transactional
  dao/src/main/java/org/thingsboard/server/dao/rule/BaseRuleChainService.java
Labels: bug

#10137 SNMP: delay between sending request chunks; traps processing fixes
  application/src/main/resources/thingsboard.yml
  common/transport/snmp/src/main/java/org/thingsboard/server/transport/snmp/SnmpTransportContext.java
  common/transport/snmp/src/main/java/org/thingsboard/server/transport/snmp/service/SnmpTransportService.java
  common/transport/snmp/src/main/java/org/thingsboard/server/transport/snmp/session/DeviceSessionContext.java
  common/transport/snmp/src/main/java/org/thingsboard/server/transport/snmp/session/ScheduledTask.java
  common/transport/snmp/src/test/java/org/thingsboard/server/transport/snmp/SnmpDeviceSimulatorV2.java
  common/transport/snmp/src/test/java/org/thingsboard/server/transport/snmp/SnmpTestV2.java
  common/transport/snmp/src/test/resources/snmp-device-profile-transport-config.json
  common/transport/snmp/src/test/resources/snmp-device-transport-config-v3.json
  common/transport/snmp/src/test/resources/snmp-device-transport-config.json
  common/transport/snmp/src/test/resources/snmp_device_profile.json
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/service/DefaultTransportService.java
  transport/snmp/src/main/resources/tb-snmp-transport.yml
Labels: Transport

#9225 Added ssl support for redis
  application/src/main/resources/thingsboard.yml
  common/cache/src/main/java/org/thingsboard/server/cache/RedisSslCredentials.java
  common/cache/src/main/java/org/thingsboard/server/cache/TBRedisCacheConfiguration.java
  common/cache/src/main/java/org/thingsboard/server/cache/TBRedisClusterConfiguration.java
  common/cache/src/main/java/org/thingsboard/server/cache/TBRedisSentinelConfiguration.java
  common/cache/src/main/java/org/thingsboard/server/cache/TBRedisStandaloneConfiguration.java
  common/util/src/main/java/org/thingsboard/common/util/SslUtil.java
  msa/black-box-tests/README.md
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ContainerTestSuite.java
  msa/black-box-tests/src/test/resources/docker-compose.redis-ssl.volumes.yml
  msa/black-box-tests/src/test/resources/docker-compose.redis-ssl.yml
  msa/black-box-tests/src/test/resources/redis-certs/redis.crt
  msa/black-box-tests/src/test/resources/redis-certs/redis.key
  msa/black-box-tests/src/test/resources/redis-certs/redisCA.crt
  transport/coap/src/main/resources/tb-coap-transport.yml
  transport/http/src/main/resources/tb-http-transport.yml
  transport/lwm2m/src/main/resources/tb-lwm2m-transport.yml
  transport/mqtt/src/main/resources/tb-mqtt-transport.yml
  transport/snmp/src/main/resources/tb-snmp-transport.yml
Labels: feature, Core

#10146 Added Transactional for saveDeviceWithAccessToken
  dao/src/main/java/org/thingsboard/server/dao/device/DeviceServiceImpl.java
  dao/src/test/java/org/thingsboard/server/dao/service/DeviceServiceTest.java
Labels: bug

#10162 Power button widget
  application/src/main/data/json/system/widget_bundles/buttons.json
  application/src/main/data/json/system/widget_bundles/control_widgets.json
  application/src/main/data/json/system/widget_types/power_button.json
  ui-ngx/package.json
  ui-ngx/src/app/modules/home/components/widget/config/basic/basic-widget-config.module.ts
  ui-ngx/src/app/modules/home/components/widget/config/basic/button/power-button-basic-config.component.html
  ui-ngx/src/app/modules/home/components/widget/config/basic/button/power-button-basic-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/action/action-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/rpc/power-button-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/rpc/power-button-widget.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/rpc/power-button-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/rpc/power-button-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/button/power-button-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/button/power-button-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/widget-settings.module.ts
  ui-ngx/src/app/modules/home/components/widget/widget-components.module.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
  ui-ngx/src/assets/widget/power-button/default-layout.svg
  ui-ngx/src/assets/widget/power-button/default-volume-layout.svg
  ui-ngx/src/assets/widget/power-button/outlined-layout.svg
  ui-ngx/src/assets/widget/power-button/outlined-volume-layout.svg
  ui-ngx/src/assets/widget/power-button/simplified-layout.svg
  ui-ngx/src/assets/widget/power-button/simplified-volume-layout.svg
  ui-ngx/yarn.lock
Labels: UI, feature

#10158 Lwm2m_without_odservation service.impl_in_root
  application/src/main/java/org/eclipse/leshan/server/observation/ObservationServiceImpl.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2MIntegrationObserveCompositeTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationObserveTest.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/downlink/DefaultLwM2mDownlinkMsgHandler.java
Labels: Core

#10147 Map optimisation improvements for requests of icon images and async rendering
  ui-ngx/src/app/core/http/image.service.ts
  ui-ngx/src/app/modules/home/components/widget/lib/maps/leaflet-map.ts
  ui-ngx/src/app/modules/home/components/widget/lib/maps/markers.ts
Labels: bug, UI

#9798 Update locale.constant-de_DE.json
  ui-ngx/src/assets/locale/locale.constant-de_DE.json
Labels: UI

#9927 Update locale.constant-zh_CN.json
  ui-ngx/src/assets/locale/locale.constant-zh_CN.json
Labels: UI

#9956 Shared some models and components to use in thingsboard-extension
  ui-ngx/src/app/modules/common/modules-map.ts
  ui-ngx/src/app/modules/home/components/public-api.ts
Labels: enhancement, UI

#10036 Fixed progress bar
  ui-ngx/src/app/modules/home/components/vc/repository-settings.component.html
  ui-ngx/src/app/modules/home/components/vc/repository-settings.component.ts
  ui-ngx/src/app/modules/home/components/vc/version-control.component.html
  ui-ngx/src/app/modules/home/home.component.ts
  ui-ngx/src/app/modules/home/pages/account/account-routing.module.ts
  ui-ngx/src/app/modules/home/pages/admin/admin-routing.module.ts
  ui-ngx/src/app/modules/home/pages/admin/oauth2-settings.component.ts
  ui-ngx/src/app/modules/home/pages/admin/security-settings.component.ts
  ui-ngx/src/app/modules/home/pages/admin/two-factor-auth-settings.component.ts
  ui-ngx/src/app/modules/home/pages/home-pages.models.ts
  ui-ngx/src/app/shared/components/page.component.ts
Labels: bug, UI

#10050 Added dynamic volume inputs and other minor improvements for liquid level widget.
  ui-ngx/src/app/modules/home/components/widget/config/basic/indicator/liquid-level-card-basic-config.component.html
  ui-ngx/src/app/modules/home/components/widget/config/basic/indicator/liquid-level-card-basic-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/indicator/liquid-level-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/indicator/liquid-level-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/indicator/liquid-level-card-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/indicator/liquid-level-card-widget-settings.component.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
  ui-ngx/src/form.scss
Labels: enhancement, UI

#10052 Fixed in Thingsboard Iot Gateway dashboard validator gateway configuration
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-configuration.component.ts
Labels: bug, UI

#10062 Added html responsive improvement for SNMP transport config
  ui-ngx/src/app/modules/home/components/profile/device/snmp/snmp-device-profile-communication-config.component.html
  ui-ngx/src/app/modules/home/components/profile/device/snmp/snmp-device-profile-communication-config.component.scss
  ui-ngx/src/app/modules/home/components/profile/device/snmp/snmp-device-profile-mapping.component.html
  ui-ngx/src/app/modules/home/components/profile/device/snmp/snmp-device-profile-mapping.component.scss
Labels: bug, UI

#10064 Improvements for styles and timewindow scss
  ui-ngx/src/app/shared/components/time/timewindow.component.scss
  ui-ngx/src/styles.scss
Labels: enhancement, UI

#10065 Fixed singletonMode info on copy of rule-node
  ui-ngx/src/app/core/services/item-buffer.service.ts
Labels: bug, UI

#10066 For Angular Gridster, increase "maxRows" limit from "100" to "3000"
  ui-ngx/src/app/modules/home/components/dashboard/dashboard.component.ts
Labels: enhancement, UI

#10084 Fixed dynamic links creation for dashboard gateways devices instances details
  application/src/main/data/json/tenant/dashboards/gateways.json
  ui-ngx/src/app/core/api/widget-api.models.ts
  ui-ngx/src/app/modules/home/models/widget-component.models.ts
Labels: bug, UI

#10087 Removed extra > character
  ui-ngx/src/app/shared/components/dashboard-autocomplete.component.html
Labels: bug, UI, Ignore for release

#10088 Replaced hard-coded document link paths with site-base-url
  ui-ngx/src/assets/help/en_US/rulenode/common_node_fields_templatization.md
  ui-ngx/src/assets/help/en_US/rulenode/common_node_script_args.md
  ui-ngx/src/assets/help/en_US/rulenode/switch_node_script_fn.md
  ui-ngx/src/assets/help/en_US/rulenode/tbel/common_node_script_args.md
  ui-ngx/src/assets/help/en_US/rulenode/tbel/switch_node_script_fn.md
Labels: enhancement, UI

#10122 Fixed dashboard entity filter remembers user input on close and cancel
  ui-ngx/src/app/modules/home/components/filter/filters-edit.component.ts
Labels: bug, UI

#10130 Fixed gridster options update for mobile mode
  ui-ngx/src/app/modules/home/components/dashboard/dashboard.component.ts
Labels: bug, UI

#10139 Update toast notification
  ui-ngx/src/app/core/notification/notification.models.ts
  ui-ngx/src/app/modules/home/models/widget-component.models.ts
  ui-ngx/src/app/shared/components/snack-bar-component.html
  ui-ngx/src/app/shared/components/snack-bar-component.scss
  ui-ngx/src/app/shared/components/toast.directive.ts
Labels: UI, feature

#10153 Added new widget action type: Open URL
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/widget-action.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/widget-action.component.ts
  ui-ngx/src/app/modules/home/components/widget/widget.component.ts
  ui-ngx/src/app/shared/models/widget.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI, feature

#10156 Add Polish locale
  ui-ngx/src/assets/locale/locale.constant-en_US.json
  ui-ngx/src/assets/locale/locale.constant-pl_PL.json
Labels: UI, feature

#10195 Slider widget
  application/src/main/data/json/system/widget_bundles/control_widgets.json
  application/src/main/data/json/system/widget_types/progress_bar.json
  application/src/main/data/json/system/widget_types/simple_value_and_chart_card.json
  application/src/main/data/json/system/widget_types/slider.json
  ui-ngx/src/app/modules/home/components/widget/config/basic/basic-widget-config.module.ts
  ui-ngx/src/app/modules/home/components/widget/config/basic/button/power-button-basic-config.component.html
  ui-ngx/src/app/modules/home/components/widget/config/basic/cards/progress-bar-basic-config.component.html
  ui-ngx/src/app/modules/home/components/widget/config/basic/rpc/single-switch-basic-config.component.html
  ui-ngx/src/app/modules/home/components/widget/config/basic/rpc/slider-basic-config.component.html
  ui-ngx/src/app/modules/home/components/widget/config/basic/rpc/slider-basic-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/action/action-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/action/action-widget.scss
  ui-ngx/src/app/modules/home/components/widget/lib/button/action-button-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/button/command-button-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/rpc/power-button-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/rpc/single-switch-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/rpc/slider-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/rpc/slider-widget.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/rpc/slider-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/rpc/slider-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/button/power-button-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/progress-bar-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/set-value-action-settings-panel.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/set-value-action-settings-panel.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/set-value-action-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/button/widget-button-appearance.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/control/single-switch-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/control/slider-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/control/slider-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/widget-settings.module.ts
  ui-ngx/src/app/modules/home/components/widget/widget-components.module.ts
  ui-ngx/src/app/shared/components/toast.directive.ts
  ui-ngx/src/app/shared/models/action-widget-settings.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
  ui-ngx/src/assets/widget/slider/default-layout.svg
  ui-ngx/src/assets/widget/slider/extended-layout.svg
  ui-ngx/src/assets/widget/slider/simplified-layout.svg
Labels: UI, feature

#10187 fix_bug_lwm2m/coap_client_queue_Mode
  common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/client/DefaultCoapClientContext.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mClientContextImpl.java
Labels: bug

#10204 Update rule node core config
  rule-engine/rule-engine-components/src/main/resources/public/static/rulenode/rulenode-core-config.js
Labels: UI, Rule Engine, Ignore for release

#10167 lwm2m_coap: DTLS Cid Length
  application/src/main/resources/thingsboard.yml
  application/src/test/java/org/thingsboard/server/transport/lwm2m/AbstractLwM2MIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/Lwm2mTestHelper.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/client/DtlsSessionLogger.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/client/LwM2MTestClient.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/ota/sql/OtaLwM2MIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/AbstractRpcLwM2MIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/security/AbstractSecurityLwM2MIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/security/cid/AbstractSecurityLwM2MIntegrationDtlsCidLength0Test.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/security/cid/AbstractSecurityLwM2MIntegrationDtlsCidLength3Test.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/security/cid/AbstractSecurityLwM2MIntegrationDtlsCidLengthNullTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/security/cid/AbstractSecurityLwM2MIntegrationDtlsCidLengthTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/security/cid/serverDtlsCidLength_0/NoSecLwM2MIntegrationDtlsCidLengthTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/security/cid/serverDtlsCidLength_0/PskLwm2mIntegrationDtlsCidLengthTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/security/cid/serverDtlsCidLength_3/NoSecLwM2MIntegrationDtlsCidLengthTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/security/cid/serverDtlsCidLength_3/PskLwm2mIntegrationDtlsCidLengthTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/security/cid/serverDtlsCidLength_null/NoSecLwM2MIntegrationDtlsCidLengthTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/security/cid/serverDtlsCidLength_null/PskLwm2mIntegrationDtlsCidLengthTest.java
  common/coap-server/src/main/java/org/thingsboard/server/coapserver/TbCoapDtlsSettings.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/bootstrap/LwM2MTransportBootstrapService.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/config/LwM2MTransportServerConfig.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/DefaultLwM2mTransportService.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/utils/LwM2MTransportUtil.java
  transport/coap/src/main/resources/tb-coap-transport.yml
  transport/lwm2m/src/main/resources/tb-lwm2m-transport.yml
Labels: Core

#10174 RegistrationOnAwakeCclientQueueMode
  application/src/test/java/org/thingsboard/server/transport/lwm2m/AbstractLwM2MIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/client/LwM2MTestClient.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/ota/sql/OtaLwM2MIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/AbstractRpcLwM2MIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/security/AbstractSecurityLwM2MIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/security/sql/NoSecLwM2MIntegrationTest.java
  common/transport/coap/src/main/java/org/thingsboard/server/transport/coap/client/DefaultCoapClientContext.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mClientContextImpl.java
Labels: Core

#9030 Device state rule node; device state service improvements
  application/src/main/java/org/thingsboard/server/actors/ActorSystemContext.java
  application/src/main/java/org/thingsboard/server/actors/ruleChain/DefaultTbContext.java
  application/src/main/java/org/thingsboard/server/service/queue/DefaultTbCoreConsumerService.java
  application/src/main/java/org/thingsboard/server/service/queue/TbCoreConsumerStats.java
  application/src/main/java/org/thingsboard/server/service/state/DefaultDeviceStateService.java
  application/src/main/java/org/thingsboard/server/service/state/DefaultRuleEngineDeviceStateManager.java
  application/src/main/java/org/thingsboard/server/service/state/DeviceStateService.java
  application/src/main/resources/thingsboard.yml
  application/src/test/java/org/thingsboard/server/service/queue/DefaultTbCoreConsumerServiceTest.java
  application/src/test/java/org/thingsboard/server/service/state/DefaultDeviceStateServiceTest.java
  application/src/test/java/org/thingsboard/server/service/state/DefaultRuleEngineDeviceStateManagerTest.java
  common/data/src/test/java/org/thingsboard/server/common/data/msg/TbMsgTypeTest.java
  common/message/src/main/java/org/thingsboard/server/common/msg/TbMsg.java
  common/proto/src/main/proto/queue.proto
  common/queue/src/main/java/org/thingsboard/server/queue/common/SimpleTbQueueCallback.java
  rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/RuleEngineDeviceStateManager.java
  rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/TbContext.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/action/TbDeviceStateNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/action/TbDeviceStateNodeConfiguration.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/action/TbDeviceStateNodeTest.java
Labels: enhancement, feature, Core, Rule Engine

#10205 fixed delete alarm events (device profile node)
  application/src/main/java/org/thingsboard/server/service/edge/EdgeEventSourcingListener.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/BaseEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/alarm/AlarmEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/alarm/BaseAlarmProcessor.java
  application/src/main/java/org/thingsboard/server/service/entitiy/alarm/DefaultTbAlarmService.java
  application/src/test/java/org/thingsboard/server/controller/AlarmControllerTest.java
  application/src/test/java/org/thingsboard/server/service/entitiy/alarm/DefaultTbAlarmServiceTest.java
  common/data/src/main/java/org/thingsboard/server/common/data/edge/EdgeEventActionType.java
  dao/src/main/java/org/thingsboard/server/dao/audit/AuditLogServiceImpl.java
Labels: bug, Core

#10185 Added global queue prefix to js-executor, rule-node and tb-rule-engine-notifications-node- consumer group id
  common/queue/src/main/java/org/thingsboard/server/queue/provider/KafkaMonolithQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/KafkaTbCoreQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/KafkaTbRuleEngineQueueFactory.java
  msa/js-executor/queue/kafkaTemplate.ts
Labels: bug, Core

#10152 CASSANDRA_QUERY_SET_NULL_VALUES_ENABLED=true by default
  application/src/main/resources/thingsboard.yml
Labels: enhancement, Core

#10094 Updated env parameter description for SQL_TTL_TS_TS_KEY_VALUE_TTL
  application/src/main/resources/thingsboard.yml
Labels: Docs enhancement

#10175 Added alarm state handling for IN, NOT_IN types of operation
  common/data/src/main/java/org/thingsboard/server/common/data/StringUtils.java
  dao/src/main/java/org/thingsboard/server/dao/sql/query/EntityKeyMapping.java
  dao/src/test/java/org/thingsboard/server/dao/sql/query/EntityKeyMappingTest.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/profile/AlarmRuleState.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/profile/AlarmRuleStateTest.java
  ui-ngx/src/app/modules/home/components/filter/filter-predicate-value.component.html
  ui-ngx/src/app/modules/home/components/filter/filter-predicate-value.component.ts
  ui-ngx/src/app/modules/home/components/filter/string-filter-predicate.component.html
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: bug, Core

#10189 Change the link to the documentation
  ui-ngx/src/app/shared/models/constants.ts
Labels: enhancement, UI

#10214 Change the link to the documentation (wrong urls)
  ui-ngx/src/app/shared/models/constants.ts
Labels: bug, UI, Ignore for release

#10229 lwm2m: refactoring tests
  application/src/test/java/org/thingsboard/server/transport/lwm2m/AbstractLwM2MIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/client/LwM2MTestClient.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/ota/sql/OtaLwM2MIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/AbstractRpcLwM2MIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/security/AbstractSecurityLwM2MIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/security/cid/AbstractSecurityLwM2MIntegrationDtlsCidLengthTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/security/diffPort/AbstractLwM2MIntegrationDiffPortTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/security/sql/NoSecLwM2MIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/security/sql/PskLwm2mIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/security/sql/RpkLwM2MIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/security/sql/X509_NoTrustLwM2MIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/security/sql/X509_TrustLwM2MIntegrationTest.java
Labels: Transport

#10254 TbDate - use strict constructors instead of constructors with var args
  common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/TbDate.java
Labels: bug

#10265 js executor log memory usage as a single line
  msa/js-executor/api/jsInvokeMessageProcessor.ts
Labels: enhancement

#10173 Added workaround for matChipInputAddOnBlur selection bug in tb-entity-subtype-list input
  ui-ngx/src/app/shared/components/entity/entity-subtype-list.component.html
  ui-ngx/src/app/shared/components/entity/entity-subtype-list.component.ts
Labels: bug, UI

#10177 Fixed dashboard state autocomplete in widget action component
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/widget-action.component.ts
Labels: bug, UI

#10183 Fix the caption to "Relation types to propagate
  ui-ngx/src/app/modules/home/components/profile/alarm/device-profile-alarm.component.html
  ui-ngx/src/assets/locale/locale.constant-en_US.json
  ui-ngx/src/assets/locale/locale.constant-ko_KR.json
  ui-ngx/src/assets/locale/locale.constant-sl_SI.json
Labels: bug, UI

#10206 Fixed typeList URL query and alarm filter config translation
  ui-ngx/src/app/modules/home/components/alarm/alarm-filter-config.component.ts
  ui-ngx/src/app/shared/models/alarm.models.ts
Labels: bug, UI

#10215 Optimized updated image in Image Gallery
  ui-ngx/src/app/shared/components/image/image-dialog.component.ts
  ui-ngx/src/app/shared/components/image/upload-image-dialog.component.ts
  ui-ngx/src/app/shared/models/resource.models.ts
Labels: enhancement, UI

#10227 Typo in send notification component
  ui-ngx/src/app/modules/home/pages/notification/sent/sent-notification-dialog.component.html
Labels: bug, UI, Ignore for release

#10243 Minor fixed in notification dialog
  ui-ngx/src/app/modules/home/pages/notification/sent/sent-notification-dialog.component.html
  ui-ngx/src/app/modules/home/pages/notification/sent/sent-notification-dialog.component.scss
  ui-ngx/src/app/modules/home/pages/notification/sent/sent-notification-dialog.componet.ts
  ui-ngx/src/app/modules/home/pages/notification/template/configuration/notification-template-configuration.component.scss
  ui-ngx/src/app/modules/home/pages/notification/template/template-notification-dialog.component.html
  ui-ngx/src/app/modules/home/pages/notification/template/template-notification-dialog.component.ts
Labels: bug, UI, Ignore for release

#10245 Add hint to setting notification rule Edge communication failure
  ui-ngx/src/app/modules/home/pages/notification/rule/rule-notification-dialog.component.html
Labels: enhancement, UI, Ignore for release

#10247 Required mark and error text were changed in the recipients' field of the notification rule dialog
  ui-ngx/src/app/modules/home/pages/notification/rule/rule-notification-dialog.component.html
Labels: bug, UI

#10262 Space before the required mark has been removed in widget action
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/widget-action.component.html
Labels: bug, UI, Ignore for release

#10268 New services added to Services Map in Widget Context
  ui-ngx/src/app/core/http/public-api.ts
  ui-ngx/src/app/modules/home/models/services.map.ts
Labels: enhancement, UI

#10226 Add the possibility of setting the value range manually in the Signal Strength widget configuration
  application/src/main/data/json/system/widget_types/signal_strength.json
  ui-ngx/src/app/modules/home/components/widget/lib/indicator/signal-strength-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/indicator/signal-strength-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/indicator/signal-strength-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/indicator/signal-strength-widget-settings.component.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI
