Repository thingsboard/thingsboard, pull requests merged in 2024-06, with the labels that each got.

#10848 REST api call reply node help link
  ui-ngx/src/app/shared/models/constants.ts
  ui-ngx/src/app/shared/models/rule-node.models.ts
Labels: enhancement, UI

#10904 Fixed layout with long file name
  ui-ngx/src/app/shared/components/image/gallery-image-input.component.scss
Labels: bug, UI

#10926 fixed component type dropdown in swagger
  application/src/main/java/org/thingsboard/server/controller/ComponentDescriptorController.java
Labels: Ignore for release

#10927 Fixed entity data query for dashboards on customer level
  application/src/test/java/org/thingsboard/server/controller/EntityQueryControllerTest.java
  dao/src/main/java/org/thingsboard/server/dao/sql/query/DefaultEntityQueryRepository.java
Labels: bug

#10919 added rate limits for the gateway device
  application/src/main/java/org/thingsboard/server/controller/TenantProfileController.java
  application/src/main/java/org/thingsboard/server/service/install/update/DefaultDataUpdateService.java
  application/src/test/java/org/thingsboard/server/transport/mqtt/MqttGatewayRateLimitsTest.java
  common/data/src/main/java/org/thingsboard/server/common/data/limit/LimitedApi.java
  common/data/src/main/java/org/thingsboard/server/common/data/tenant/profile/DefaultTenantProfileConfiguration.java
  common/proto/src/main/java/org/thingsboard/server/common/util/ProtoUtils.java
  common/proto/src/main/proto/queue.proto
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/auth/SessionInfoCreator.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/auth/TransportDeviceInfo.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/limits/DefaultTransportRateLimitService.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/limits/TransportLimitsType.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/limits/TransportRateLimitService.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/service/DefaultTransportService.java
  ui-ngx/src/app/modules/home/components/profile/tenant/default-tenant-profile-configuration.component.html
  ui-ngx/src/app/modules/home/components/profile/tenant/default-tenant-profile-configuration.component.ts
  ui-ngx/src/app/modules/home/components/profile/tenant/rate-limits/rate-limits.models.ts
  ui-ngx/src/app/shared/models/limited-api.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: Ignore for release

#10920 Added api to retrieve queue stats entities
  application/src/main/java/org/thingsboard/server/controller/ControllerConstants.java
  application/src/main/java/org/thingsboard/server/controller/QueueStatsController.java
  application/src/test/java/org/thingsboard/server/controller/BaseQueueControllerTest.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/queue/QueueStatsService.java
  dao/src/main/java/org/thingsboard/server/dao/queue/BaseQueueStatsService.java
  dao/src/main/java/org/thingsboard/server/dao/queue/QueueStatsDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/queue/JpaQueueStatsDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/queue/QueueStatsRepository.java
  dao/src/test/java/org/thingsboard/server/dao/service/QueueStatsServiceTest.java
Labels: Ignore for release

#10934 fixed multipart file for image upload in swagger
  application/src/main/java/org/thingsboard/server/controller/ImageController.java
Labels: Ignore for release

#10942 used package name instead of hardcoded for windows packaging
  packaging/java/scripts/windows/install.bat
  packaging/java/scripts/windows/install_dev_db.bat
Labels: enhancement

#10918 Mobile app qr code improvements
  application/src/main/data/json/system/widget_types/mobile_app_qr_code.json
  application/src/main/java/org/thingsboard/server/controller/MobileApplicationController.java
  application/src/main/resources/thingsboard.yml
  common/data/src/main/java/org/thingsboard/server/common/data/mobile/AndroidConfig.java
  common/data/src/main/java/org/thingsboard/server/common/data/mobile/IosConfig.java
  common/data/src/main/java/org/thingsboard/server/common/data/mobile/MobileAppSettings.java
  dao/src/main/java/org/thingsboard/server/dao/mobile/BaseMobileAppSettingsService.java
  ui-ngx/src/app/modules/home/components/widget/config/basic/cards/mobile-app-qr-code-basic-config.component.html
  ui-ngx/src/app/modules/home/components/widget/config/basic/cards/mobile-app-qr-code-basic-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/cards/mobile-app-qr-code-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/mobile-app-qrcode-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/mobile-app-qrcode-widget.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/mobile-app-qrcode-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/mobile-app-qr-code-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/mobile-app-qr-code-widget-settings.component.ts
  ui-ngx/src/app/modules/home/pages/admin/mobile-app-settings.component.html
  ui-ngx/src/app/modules/home/pages/admin/mobile-app-settings.component.ts
  ui-ngx/src/app/shared/models/mobile-app.models.ts
  ui-ngx/src/assets/dashboard/sys_admin_home_page.json
  ui-ngx/src/assets/dashboard/tenant_admin_home_page.json
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI, Ignore for release

#10928 Hotfix for queue statistics
  ui-ngx/src/app/core/http/entity.service.ts
  ui-ngx/src/app/core/http/queue.service.ts
  ui-ngx/src/app/modules/home/components/entity/entity-filter.component.html
  ui-ngx/src/app/modules/home/components/entity/entity-filter.component.ts
  ui-ngx/src/app/shared/components/entity/entity-autocomplete.component.ts
  ui-ngx/src/app/shared/components/entity/entity-type-select.component.ts
  ui-ngx/src/app/shared/models/entity-type.models.ts
  ui-ngx/src/app/shared/models/queue.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: bug, UI, Ignore for release

#10944 Updated widget template for new timeseries widget creation
  ui-ngx/src/app/shared/models/widget.models.ts
Labels: enhancement, UI

#10948 Hot fix for color settings and digital gauge
  ui-ngx/src/app/modules/home/components/widget/config/basic/cards/progress-bar-basic-config.component.html
  ui-ngx/src/app/modules/home/components/widget/config/basic/gauge/digital-simple-gauge-basic-config.component.html
  ui-ngx/src/app/modules/home/components/widget/config/basic/gauge/digital-simple-gauge-basic-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/cards/progress-bar-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/digital-gauge.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/digital-gauge.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/progress-bar-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/color-range-list.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/color-range-list.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/color-range-list.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/color-settings-panel.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/color-settings-panel.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/color-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/gradient.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/gradient.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/gauge/digital-gauge-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/gauge/digital-gauge-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/indicator/battery-level-widget-settings.component.html
  ui-ngx/src/app/shared/models/widget-settings.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: bug, UI, Ignore for release

#10969 Implemented entity field "name" for queue stats entity
  application/src/test/java/org/thingsboard/server/controller/EntityQueryControllerTest.java
  dao/src/main/java/org/thingsboard/server/dao/sql/query/EntityKeyMapping.java
Labels: Ignore for release

#10971 Swagger: fixed the way arrays are displayed in request param
  application/src/main/java/org/thingsboard/server/controller/AlarmController.java
  application/src/main/java/org/thingsboard/server/controller/AssetController.java
  application/src/main/java/org/thingsboard/server/controller/ComponentDescriptorController.java
  application/src/main/java/org/thingsboard/server/controller/DeviceController.java
  application/src/main/java/org/thingsboard/server/controller/EdgeController.java
  application/src/main/java/org/thingsboard/server/controller/NotificationTargetController.java
  application/src/main/java/org/thingsboard/server/controller/NotificationTemplateController.java
  application/src/main/java/org/thingsboard/server/controller/QueueStatsController.java
  application/src/main/java/org/thingsboard/server/controller/TbResourceController.java
  application/src/main/java/org/thingsboard/server/controller/TelemetryController.java
  application/src/main/java/org/thingsboard/server/controller/TenantProfileController.java
  application/src/main/java/org/thingsboard/server/controller/WidgetTypeController.java
Labels: Ignore for release

#10955 Fixed colors for neon gauge
  ui-ngx/src/app/modules/home/components/widget/lib/canvas-digital-gauge.ts
Labels: bug, UI

#10959 Relation filter enhancement
  ui-ngx/src/app/modules/home/components/alias/entity-alias-dialog.component.ts
  ui-ngx/src/app/modules/home/components/relation/relation-filters.component.html
  ui-ngx/src/app/modules/home/components/relation/relation-filters.component.ts
Labels: bug, UI

#10972 Fixed typo translate in api-limit
  ui-ngx/src/app/shared/models/limited-api.models.ts
Labels: bug, UI, Ignore for release

#10976 Fixed notification again not apply new params
  ui-ngx/src/app/modules/home/pages/notification/template/configuration/notification-template-configuration.component.ts
Labels: bug, UI

#10978 Fix_bug lwm2m Bootstrap ShortServerId
  dao/src/main/java/org/thingsboard/server/dao/service/validator/DeviceProfileDataValidator.java
  dao/src/test/java/org/thingsboard/server/dao/service/validator/DeviceProfileDataValidatorTest.java
Labels: bug

#10970 Fix sysadmin notification being sent with tenant mail sender
  application/src/main/java/org/thingsboard/server/service/notification/channels/EmailNotificationChannel.java
  application/src/main/java/org/thingsboard/server/service/notification/channels/SmsNotificationChannel.java
Labels: Ignore for release

#10877 Rest API call node: removed deprecated 'useRedisQueueForMessagePersistence' parameter
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/rest/TbRestApiCallNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/rest/TbRestApiCallNodeConfiguration.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/rest/TbRestApiCallNodeTest.java
Labels: enhancement, Rule Engine

#10549 Send rpc request and send rpc reply nodes: added tests
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/rpc/TbSendRPCReplyNodeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/rpc/TbSendRPCRequestNodeTest.java
Labels: Ignore for release

#10989 Rule node ids seach query: replaced Page with Slice to exclude count query execution
  dao/src/main/java/org/thingsboard/server/dao/sql/rule/RuleNodeRepository.java
  dao/src/test/java/org/thingsboard/server/dao/sql/rule/JpaRuleNodeDaoTest.java
Labels: Ignore for release

#10985 Fixed validation short server id for bootstrap server in LwM2M transport configuration
  ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-bootstrap-config-servers.component.html
  ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-device-config-server.component.html
  ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-device-config-server.component.ts
  ui-ngx/src/assets/locale/locale.constant-ar_AE.json
  ui-ngx/src/assets/locale/locale.constant-ca_ES.json
  ui-ngx/src/assets/locale/locale.constant-cs_CZ.json
  ui-ngx/src/assets/locale/locale.constant-en_US.json
  ui-ngx/src/assets/locale/locale.constant-es_ES.json
  ui-ngx/src/assets/locale/locale.constant-lt_LT.json
  ui-ngx/src/assets/locale/locale.constant-nl_BE.json
  ui-ngx/src/assets/locale/locale.constant-pl_PL.json
  ui-ngx/src/assets/locale/locale.constant-tr_TR.json
  ui-ngx/src/assets/locale/locale.constant-zh_CN.json
  ui-ngx/src/assets/locale/locale.constant-zh_TW.json
Labels: bug, UI, Ignore for release

#10986 Changed docker commands button and pop-up window title in gateway dashboard
  application/src/main/data/json/tenant/dashboards/gateways.json
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI

#11002 Hotfix for color settings
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/color-range-list.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/color-settings-panel.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/gradient.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/gradient.component.ts
Labels: bug, UI, Ignore for release

#11009 Fixed templates display on opening SNMP connector
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc-connector.component.ts
Labels: bug, UI

#10973 Handle TenantNotFoundException for stale subscriptions
  application/src/main/java/org/thingsboard/server/service/subscription/DefaultTbLocalSubscriptionService.java
Labels: Ignore for release

#11024 Refactor stale subs cleanup on ClusterTopologyChangeEvent
  application/src/main/java/org/thingsboard/server/service/subscription/DefaultTbLocalSubscriptionService.java
Labels: Ignore for release

#11043 "Request Timeout." -> "Request timeout"
  ui-ngx/src/app/modules/home/components/widget/lib/rpc/persistent-table.component.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: Ignore for release

#11044 Fix MD5 SNMP authentication protocol
  ui-ngx/src/app/shared/models/device.models.ts
Labels: bug, Transport

#10987 Add tests for LwM2M device profile validation
  dao/src/test/java/org/thingsboard/server/dao/service/validator/DeviceProfileDataValidatorTest.java
Labels: Ignore for release

#11018 Updated TenantProfile swagger example
  application/src/main/java/org/thingsboard/server/controller/TenantProfileController.java
  common/data/src/main/java/org/thingsboard/server/common/data/TenantProfile.java
  common/data/src/main/java/org/thingsboard/server/common/data/tenant/profile/DefaultTenantProfileConfiguration.java
  common/data/src/main/java/org/thingsboard/server/common/data/tenant/profile/TenantProfileConfiguration.java
Labels: Ignore for release

#11005 Fixed cassandra timeseries deletion if partition is INDEFINITE
  dao/src/main/java/org/thingsboard/server/dao/timeseries/CassandraBaseTimeseriesDao.java
Labels: bug, Core

#11056 Mqtt node: set rule node version
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/mqtt/TbMqttNode.java
Labels: Ignore for release

#11064 Edge install instructions update. Use Java 17. Fix tag usage
  application/src/main/data/json/edge/instructions/install/centos/instructions.md
  application/src/main/data/json/edge/instructions/install/ubuntu/instructions.md
  application/src/main/java/org/thingsboard/server/service/edge/instructions/BaseEdgeInstallUpgradeInstructionsService.java
  application/src/main/java/org/thingsboard/server/service/edge/instructions/DefaultEdgeInstallInstructionsService.java
  application/src/main/java/org/thingsboard/server/service/edge/instructions/DefaultEdgeUpgradeInstructionsService.java
Labels: Ignore for release

#10981 Made response topic expression required in gateway dashboard
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc-connector.component.ts
Labels: bug, UI

#10992 Removed dot from the message when connector created/updated successfully
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI

#10996 Added adaptive height for datamaping dialog
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/dialog/mapping-dialog.component.scss
Labels: bug, UI

#11001 Added asterisk symbol in Device Configuration
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/device-info-table.component.html
Labels: bug, UI

#11004 Changed method field in SNMP Connector
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc-connector-templates.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc-connector-templates.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-widget.models.ts
Labels: enhancement, UI

#11007 Added max width to the display of the template name
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc-connector-templates.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc-connector-templates.component.scss
Labels: enhancement, UI

#11015 Added missing inputs for Custom and GRCP Connectors
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/dialog/add-connector-dialog.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/dialog/add-connector-dialog.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-connectors.component.html
Labels: bug, UI

#11017 Removed toggle 'fill configuration with default values'
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/dialog/add-connector-dialog.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/dialog/add-connector-dialog.component.ts
Labels: bug, UI

#11019 Fixed Command launcher pop up and dashboard open after creation
  application/src/main/data/json/tenant/dashboards/gateways.json
Labels: bug, UI

#11022 Optimized the 'Commands' table in the statistics tab
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-configuration.component.scss
Labels: bug, UI

#11023 Fixed mistakes in tooltips - IoT Gateway dashboard
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI

#11028 Fixed jumping rows when updating data in Gateway Logs table
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-logs.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-logs.component.ts
Labels: enhancement, UI

#11036 Added optimization for the fields in Gateway Configuration
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-configuration.component.html
Labels: bug, UI

#11051 Changed Security block for REST Connector
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/rest-connector-secuirity/rest-connector-security.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/rest-connector-secuirity/rest-connector-security.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/connectors-configuration/rest-connector-secuirity/rest-connector-security.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc-connector.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc-connector.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/widget-components.module.ts
Labels: bug, UI

#11062 Removed 'OPCUA ASYNCIO' Connector Type
  application/src/main/data/json/tenant/dashboards/gateways.json
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc-connector.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc-connector.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-service-rpc.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-widget.models.ts
Labels: enhancement, UI

#11038 Made JSON content toolbar visible
  ui-ngx/src/app/shared/components/json-content.component.html
Labels: bug, UI

#11000 Fixed Gateway connectors name form fields
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/dialog/add-connector-dialog.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-connectors.component.html
Labels: bug, UI

#11057 General Config - Security: added static height for username field
  ui-ngx/src/app/modules/home/components/widget/lib/gateway/gateway-configuration.component.html
Labels: bug, UI

#11070 Added Connector Name to Gateway Connector Logs
  application/src/main/data/json/tenant/dashboards/gateways.json
Labels: enhancement, UI

#11079 Label widgets
  application/src/main/data/json/system/widget_bundles/cards.json
  application/src/main/data/json/system/widget_types/label___value_card.json
  application/src/main/data/json/system/widget_types/label_card.json
  ui-ngx/src/app/modules/home/components/widget/config/basic/basic-widget-config.module.ts
  ui-ngx/src/app/modules/home/components/widget/config/basic/cards/label-card-basic-config.component.html
  ui-ngx/src/app/modules/home/components/widget/config/basic/cards/label-card-basic-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/config/basic/cards/label-value-card-basic-config.component.html
  ui-ngx/src/app/modules/home/components/widget/config/basic/cards/label-value-card-basic-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/cards/label-card-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/cards/label-card-widget.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/cards/label-card-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/cards/label-card-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/cards/label-value-card-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/cards/label-value-card-widget.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/cards/label-value-card-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/cards/label-value-card-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/label-card-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/label-card-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/label-value-card-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/label-value-card-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/widget-settings.module.ts
  ui-ngx/src/app/modules/home/components/widget/widget-components.module.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI

#10529 Copy to view node: added tests
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/action/TbCopyAttributesToEntityViewNodeTest.java
Labels: Ignore for release

#10541 Message count node: added tests
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/action/TbMsgCountNodeTest.java
Labels: Ignore for release

#10556 Save timeseries node: added tests
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/telemetry/TbMsgTimeseriesNodeTest.java
Labels: Ignore for release

#10921 AWS nodes: added tests
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/aws/sns/TbSnsNode.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/aws/sns/TbSnsNodeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/aws/sqs/TbSqsNodeTest.java
Labels: Ignore for release
