Repository thingsboard/thingsboard, pull requests merged in 2025-01, with the labels that each got.

#12386 Clear JS executor dependencies and code
  msa/js-executor/api/jsExecutor.models.ts
  msa/js-executor/api/jsInvokeMessageProcessor.ts
  msa/js-executor/api/utils.ts
  msa/js-executor/package.json
  msa/js-executor/queue/kafkaTemplate.ts
  msa/js-executor/yarn.lock
Labels: enhancement, UI, Ignore for release

#12366 tbel test refactoring
  application/src/main/java/org/thingsboard/server/service/ttl/AlarmsCleanUpService.java
  application/src/test/java/org/thingsboard/server/controller/AbstractWebTest.java
  application/src/test/java/org/thingsboard/server/service/script/AbstractTbelInvokeTest.java
  application/src/test/java/org/thingsboard/server/service/script/TbelInvokeDocsIoTest.java
  application/src/test/java/org/thingsboard/server/service/script/TbelInvokeServiceTest.java
  application/src/test/java/org/thingsboard/server/service/ttl/AlarmsCleanUpServiceTest.java
Labels: Ignore for release

#12389 Fixed notification template/rules table not updating after copy creation
  ui-ngx/src/app/modules/home/pages/notification/recipient/recipient-table-config.resolver.ts
  ui-ngx/src/app/modules/home/pages/notification/rule/rule-table-config.resolver.ts
  ui-ngx/src/app/modules/home/pages/notification/template/template-table-config.resolver.ts
Labels: bug, UI

#12405 tbel: add hexToBytesArray, base64ToBytesList
  application/src/test/java/org/thingsboard/server/service/script/TbelInvokeDocsIoTest.java
  common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/TbUtils.java
  common/script/script-api/src/test/java/org/thingsboard/script/api/tbel/TbUtilsTest.java
Labels: Tbel

#12426 Fixed not allow edit release note in mobile application
  ui-ngx/src/app/modules/home/pages/mobile/applications/mobile-app-dialog.component.ts
Labels: bug, UI

#12274 HP SCADA Oil and gas symbols with bundle
  application/src/main/data/json/system/scada_symbols/crane-hp.svg
  application/src/main/data/json/system/scada_symbols/drawwork-hp.svg
  application/src/main/data/json/system/scada_symbols/drill-hp.svg
  application/src/main/data/json/system/scada_symbols/drilling-line-hp.svg
  application/src/main/data/json/system/scada_symbols/drilling-rig-hp.svg
  application/src/main/data/json/system/scada_symbols/hook-hp.svg
  application/src/main/data/json/system/scada_symbols/platform-hp.svg
  application/src/main/data/json/system/scada_symbols/preventer-hp.svg
  application/src/main/data/json/system/scada_symbols/rotor-hp.svg
  application/src/main/data/json/system/widget_bundles/general_high_performance_scada_symbols.json
  application/src/main/data/json/system/widget_bundles/high_performance_scada_oil_gas.json
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI, feature

#12372 Add Meter traditional SCADA symbols
  application/src/main/data/json/system/scada_symbols/meter.svg
  application/src/main/data/json/system/scada_symbols/small-left-meter.svg
  application/src/main/data/json/system/scada_symbols/small-meter.svg
  application/src/main/data/json/system/scada_symbols/small-right-center.svg
  application/src/main/data/json/system/widget_bundles/scada_fluid_system.json
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI, feature

#12393 Fixed blank screen on SCADA editor page refresh in development mode
  ui-ngx/angular.json
  ui-ngx/esbuild/tb-html-fallback-middleware.ts
Labels: bug, UI

#12416 Fixed empty notifications on slow WS connection
  ui-ngx/src/app/modules/home/components/notification/show-notification-popover.component.html
  ui-ngx/src/app/modules/home/components/notification/show-notification-popover.component.ts
Labels: bug, UI

#12414 Fixed mobile app store info validation
  dao/src/main/java/org/thingsboard/server/dao/service/validator/MobileAppDataValidator.java
Labels: bug, Ignore for release

#12444 VC: fix invalid error when checking access to repository
  common/version-control/src/main/java/org/thingsboard/server/service/sync/vc/GitRepository.java
Labels: bug, Core

#12445 Fixed mobile app bundle id null pointer exception after migration
  dao/src/main/java/org/thingsboard/server/dao/mobile/QrCodeSettingServiceImpl.java
Labels: bug, Core

#12398 fix bug: lwm2m update Observe dynamically and between connections
  application/src/test/java/org/thingsboard/server/edge/DeviceProfileEdgeTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/AbstractLwM2MIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/client/LwM2MTestClient.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/client/SimpleLwM2MDevice.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/ota/sql/Ota5LwM2MIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/security/AbstractSecurityLwM2MIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/security/sql/PskLwm2mIntegrationTest.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/uplink/DefaultLwM2mUplinkMsgHandler.java
Labels: bug, Transport

#12427 [Transport] lwm2m client serialization fixes
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/store/util/LwM2MClientSerDes.java
  common/transport/lwm2m/src/test/java/org/thingsboard/server/transport/lwm2m/server/store/util/LwM2MClientSerDesTest.java
Labels: bug, Transport

#12450 Set Edge Client version to 4.0.0
  common/edge-api/src/main/java/org/thingsboard/edge/rpc/EdgeGrpcClient.java
  common/edge-api/src/main/proto/edge.proto
Labels: Ignore for release

#12447 Fixed systemd template Restart parameter
  packaging/java/scripts/control/template.service
Labels: bug, Build Scripts

#12455 Fix issue where drawing a circle didn't work in map widgets
  ui-ngx/src/app/modules/home/components/widget/lib/maps/leaflet-map.ts
Labels: bug, UI

#12456 Fix issue where polygon/circle fill and stroke color functions didn't work in map widgets
  ui-ngx/src/app/modules/home/components/widget/lib/maps/common-maps-utils.ts
Labels: bug, UI

#12457 Synchronize validation rules for the mobile app configuration form with the API
  ui-ngx/src/app/modules/home/pages/mobile/applications/mobile-app.component.html
  ui-ngx/src/app/modules/home/pages/mobile/applications/mobile-app.component.ts
Labels: enhancement, UI

#12485 Fixed incorrect display of negative values in the time series bar chart
  ui-ngx/src/app/modules/home/components/widget/lib/chart/time-series-chart-bar.models.ts
Labels: bug, UI

#12394 Removed default host value for RabbitMQ node
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/rabbitmq/TbRabbitMqNodeConfiguration.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/rabbitmq/TbRabbitMqNodeTest.java
Labels: Ignore for release

#12494 Fixed some of the applied settings not being shown in trip animation widget
  ui-ngx/src/app/modules/home/components/widget/lib/settings/map/trip-animation-widget-settings.component.ts
Labels: bug, UI

#12439 Added custom translation support
  ui-ngx/src/app/modules/home/components/entity/entity-chips.component.html
  ui-ngx/src/app/modules/home/components/relation/relation-table.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/home-page/doc-link.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/home-page/doc-links-widget.component.html
Labels: enhancement, UI

#12442 Fixed both import types active on import dialog open
  ui-ngx/src/app/shared/import-export/import-dialog.component.ts
Labels: bug, UI, Ignore for release

#12443 Fixed columns to display filter panel scroll when on dashboard edge
  ui-ngx/src/app/modules/home/components/widget/lib/display-columns-panel.component.scss
Labels: bug, UI

#12446 Added domain update request chaining
  ui-ngx/src/app/core/http/domain.service.ts
  ui-ngx/src/app/modules/home/pages/admin/oauth2/domains/domain-table-config.resolver.ts
  ui-ngx/src/app/shared/models/oauth2.models.ts
Labels: enhancement, UI

#12470 Fixed oathclient - client id and secret removal with slow internet
  ui-ngx/src/app/modules/home/pages/admin/oauth2/clients/client.component.ts
Labels: bug, UI

#12471 Fixed unnecessary scroll in JS Library alias on error tooltip showing
  ui-ngx/src/app/shared/components/js-func-modules.component.html
Labels: bug, UI

#12511 Fixed issues where 'Update Device Attribute' widgets failed when send data
  application/src/main/data/json/system/widget_types/update_device_attribute.json
Labels: bug, UI

#12528 Fixed validation issues for URLs on the mobile page configuration, including Unicode symbols
  ui-ngx/src/app/modules/home/pages/mobile/bundes/layout/custom-mobile-page.component.ts
  ui-ngx/src/app/shared/models/mobile-app.models.ts
Labels: bug, UI

#12548 Fixed error when using path decorator setting in trip animation widget
  ui-ngx/src/app/modules/home/components/widget/lib/maps/polyline.ts
Labels: bug, UI

#12512 High-performance SCADA energy system widget bundle
  application/src/main/data/json/system/scada_symbols/3-phase-voltage-relay-hp.svg
  application/src/main/data/json/system/scada_symbols/apartments-hp.svg
  application/src/main/data/json/system/scada_symbols/battery-hp.svg
  application/src/main/data/json/system/scada_symbols/bottom-light-bulb-hp.svg
  application/src/main/data/json/system/scada_symbols/consumers-hp.svg
  application/src/main/data/json/system/scada_symbols/curcuit-breaker-hp.svg
  application/src/main/data/json/system/scada_symbols/electrical-distribution-board-hp.svg
  application/src/main/data/json/system/scada_symbols/energy-meter-hp.svg
  application/src/main/data/json/system/scada_symbols/four-rate-energy-meter-hp.svg
  application/src/main/data/json/system/scada_symbols/fuel-generator-hp.svg
  application/src/main/data/json/system/scada_symbols/high-voltage-tower-hp.svg
  application/src/main/data/json/system/scada_symbols/horizontal-curcuit-breaker-hp.svg
  application/src/main/data/json/system/scada_symbols/horizontal-energy-system-controller-hp.svg
  application/src/main/data/json/system/scada_symbols/house-hp.svg
  application/src/main/data/json/system/scada_symbols/industrial-fuel-generator-hp.svg
  application/src/main/data/json/system/scada_symbols/inverter-hp.svg
  application/src/main/data/json/system/scada_symbols/large-inverter-hp.svg
  application/src/main/data/json/system/scada_symbols/low-voltage-tower-hp.svg
  application/src/main/data/json/system/scada_symbols/low-voltage-transformer-tower-hp.svg
  application/src/main/data/json/system/scada_symbols/manufacture-hp.svg
  application/src/main/data/json/system/scada_symbols/power-socket-hp.svg
  application/src/main/data/json/system/scada_symbols/power-transformer-hp.svg
  application/src/main/data/json/system/scada_symbols/single-key-switch-hp.svg
  application/src/main/data/json/system/scada_symbols/small-power-transformer-hp.svg
  application/src/main/data/json/system/scada_symbols/solar-panel-hp.svg
  application/src/main/data/json/system/scada_symbols/stand-solar-panel-hp.svg
  application/src/main/data/json/system/scada_symbols/three-rate-energy-meter-hp.svg
  application/src/main/data/json/system/scada_symbols/top-light-bulb-hp.svg
  application/src/main/data/json/system/scada_symbols/two-key-switch-hp.svg
  application/src/main/data/json/system/scada_symbols/two-rate-energy-meter-hp.svg
  application/src/main/data/json/system/scada_symbols/vertical-energy-system-controller-hp.svg
  application/src/main/data/json/system/scada_symbols/voltage-relay-hp.svg
  application/src/main/data/json/system/scada_symbols/voltage-stabilizer-hp.svg
  application/src/main/data/json/system/scada_symbols/wind-turbine-cluster-hp.svg
  application/src/main/data/json/system/scada_symbols/wind-turbine-hp.svg
  application/src/main/data/json/system/widget_bundles/general_high_performance_scada_symbols.json
  application/src/main/data/json/system/widget_bundles/high_performance_scada_energy_system.json
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI, feature

#12544 Entity data subscription cmds prepare keys without duplicates.
  ui-ngx/src/app/core/api/entity-data-subscription.ts
Labels: enhancement, UI
