Repository thingsboard/thingsboard, pull requests merged in 2025-09, with the labels that each got.

#13941 Fixed occasional duplicated CF evaluations after TB restart
  application/src/main/java/org/thingsboard/server/actors/app/AppActor.java
  application/src/main/java/org/thingsboard/server/actors/calculatedField/CalculatedFieldManagerActor.java
  application/src/main/java/org/thingsboard/server/actors/calculatedField/CalculatedFieldManagerMessageProcessor.java
  application/src/main/java/org/thingsboard/server/actors/tenant/TenantActor.java
  application/src/main/java/org/thingsboard/server/service/cf/DefaultCalculatedFieldCache.java
  common/message/src/main/java/org/thingsboard/server/common/msg/MsgType.java
  common/message/src/main/java/org/thingsboard/server/common/msg/cf/CalculatedFieldInitMsg.java
  common/message/src/main/java/org/thingsboard/server/common/msg/cf/CalculatedFieldInitProfileEntityMsg.java
  common/message/src/main/java/org/thingsboard/server/common/msg/cf/CalculatedFieldLinkInitMsg.java
Labels: Bug, Rule Engine

#13958 Cleanup upgrade for version 4.3.0
  application/src/main/data/upgrade/basic/schema_update.sql
  application/src/main/java/org/thingsboard/server/actors/app/AppActor.java
  application/src/main/java/org/thingsboard/server/actors/calculatedField/CalculatedFieldManagerActor.java
  application/src/main/java/org/thingsboard/server/actors/calculatedField/CalculatedFieldManagerMessageProcessor.java
  application/src/main/java/org/thingsboard/server/actors/tenant/TenantActor.java
  application/src/main/java/org/thingsboard/server/service/cf/DefaultCalculatedFieldCache.java
  application/src/main/java/org/thingsboard/server/service/install/DefaultDatabaseSchemaSettingsService.java
  application/src/main/java/org/thingsboard/server/service/install/update/DefaultDataUpdateService.java
  application/src/test/java/org/thingsboard/server/controller/EntityQueryControllerTest.java
  application/src/test/java/org/thingsboard/server/service/install/update/DefaultDataUpdateServiceTest.java
  common/message/src/main/java/org/thingsboard/server/common/msg/MsgType.java
  common/message/src/main/java/org/thingsboard/server/common/msg/cf/CalculatedFieldInitMsg.java
  common/message/src/main/java/org/thingsboard/server/common/msg/cf/CalculatedFieldInitProfileEntityMsg.java
  common/message/src/main/java/org/thingsboard/server/common/msg/cf/CalculatedFieldLinkInitMsg.java
  dao/src/test/java/org/thingsboard/server/dao/AbstractRedisClusterContainer.java
  dao/src/test/java/org/thingsboard/server/dao/AbstractRedisContainer.java
  dao/src/test/java/org/thingsboard/server/dao/RedisJUnit5Test.java
  docker/docker-compose.kafka.yml
  docker/docker-compose.valkey-cluster.yml
  docker/docker-compose.valkey-sentinel.yml
  docker/docker-compose.valkey.yml
  msa/black-box-tests/src/test/resources/docker-compose.valkey-ssl.yml
  ui-ngx/src/app/modules/home/components/rule-node/external/ai-config.component.ts
Labels: Ignore for release

#13944 Add API Usage widget and update dashboard
  application/src/main/data/json/system/widget_bundles/home_page_widgets.json
  application/src/main/data/json/system/widget_types/api_usage.json
  ui-ngx/src/app/modules/home/components/widget/lib/cards/api-usage-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/cards/api-usage-widget.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/cards/api-usage-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/api-usage-data-key-row.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/api-usage-data-key-row.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/api-usage-data-key-row.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/api-usage-settings.component.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/api-usage-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/api-usage-widget-settings.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/api-usage-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/widget-settings.module.ts
  ui-ngx/src/app/modules/home/components/widget/widget-components.module.ts
  ui-ngx/src/app/modules/home/models/widget-component.models.ts
  ui-ngx/src/assets/dashboard/api_usage.json
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI

#14033 Save to custom table node: remove redundant executor per node
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/action/TbSaveToCustomCassandraTableNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/action/TbSaveToCustomCassandraTableNodeConfiguration.java
Labels: Ignore for release

#13927 Malicious code injection into the SVG image vulnerability
  application/src/main/java/org/thingsboard/server/controller/ImageController.java
Labels: Ignore for release

#14050 NoXss validation enhancements
  common/data/src/main/java/org/thingsboard/server/common/data/mobile/bundle/MobileAppBundle.java
  common/data/src/main/java/org/thingsboard/server/common/data/notification/rule/NotificationRule.java
  common/data/src/main/java/org/thingsboard/server/common/data/notification/rule/NotificationRuleConfig.java
  ui-ngx/src/app/modules/home/components/widget/action/manage-widget-actions.component.ts
Labels: Ignore for release

#14046 Fixed missing values in exported alarm data widget
  application/src/main/java/org/thingsboard/server/service/query/DefaultEntityQueryService.java
  application/src/test/java/org/thingsboard/server/controller/EntityQueryControllerTest.java
Labels: Bug, Core

#13994 Fixed lat/long keys duplication in additional keys list in map widget settings
  ui-ngx/src/app/shared/models/widget/maps/map-model.definition.ts
  ui-ngx/src/app/shared/models/widget/maps/map.models.ts
Labels: enhancement, UI, Ignore for release

#14011 Version control: fixed multiple identical requests, update template style
  ui-ngx/src/app/modules/home/components/vc/complex-version-create.component.html
  ui-ngx/src/app/modules/home/components/vc/complex-version-load.component.html
  ui-ngx/src/app/modules/home/components/vc/entity-types-version-create.component.html
  ui-ngx/src/app/modules/home/components/vc/entity-types-version-create.component.ts
  ui-ngx/src/app/modules/home/components/vc/entity-types-version-load.component.html
  ui-ngx/src/app/modules/home/components/vc/entity-version-create.component.html
  ui-ngx/src/app/modules/home/components/vc/entity-version-restore.component.html
  ui-ngx/src/app/modules/home/components/vc/remove-other-entities-confirm.component.html
  ui-ngx/src/app/shared/components/vc/branch-autocomplete.component.html
  ui-ngx/src/app/shared/components/vc/branch-autocomplete.component.ts
Labels: enhancement, UI

#14012 Fixed decimals support in Liquid level widget
  ui-ngx/src/app/modules/home/components/widget/lib/indicator/liquid-level-widget.component.ts
Labels: Bug, UI

#14027 Fixed XSS vulnerabilities in the Rule node
  ui-ngx/src/app/core/interceptors/global-http-interceptor.ts
  ui-ngx/src/app/core/utils.ts
  ui-ngx/src/app/modules/home/pages/rulechain/rulechain-page.component.ts
Labels: Bug, UI

#14056 Send notification dialog: fix navigation error for Teams
  ui-ngx/src/app/modules/home/pages/notification/sent/sent-notification-dialog.component.html
Labels: Bug, UI

#14037 Fixed API usage cycle reset
  application/src/main/java/org/thingsboard/server/service/apiusage/DefaultTbApiUsageStateService.java
  application/src/test/java/org/thingsboard/server/service/apiusage/DefaultTbApiUsageStateServiceTest.java
  common/message/src/main/java/org/thingsboard/server/common/msg/tools/SchedulerUtils.java
Labels: Bug, Core

#14067 Improved Edge session cleanup to prevent resource leaks and message backlog due to unstable network conditions and Kafka busy timeout
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcService.java
Labels: Ignore for release
