Repository thingsboard/thingsboard, pull requests merged in 2025-06, with the labels that each got.

#13475 Task manager improvements
  application/src/main/java/org/thingsboard/server/controller/BaseController.java
  application/src/main/java/org/thingsboard/server/controller/JobController.java
  application/src/main/java/org/thingsboard/server/service/cf/ctx/state/KafkaCalculatedFieldStateService.java
  application/src/main/java/org/thingsboard/server/service/job/DummyJobProcessor.java
  application/src/main/java/org/thingsboard/server/service/job/task/DummyTaskProcessor.java
  application/src/main/java/org/thingsboard/server/service/queue/DefaultTbCalculatedFieldConsumerService.java
  application/src/main/java/org/thingsboard/server/service/queue/DefaultTbCoreConsumerService.java
  application/src/main/java/org/thingsboard/server/service/queue/DefaultTbEdgeConsumerService.java
  application/src/main/java/org/thingsboard/server/service/queue/ruleengine/TbRuleEngineQueueConsumerManager.java
  application/src/main/java/org/thingsboard/server/service/security/permission/Resource.java
  application/src/main/java/org/thingsboard/server/service/security/permission/TenantAdminPermissions.java
  application/src/test/java/org/thingsboard/server/service/job/JobManagerTest.java
  application/src/test/java/org/thingsboard/server/service/queue/ruleengine/TbRuleEngineStrategyTest.java
  common/data/src/main/java/org/thingsboard/server/common/data/job/DummyJobConfiguration.java
  common/data/src/main/java/org/thingsboard/server/common/data/job/task/DummyTask.java
  common/edqs/src/main/java/org/thingsboard/server/edqs/processor/EdqsProcessor.java
  common/edqs/src/main/java/org/thingsboard/server/edqs/state/KafkaEdqsStateService.java
  common/queue/src/main/java/org/thingsboard/server/queue/common/PartitionedQueueResponseTemplate.java
  common/queue/src/main/java/org/thingsboard/server/queue/common/consumer/MainQueueConsumerManager.java
  common/queue/src/main/java/org/thingsboard/server/queue/task/TaskProcessor.java
Labels: Ignore for release

#13428 Separate rate limits (READ and WRITE) for Cassandra
  application/pom.xml
  application/src/main/data/upgrade/basic/schema_update.sql
  application/src/main/java/org/thingsboard/server/service/install/update/DefaultDataUpdateService.java
  application/src/test/java/org/thingsboard/server/controller/TenantProfileControllerTest.java
  application/src/test/java/org/thingsboard/server/service/limits/RateLimitServiceTest.java
  common/coap-server/pom.xml
  common/data/src/main/java/org/thingsboard/server/common/data/limit/LimitedApi.java
  common/data/src/main/java/org/thingsboard/server/common/data/limit/RateLimitEntry.java
  common/data/src/main/java/org/thingsboard/server/common/data/limit/RateLimitUtil.java
  common/data/src/main/java/org/thingsboard/server/common/data/tenant/profile/DefaultTenantProfileConfiguration.java
  common/data/src/main/java/org/thingsboard/server/common/data/validation/RateLimit.java
  common/data/src/test/java/org/thingsboard/server/common/data/limit/LimitedApiTest.java
  common/data/src/test/java/org/thingsboard/server/common/data/limit/RateLimitUtilTest.java
  common/discovery-api/pom.xml
  common/discovery-api/src/main/java/org/thingsboard/server/queue/discovery/TbServiceInfoProvider.java
  common/edqs/pom.xml
  common/message/src/main/java/org/thingsboard/server/common/msg/tools/TbRateLimits.java
  common/message/src/test/java/org/thingsboard/server/common/msg/tools/TbRateLimitsTest.java
  common/pom.xml
  common/queue/pom.xml
  common/queue/src/main/java/org/thingsboard/server/queue/discovery/DefaultTbServiceInfoProvider.java
  common/transport/transport-api/pom.xml
  dao/pom.xml
  dao/src/main/java/org/thingsboard/server/dao/nosql/CassandraBufferedRateReadExecutor.java
  dao/src/main/java/org/thingsboard/server/dao/nosql/CassandraBufferedRateWriteExecutor.java
  dao/src/main/java/org/thingsboard/server/dao/service/ConstraintValidator.java
  dao/src/main/java/org/thingsboard/server/dao/service/RateLimitValidator.java
  dao/src/main/java/org/thingsboard/server/dao/service/validator/TenantProfileDataValidator.java
  dao/src/main/java/org/thingsboard/server/dao/util/AbstractBufferedRateExecutor.java
  dao/src/main/java/org/thingsboard/server/dao/util/BufferedRateExecutorType.java
  pom.xml
  ui-ngx/src/app/modules/home/components/profile/tenant/default-tenant-profile-configuration.component.html
  ui-ngx/src/app/modules/home/components/profile/tenant/default-tenant-profile-configuration.component.ts
  ui-ngx/src/app/modules/home/components/profile/tenant/rate-limits/rate-limits.models.ts
  ui-ngx/src/app/shared/models/tenant.model.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, Core

#13499 EDQS: fix null uuid customer id after sync
  common/data/src/main/java/org/thingsboard/server/common/data/edqs/fields/AbstractEntityFields.java
Labels: Ignore for release

#13442 Hide zero tooltip for time series charts
  ui-ngx/src/app/modules/home/components/widget/config/basic/chart/time-series-chart-basic-config.component.html
  ui-ngx/src/app/modules/home/components/widget/config/basic/chart/time-series-chart-basic-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/chart/time-series-chart-tooltip.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/chart/time-series-chart-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/chart/time-series-chart-widget-settings.component.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI

#13469 Fixed unit conversion
  ui-ngx/src/app/modules/home/components/widget/config/basic/chart/time-series-chart-basic-config.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/entity/entities-table-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/chart/time-series-chart-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/chart/time-series-chart-threshold-row.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/chart/time-series-chart-threshold-row.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/chart/time-series-chart-thresholds-panel.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/chart/time-series-chart-thresholds-panel.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/chart/time-series-chart-y-axes-panel.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/chart/time-series-chart-y-axes-panel.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/chart/time-series-chart-y-axis-row.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/chart/time-series-chart-y-axis-row.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/table-widget.models.ts
  ui-ngx/src/app/shared/components/unit-settings-panel.component.ts
  ui-ngx/src/app/shared/models/widget-settings.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: bug, UI, Ignore for release

#13500 Improved knob control widgets
  application/src/main/data/json/system/widget_types/knob_control.json
  ui-ngx/src/app/modules/home/components/widget/lib/rpc/knob.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/rpc/knob.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/control/knob-control-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/control/knob-control-widget-settings.component.ts
  ui-ngx/src/app/shared/models/widget/rpc/knob.component.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI

#13501 Add allow created/view relation to rule chain
  ui-ngx/src/app/modules/home/components/relation/relation-dialog.component.html
  ui-ngx/src/app/modules/home/components/relation/relation-dialog.component.ts
  ui-ngx/src/app/shared/components/entity/entity-list-select.component.html
  ui-ngx/src/app/shared/components/entity/entity-list-select.component.ts
Labels: enhancement, UI

#13504 Fixed SCADA connectors arrow color
  application/src/main/data/json/system/scada_symbols/horizontal-connector-hp.svg
  application/src/main/data/json/system/scada_symbols/long-horizontal-connector-hp.svg
  application/src/main/data/json/system/scada_symbols/long-vertical-connector-hp.svg
  application/src/main/data/json/system/scada_symbols/vertical-connector-hp.svg
Labels: bug, UI

#13508 Fixed full screen mode in editors
  ui-ngx/src/app/modules/home/pages/mobile/common/editor-panel.component.ts
  ui-ngx/src/styles.scss
Labels: bug, UI

#13509 Calculated fields: fixed JSON argument handling
  application/src/main/java/org/thingsboard/server/service/cf/ctx/state/SingleValueArgumentEntry.java
Labels: bug, Core

#13506 Edqs - VersionStore - Use local cache instead of caffeine to reduce memory heap size
  common/edqs/src/main/java/org/thingsboard/server/edqs/processor/EdqsProcessor.java
  common/edqs/src/main/java/org/thingsboard/server/edqs/state/KafkaEdqsStateService.java
  common/edqs/src/main/java/org/thingsboard/server/edqs/util/VersionsStore.java
Labels: Ignore for release

#13517 Fixed details panel button freeze midway in firefox
  ui-ngx/src/scss/animations.scss
Labels: bug, UI

#13519 Fixed visible elements behind widget preview
  ui-ngx/src/app/modules/home/components/dashboard-page/edit-widget.component.scss
Labels: bug, UI

#13520 Fixed lwm2m device profile object configuration checkbox alignment
  ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-observe-attr-telemetry-instances.component.scss
  ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-observe-attr-telemetry-resources.component.html
Labels: bug, UI

#13525 Fixed advanced button style on edit action
  ui-ngx/src/app/modules/home/components/widget/action/widget-action-dialog.component.ts
Labels: bug, UI, Ignore for release

#13533 Added "Confirm OTA Update" title to the OTA update confirmation dialog
  ui-ngx/src/app/core/http/ota-package.service.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI

#13539 Fixed tooltip with string false and empty tooltip
  ui-ngx/src/app/modules/home/components/widget/lib/chart/time-series-chart-tooltip.models.ts
Labels: bug, UI, Ignore for release

#13548 Handle ExecutionException in controllers
  application/src/main/java/org/thingsboard/server/controller/BaseController.java
Labels: Ignore for release

#13487 KafkaEdgeGrpcSession - Stability Improvements During Core Service Restarts or Network Timeouts
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcService.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/KafkaEdgeGrpcSession.java
Labels: bug, Edge, Ignore for release

#13549 Fixed dynamicly update slider on input value change for Rule notification dialog
  ui-ngx/src/app/modules/home/pages/notification/rule/rule-notification-dialog.component.html
Labels: bug, UI, Ignore for release

#13550 Prevent deleting an (entity alias/filter) that’s still used in map widgets
  ui-ngx/src/app/core/services/dashboard-utils.service.ts
  ui-ngx/src/app/core/services/item-buffer.service.ts
  ui-ngx/src/app/modules/home/components/alias/entity-aliases-dialog.component.ts
  ui-ngx/src/app/modules/home/components/filter/filters-dialog.component.ts
  ui-ngx/src/app/shared/models/widget/maps/map-model.definition.ts
  ui-ngx/src/app/shared/models/widget/widget-model.definition.ts
Labels: bug, UI

#13552 Make last day selection default in Range (Time window History)
  ui-ngx/src/app/shared/components/time/timewindow-panel.component.ts
Labels: bug, UI

#13564 Fixed NPE when load resource version
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/ResourceImportService.java
Labels: Ignore for release

#13566 Fixed updating timewindow configuration
  ui-ngx/src/app/shared/models/time/time.models.ts
Labels: bug, UI, Ignore for release

#13559 EdgeGrpcService - destroy if previous session exists
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcService.java
Labels: Edge, Ignore for release

#13561 EDQS - added SQL like style for filter contains/starts with/ends with
  common/edqs/src/main/java/org/thingsboard/server/edqs/query/processor/AbstractEntityProfileNameQueryProcessor.java
  common/edqs/src/main/java/org/thingsboard/server/edqs/query/processor/AbstractEntityProfileQueryProcessor.java
  common/edqs/src/main/java/org/thingsboard/server/edqs/query/processor/EntityNameQueryProcessor.java
  common/edqs/src/main/java/org/thingsboard/server/edqs/util/RepositoryUtils.java
  edqs/src/test/java/org/thingsboard/server/edqs/repo/RepositoryUtilsTest.java
Labels: Ignore for release

#13590 Credentials expansion paned expanded by default
  ui-ngx/src/app/modules/home/components/rule-node/common/credentials-config.component.html
Labels: enhancement, UI, Ignore for release

#13602 Fix testCancelJob_whileRunning
  application/src/test/java/org/thingsboard/server/service/job/JobManagerTest.java
Labels: Ignore for release

#13570 Memory usage improvements
  common/actor/src/main/java/org/thingsboard/server/actors/TbActorMailbox.java
  common/data/src/main/java/org/thingsboard/server/common/data/AdminSettings.java
  common/data/src/main/java/org/thingsboard/server/common/data/BaseData.java
  common/data/src/main/java/org/thingsboard/server/common/data/Dashboard.java
  common/data/src/main/java/org/thingsboard/server/common/data/rule/RuleNode.java
  common/data/src/main/java/org/thingsboard/server/common/data/settings/UserSettings.java
  common/data/src/main/java/org/thingsboard/server/common/data/widget/WidgetType.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/config/ssl/KeystoreSslCredentials.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/config/ssl/PemSslCredentials.java
Labels: enhancement, Rule Engine

#13609 Fix some flaky tests
  application/src/test/java/org/thingsboard/server/service/job/JobManagerTest.java
  application/src/test/java/org/thingsboard/server/service/queue/ruleengine/TbRuleEngineQueueConsumerManagerTest.java
Labels: Ignore for release

#13620 Add new units definition MBtu, MMBtu and BTU/d
  ui-ngx/src/app/shared/models/units/energy.ts
  ui-ngx/src/app/shared/models/units/power.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI, Ignore for release

#13621 Exclude mqtt version select in azure rule node
  ui-ngx/src/app/modules/home/components/rule-node/external/azure-iot-hub-config.component.html
  ui-ngx/src/app/modules/home/components/rule-node/external/azure-iot-hub-config.component.ts
  ui-ngx/src/app/shared/components/mqtt-version-select.component.ts
Labels: enhancement, UI, Ignore for release

#13627 Fix showing outdated system resource info on tenant level
  application/src/test/java/org/thingsboard/server/controller/TbResourceControllerTest.java
  common/cache/src/main/java/org/thingsboard/server/cache/resourceInfo/ResourceInfoCacheKey.java
  dao/src/main/java/org/thingsboard/server/dao/resource/BaseResourceService.java
Labels: bug, Core

#13641 Added missing fields for RPC message in cluster mode
  common/proto/src/main/java/org/thingsboard/server/common/util/ProtoUtils.java
  common/proto/src/main/proto/queue.proto
Labels: bug, Core

#13642 Add new unit in/s and capitalize unit name
  ui-ngx/src/app/shared/models/units/speed.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI, Ignore for release

#13494 Added calculated fields sync for Edge
  application/src/main/java/org/thingsboard/server/service/edge/EdgeContextComponent.java
  application/src/main/java/org/thingsboard/server/service/edge/EdgeEventSourcingListener.java
  application/src/main/java/org/thingsboard/server/service/edge/EdgeMsgConstructorUtils.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeSyncCursor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/BaseEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/asset/AssetEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/cf/BaseCalculatedFieldProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/cf/CalculatedFieldEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/cf/CalculatedFieldProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/device/DeviceEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/sync/DefaultEdgeRequestsService.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/sync/EdgeRequestsService.java
  application/src/test/java/org/thingsboard/server/edge/AbstractEdgeTest.java
  application/src/test/java/org/thingsboard/server/edge/CalculatedFieldEdgeTest.java
  application/src/test/java/org/thingsboard/server/edge/imitator/EdgeImitator.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/cf/CalculatedFieldService.java
  common/data/src/main/java/org/thingsboard/server/common/data/edge/EdgeEventType.java
  common/data/src/main/java/org/thingsboard/server/common/data/id/EntityIdFactory.java
  common/edge-api/src/main/java/org/thingsboard/edge/rpc/EdgeGrpcClient.java
  common/edge-api/src/main/proto/edge.proto
  dao/src/main/java/org/thingsboard/server/dao/cf/BaseCalculatedFieldService.java
  dao/src/main/java/org/thingsboard/server/dao/cf/CalculatedFieldDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/cf/CalculatedFieldRepository.java
  dao/src/main/java/org/thingsboard/server/dao/sql/cf/JpaCalculatedFieldDao.java
Labels: enhancement, Edge

#13562 Version control support for OTA packages
  application/src/main/data/upgrade/basic/schema_update.sql
  application/src/main/java/org/thingsboard/server/controller/OtaPackageController.java
  application/src/main/java/org/thingsboard/server/service/entitiy/ota/DefaultTbOtaPackageService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/DefaultEntitiesExportImportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/exporting/impl/DeviceExportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/exporting/impl/DeviceProfileExportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/exporting/impl/OtaPackageExportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/BaseEntityImportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/DeviceImportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/DeviceProfileImportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/OtaPackageImportService.java
  application/src/test/java/org/thingsboard/server/service/sync/ie/ExportImportServiceSqlTest.java
  application/src/test/java/org/thingsboard/server/service/sync/vc/VersionControlTest.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/ota/OtaPackageService.java
  common/data/src/main/java/org/thingsboard/server/common/data/OtaPackage.java
  common/data/src/main/java/org/thingsboard/server/common/data/OtaPackageInfo.java
  common/data/src/main/java/org/thingsboard/server/common/data/TbResource.java
  common/data/src/main/java/org/thingsboard/server/common/data/id/OtaPackageId.java
  common/data/src/main/java/org/thingsboard/server/common/data/sync/JsonTbEntity.java
  common/data/src/main/java/org/thingsboard/server/common/data/sync/ie/EntityExportData.java
  common/data/src/main/java/org/thingsboard/server/common/data/sync/ie/OtaPackageExportData.java
  common/data/src/main/java/org/thingsboard/server/common/data/sync/vc/request/create/AutoVersionCreateConfig.java
  common/util/src/main/java/org/thingsboard/common/util/JacksonUtil.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/OtaPackageEntity.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/OtaPackageInfoEntity.java
  dao/src/main/java/org/thingsboard/server/dao/ota/BaseOtaPackageService.java
  dao/src/main/java/org/thingsboard/server/dao/ota/OtaPackageDao.java
  dao/src/main/java/org/thingsboard/server/dao/service/validator/OtaPackageDataValidator.java
  dao/src/main/java/org/thingsboard/server/dao/sql/JpaAbstractDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/asset/JpaAssetDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/ota/JpaOtaPackageDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/ota/OtaPackageInfoRepository.java
  dao/src/main/java/org/thingsboard/server/dao/sql/ota/OtaPackageRepository.java
  dao/src/main/resources/sql/schema-entities-idx.sql
  dao/src/main/resources/sql/schema-entities.sql
  ui-ngx/src/app/modules/home/pages/admin/admin.module.ts
  ui-ngx/src/app/modules/home/pages/admin/resource/resource-library-tabs.component.html
  ui-ngx/src/app/modules/home/pages/admin/resource/resource-library-tabs.component.ts
  ui-ngx/src/app/modules/home/pages/admin/resource/resources-library-table-config.resolve.ts
  ui-ngx/src/app/modules/home/pages/ota-update/ota-update-table-config.resolve.ts
  ui-ngx/src/app/modules/home/pages/ota-update/ota-update-tabs.component.html
  ui-ngx/src/app/modules/home/pages/ota-update/ota-update-tabs.component.ts
  ui-ngx/src/app/modules/home/pages/ota-update/ota-update.module.ts
  ui-ngx/src/app/shared/models/entity-type.models.ts
  ui-ngx/src/app/shared/models/ota-package.models.ts
  ui-ngx/src/app/shared/models/vc.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: feature, Core

#13607 EDQS: handle Kafka response sending error
  common/cluster-api/src/main/java/org/thingsboard/server/queue/TbQueueHandler.java
  common/edqs/src/main/java/org/thingsboard/server/edqs/processor/EdqsProcessor.java
  common/queue/src/main/java/org/thingsboard/server/queue/common/PartitionedQueueResponseTemplate.java
Labels: enhancement, Core

#13659 Fixed detect changes for entities and alarm tables
  ui-ngx/src/app/modules/home/components/widget/lib/alarm/alarms-table-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/entity/entities-table-widget.component.ts
Labels: bug, UI, Ignore for release

#13394 Fix for widgetTitlePanel templateOutlet
  ui-ngx/src/app/modules/home/components/widget/lib/chart/bar-chart-with-labels-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/chart/bar-chart-with-labels-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/chart/range-chart-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/chart/range-chart-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/chart/time-series-chart-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/chart/time-series-chart-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/maps/map-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/maps/map-widget.component.ts
Labels: bug, UI
