Repository thingsboard/thingsboard, pull requests merged in 2025-07, with the labels that each got.

#13669 Fixed no type-cast for attributes when adding from UI
  application/src/main/java/org/thingsboard/server/controller/TelemetryController.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/telemetry/BaseTelemetryProcessor.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/csv/AbstractBulkImportService.java
  common/proto/src/main/java/org/thingsboard/server/common/adaptor/JsonConverter.java
  common/proto/src/test/java/org/thingsboard/server/common/adaptor/JsonConverterTest.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/action/TbCopyAttributesToEntityViewNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/profile/DeviceState.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/telemetry/TbCalculatedFieldsNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/telemetry/TbMsgAttributesNode.java
Labels: bug, Core

#13689 Fixed consuming wrong rate limit for devices connected via gateway
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/limits/DefaultTransportRateLimitService.java
Labels: bug, Transport

#13701 MQTT: validate client id length based on protocol version
  common/data/src/main/java/org/thingsboard/server/common/data/DataConstants.java
  netty-mqtt/src/main/java/org/thingsboard/mqtt/ChannelClosedException.java
  netty-mqtt/src/main/java/org/thingsboard/mqtt/MqttClientCallback.java
  netty-mqtt/src/main/java/org/thingsboard/mqtt/MqttClientConfig.java
  netty-mqtt/src/main/java/org/thingsboard/mqtt/MqttClientImpl.java
  netty-mqtt/src/main/java/org/thingsboard/mqtt/MqttConnectResult.java
  netty-mqtt/src/main/java/org/thingsboard/mqtt/MqttSubscription.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/mqtt/TbMqttNode.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/mqtt/TbMqttNodeTest.java
Labels: enhancement, Rule Engine

#13707 tbel_add_ExecutionLinkedHashSet
  application/src/test/java/org/thingsboard/server/service/script/TbelInvokeDocsIoTest.java
  common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/TbUtils.java
  common/script/script-api/src/test/java/org/thingsboard/script/api/tbel/TbUtilsTest.java
  pom.xml
Labels: Tbel

#13663 Style fix for custom action editor
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/custom-action-pretty-editor.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/custom-action-pretty-editor.component.scss
Labels: bug, UI

#13679 Improved mobile configuration dialog: replace manual setup with JSON config file
  application/src/main/data/upgrade/basic/schema_update.sql
  common/data/src/main/java/org/thingsboard/server/common/data/mobile/app/MobileApp.java
  dao/src/main/java/org/thingsboard/server/dao/model/ModelConstants.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/MobileAppEntity.java
  dao/src/main/resources/sql/schema-entities.sql
  ui-ngx/src/app/modules/home/pages/mobile/applications/mobile-app-table-config.resolver.ts
  ui-ngx/src/app/modules/home/pages/mobile/applications/mobile-app.component.html
  ui-ngx/src/app/modules/home/pages/mobile/applications/mobile-app.component.ts
  ui-ngx/src/app/modules/home/pages/mobile/bundes/mobile-app-configuration-dialog.component.html
  ui-ngx/src/app/modules/home/pages/mobile/bundes/mobile-app-configuration-dialog.component.ts
  ui-ngx/src/app/modules/home/pages/mobile/bundes/mobile-bundle-table-config.resolve.ts
  ui-ngx/src/app/shared/import-export/import-export.service.ts
  ui-ngx/src/app/shared/models/mobile-app.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI

#13680 Enhancement Mobile center Applications form label
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI

#13682 Fix rewrite of dashboard duplicate state with same id
  ui-ngx/src/app/modules/home/components/dashboard-page/states/manage-dashboard-states-dialog.component.ts
Labels: bug, UI

#13748 Fix race condition in EntitiesDataSource loadEntities by cancelling previous requests
  ui-ngx/src/app/modules/home/models/datasource/entity-datasource.ts
Labels: bug, UI

#13754 Fixed MQTT client disconnect
  netty-mqtt/src/main/java/org/thingsboard/mqtt/MqttClientImpl.java
Labels: bug, Core

#13744 RPM packaging support for java-17-openjdk-headless
  packaging/java/build.gradle
Labels: Build Scripts

#13741 Create alarm node: process message asynchronously to avoid blocking dispatcher thread
  application/src/main/java/org/thingsboard/server/service/telemetry/DefaultAlarmSubscriptionService.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/alarm/AlarmService.java
  dao/src/main/java/org/thingsboard/server/dao/alarm/AlarmDao.java
  dao/src/main/java/org/thingsboard/server/dao/alarm/BaseAlarmService.java
  dao/src/main/java/org/thingsboard/server/dao/sql/alarm/JpaAlarmDao.java
  rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/RuleEngineAlarmService.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/action/TbCreateAlarmNode.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/action/TbCreateAlarmNodeTest.java
Labels: enhancement, Rule Engine

#13747 Fixed vulnerabilites and updated libraries
  application/pom.xml
  application/src/main/java/org/thingsboard/server/config/ThingsboardSecurityConfiguration.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/config/ssl/SslCredentialsWebServerCustomizer.java
  dao/src/main/java/org/thingsboard/server/dao/model/BaseSqlEntity.java
  dao/src/main/java/org/thingsboard/server/dao/sql/IdGenerator.java
  dao/src/main/java/org/thingsboard/server/dao/sql/JpaAbstractDao.java
  pom.xml
  rule-engine/rule-engine-components/pom.xml
Labels: enhancement, Major Core

#13771 Fix error message in Alarm widget preview when opening Assign field dropdown
  ui-ngx/src/app/modules/home/components/widget/lib/alarm/alarms-table-widget.component.ts
Labels: bug, UI

#13772 Stabilize calculated field argument settings popover position on argument type change
  ui-ngx/src/app/modules/home/components/calculated-fields/components/arguments-table/calculated-field-arguments-table.component.ts
Labels: bug, UI

#13751 Fixed EDQS entity field filter for numeric values saved as string
  common/edqs/src/main/java/org/thingsboard/server/edqs/data/dp/StringDataPoint.java
  edqs/src/test/java/org/thingsboard/server/edqs/repo/EntityTypeFilterTest.java
Labels: bug, Core

#13777 Fixed handling of RPC with missing additional info in cluster mode
  application/src/main/java/org/thingsboard/server/actors/device/DeviceActorMessageProcessor.java
  common/proto/src/main/java/org/thingsboard/server/common/util/ProtoUtils.java
  common/proto/src/main/proto/queue.proto
  common/proto/src/test/java/org/thingsboard/server/common/util/ProtoUtilsTest.java
Labels: bug, Core

#13651 Added per-edge stats
  application/src/main/java/org/thingsboard/server/service/edge/EdgeContextComponent.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/KafkaEdgeEventService.java
  application/src/main/java/org/thingsboard/server/service/edge/stats/EdgeStatsService.java
  application/src/main/resources/thingsboard.yml
  application/src/test/java/org/thingsboard/server/service/edge/EdgeStatsTest.java
  common/queue/src/main/java/org/thingsboard/server/queue/kafka/TbKafkaAdmin.java
  dao/src/main/java/org/thingsboard/server/dao/edge/PostgresEdgeEventService.java
  dao/src/main/java/org/thingsboard/server/dao/edge/stats/EdgeStatsCounterService.java
  dao/src/main/java/org/thingsboard/server/dao/edge/stats/EdgeStatsKey.java
  dao/src/main/java/org/thingsboard/server/dao/edge/stats/MsgCounters.java
Labels: enhancement, Edge

#13794 Fix Slack files upload support
  application/src/main/java/org/thingsboard/server/service/notification/provider/DefaultSlackService.java
  common/data/src/main/java/org/thingsboard/server/common/data/notification/targets/slack/SlackFile.java
  rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/notification/SlackService.java
Labels: Ignore for release

#13780 Fixed line width for Cross connector HP SCADA symbol
  application/src/main/data/json/system/scada_symbols/cross-connector-hp.svg
Labels: bug, UI

#13798 Fixed widget preview height in widget type autocomplete
  ui-ngx/src/app/modules/home/pages/widget/widget-type-autocomplete.component.scss
Labels: bug, UI
