Repository thingsboard/thingsboard, pull requests merged in 2025-05, with the labels that each got.

#13253 Fixed an issue with broken pagination settings validation in table-widgets
  ui-ngx/src/app/modules/home/components/widget/lib/alarm/alarms-table-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/entity/entities-table-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/rpc/persistent-table.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/table-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/timeseries-table-widget.component.ts
Labels: bug, UI

#13289 Fixed incorrect help links for calculated fields
  ui-ngx/src/app/shared/models/constants.ts
Labels: bug, UI

#13290 Improved Nederlands (België) translation
  ui-ngx/src/assets/locale/locale.constant-nl_BE.json
Labels: enhancement, UI

#13301 Added Trendz setting
  application/src/main/java/org/thingsboard/server/controller/SystemInfoController.java
  application/src/main/java/org/thingsboard/server/controller/TrendzController.java
  application/src/main/java/org/thingsboard/server/service/security/permission/SysAdminPermissions.java
  application/src/main/resources/thingsboard.yml
  application/src/test/java/org/thingsboard/server/controller/TrendzControllerTest.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/trendz/TrendzSettingsService.java
  common/data/src/main/java/org/thingsboard/server/common/data/CacheConstants.java
  common/data/src/main/java/org/thingsboard/server/common/data/SystemParams.java
  common/data/src/main/java/org/thingsboard/server/common/data/trendz/TrendzSettings.java
  dao/src/main/java/org/thingsboard/server/dao/tenant/TenantServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/trendz/DefaultTrendzSettingsService.java
  dao/src/test/resources/application-test.properties
  ui-ngx/src/app/core/auth/auth.models.ts
  ui-ngx/src/app/core/auth/auth.reducer.ts
  ui-ngx/src/app/core/http/public-api.ts
  ui-ngx/src/app/core/http/trendz-settings.service.ts
  ui-ngx/src/app/core/services/menu.models.ts
  ui-ngx/src/app/modules/home/models/services.map.ts
  ui-ngx/src/app/modules/home/pages/admin/admin-routing.module.ts
  ui-ngx/src/app/modules/home/pages/admin/admin.module.ts
  ui-ngx/src/app/modules/home/pages/admin/trendz-settings.component.html
  ui-ngx/src/app/modules/home/pages/admin/trendz-settings.component.scss
  ui-ngx/src/app/modules/home/pages/admin/trendz-settings.component.ts
  ui-ngx/src/app/shared/models/constants.ts
  ui-ngx/src/app/shared/models/icon.models.ts
  ui-ngx/src/app/shared/models/public-api.ts
  ui-ngx/src/app/shared/models/trendz-settings.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI, feature

#13148 Make Kafka consumer properties configurable for overridden topic names
  application/src/main/resources/thingsboard.yml
  common/data/src/main/java/org/thingsboard/server/common/data/TbProperty.java
  common/queue/src/main/java/org/thingsboard/server/queue/kafka/TbKafkaSettings.java
  common/queue/src/main/java/org/thingsboard/server/queue/util/PropertyUtils.java
  common/queue/src/test/java/org/thingsboard/server/queue/kafka/TbKafkaSettingsTest.java
  edqs/src/main/resources/edqs.yml
  msa/vc-executor/src/main/resources/tb-vc-executor.yml
  transport/coap/src/main/resources/tb-coap-transport.yml
  transport/http/src/main/resources/tb-http-transport.yml
  transport/lwm2m/src/main/resources/tb-lwm2m-transport.yml
  transport/mqtt/src/main/resources/tb-mqtt-transport.yml
  transport/snmp/src/main/resources/tb-snmp-transport.yml
Labels: enhancement, Core

#13322 Automatic relations creation between Rule Chains when adding "Rule Chain" node
  application/src/main/java/org/thingsboard/server/service/install/update/DefaultDataUpdateService.java
  common/data/src/main/java/org/thingsboard/server/common/data/relation/EntityRelation.java
  dao/src/main/java/org/thingsboard/server/dao/rule/BaseRuleChainService.java
  dao/src/test/java/org/thingsboard/server/dao/service/RuleChainServiceTest.java
Labels: feature, Rule Engine

#12257 Used TbMsgProto instead of ByteString
  application/src/main/java/org/thingsboard/server/actors/ruleChain/DefaultTbContext.java
  application/src/main/java/org/thingsboard/server/actors/ruleChain/RuleChainActorMessageProcessor.java
  application/src/main/java/org/thingsboard/server/actors/ruleChain/RuleNodeActorMessageProcessor.java
  application/src/main/java/org/thingsboard/server/service/device/DeviceProvisionServiceImpl.java
  application/src/main/java/org/thingsboard/server/service/queue/processing/SequentialByOriginatorIdTbRuleEngineSubmitStrategy.java
  application/src/main/java/org/thingsboard/server/service/queue/processing/TbRuleEngineProcessingStrategyFactory.java
  application/src/main/java/org/thingsboard/server/service/queue/ruleengine/TbRuleEngineQueueConsumerManager.java
  application/src/main/java/org/thingsboard/server/service/rpc/DefaultTbRuleEngineRpcService.java
  application/src/main/java/org/thingsboard/server/service/ruleengine/DefaultRuleEngineCallService.java
  application/src/test/java/org/thingsboard/server/actors/rule/DefaultTbContextTest.java
  application/src/test/java/org/thingsboard/server/controller/TenantControllerTest.java
  application/src/test/java/org/thingsboard/server/service/queue/ruleengine/TbRuleEngineQueueConsumerManagerTest.java
  application/src/test/java/org/thingsboard/server/service/queue/ruleengine/TbRuleEngineStrategyTest.java
  application/src/test/java/org/thingsboard/server/service/rpc/DefaultTbRuleEngineRpcServiceTest.java
  application/src/test/java/org/thingsboard/server/service/ruleengine/DefaultRuleEngineCallServiceTest.java
  common/message/src/main/java/org/thingsboard/server/common/msg/TbMsg.java
  common/proto/src/main/proto/queue.proto
  common/queue/src/main/java/org/thingsboard/server/queue/common/TbRuleEngineProducerService.java
Labels: enhancement, Rule Engine

#12905 Version control: fixed resource restoring
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/AssetImportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/AssetProfileImportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/BaseEntityImportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/CustomerImportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/DashboardImportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/DeviceImportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/DeviceProfileImportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/EntityViewImportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/NotificationRuleImportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/NotificationTargetImportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/NotificationTemplateImportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/ResourceImportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/RuleChainImportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/WidgetTypeImportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/WidgetsBundleImportService.java
  application/src/main/java/org/thingsboard/server/service/sync/vc/DefaultEntitiesVersionControlService.java
  application/src/test/java/org/thingsboard/server/controller/TbResourceControllerTest.java
  application/src/test/java/org/thingsboard/server/service/sync/vc/VersionControlTest.java
  common/data/src/main/java/org/thingsboard/server/common/data/sync/vc/EntityLoadError.java
Labels: bug, Core

#13292 Hint for dynamic settings and refactoring flow animation connectors SCADA symbols
  application/src/main/data/json/system/scada_symbols/bottom-right-elbow-connector-hp.svg
  application/src/main/data/json/system/scada_symbols/bottom-tee-connector-hp.svg
  application/src/main/data/json/system/scada_symbols/cross-connector-hp.svg
  application/src/main/data/json/system/scada_symbols/horizontal-connector-hp.svg
  application/src/main/data/json/system/scada_symbols/left-bottom-elbow-connector-hp.svg
  application/src/main/data/json/system/scada_symbols/left-tee-connector-hp.svg
  application/src/main/data/json/system/scada_symbols/left-top-elbow-connector-hp.svg
  application/src/main/data/json/system/scada_symbols/long-horizontal-connector-hp.svg
  application/src/main/data/json/system/scada_symbols/long-vertical-connector-hp.svg
  application/src/main/data/json/system/scada_symbols/right-tee-connector-hp.svg
  application/src/main/data/json/system/scada_symbols/top-right-elbow-connector-hp.svg
  application/src/main/data/json/system/scada_symbols/top-tee-connector-hp.svg
  application/src/main/data/json/system/scada_symbols/vertical-connector-hp.svg
  ui-ngx/src/app/modules/home/components/widget/lib/scada/scada-symbol.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/dynamic-form/dynamic-form-property-panel.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/dynamic-form/dynamic-form-property-panel.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/dynamic-form/dynamic-form.component.html
  ui-ngx/src/app/modules/home/pages/scada-symbol/scada-symbol-editor.models.ts
  ui-ngx/src/app/shared/models/constants.ts
  ui-ngx/src/app/shared/models/dynamic-form.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI

#13299 Improved dashboard autocomplete component
  ui-ngx/src/app/shared/components/dashboard-autocomplete.component.ts
Labels: enhancement, UI

#13300 Fixed percent value for doughnut chart
  ui-ngx/src/app/modules/home/components/widget/lib/chart/pie-chart.ts
Labels: bug, UI

#13321 Fixed rule node config style
  ui-ngx/src/app/modules/home/components/rule-node/action/gps-geo-action-config.component.html
  ui-ngx/src/app/modules/home/components/rule-node/action/math-function-config.component.html
  ui-ngx/src/app/modules/home/components/rule-node/action/save-to-custom-table-config.component.html
  ui-ngx/src/app/modules/home/components/rule-node/common/arguments-map-config.component.html
  ui-ngx/src/app/modules/home/components/rule-node/common/device-relations-query-config.component.html
  ui-ngx/src/app/modules/home/components/rule-node/common/message-types-config.component.html
  ui-ngx/src/app/modules/home/components/rule-node/common/select-attributes.component.html
  ui-ngx/src/app/modules/home/components/rule-node/enrichment/entity-details-config.component.html
  ui-ngx/src/app/modules/home/components/rule-node/external/lambda-config.component.html
  ui-ngx/src/app/modules/home/components/rule-node/filter/check-message-config.component.html
  ui-ngx/src/app/modules/home/components/rule-node/filter/originator-type-config.component.html
  ui-ngx/src/app/modules/home/components/rule-node/transformation/copy-keys-config.component.html
  ui-ngx/src/app/modules/home/components/rule-node/transformation/deduplication-config.component.html
  ui-ngx/src/app/modules/home/components/rule-node/transformation/delete-keys-config.component.html
  ui-ngx/src/app/modules/home/pages/rulechain/rule-node-config.component.html
  ui-ngx/src/app/modules/home/pages/rulechain/rule-node-config.component.scss
  ui-ngx/src/app/modules/home/pages/rulechain/rule-node-config.component.ts
Labels: bug, UI

#12981 MQTT client exponential reconnect strategy
  netty-mqtt/src/main/java/org/thingsboard/mqtt/MqttClientImpl.java
  netty-mqtt/src/main/java/org/thingsboard/mqtt/ReconnectStrategy.java
  netty-mqtt/src/main/java/org/thingsboard/mqtt/ReconnectStrategyExponential.java
  netty-mqtt/src/test/java/org/thingsboard/mqtt/ReconnectStrategyExponentialTest.java
Labels: enhancement, Transport

#13344 Remove sticky option for argument table header row in calculate field dialog
  ui-ngx/src/app/modules/home/components/calculated-fields/components/arguments-table/calculated-field-arguments-table.component.html
Labels: bug, UI

#13346 Event table hide clear event button as input
  ui-ngx/src/app/modules/home/components/event/event-table-config.ts
  ui-ngx/src/app/modules/home/components/event/event-table.component.ts
Labels: enhancement, UI, Ignore for release

#13364 Fixed help icon color in rule node
  ui-ngx/src/app/modules/home/components/rule-node/action/gps-geo-action-config.component.html
  ui-ngx/src/app/modules/home/components/rule-node/action/save-to-custom-table-config.component.html
  ui-ngx/src/app/modules/home/components/rule-node/action/timeseries-config.component.html
Labels: bug, UI, Ignore for release

#13279 lwm2m_Extend observe strategies: add Composite per-object and Composite all-at-once to existing Single
  application/src/main/java/org/thingsboard/server/service/device/DeviceBulkImportService.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/AbstractLwM2MIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/client/LwM2mBinaryAppDataContainer.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/client/SimpleLwM2MDevice.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/ota/AbstractOtaLwM2MIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/AbstractRpcLwM2MIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationCreateTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationObserveTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationReadTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/security/AbstractSecurityLwM2MIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/security/sql/NoSecLwM2MIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/transportConfiguration/ObserveStrategyTransportConfigurationTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/transportConfiguration/ObserveStrategyWithNoSecQueueModeConnectTest.java
  common/data/src/main/java/org/thingsboard/server/common/data/device/profile/lwm2m/TelemetryMappingConfiguration.java
  common/data/src/main/java/org/thingsboard/server/common/data/device/profile/lwm2m/TelemetryObserveStrategy.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mClient.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mClientContext.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mClientContextImpl.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/ResourceUpdateResult.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/downlink/TbLwM2MCreateResponseCallback.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/model/LwM2MModelConfig.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/model/LwM2MModelConfigServiceImpl.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/model/ParametersAnalyzeResult.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/model/ParametersObserveAnalyzeResult.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/model/ParametersUpdateAnalyzeResult.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/ota/DefaultLwM2MOtaUpdateService.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/uplink/DefaultLwM2mUplinkMsgHandler.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/uplink/LwM2mUplinkMsgHandler.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/utils/LwM2MTransportUtil.java
  ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-device-profile-transport-configuration.component.html
  ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-device-profile-transport-configuration.component.ts
  ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-profile-config.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI, Transport

#13385 Added type to CSSJS
  ui-ngx/src/app/core/css/css.js
  ui-ngx/src/app/core/css/css.ts
  ui-ngx/src/app/modules/home/components/widget/lib/markdown-widget.component.ts
Labels: enhancement, UI, Ignore for release

#13413 Fixed HP curcuit breaker widget type fqn
  application/src/main/data/json/system/widget_bundles/high_performance_scada_energy_system.json
Labels: bug, UI

#13414 deduplication node: fixed retry mechanism
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/deduplication/TbMsgDeduplicationNode.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/transform/TbMsgDeduplicationNodeTest.java
Labels: bug, Rule Engine

#13324 Add MQTT version selection for rule nodes
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/mqtt/TbMqttNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/mqtt/TbMqttNodeConfiguration.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/mqtt/azure/TbAzureIotHubNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/mqtt/azure/TbAzureIotHubNodeConfiguration.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/AbstractRuleNodeUpgradeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/mqtt/TbMqttNodeTest.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/mqtt/azure/TbAzureIotHubNodeTest.java
  ui-ngx/src/app/modules/home/components/rule-node/external/azure-iot-hub-config.component.html
  ui-ngx/src/app/modules/home/components/rule-node/external/azure-iot-hub-config.component.ts
  ui-ngx/src/app/modules/home/components/rule-node/external/mqtt-config.component.html
  ui-ngx/src/app/modules/home/components/rule-node/external/mqtt-config.component.ts
  ui-ngx/src/app/shared/components/mqtt-version-select.component.html
  ui-ngx/src/app/shared/components/mqtt-version-select.component.ts
  ui-ngx/src/app/shared/models/mqtt.models.ts
  ui-ngx/src/app/shared/shared.module.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, Rule Engine

#13427 Trendz settings api key
  application/src/test/java/org/thingsboard/server/controller/TrendzControllerTest.java
  common/data/src/main/java/org/thingsboard/server/common/data/trendz/TrendzSettings.java
  ui-ngx/src/app/modules/home/pages/admin/trendz-settings.component.html
  ui-ngx/src/app/modules/home/pages/admin/trendz-settings.component.scss
  ui-ngx/src/app/modules/home/pages/admin/trendz-settings.component.ts
  ui-ngx/src/app/shared/models/trendz-settings.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI, Core, Ignore for release

#13072 Fix manually added telemetry not triggerring alarm
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/profile/DeviceState.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/profile/TbDeviceProfileNodeTest.java
Labels: bug, Rule Engine

#12926 Cassandra 5.0 support
  dao/src/test/java/org/thingsboard/server/dao/AbstractNoSqlContainer.java
  docker/docker-compose.hybrid.yml
Labels: Major Core

#12925 ValKey 8.0 (alternative to Redis > 7.2)
  dao/src/test/java/org/thingsboard/server/dao/AbstractRedisClusterContainer.java
  dao/src/test/java/org/thingsboard/server/dao/AbstractRedisContainer.java
  dao/src/test/java/org/thingsboard/server/dao/RedisClusterSqlTestSuite.java
  dao/src/test/java/org/thingsboard/server/dao/RedisJUnit5Test.java
  docker/.env
  docker/.gitignore
  docker/README.md
  docker/cache-redis-cluster.env
  docker/cache-redis.env
  docker/cache-valkey-cluster.env
  docker/cache-valkey-sentinel.env
  docker/cache-valkey.env
  docker/compose-utils.sh
  docker/docker-compose.redis-cluster.volumes.yml
  docker/docker-compose.redis-cluster.yml
  docker/docker-compose.redis-sentinel.yml
  docker/docker-compose.valkey-cluster.volumes.yml
  docker/docker-compose.valkey-cluster.yml
  docker/docker-compose.valkey-sentinel.volumes.yml
  docker/docker-compose.valkey-sentinel.yml
  docker/docker-compose.valkey.volumes.yml
  docker/docker-compose.valkey.yml
  msa/black-box-tests/README.md
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ContainerTestSuite.java
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ThingsBoardDbInstaller.java
  msa/black-box-tests/src/test/resources/docker-compose.valkey-ssl.volumes.yml
  msa/black-box-tests/src/test/resources/docker-compose.valkey-ssl.yml
  msa/black-box-tests/src/test/resources/redis-certs/redis.crt
  msa/black-box-tests/src/test/resources/redis-certs/redis.key
  msa/black-box-tests/src/test/resources/redis-certs/redisCA.crt
  msa/black-box-tests/src/test/resources/valkey-certs/valkey.crt
  msa/black-box-tests/src/test/resources/valkey-certs/valkey.key
  msa/black-box-tests/src/test/resources/valkey-certs/valkeyCA.crt
Labels: Major Core

#13468 [EDQS] Fixed customer creation for NULL customer id
  common/edqs/src/main/java/org/thingsboard/server/edqs/repo/TenantRepo.java
Labels: Ignore for release

#13479 Fix EntityFields customerId
  common/data/src/main/java/org/thingsboard/server/common/data/edqs/fields/AbstractEntityFields.java
Labels: Ignore for release

#13480 Fix tenant id resolving in OAuth2 mapper
  application/src/main/java/org/thingsboard/server/service/security/auth/oauth2/AbstractOAuth2ClientMapper.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/tenant/TenantService.java
  dao/src/main/java/org/thingsboard/server/dao/sql/tenant/JpaTenantDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/tenant/TenantRepository.java
  dao/src/main/java/org/thingsboard/server/dao/tenant/TenantDao.java
  dao/src/main/java/org/thingsboard/server/dao/tenant/TenantServiceImpl.java
Labels: bug, Core
