Repository thingsboard/thingsboard, pull requests merged in 2025-08, with the labels that each got.

#13809 Fix overwrite of dashboard state duplicates when changing name
  ui-ngx/src/app/modules/home/components/dashboard-page/states/manage-dashboard-states-dialog.component.ts
Labels: bug, UI, Ignore for release

#13813 Refactoring dashboard managment
  ui-ngx/src/app/modules/home/components/dashboard-page/dashboard-page.component.ts
  ui-ngx/src/app/modules/home/components/dashboard-page/states/manage-dashboard-states-dialog.component.html
  ui-ngx/src/app/modules/home/components/dashboard-page/states/manage-dashboard-states-dialog.component.scss
  ui-ngx/src/app/modules/home/components/dashboard-page/states/manage-dashboard-states-dialog.component.ts
Labels: enhancement, UI

#13830 Fixed default sort property for alarm entity query
  application/src/main/java/org/thingsboard/server/service/query/DefaultEntityQueryService.java
Labels: enhancement

#13838 Minor fixes for Ai models
  ui-ngx/src/app/modules/home/components/ai-model/ai-model-dialog.component.ts
  ui-ngx/src/app/modules/home/components/rule-node/external/ai-config.component.html
  ui-ngx/src/app/modules/home/components/rule-node/external/ai-config.component.ts
  ui-ngx/src/app/modules/home/pages/ai-model/ai-model-table-header.component.ts
Labels: bug, UI, Ignore for release

#13834 Fixed flaky edqs tests
  application/src/test/java/org/thingsboard/server/controller/EdqsEntityQueryControllerTest.java
  application/src/test/java/org/thingsboard/server/controller/EntityQueryControllerTest.java
Labels: Ignore for release

#13859 Fixed flaky test
  application/src/test/java/org/thingsboard/server/controller/EntityQueryControllerTest.java
Labels: Ignore for release

#13848 Fix some MSA tests not running
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/cf/CalculatedFieldTest.java
  msa/black-box-tests/src/test/resources/connectivity.xml
Labels: Ignore for release

#13869 Fixed tranlate format in da_DK
  ui-ngx/src/assets/locale/locale.constant-da_DK.json
Labels: bug, UI, Ignore for release

#13849 Improve mobile action
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/mobile-action-editor.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/mobile-action-editor.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/mobile-action-editor.models.ts
  ui-ngx/src/app/modules/home/components/widget/widget.component.ts
  ui-ngx/src/app/shared/models/widget.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI

#13894 Map widget tooltip no longer closes when hovering from overlay to tooltip
  ui-ngx/src/app/modules/home/components/widget/lib/maps/data-layer/data-layer-utils.ts
Labels: Bug, UI

#13878 Fixed calculated fields search not working
  dao/src/main/java/org/thingsboard/server/dao/sql/cf/CalculatedFieldRepository.java
  dao/src/main/java/org/thingsboard/server/dao/sql/cf/JpaCalculatedFieldDao.java
Labels: Bug, Core
