Repository thingsboard/thingsboard, pull requests merged in 2025-03, with the labels that each got.

#12588 Kafka: make more topics configurable
  application/src/main/resources/thingsboard.yml
  common/queue/src/main/java/org/thingsboard/server/queue/discovery/TopicService.java
  msa/vc-executor/src/main/resources/tb-vc-executor.yml
  transport/coap/src/main/resources/tb-coap-transport.yml
  transport/http/src/main/resources/tb-http-transport.yml
  transport/lwm2m/src/main/resources/tb-lwm2m-transport.yml
  transport/mqtt/src/main/resources/tb-mqtt-transport.yml
  transport/snmp/src/main/resources/tb-snmp-transport.yml
Labels: enhancement, Core

#12652 Entity filters for AlarmCountQuery
  application/src/main/java/org/thingsboard/server/service/subscription/DefaultTbEntityDataSubscriptionService.java
  application/src/main/java/org/thingsboard/server/service/subscription/TbAlarmCountSubCtx.java
  application/src/test/java/org/thingsboard/server/controller/WebsocketApiTest.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/alarm/AlarmService.java
  common/data/src/main/java/org/thingsboard/server/common/data/query/AlarmCountQuery.java
  dao/src/main/java/org/thingsboard/server/dao/alarm/AlarmDao.java
  dao/src/main/java/org/thingsboard/server/dao/alarm/BaseAlarmService.java
  dao/src/main/java/org/thingsboard/server/dao/sql/alarm/JpaAlarmDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/query/AlarmQueryRepository.java
  dao/src/main/java/org/thingsboard/server/dao/sql/query/DefaultAlarmQueryRepository.java
  dao/src/test/java/org/thingsboard/server/dao/service/AlarmServiceTest.java
  ui-ngx/src/app/modules/home/components/widget/config/basic/alarm/alarm-count-basic-config.component.html
  ui-ngx/src/app/modules/home/components/widget/config/basic/alarm/alarm-count-basic-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/config/datasource.component.html
  ui-ngx/src/app/modules/home/components/widget/config/datasource.component.ts
  ui-ngx/src/app/modules/home/components/widget/config/datasources.component.ts
Labels: feature

#12813 Fixed flaky alarm count test
  application/src/main/java/org/thingsboard/server/service/subscription/DefaultTbEntityDataSubscriptionService.java
  application/src/test/java/org/thingsboard/server/controller/WebsocketApiTest.java
Labels: Ignore for release

#12800 Added latest debug event call in СF Dialog on Test function
  ui-ngx/src/app/core/http/calculated-fields.service.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.ts
Labels: enhancement, UI, Ignore for release

#12707 VC support for Calculated fields
  application/src/main/java/org/thingsboard/server/service/sync/ie/DefaultEntitiesExportImportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/EntitiesExportImportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/exporting/impl/DefaultEntityExportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/AssetImportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/AssetProfileImportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/BaseEntityImportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/DeviceImportService.java
  application/src/main/java/org/thingsboard/server/service/sync/ie/importing/impl/DeviceProfileImportService.java
  application/src/main/java/org/thingsboard/server/service/sync/vc/DefaultEntitiesVersionControlService.java
  application/src/main/java/org/thingsboard/server/service/sync/vc/data/EntitiesExportCtx.java
  application/src/main/java/org/thingsboard/server/service/sync/vc/data/EntitiesImportCtx.java
  application/src/main/java/org/thingsboard/server/service/sync/vc/data/EntityTypeExportCtx.java
  application/src/test/java/org/thingsboard/server/service/sync/ie/ExportImportServiceSqlTest.java
  application/src/test/java/org/thingsboard/server/service/sync/vc/VersionControlTest.java
  common/data/src/main/java/org/thingsboard/server/common/data/cf/CalculatedField.java
  common/data/src/main/java/org/thingsboard/server/common/data/id/CalculatedFieldId.java
  common/data/src/main/java/org/thingsboard/server/common/data/sync/ie/DeviceExportData.java
  common/data/src/main/java/org/thingsboard/server/common/data/sync/ie/EntityExportData.java
  common/data/src/main/java/org/thingsboard/server/common/data/sync/ie/EntityExportSettings.java
  common/data/src/main/java/org/thingsboard/server/common/data/sync/ie/EntityImportSettings.java
  common/data/src/main/java/org/thingsboard/server/common/data/sync/vc/request/create/VersionCreateConfig.java
  common/data/src/main/java/org/thingsboard/server/common/data/sync/vc/request/load/VersionLoadConfig.java
  common/message/src/main/java/org/thingsboard/server/common/msg/plugin/ComponentLifecycleMsg.java
  common/proto/src/main/java/org/thingsboard/server/common/util/ProtoUtils.java
  dao/src/main/java/org/thingsboard/server/dao/cf/BaseCalculatedFieldService.java
  dao/src/main/java/org/thingsboard/server/dao/model/ModelConstants.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/CalculatedFieldEntity.java
  dao/src/main/java/org/thingsboard/server/dao/sql/cf/DefaultNativeCalculatedFieldRepository.java
  dao/src/main/resources/sql/schema-entities.sql
  dao/src/test/java/org/thingsboard/server/dao/service/CalculatedFieldServiceTest.java
  ui-ngx/src/app/modules/home/components/vc/auto-commit-settings.component.html
  ui-ngx/src/app/modules/home/components/vc/auto-commit-settings.component.ts
  ui-ngx/src/app/modules/home/components/vc/entity-types-version-create.component.html
  ui-ngx/src/app/modules/home/components/vc/entity-types-version-create.component.ts
  ui-ngx/src/app/modules/home/components/vc/entity-types-version-load.component.html
  ui-ngx/src/app/modules/home/components/vc/entity-types-version-load.component.ts
  ui-ngx/src/app/modules/home/components/vc/entity-version-create.component.html
  ui-ngx/src/app/modules/home/components/vc/entity-version-create.component.ts
  ui-ngx/src/app/modules/home/components/vc/entity-version-restore.component.html
  ui-ngx/src/app/modules/home/components/vc/entity-version-restore.component.ts
  ui-ngx/src/app/shared/models/vc.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: Ignore for release

#12804 tbel_Unmodifiable
  application/src/test/java/org/thingsboard/server/service/script/TbelInvokeDocsIoTest.java
  pom.xml
Labels: Tbel

#12820 Calculated field adjustments
  ui-ngx/src/app/modules/home/components/calculated-fields/calculated-fields-table-config.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/calculated-fields-table.component.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/components/arguments-table/calculated-field-arguments-table.component.html
  ui-ngx/src/app/modules/home/components/calculated-fields/components/arguments-table/calculated-field-arguments-table.component.scss
  ui-ngx/src/app/modules/home/components/calculated-fields/components/arguments-table/calculated-field-arguments-table.component.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.html
  ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.scss
  ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/components/panel/calculated-field-argument-panel.component.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/components/test-dialog/calculated-field-script-test-dialog.component.scss
  ui-ngx/src/app/modules/home/components/event/event-table-config.ts
  ui-ngx/src/app/shared/components/js-func.component.ts
  ui-ngx/src/app/shared/models/ace/ace.models.ts
  ui-ngx/src/app/shared/models/calculated-field.models.ts
  ui-ngx/src/app/shared/models/regex.constants.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI, Ignore for release

#12850 Changed Calculated fields highlights and autocompletes
  ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.scss
  ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/components/panel/calculated-field-argument-panel.component.html
  ui-ngx/src/app/modules/home/components/calculated-fields/components/panel/calculated-field-argument-panel.component.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/components/test-dialog/calculated-field-script-test-dialog.component.html
  ui-ngx/src/app/modules/home/components/calculated-fields/components/test-dialog/calculated-field-script-test-dialog.component.scss
  ui-ngx/src/app/modules/home/components/calculated-fields/components/test-dialog/calculated-field-script-test-dialog.component.ts
  ui-ngx/src/app/shared/models/calculated-field.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI, Ignore for release

#12866 Fixed fill-opacity in marker shape7.svg
  ui-ngx/src/app/shared/models/widget/maps/marker-shape.models.ts
  ui-ngx/src/assets/markers/shape7.svg
Labels: UI, Ignore for release

#12774 [Kafka node] Removed key/value serializers from config
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/kafka/TbKafkaNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/kafka/TbKafkaNodeConfiguration.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/kafka/TbKafkaNodeTest.java
  ui-ngx/src/app/modules/home/components/rule-node/external/kafka-config.component.html
  ui-ngx/src/app/modules/home/components/rule-node/external/kafka-config.component.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, Rule Engine

#12224 Added TBEL metrics, refactored JS stats
  application/src/main/java/org/thingsboard/server/actors/ActorSystemContext.java
  application/src/main/java/org/thingsboard/server/actors/ruleChain/DefaultTbContext.java
  application/src/main/java/org/thingsboard/server/service/stats/DefaultJsInvokeStats.java
  application/src/main/resources/thingsboard.yml
  application/src/test/java/org/thingsboard/server/service/cf/ctx/state/ScriptCalculatedFieldStateTest.java
  application/src/test/java/org/thingsboard/server/service/script/AbstractTbelInvokeTest.java
  application/src/test/java/org/thingsboard/server/service/script/RemoteJsInvokeServiceTest.java
  common/actor/src/main/java/org/thingsboard/server/actors/JsInvokeStats.java
  common/script/script-api/src/main/java/org/thingsboard/script/api/AbstractScriptInvokeService.java
  common/script/script-api/src/main/java/org/thingsboard/script/api/ScriptStatCallback.java
  common/script/script-api/src/main/java/org/thingsboard/script/api/js/AbstractJsInvokeService.java
  common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/DefaultTbelInvokeService.java
  common/stats/src/main/java/org/thingsboard/server/common/stats/DefaultCounter.java
  common/stats/src/main/java/org/thingsboard/server/common/stats/StatsType.java
  docker/monitoring/grafana/provisioning/dashboards/core_and_js_metrics.json
  rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/TbContext.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/action/TbClearAlarmNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/action/TbCreateAlarmNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/action/TbLogNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/debug/TbMsgGeneratorNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/filter/TbJsFilterNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/filter/TbJsSwitchNode.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/transform/TbTransformMsgNode.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/action/TbCreateAlarmNodeTest.java
Labels: enhancement

#12385 Changed gateway dist branch
  application/src/main/resources/thingsboard.yml
Labels: enhancement, UI, Ignore for release

#12738 Mobile center added page name validators
  ui-ngx/src/app/modules/home/pages/mobile/bundes/layout/default-mobile-page-panel.component.html
  ui-ngx/src/app/modules/home/pages/mobile/bundes/layout/default-mobile-page-panel.component.ts
  ui-ngx/src/app/modules/home/pages/mobile/bundes/layout/mobile-page-item-row.component.html
  ui-ngx/src/app/modules/home/pages/mobile/bundes/layout/mobile-page-item-row.component.ts
Labels: enhancement, UI

#12749 Pagination settings improvements
  ui-ngx/src/app/modules/home/components/widget/lib/alarm/alarms-table-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/entity/entities-table-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/rpc/persistent-table.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/alarm/alarms-table-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/alarm/alarms-table-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/timeseries-table-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/timeseries-table-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/control/persistent-table-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/control/persistent-table-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/entity/entities-table-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/entity/entities-table-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/table-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/timeseries-table-widget.component.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI, feature

#12781 Flow animation for hp scada connectors
  application/src/main/data/json/system/scada_symbols/bottom-right-elbow-connector-hp.svg
  application/src/main/data/json/system/scada_symbols/bottom-tee-connector-hp.svg
  application/src/main/data/json/system/scada_symbols/cross-connector-hp.svg
  application/src/main/data/json/system/scada_symbols/horizontal-connector-hp.svg
  application/src/main/data/json/system/scada_symbols/left-bottom-elbow-connector-hp.svg
  application/src/main/data/json/system/scada_symbols/left-tee-connector-hp.svg
  application/src/main/data/json/system/scada_symbols/left-top-elbow-connector-hp.svg
  application/src/main/data/json/system/scada_symbols/long-horizontal-connector-hp.svg
  application/src/main/data/json/system/scada_symbols/long-vertical-connector-hp.svg
  application/src/main/data/json/system/scada_symbols/right-tee-connector-hp.svg
  application/src/main/data/json/system/scada_symbols/top-right-elbow-connector-hp.svg
  application/src/main/data/json/system/scada_symbols/top-tee-connector-hp.svg
  application/src/main/data/json/system/scada_symbols/vertical-connector-hp.svg
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI, feature

#12790 Setting to disable sorting in Table-widgets
  ui-ngx/src/app/modules/home/components/widget/lib/alarm/alarms-table-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/alarm/alarms-table-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/entity/entities-table-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/alarm/alarms-table-key-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/alarm/alarms-table-key-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/timeseries-table-key-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/timeseries-table-key-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/timeseries-table-latest-key-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/timeseries-table-latest-key-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/entity/entities-table-key-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/entity/entities-table-key-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/table-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/timeseries-table-widget.component.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI, feature

#12802 Fixed transport messages maximum number hints
  ui-ngx/src/app/modules/home/components/profile/tenant/default-tenant-profile-configuration.component.html
Labels: bug, UI

#12810 Fix device profile extra scroll in lwm2m model
  ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-observe-attr-telemetry-instances.component.scss
Labels: enhancement, UI

#12840 Handeled deepClone of Observable
  ui-ngx/src/app/core/utils.ts
Labels: enhancement, UI, Ignore for release

#12841 Fix pop-up closing issue on dashboards
  ui-ngx/src/app/modules/home/components/dashboard/dashboard.component.ts
  ui-ngx/src/app/modules/home/components/widget/widget-container.component.ts
Labels: bug, UI

#12859 Remove flex-layout
  ui-ngx/package.json
  ui-ngx/patches/@angular+flex-layout+15.0.0-beta.42.patch
  ui-ngx/src/app/core/services/dynamic-component-factory.service.ts
  ui-ngx/src/app/core/services/resources.service.ts
  ui-ngx/src/app/modules/common/modules-map.ts
  ui-ngx/src/app/shared/legacy/flex-layout.models.ts
  ui-ngx/yarn.lock
Labels: enhancement, UI

#12601 Usage of long refactored to int in LinkedHashMapRemoveEldest class
  application/src/main/java/org/thingsboard/server/actors/ActorSystemContext.java
  application/src/test/java/org/thingsboard/server/actors/device/DeviceActorMessageProcessorTest.java
  common/util/src/main/java/org/thingsboard/common/util/LinkedHashMapRemoveEldest.java
  common/util/src/test/java/org/thingsboard/common/util/LinkedHashMapRemoveEldestTest.java
Labels: Ignore for release

#12736 StatsPersistTick scheduled future cancel on actor destroy
  application/src/main/java/org/thingsboard/server/actors/ActorSystemContext.java
  application/src/main/java/org/thingsboard/server/actors/service/ComponentActor.java
  application/src/main/java/org/thingsboard/server/actors/shared/AbstractContextAwareMsgProcessor.java
  application/src/main/java/org/thingsboard/server/actors/shared/ComponentMsgProcessor.java
Labels: enhancement, Rule Engine

#12914 Gateway relation fix
  application/src/main/java/org/thingsboard/server/service/transport/DefaultTransportApiService.java
Labels: Ignore for release

#12912 Fixed missed "title" entity field subscription
  common/data/src/main/java/org/thingsboard/server/common/data/edqs/fields/EntityFields.java
Labels: Ignore for release

#12467 Added device provision mobile action
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/mobile-action-editor.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/mobile-action-editor.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/mobile-action-editor.models.ts
  ui-ngx/src/app/modules/home/components/widget/widget.component.ts
  ui-ngx/src/app/shared/models/widget.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI, feature

#12817 Scale format for SCADA tank with units
  application/src/main/data/json/system/scada_symbols/cylindrical-tank.svg
  application/src/main/data/json/system/scada_symbols/elevated-tank.svg
  application/src/main/data/json/system/scada_symbols/horizontal-tank-hp.svg
  application/src/main/data/json/system/scada_symbols/horizontal-tank.svg
  application/src/main/data/json/system/scada_symbols/large-cylindrical-tank.svg
  application/src/main/data/json/system/scada_symbols/large-stand-cylindrical-tank.svg
  application/src/main/data/json/system/scada_symbols/large-stand-vertical-tank.svg
  application/src/main/data/json/system/scada_symbols/large-vertical-tank.svg
  application/src/main/data/json/system/scada_symbols/pool-hp.svg
  application/src/main/data/json/system/scada_symbols/short-vertical-tank-hp.svg
  application/src/main/data/json/system/scada_symbols/small-cylindrical-tank.svg
  application/src/main/data/json/system/scada_symbols/small-spherical-tank.svg
  application/src/main/data/json/system/scada_symbols/spherical-tank.svg
  application/src/main/data/json/system/scada_symbols/stand-cylindrical-tank.svg
  application/src/main/data/json/system/scada_symbols/stand-horizontal-tank.svg
  application/src/main/data/json/system/scada_symbols/stand-vertical-short-tank.svg
  application/src/main/data/json/system/scada_symbols/stand-vertical-tank.svg
  application/src/main/data/json/system/scada_symbols/vertical-short-tank.svg
  application/src/main/data/json/system/scada_symbols/vertical-tank-hp.svg
  application/src/main/data/json/system/scada_symbols/vertical-tank.svg
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI

#12848 Widget header button action imporovement
  ui-ngx/src/app/modules/home/components/widget/action/widget-action-dialog.component.html
  ui-ngx/src/app/modules/home/components/widget/action/widget-action-dialog.component.ts
  ui-ngx/src/app/modules/home/components/widget/widget-container.component.html
  ui-ngx/src/app/modules/home/components/widget/widget-container.component.scss
  ui-ngx/src/app/modules/home/components/widget/widget-container.component.ts
  ui-ngx/src/app/modules/home/components/widget/widget.component.ts
  ui-ngx/src/app/modules/home/models/widget-component.models.ts
  ui-ngx/src/app/shared/models/widget.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI, feature

#12856 Implemented tbel utils autocompletes and highlights
  ui-ngx/src/app/shared/components/js-func.component.scss
  ui-ngx/src/app/shared/components/js-func.component.ts
  ui-ngx/src/app/shared/models/ace/tbel-utils.models.ts
Labels: UI, feature

#12878 Fixed drag and drop for data keys chip
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/key/data-keys.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/key/data-keys.component.scss
Labels: bug, UI

#12892 Fixed get rule chains for entity list component
  ui-ngx/src/app/core/http/entity.service.ts
Labels: bug, UI

#12897 Fixed entity autocomplete
  ui-ngx/src/app/shared/components/entity/entity-autocomplete.component.ts
Labels: bug, UI, Ignore for release

#12898 Fixed icon close button position
  ui-ngx/src/app/shared/components/string-autocomplete.component.html
  ui-ngx/src/app/shared/components/unit-input.component.html
Labels: enhancement, UI

#12899 Fixed default shape for horizontal ellipse tank widget
  application/src/main/data/json/system/widget_types/horizontal_ellipse_tank.json
Labels: bug, UI

#12908 Fixed help button color and position
  ui-ngx/src/app/modules/home/pages/admin/settings-card.scss
  ui-ngx/src/app/modules/home/pages/admin/sms-provider.component.scss
  ui-ngx/src/styles.scss
Labels: enhancement, UI

#12909 Fixed validation for target entity type create relation node
  ui-ngx/src/app/modules/home/components/rule-node/action/create-relation-config.component.ts
Labels: bug, UI

#12913 Help for get dashboard state id aciton
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/get-value-action-settings-panel.component.ts
  ui-ngx/src/assets/help/en_US/widget/config/parse_value_get_dashboard_state_id_fn.md
Labels: enhancement, UI

#12917 Fixed default events and add hot keys for Mac
  ui-ngx/src/app/modules/home/components/dashboard-page/layout/dashboard-layout.component.ts
Labels: enhancement, UI

#12927 Fixed UI build
  ui-ngx/src/app/modules/home/components/widget/widget-container.component.ts
Labels: bug, UI, Ignore for release

#12811 Added debug settings service
  ui-ngx/src/app/modules/home/components/calculated-fields/calculated-fields-table-config.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/calculated-fields-table.component.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/components/debug-dialog/calculated-field-debug-dialog.component.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/components/test-dialog/calculated-field-script-test-dialog.component.ts
  ui-ngx/src/app/modules/home/components/entity/debug/entity-debug-settings-button.component.html
  ui-ngx/src/app/modules/home/components/entity/debug/entity-debug-settings-button.component.ts
  ui-ngx/src/app/modules/home/components/entity/debug/entity-debug-settings-panel.component.ts
  ui-ngx/src/app/modules/home/components/entity/debug/entity-debug-settings.model.ts
  ui-ngx/src/app/modules/home/components/entity/debug/entity-debug-settings.service.ts
  ui-ngx/src/app/modules/home/components/home-components.module.ts
  ui-ngx/src/app/shared/models/calculated-field.models.ts
  ui-ngx/src/app/shared/models/entity.models.ts
  ui-ngx/src/app/shared/shared.module.ts
Labels: enhancement, UI, Ignore for release

#12885 Calculated adjustments
  ui-ngx/src/app/modules/home/components/calculated-fields/calculated-fields-table-config.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/components/arguments-table/calculated-field-arguments-table.component.html
  ui-ngx/src/app/modules/home/components/calculated-fields/components/arguments-table/calculated-field-arguments-table.component.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/components/debug-dialog/calculated-field-debug-dialog.component.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.html
  ui-ngx/src/app/modules/home/components/calculated-fields/components/panel/calculated-field-argument-panel.component.html
  ui-ngx/src/app/modules/home/components/calculated-fields/components/panel/calculated-field-argument-panel.component.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/components/test-dialog/calculated-field-script-test-dialog.component.html
  ui-ngx/src/app/modules/home/components/event/event-table-config.ts
  ui-ngx/src/app/modules/home/components/vc/entity-version-create.component.ts
  ui-ngx/src/app/shared/components/js-func.component.html
  ui-ngx/src/app/shared/components/js-func.component.ts
  ui-ngx/src/app/shared/import-export/import-export.service.ts
  ui-ngx/src/app/shared/models/calculated-field.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI, Ignore for release

#12928 Improvement event handling hotkeys for Mac on the rulechain page
  ui-ngx/src/app/modules/home/pages/rulechain/rulechain-page.component.ts
Labels: enhancement, UI

#12931 Fixed date time period start/end values check
  ui-ngx/src/app/shared/components/time/datetime-period.component.ts
Labels: bug, UI, Ignore for release

#12932 Refactoring tbel utils autocompletes and highlights
  ui-ngx/src/app/shared/models/ace/tbel-utils.models.ts
Labels: UI, Ignore for release

#12933 Added link to help page for timewindow settings
  ui-ngx/src/app/shared/components/time/timewindow-config-dialog.component.html
  ui-ngx/src/app/shared/models/constants.ts
Labels: enhancement, UI

#12919 Fixed entity relation cleanup method
  application/src/test/java/org/thingsboard/server/service/entitiy/EntityServiceTest.java
  dao/src/main/java/org/thingsboard/server/dao/relation/BaseRelationService.java
Labels: Ignore for release

#12191 Reduce API usage traffic
  application/src/main/java/org/thingsboard/server/service/apiusage/DefaultTbApiUsageStateService.java
  application/src/main/resources/thingsboard.yml
  common/proto/src/main/java/org/thingsboard/server/common/util/ProtoUtils.java
  common/proto/src/main/proto/queue.proto
  common/queue/src/main/java/org/thingsboard/server/queue/usagestats/DefaultTbApiUsageReportClient.java
  msa/vc-executor/src/main/resources/tb-vc-executor.yml
  transport/coap/src/main/resources/tb-coap-transport.yml
  transport/http/src/main/resources/tb-http-transport.yml
  transport/lwm2m/src/main/resources/tb-lwm2m-transport.yml
  transport/mqtt/src/main/resources/tb-mqtt-transport.yml
  transport/snmp/src/main/resources/tb-snmp-transport.yml
Labels: enhancement

#12947 Hotfix for header action
  ui-ngx/src/app/modules/home/components/widget/widget-container.component.html
Labels: bug, UI, Ignore for release

#12952 [API usage] revert accidentally deleted api-usage clearing
  common/queue/src/main/java/org/thingsboard/server/queue/usagestats/DefaultTbApiUsageReportClient.java
Labels: Ignore for release

#12958 Ignore null version
  dao/src/main/java/org/thingsboard/server/dao/timeseries/BaseTimeseriesService.java
Labels: Ignore for release

#12956 Debug Configuration improvements
  ui-ngx/src/app/modules/home/components/entity/debug/entity-debug-settings-panel.component.html
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI

#12961 Refactoring widget header action button
  ui-ngx/src/app/modules/home/components/widget/action/widget-action-dialog.component.ts
  ui-ngx/src/app/modules/home/components/widget/widget-container.component.html
  ui-ngx/src/app/modules/home/components/widget/widget.component.ts
  ui-ngx/src/app/modules/home/models/widget-component.models.ts
  ui-ngx/src/app/shared/models/widget.models.ts
Labels: enhancement, UI, Ignore for release

#12969 Fixed edqs sync
  application/src/test/java/org/thingsboard/server/controller/EdqsControllerTest.java
  common/edqs/src/main/java/org/thingsboard/server/edqs/util/VersionsStore.java
Labels: bug, Ignore for release

#12985 Renamed package to tb-edqs
  edqs/pom.xml
  edqs/src/main/conf/tb-edqs.conf
  msa/edqs/pom.xml
Labels: Ignore for release

#12975 Fixed EDQS sorting
  common/edqs/src/main/java/org/thingsboard/server/edqs/data/ApiUsageStateData.java
  common/edqs/src/main/java/org/thingsboard/server/edqs/data/BaseEntityData.java
  common/edqs/src/main/java/org/thingsboard/server/edqs/data/EntityData.java
  common/edqs/src/main/java/org/thingsboard/server/edqs/repo/TenantRepo.java
  common/edqs/src/main/java/org/thingsboard/server/edqs/util/RepositoryUtils.java
Labels: Ignore for release

#12967 COAP DTLS: updated connectivity commands
  application/src/main/resources/thingsboard.yml
  application/src/test/java/org/thingsboard/server/controller/DeviceConnectivityControllerTest.java
  dao/src/main/java/org/thingsboard/server/dao/device/DeviceConnectivityServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/util/DeviceConnectivityUtil.java
Labels: Docs enhancement

#12611 Do not copy latest to entity views when data was not saved on the main entity
  application/src/main/java/org/thingsboard/server/service/telemetry/DefaultTelemetrySubscriptionService.java
  application/src/test/java/org/thingsboard/server/service/telemetry/DefaultTelemetrySubscriptionServiceTest.java
  common/data/src/main/java/org/thingsboard/server/common/data/EntityType.java
Labels: Ignore for release

#12920 MQTT transport handler - log tenant on subscribe issue
  common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttTransportHandler.java
Labels: Ignore for release

#12982 [WS] fixed OOM
  dao/src/main/java/org/thingsboard/server/dao/sqlts/AbstractChunkedAggregationTimeseriesDao.java
  dao/src/main/java/org/thingsboard/server/dao/timeseries/BaseTimeseriesService.java
  dao/src/test/java/org/thingsboard/server/dao/service/timeseries/BaseTimeseriesServiceTest.java
  dao/src/test/java/org/thingsboard/server/dao/sqlts/AbstractChunkedAggregationTimeseriesDaoTest.java
Labels: Ignore for release

#12923 Added md help files for REST connector
  ui-ngx/src/assets/help/en_US/widget/lib/gateway/rest-json_fn.md
Labels: UI, Ignore for release

#12976 Fixed Calculated Field cross instance import with current tenant target entity argument shows unnecessary error
  ui-ngx/src/app/modules/home/components/calculated-fields/calculated-fields-table-config.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/components/arguments-table/calculated-field-arguments-table.component.html
Labels: bug, UI, Ignore for release

#12994 Limit table content height in map layers with scroll on overflow
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/map/map-layers.component.html
Labels: enhancement, UI, Ignore for release

#12987 Add new map widgets helps/example
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/custom-action-pretty-editor.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/custom-action-pretty-editor.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/custom-action-pretty-resources-tabs.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/custom-action-pretty-resources-tabs.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/custom-action.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/place-map-item-sample-html.raw
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/place-map-item-sample-js.raw
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/widget-action.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/widget-action.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/map/map-data-layer-dialog.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/map/map-settings.component.html
  ui-ngx/src/app/shared/components/entity/entity-type-select.component.html
  ui-ngx/src/app/shared/components/entity/entity-type-select.component.ts
  ui-ngx/src/assets/help/en_US/widget/action/custom_additional_params.md
  ui-ngx/src/assets/help/en_US/widget/action/place_map_item/create_dialog_html.md
  ui-ngx/src/assets/help/en_US/widget/action/place_map_item/create_dialog_js.md
  ui-ngx/src/assets/help/en_US/widget/action/place_map_item/place_map_item_action.md
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI, Ignore for release

#13002 Fixed click area for SCADA symbols
  application/src/main/data/json/system/scada_symbols/apartments-hp.svg
  application/src/main/data/json/system/scada_symbols/bottom-light-bulb-hp.svg
  application/src/main/data/json/system/scada_symbols/conical-tank.svg
  application/src/main/data/json/system/scada_symbols/consumers-hp.svg
  application/src/main/data/json/system/scada_symbols/dynamic-horizontal-scale-hp.svg
  application/src/main/data/json/system/scada_symbols/dynamic-vertical-scale-hp.svg
  application/src/main/data/json/system/scada_symbols/electrical-distribution-board-hp.svg
  application/src/main/data/json/system/scada_symbols/filter-hp.svg
  application/src/main/data/json/system/scada_symbols/four-rate-energy-meter-hp.svg
  application/src/main/data/json/system/scada_symbols/gas-preventer-hp.svg
  application/src/main/data/json/system/scada_symbols/heat-exchanger-hp.svg
  application/src/main/data/json/system/scada_symbols/heat-pump-hp.svg
  application/src/main/data/json/system/scada_symbols/horizontal-tank-hp.svg
  application/src/main/data/json/system/scada_symbols/house-hp.svg
  application/src/main/data/json/system/scada_symbols/industrial-fuel-generator-hp.svg
  application/src/main/data/json/system/scada_symbols/large-horizontal-separator-hp.svg
  application/src/main/data/json/system/scada_symbols/large-inverter-hp.svg
  application/src/main/data/json/system/scada_symbols/large-stand-cylindrical-tank.svg
  application/src/main/data/json/system/scada_symbols/large-stand-vertical-tank.svg
  application/src/main/data/json/system/scada_symbols/large-vertical-separator-hp.svg
  application/src/main/data/json/system/scada_symbols/leak-sensor.svg
  application/src/main/data/json/system/scada_symbols/low-voltage-tower-hp.svg
  application/src/main/data/json/system/scada_symbols/meter.svg
  application/src/main/data/json/system/scada_symbols/oil-pump-hp.svg
  application/src/main/data/json/system/scada_symbols/pool-hp.svg
  application/src/main/data/json/system/scada_symbols/pool.svg
  application/src/main/data/json/system/scada_symbols/power-socket-hp.svg
  application/src/main/data/json/system/scada_symbols/short-vertical-tank-hp.svg
  application/src/main/data/json/system/scada_symbols/simple-horizontal-scale-hp.svg
  application/src/main/data/json/system/scada_symbols/simple-vertical-scale-hp.svg
  application/src/main/data/json/system/scada_symbols/small-cylindrical-tank.svg
  application/src/main/data/json/system/scada_symbols/small-horizontal-separator-connector-hp.svg
  application/src/main/data/json/system/scada_symbols/small-left-meter.svg
  application/src/main/data/json/system/scada_symbols/small-vertical-separator-connector-hp.svg
  application/src/main/data/json/system/scada_symbols/small-vertical-separator-hp.svg
  application/src/main/data/json/system/scada_symbols/spherical-tank.svg
  application/src/main/data/json/system/scada_symbols/stand-cylindrical-tank.svg
  application/src/main/data/json/system/scada_symbols/stand-vertical-short-tank.svg
  application/src/main/data/json/system/scada_symbols/top-light-bulb-hp.svg
  application/src/main/data/json/system/scada_symbols/turbine-hp.svg
  application/src/main/data/json/system/scada_symbols/vertical-energy-system-controller-hp.svg
  application/src/main/data/json/system/scada_symbols/vertical-tank-hp.svg
  application/src/main/data/json/system/scada_symbols/voltage-stabilizer-hp.svg
  application/src/main/data/json/system/scada_symbols/wind-turbine-cluster-hp.svg
  application/src/main/data/json/system/scada_symbols/wind-turbine-hp.svg
Labels: bug, UI, Ignore for release

#13016 Fixed not work decline settings in advanced map settings
  ui-ngx/src/app/modules/home/components/widget/lib/settings/map/map-widget-settings.component.ts
Labels: bug, UI, Ignore for release

#13022 Fixed autocomplete not closing in LWM2M list model
  ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-object-list.component.html
  ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-object-list.component.ts
Labels: bug, UI

#13033 Clear getting start widget style
  ui-ngx/src/app/modules/home/components/widget/lib/home-page/getting-started-widget.component.scss
Labels: enhancement, UI, Ignore for release

#13013 Adding threshold to time-series line chart affects data sources post-processing
  application/src/main/java/org/thingsboard/server/service/subscription/DefaultTbEntityDataSubscriptionService.java
Labels: bug, UI

#13036 Fixed incorrect update date in widgets action table when switching widgets
  ui-ngx/src/app/modules/home/components/widget/action/manage-widget-actions.component.models.ts
  ui-ngx/src/app/modules/home/components/widget/action/manage-widget-actions.component.ts
Labels: bug, UI

#13038 Fixed place map item action on multiple header button clicks
  ui-ngx/src/app/core/api/widget-api.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/maps/map.ts
Labels: bug, UI, Ignore for release

#13042 Fixed Calculated fields creation of arguments with same name
  ui-ngx/src/app/modules/home/components/calculated-fields/calculated-fields-table-config.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/components/arguments-table/calculated-field-arguments-table.component.html
  ui-ngx/src/app/modules/home/components/calculated-fields/components/arguments-table/calculated-field-arguments-table.component.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/components/panel/calculated-field-argument-panel.component.html
  ui-ngx/src/app/modules/home/components/calculated-fields/components/panel/calculated-field-argument-panel.component.ts
  ui-ngx/src/app/modules/home/components/entity/debug/entity-debug-settings-button.component.ts
  ui-ngx/src/app/modules/home/components/entity/debug/entity-debug-settings-panel.component.html
  ui-ngx/src/app/shared/models/calculated-field.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI, Ignore for release

#13046 Fixed circle for wind turbine cluster SCADA symbol
  application/src/main/data/json/system/scada_symbols/wind-turbine-cluster-hp.svg
Labels: bug, UI, Ignore for release

#13052 Minor improvement in map widget
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/custom-action-pretty-editor.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/custom-action-pretty-resources-tabs.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/widget-action.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/map/data-layer-color-settings-panel.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/map/data-layer-color-settings-panel.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/map/data-layer-pattern-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/map/marker-clustering-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/map/marker-image-settings-panel.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/map/trip-timeline-settings.component.html
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI, Ignore for release

#13051 Dynamic title height for widget title
  application/src/main/data/json/system/widget_types/bar_chart.json
  application/src/main/data/json/system/widget_types/bar_chart_with_labels.json
  application/src/main/data/json/system/widget_types/bars.json
  application/src/main/data/json/system/widget_types/doughnut.json
  application/src/main/data/json/system/widget_types/horizontal_doughnut.json
  application/src/main/data/json/system/widget_types/image_map.json
  application/src/main/data/json/system/widget_types/line_chart.json
  application/src/main/data/json/system/widget_types/map.json
  application/src/main/data/json/system/widget_types/pie.json
  application/src/main/data/json/system/widget_types/point_chart.json
  application/src/main/data/json/system/widget_types/polar_area.json
  application/src/main/data/json/system/widget_types/radar.json
  application/src/main/data/json/system/widget_types/range_chart.json
  application/src/main/data/json/system/widget_types/route_map.json
  application/src/main/data/json/system/widget_types/state_chart.json
  application/src/main/data/json/system/widget_types/time_series_chart.json
  application/src/main/data/json/system/widget_types/trip_map.json
  ui-ngx/src/app/modules/home/components/widget/lib/chart/bar-chart-with-labels-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/chart/bar-chart-with-labels-widget.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/chart/bar-chart-with-labels-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/chart/latest-chart-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/chart/latest-chart.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/chart/latest-chart.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/chart/latest-chart.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/chart/range-chart-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/chart/range-chart-widget.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/chart/range-chart-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/chart/time-series-chart-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/chart/time-series-chart-widget.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/chart/time-series-chart-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/maps/map-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/maps/map-widget.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/maps/map-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/widget-component.service.ts
  ui-ngx/src/app/modules/home/components/widget/widget-container.component.html
  ui-ngx/src/app/modules/home/components/widget/widget-container.component.ts
  ui-ngx/src/app/modules/home/components/widget/widget.component.ts
  ui-ngx/src/app/modules/home/models/widget-component.models.ts
  ui-ngx/src/app/shared/models/widget.models.ts
Labels: enhancement, UI, Ignore for release

#13037 Fixed vulnerabilities
  pom.xml
Labels: enhancement

#13059 Fix custom translation not working for Y-axis label in chart widget
  ui-ngx/src/app/modules/home/components/widget/lib/chart/time-series-chart.ts
Labels: bug, UI

#13063 Fix map settings not updating when switching between different map type widgets
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/map/map-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/map/map-widget-settings.component.ts
Labels: bug, UI, Ignore for release

#13067 Fixed scrolling markdown source code module
  ui-ngx/src/app/shared/models/js-function.models.ts
Labels: bug, UI

#13068 Fixed chart settings not updating when switching types in Advanced Mode
  ui-ngx/src/app/modules/home/components/widget/lib/settings/chart/time-series-chart-widget-settings.component.ts
Labels: bug, UI

#13071 Refactoring widget action
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/widget-action.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/widget-action.component.ts
Labels: enhancement, UI, Ignore for release

#13060 Fixed empty "Step increment" field and adaptive view in Pagination settings
  ui-ngx/src/app/modules/home/components/widget/lib/settings/alarm/alarms-table-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/alarm/alarms-table-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/timeseries-table-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/timeseries-table-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/control/persistent-table-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/control/persistent-table-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/entity/entities-table-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/entity/entities-table-widget-settings.component.ts
  ui-ngx/src/form.scss
  ui-ngx/tailwind.config.js
Labels: bug, UI, Ignore for release
