Repository thingsboard/thingsboard, pull requests merged in 2025-02, with the labels that each got.

#12497 Fix RPC Rule Node not producing any Success or Failure out message
  application/src/main/java/org/thingsboard/server/service/rpc/DefaultTbRuleEngineRpcService.java
Labels: bug, Rule Engine

#12509 Implemented Device Calculated Fields
  ui-ngx/src/app/core/http/calculated-fields.service.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/calculated-fields-table-config.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/calculated-fields-table.component.html
  ui-ngx/src/app/modules/home/components/calculated-fields/calculated-fields-table.component.scss
  ui-ngx/src/app/modules/home/components/calculated-fields/calculated-fields-table.component.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/components/arguments-table/calculated-field-arguments-table.component.html
  ui-ngx/src/app/modules/home/components/calculated-fields/components/arguments-table/calculated-field-arguments-table.component.scss
  ui-ngx/src/app/modules/home/components/calculated-fields/components/arguments-table/calculated-field-arguments-table.component.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.html
  ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/components/panel/calculated-field-argument-panel.component.html
  ui-ngx/src/app/modules/home/components/calculated-fields/components/panel/calculated-field-argument-panel.component.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/components/public-api.ts
  ui-ngx/src/app/modules/home/components/entity/debug/entity-debug-settings-button.component.ts
  ui-ngx/src/app/modules/home/components/entity/debug/entity-debug-settings-panel.component.ts
  ui-ngx/src/app/modules/home/components/entity/entities-table.component.ts
  ui-ngx/src/app/modules/home/components/home-components.module.ts
  ui-ngx/src/app/modules/home/models/entity/entity-table-component.models.ts
  ui-ngx/src/app/modules/home/pages/device/device-tabs.component.html
  ui-ngx/src/app/shared/components/entity/entity-autocomplete.component.html
  ui-ngx/src/app/shared/components/entity/entity-autocomplete.component.ts
  ui-ngx/src/app/shared/components/entity/entity-key-autocomplete.component.html
  ui-ngx/src/app/shared/components/entity/entity-key-autocomplete.component.ts
  ui-ngx/src/app/shared/components/js-func.component.ts
  ui-ngx/src/app/shared/models/calculated-field.models.ts
  ui-ngx/src/app/shared/models/constants.ts
  ui-ngx/src/app/shared/models/entity-type.models.ts
  ui-ngx/src/app/shared/models/id/calculated-field-id.ts
  ui-ngx/src/app/shared/models/public-api.ts
  ui-ngx/src/app/shared/models/regex.constants.ts
  ui-ngx/src/app/shared/shared.module.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: Major UI

#12581 core device actor: device subscriptions remove on session limit
  application/src/main/java/org/thingsboard/server/actors/device/DeviceActorMessageProcessor.java
Labels: Core

#12589 Fixed lose context when use expandSettingComponentMap in custom widgets
  ui-ngx/src/app/modules/home/components/widget/widget-component.service.ts
Labels: bug, UI, Ignore for release

#12599 Fixed unclear cached result in dashboard autocomplete when changing user
  ui-ngx/src/app/shared/components/dashboard-autocomplete.component.html
  ui-ngx/src/app/shared/components/dashboard-autocomplete.component.ts
Labels: bug, UI

#12593 Edge - fixed assignment/un-assignment of dashboards
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/dashboard/BaseDashboardProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/dashboard/DashboardEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/dashboard/DashboardEdgeProcessorV1.java
  application/src/test/java/org/thingsboard/server/edge/DashboardEdgeTest.java
Labels: bug, Edge

#12603 Added calculated field import/export
  ui-ngx/src/app/modules/home/components/calculated-fields/calculated-fields-table-config.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/calculated-fields-table.component.ts
  ui-ngx/src/app/shared/import-export/import-dialog.component.ts
  ui-ngx/src/app/shared/import-export/import-export.service.ts
  ui-ngx/src/app/shared/models/calculated-field.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI, Ignore for release

#12575 MQTT: fix unsubscribe error without previous subscribe
  common/transport/mqtt/src/main/java/org/thingsboard/server/transport/mqtt/MqttTransportHandler.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/service/DefaultTransportService.java
Labels: bug, Transport

#12565 Fix error in resource processing
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/resource/BaseResourceProcessor.java
  application/src/test/java/org/thingsboard/server/edge/ResourceEdgeTest.java
Labels: Ignore for release

#12612 Resolve gateway dashboard branch automatically
  application/src/main/java/org/thingsboard/server/service/entitiy/dashboard/DashboardSyncService.java
  application/src/main/java/org/thingsboard/server/service/install/DefaultDatabaseSchemaSettingsService.java
  application/src/main/java/org/thingsboard/server/service/install/ProjectInfo.java
  application/src/main/resources/thingsboard.yml
  common/version-control/src/main/java/org/thingsboard/server/service/sync/vc/GitRepository.java
Labels: Ignore for release

#12613 Calculated Fields Debug Events dialog basic implementation
  common/data/src/main/java/org/thingsboard/server/common/data/event/EventFilter.java
  ui-ngx/src/app/modules/home/components/calculated-fields/calculated-fields-table-config.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/components/debug-dialog/calculated-field-debug-dialog.component.html
  ui-ngx/src/app/modules/home/components/calculated-fields/components/debug-dialog/calculated-field-debug-dialog.component.scss
  ui-ngx/src/app/modules/home/components/calculated-fields/components/debug-dialog/calculated-field-debug-dialog.component.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.html
  ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/components/public-api.ts
  ui-ngx/src/app/modules/home/components/entity/debug/entity-debug-settings-button.component.ts
  ui-ngx/src/app/modules/home/components/entity/debug/entity-debug-settings-panel.component.html
  ui-ngx/src/app/modules/home/components/entity/debug/entity-debug-settings-panel.component.ts
  ui-ngx/src/app/modules/home/components/event/event-table-config.ts
  ui-ngx/src/app/modules/home/components/home-components.module.ts
  ui-ngx/src/app/shared/models/calculated-field.models.ts
  ui-ngx/src/app/shared/models/entity.models.ts
  ui-ngx/src/app/shared/models/event.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI, Ignore for release

#12651 Fix Basic auth in REST API call node
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/rest/TbHttpClient.java
Labels: bug, Rule Engine

#12551 Add 'Get dashboard state object' action type
  ui-ngx/src/app/modules/home/components/widget/lib/action/action-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/get-value-action-settings-panel.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/get-value-action-settings-panel.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/get-value-action-settings.component.ts
  ui-ngx/src/app/shared/models/action-widget-settings.models.ts
  ui-ngx/src/assets/help/en_US/widget/config/parse_value_get_dashboard_state_object_fn.md
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI, feature

#12630 Timewindow date-time period - improve behavior on changing start/end time
  ui-ngx/src/app/shared/components/time/datetime-period.component.html
  ui-ngx/src/app/shared/components/time/datetime-period.component.ts
Labels: enhancement, UI

#12633 Fixed CSV export for strings containing semicolon
  ui-ngx/src/app/shared/import-export/import-export.service.ts
Labels: bug, UI

#12634 Fixed incorrect entity details page link in entity autocomplete component
  ui-ngx/src/app/shared/components/entity/entity-autocomplete.component.html
  ui-ngx/src/app/shared/components/entity/entity-autocomplete.component.ts
Labels: bug, UI

#12663 Fixed incorrect liquid level widget config selector
  ui-ngx/src/app/modules/home/components/widget/config/basic/indicator/liquid-level-card-basic-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/indicator/liquid-level-card-widget-settings.component.ts
Labels: bug, UI, Ignore for release

#12664 Fixed incorrect shape layout settings in liquid level widget
  ui-ngx/src/app/modules/home/components/widget/config/basic/indicator/liquid-level-card-basic-config.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/indicator/liquid-level-card-widget-settings.component.html
Labels: bug, UI

#12653 Improved Edge handling in case connect/disconnect. Speed up initial setup
  application/src/main/data/json/edge/instructions/upgrade/docker/upgrade_db.md
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcService.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/fetch/GeneralEdgeEventFetcher.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/dashboard/BaseDashboardProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/sync/EdgeRequestsService.java
  application/src/test/java/org/thingsboard/server/edge/DashboardEdgeTest.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/KafkaMonolithQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/KafkaTbCoreQueueFactory.java
Labels: enhancement, Edge

#12595 Added test to verify attribute and RPC subscriptions removal
  application/src/main/java/org/thingsboard/server/actors/device/DeviceActorMessageProcessor.java
  application/src/test/java/org/thingsboard/server/actors/device/DeviceActorMessageProcessorTest.java
Labels: Ignore for release

#12650 Implemented Calculated Fields debug test
  ui-ngx/src/app/core/http/calculated-fields.service.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/calculated-fields-table-config.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/components/arguments-table/calculated-field-arguments-table.component.html
  ui-ngx/src/app/modules/home/components/calculated-fields/components/debug-dialog/calculated-field-debug-dialog.component.html
  ui-ngx/src/app/modules/home/components/calculated-fields/components/debug-dialog/calculated-field-debug-dialog.component.scss
  ui-ngx/src/app/modules/home/components/calculated-fields/components/debug-dialog/calculated-field-debug-dialog.component.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.html
  ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/components/public-api.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/components/test-arguments/calculated-field-test-arguments.component.html
  ui-ngx/src/app/modules/home/components/calculated-fields/components/test-arguments/calculated-field-test-arguments.component.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/components/test-dialog/calculated-field-script-test-dialog.component.html
  ui-ngx/src/app/modules/home/components/calculated-fields/components/test-dialog/calculated-field-script-test-dialog.component.scss
  ui-ngx/src/app/modules/home/components/calculated-fields/components/test-dialog/calculated-field-script-test-dialog.component.ts
  ui-ngx/src/app/modules/home/components/entity/debug/entity-debug-settings-panel.component.html
  ui-ngx/src/app/modules/home/components/event/event-table-config.ts
  ui-ngx/src/app/modules/home/components/home-components.module.ts
  ui-ngx/src/app/shared/components/value-input.component.html
  ui-ngx/src/app/shared/components/value-input.component.ts
  ui-ngx/src/app/shared/models/calculated-field.models.ts
  ui-ngx/src/app/shared/models/entity.models.ts
  ui-ngx/src/app/shared/models/rule-node.models.ts
  ui-ngx/src/assets/help/en_US/calculated-field/expression_fn.md
  ui-ngx/src/assets/help/en_US/calculated-field/test-expression_fn.md
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI, feature, Ignore for release

#12685 Calculated field adjustments
  ui-ngx/src/app/modules/home/components/calculated-fields/calculated-fields-table-config.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.html
  ui-ngx/src/app/modules/home/components/entity/entities-table.component.ts
  ui-ngx/src/app/modules/home/components/event/event-table-config.ts
  ui-ngx/src/app/modules/home/models/entity/entities-table-config.models.ts
  ui-ngx/src/app/modules/home/pages/device-profile/device-profile-tabs.component.html
Labels: enhancement, UI, Ignore for release

#12566 Fix error in deviceProfile processing
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeSyncCursor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/BaseEdgeProcessor.java
  application/src/test/java/org/thingsboard/server/controller/EdgeControllerTest.java
  application/src/test/java/org/thingsboard/server/edge/AbstractEdgeTest.java
  application/src/test/java/org/thingsboard/server/edge/DeviceProfileEdgeTest.java
Labels: bug, Edge

#12691 Added debug events action from calculated field table
  ui-ngx/src/app/modules/home/components/calculated-fields/calculated-fields-table-config.ts
Labels: enhancement, UI, Ignore for release

#12694 Added Calculated field arguments autocomplete
  ui-ngx/src/app/modules/home/components/calculated-fields/calculated-fields-table-config.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.html
  ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/components/test-dialog/calculated-field-script-test-dialog.component.html
  ui-ngx/src/app/shared/components/js-func.component.ts
  ui-ngx/src/app/shared/models/calculated-field.models.ts
Labels: enhancement, UI, Ignore for release

#12700 Calculated field adjustments
  ui-ngx/src/app/modules/home/components/calculated-fields/calculated-fields-table-config.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/components/arguments-table/calculated-field-arguments-table.component.html
  ui-ngx/src/app/modules/home/components/calculated-fields/components/arguments-table/calculated-field-arguments-table.component.scss
  ui-ngx/src/app/modules/home/components/calculated-fields/components/arguments-table/calculated-field-arguments-table.component.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.html
  ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.scss
  ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/components/panel/calculated-field-argument-panel.component.html
  ui-ngx/src/app/modules/home/components/calculated-fields/components/test-arguments/calculated-field-test-arguments.component.html
  ui-ngx/src/app/modules/home/components/calculated-fields/components/test-arguments/calculated-field-test-arguments.component.scss
  ui-ngx/src/app/modules/home/components/calculated-fields/components/test-arguments/calculated-field-test-arguments.component.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/components/test-dialog/calculated-field-script-test-dialog.component.html
  ui-ngx/src/app/modules/home/components/calculated-fields/components/test-dialog/calculated-field-script-test-dialog.component.scss
  ui-ngx/src/app/modules/home/components/calculated-fields/components/test-dialog/calculated-field-script-test-dialog.component.ts
  ui-ngx/src/app/shared/components/dialog/json-object-edit-dialog.component.html
  ui-ngx/src/app/shared/components/dialog/json-object-edit-dialog.component.ts
  ui-ngx/src/app/shared/components/js-func.component.ts
  ui-ngx/src/app/shared/components/value-input.component.html
  ui-ngx/src/app/shared/components/value-input.component.ts
  ui-ngx/src/app/shared/models/calculated-field.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: UI, feature, Ignore for release

#12627 Value stepper widget
  application/src/main/data/json/system/widget_bundles/buttons.json
  application/src/main/data/json/system/widget_bundles/control_widgets.json
  application/src/main/data/json/system/widget_types/value_stepper.json
  ui-ngx/src/app/modules/home/components/widget/config/basic/basic-widget-config.module.ts
  ui-ngx/src/app/modules/home/components/widget/config/basic/button/power-button-basic-config.component.html
  ui-ngx/src/app/modules/home/components/widget/config/basic/button/power-button-basic-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/config/basic/rpc/value-stepper-basic-config.component.html
  ui-ngx/src/app/modules/home/components/widget/config/basic/rpc/value-stepper-basic-config.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/rpc/power-button-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/rpc/power-button-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/rpc/value-stepper-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/rpc/value-stepper-widget.component.scss
  ui-ngx/src/app/modules/home/components/widget/lib/rpc/value-stepper-widget.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/rpc/value-stepper-widget.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/control/value-stepper-widget-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/control/value-stepper-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/widget-settings.module.ts
  ui-ngx/src/app/modules/home/components/widget/widget-components.module.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
  ui-ngx/src/assets/widget/value-stepper/filled.svg
  ui-ngx/src/assets/widget/value-stepper/simplified.svg
  ui-ngx/src/assets/widget/value-stepper/volume.svg
Labels: UI, feature

#12666 Fixed apply changes button enabled by default in Device Profile Transport configuration tab
  ui-ngx/src/app/modules/home/components/profile/device/device-profile-transport-configuration.component.ts
Labels: bug, UI

#12682 Imporove description for scada symbols
  application/src/main/data/json/system/scada_symbols/control-panel-hp.svg
  application/src/main/data/json/system/scada_symbols/horizontal-connector-hp.svg
  application/src/main/data/json/system/scada_symbols/leak-sensor.svg
  application/src/main/data/json/system/scada_symbols/left-analog-water-level-meter.svg
  application/src/main/data/json/system/scada_symbols/left-drain-pipe.svg
  application/src/main/data/json/system/scada_symbols/left-elbow-drain-pipe.svg
  application/src/main/data/json/system/scada_symbols/long-bottom-filter.svg
  application/src/main/data/json/system/scada_symbols/long-horizontal-connector-hp.svg
  application/src/main/data/json/system/scada_symbols/long-top-filter.svg
  application/src/main/data/json/system/scada_symbols/long-vertical-connector-hp.svg
  application/src/main/data/json/system/scada_symbols/right-analog-water-level-meter.svg
  application/src/main/data/json/system/scada_symbols/right-drain-pipe.svg
  application/src/main/data/json/system/scada_symbols/right-elbow-drain-pipe.svg
  application/src/main/data/json/system/scada_symbols/short-bottom-filter.svg
  application/src/main/data/json/system/scada_symbols/short-left-drain-pipe.svg
  application/src/main/data/json/system/scada_symbols/short-right-drain-pipe.svg
  application/src/main/data/json/system/scada_symbols/short-top-filter.svg
  application/src/main/data/json/system/scada_symbols/vertical-connector-hp.svg
Labels: enhancement, UI

#12684 Fixed scale symbol units
  application/src/main/data/json/system/scada_symbols/dynamic-vertical-scale-hp.svg
  application/src/main/data/json/system/scada_symbols/simple-vertical-scale-hp.svg
Labels: bug, UI, Ignore for release

#12704 Improve Mobile center Bundle validators, remove redundant request
  ui-ngx/src/app/modules/home/pages/mobile/bundes/layout/custom-mobile-page.component.html
  ui-ngx/src/app/modules/home/pages/mobile/bundes/layout/custom-mobile-page.component.ts
  ui-ngx/src/app/modules/home/pages/mobile/bundes/mobile-bundle-dialog.component.html
  ui-ngx/src/app/modules/home/pages/mobile/bundes/mobile-bundle-dialog.component.ts
  ui-ngx/src/app/modules/home/pages/mobile/bundes/mobile-bundle-table-config.resolve.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI

#12711 Add property decimals for flow meter symbol
  application/src/main/data/json/system/scada_symbols/bottom-flow-meter.svg
  application/src/main/data/json/system/scada_symbols/horizontal-inline-flow-meter.svg
  application/src/main/data/json/system/scada_symbols/left-flow-meter.svg
  application/src/main/data/json/system/scada_symbols/right-flow-meter.svg
  application/src/main/data/json/system/scada_symbols/top-flow-meter.svg
  application/src/main/data/json/system/scada_symbols/vertical-inline-flow-meter.svg
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI

#12722 SCADA Oil and gas extraction
  application/src/main/data/json/system/scada_symbols/electrical-engine-hp.svg
  application/src/main/data/json/system/scada_symbols/gas-preventer-hp.svg
  application/src/main/data/json/system/scada_symbols/gas-wellhead-hp.svg
  application/src/main/data/json/system/scada_symbols/heat-exchanger-hp.svg
  application/src/main/data/json/system/scada_symbols/large-horizontal-separator-connector-hp.svg
  application/src/main/data/json/system/scada_symbols/large-horizontal-separator-hp.svg
  application/src/main/data/json/system/scada_symbols/large-vertical-separator-connector-hp.svg
  application/src/main/data/json/system/scada_symbols/large-vertical-separator-hp.svg
  application/src/main/data/json/system/scada_symbols/oil-pump-hp.svg
  application/src/main/data/json/system/scada_symbols/small-horizontal-separator-connector-hp.svg
  application/src/main/data/json/system/scada_symbols/small-horizontal-separator-hp.svg
  application/src/main/data/json/system/scada_symbols/small-vertical-separator-connector-hp.svg
  application/src/main/data/json/system/scada_symbols/small-vertical-separator-hp.svg
  application/src/main/data/json/system/scada_symbols/turbine-hp.svg
  application/src/main/data/json/system/widget_bundles/general_high_performance_scada_symbols.json
  application/src/main/data/json/system/widget_bundles/high_performance_scada_oil_gas.json
Labels: UI, feature

#12623 Fixed a blur effect issue in the Getting started widget
  ui-ngx/src/app/modules/home/components/widget/lib/home-page/getting-started-widget.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/home-page/getting-started-widget.component.scss
Labels: bug, UI

#12628 Fixed mdc notch unnecessary border
  ui-ngx/src/form.scss
Labels: bug, UI

#12688 Add bundles to widget type info
  application/src/main/java/org/thingsboard/server/controller/BaseController.java
  application/src/main/java/org/thingsboard/server/controller/WidgetTypeController.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/widget/WidgetTypeService.java
  common/data/src/main/java/org/thingsboard/server/common/data/widget/WidgetBundleInfo.java
  common/data/src/main/java/org/thingsboard/server/common/data/widget/WidgetTypeInfo.java
  dao/src/main/java/org/thingsboard/server/dao/model/ModelConstants.java
  dao/src/main/java/org/thingsboard/server/dao/model/sql/WidgetTypeInfoEntity.java
  dao/src/main/java/org/thingsboard/server/dao/sql/widget/JpaWidgetTypeDao.java
  dao/src/main/java/org/thingsboard/server/dao/widget/WidgetTypeDao.java
  dao/src/main/java/org/thingsboard/server/dao/widget/WidgetTypeServiceImpl.java
  dao/src/main/resources/sql/schema-views-and-functions.sql
  dao/src/test/java/org/thingsboard/server/dao/sql/widget/JpaWidgetTypeDaoTest.java
  ui-ngx/src/app/modules/home/components/entity/entities-table.component.html
  ui-ngx/src/app/modules/home/components/entity/entity-chips.component.ts
  ui-ngx/src/app/modules/home/models/entity/entities-table-config.models.ts
  ui-ngx/src/app/modules/home/pages/widget/widget-types-table-config.resolver.ts
  ui-ngx/src/app/shared/models/widget.models.ts
Labels: UI, feature, Core

#12699 LwM2M: fix observe
  application/src/test/java/org/thingsboard/server/transport/lwm2m/AbstractLwM2MIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/Lwm2mTestHelper.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/client/LwM2MTestClient.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/AbstractRpcLwM2MIntegrationObserve_Ver_1_0_Test.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/AbstractRpcLwM2MIntegrationObserve_Ver_1_1_Test.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/AbstractRpcLwM2MIntegrationObserve_Ver_1_2_Test.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/AbstractRpcLwM2MIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2MIntegrationObserveCompositeTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationObserveTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationObserve_Ver_1_0_Test.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationObserve_Ver_1_1_Test.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationObserve_Ver_1_2_Test.java
  application/src/test/resources/lwm2m/3-1_0.xml
  application/src/test/resources/lwm2m/3-1_1.xml
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mClient.java
Labels: bug, Transport

#12448 Edge - improve attribute update strategy
  application/src/main/java/org/thingsboard/server/service/edge/EdgeMsgConstructorUtils.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/telemetry/BaseTelemetryProcessor.java
  application/src/test/java/org/thingsboard/server/edge/DeviceEdgeTest.java
  common/edge-api/src/main/proto/edge.proto
  common/proto/src/main/java/org/thingsboard/server/common/adaptor/JsonConverter.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/util/JsonUtils.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/edge/AbstractTbMsgPushNode.java
Labels: Edge

#12458 Edge - alarm ack & alarm clear sent by 'Push to Edge' node only
  application/src/main/java/org/thingsboard/server/service/edge/EdgeEventSourcingListener.java
  application/src/test/java/org/thingsboard/server/controller/AlarmControllerTest.java
  application/src/test/java/org/thingsboard/server/edge/AlarmEdgeTest.java
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/edge/AbstractTbMsgPushNode.java
Labels: Edge

#12725 Fix CoAP enabled properties
  application/src/main/resources/thingsboard.yml
  application/src/test/java/org/thingsboard/server/transport/coap/AbstractCoapIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/coap/security/AbstractCoapSecurityIntegrationTest.java
  application/src/test/resources/application-test.properties
  common/coap-server/src/main/java/org/thingsboard/server/coapserver/TbCoapServerComponent.java
  common/coap-server/src/main/java/org/thingsboard/server/coapserver/TbCoapTransportComponent.java
Labels: bug, Transport

#12648 Added versioning for ApiUsageState entity
  application/src/main/data/upgrade/basic/schema_update.sql
  application/src/main/java/org/thingsboard/server/service/apiusage/BaseApiUsageState.java
  application/src/main/java/org/thingsboard/server/service/apiusage/DefaultTbApiUsageStateService.java
  application/src/test/java/org/thingsboard/server/service/apiusage/ApiUsageTest.java
  application/src/test/java/org/thingsboard/server/service/apiusage/DefaultTbApiUsageStateServiceTest.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/usagerecord/ApiUsageStateService.java
  common/data/src/main/java/org/thingsboard/server/common/data/ApiUsageState.java
  common/proto/src/main/java/org/thingsboard/server/common/util/ProtoUtils.java
  common/proto/src/main/proto/queue.proto
  dao/src/main/java/org/thingsboard/server/dao/model/sql/ApiUsageStateEntity.java
  dao/src/main/java/org/thingsboard/server/dao/usagerecord/ApiUsageStateServiceImpl.java
  dao/src/main/resources/sql/schema-entities.sql
  dao/src/test/java/org/thingsboard/server/dao/service/ApiUsageStateServiceTest.java
Labels: Ignore for release

#12751 [Input node] Use correct queue name from msg
  application/src/main/java/org/thingsboard/server/actors/ruleChain/DefaultTbContext.java
  application/src/test/java/org/thingsboard/server/actors/rule/DefaultTbContextTest.java
Labels: bug, Rule Engine

#12743 Calculated fields adjustments
  ui-ngx/src/app/modules/home/components/calculated-fields/components/arguments-table/calculated-field-arguments-table.component.html
  ui-ngx/src/app/modules/home/components/calculated-fields/components/arguments-table/calculated-field-arguments-table.component.scss
  ui-ngx/src/app/modules/home/components/calculated-fields/components/arguments-table/calculated-field-arguments-table.component.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.ts
  ui-ngx/src/app/shared/models/calculated-field.models.ts
Labels: enhancement, UI, Ignore for release

#12723 Added new map action type - Map action buttons
  application/src/main/data/json/system/widget_types/image_map.json
  application/src/main/data/json/system/widget_types/map.json
  ui-ngx/src/app/modules/home/components/widget/action/manage-widget-actions-dialog.component.html
  ui-ngx/src/app/modules/home/components/widget/action/manage-widget-actions-dialog.component.ts
  ui-ngx/src/app/modules/home/components/widget/action/manage-widget-actions.component.ts
  ui-ngx/src/app/modules/home/components/widget/action/widget-action-dialog.component.html
  ui-ngx/src/app/modules/home/components/widget/action/widget-action-dialog.component.ts
  ui-ngx/src/app/modules/home/components/widget/config/basic/common/widget-actions-panel.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/maps/leaflet/leaflet-tb.ts
  ui-ngx/src/app/modules/home/components/widget/lib/maps/map.scss
  ui-ngx/src/app/modules/home/components/widget/lib/maps/map.ts
  ui-ngx/src/app/modules/home/components/widget/lib/maps/models/map.models.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/widget-action-settings-panel.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/widget-action-settings-panel.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/widget-action-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/widget-action.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/widget-action.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/map/map-action-button-row.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/map/map-action-button-row.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/map/map-action-buttons-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/map/map-action-buttons-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/map/map-settings.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/map/map-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/widget-settings-common.module.ts
  ui-ngx/src/app/modules/home/components/widget/widget-component.service.ts
  ui-ngx/src/app/modules/home/components/widget/widget-config.component.html
  ui-ngx/src/app/modules/home/components/widget/widget.component.ts
  ui-ngx/src/app/shared/models/widget.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
  ui-ngx/src/typings/leaflet-extend-tb.d.ts
Labels: UI, feature

#12767 JS func update
  common/script/script-api/src/test/java/org/thingsboard/script/api/tbel/TbelCfTsRollingArgTest.java
  ui-ngx/src/app/shared/components/js-func.component.ts
Labels: UI, Ignore for release

#12761 use queueName from TbMsg for enqueue
  application/src/main/java/org/thingsboard/server/actors/ruleChain/DefaultTbContext.java
  application/src/test/java/org/thingsboard/server/actors/rule/DefaultTbContextTest.java
  rule-engine/rule-engine-api/src/main/java/org/thingsboard/rule/engine/api/TbContext.java
Labels: Ignore for release

#12763 Fix invalid entity version after creation
  application/src/test/java/org/thingsboard/server/controller/DeviceProfileControllerTest.java
  dao/src/main/java/org/thingsboard/server/dao/sql/JpaAbstractDao.java
Labels: bug, Core

#12508 Added validation for resource usage across entities
  application/src/main/java/org/thingsboard/server/controller/TbResourceController.java
  application/src/main/java/org/thingsboard/server/service/resource/DefaultTbResourceService.java
  application/src/main/java/org/thingsboard/server/service/resource/TbResourceService.java
  application/src/test/java/org/thingsboard/server/controller/TbResourceControllerTest.java
  application/src/test/java/org/thingsboard/server/service/resource/sql/BaseTbResourceServiceTest.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/resource/ResourceService.java
  common/data/src/main/java/org/thingsboard/server/common/data/TbResourceDeleteResult.java
  dao/src/main/java/org/thingsboard/server/dao/ResourceContainerDao.java
  dao/src/main/java/org/thingsboard/server/dao/dashboard/DashboardInfoDao.java
  dao/src/main/java/org/thingsboard/server/dao/resource/BaseImageService.java
  dao/src/main/java/org/thingsboard/server/dao/resource/BaseResourceService.java
  dao/src/main/java/org/thingsboard/server/dao/service/validator/ResourceDataValidator.java
  dao/src/main/java/org/thingsboard/server/dao/sql/dashboard/DashboardInfoRepository.java
  dao/src/main/java/org/thingsboard/server/dao/sql/dashboard/JpaDashboardInfoDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/widget/JpaWidgetTypeDao.java
  dao/src/main/java/org/thingsboard/server/dao/sql/widget/WidgetTypeInfoRepository.java
  dao/src/main/java/org/thingsboard/server/dao/sql/widget/WidgetTypeRepository.java
  dao/src/main/java/org/thingsboard/server/dao/widget/WidgetTypeDao.java
  ui-ngx/src/app/core/http/resource.service.ts
  ui-ngx/src/app/modules/home/pages/admin/resource/js-library-table-config.resolver.ts
  ui-ngx/src/app/modules/home/pages/admin/resource/resources-datasource.ts
  ui-ngx/src/app/shared/components/image/image-gallery.component.ts
  ui-ngx/src/app/shared/components/image/image-references.component.ts
  ui-ngx/src/app/shared/components/resource/resources-in-use-dialog.component.html
  ui-ngx/src/app/shared/components/resource/resources-in-use-dialog.component.scss
  ui-ngx/src/app/shared/components/resource/resources-in-use-dialog.component.ts
  ui-ngx/src/app/shared/models/resource.models.ts
  ui-ngx/src/app/shared/shared.module.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: Core

#12739 TbDate - added functions to add years, months, days, etc.
  common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/TbDate.java
  common/script/script-api/src/test/java/org/thingsboard/script/api/tbel/TbDateTest.java
Labels: Tbel

#12777 [CoAP transport] removed unnecessary coap configs
  msa/black-box-tests/src/test/java/org/thingsboard/server/msa/ContainerTestSuite.java
  transport/coap/src/main/resources/tb-coap-transport.yml
Labels: Ignore for release

#12791 Added tenant profile configs for Calculated Fields
  ui-ngx/src/app/core/auth/auth.models.ts
  ui-ngx/src/app/core/auth/auth.reducer.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/components/arguments-table/calculated-field-arguments-table.component.html
  ui-ngx/src/app/modules/home/components/calculated-fields/components/arguments-table/calculated-field-arguments-table.component.scss
  ui-ngx/src/app/modules/home/components/calculated-fields/components/arguments-table/calculated-field-arguments-table.component.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/components/panel/calculated-field-argument-panel.component.html
  ui-ngx/src/app/modules/home/components/calculated-fields/components/panel/calculated-field-argument-panel.component.scss
  ui-ngx/src/app/modules/home/components/calculated-fields/components/panel/calculated-field-argument-panel.component.ts
  ui-ngx/src/app/modules/home/components/profile/tenant/default-tenant-profile-configuration.component.html
  ui-ngx/src/app/modules/home/components/profile/tenant/default-tenant-profile-configuration.component.ts
  ui-ngx/src/app/modules/home/components/profile/tenant/rate-limits/rate-limits.models.ts
  ui-ngx/src/app/shared/models/tenant.model.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI, Ignore for release

#12796 Added rolling argument functions autocompletes
  ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.html
  ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.scss
  ui-ngx/src/app/modules/home/components/calculated-fields/components/test-dialog/calculated-field-script-test-dialog.component.html
  ui-ngx/src/app/modules/home/components/calculated-fields/components/test-dialog/calculated-field-script-test-dialog.component.scss
  ui-ngx/src/app/shared/models/calculated-field.models.ts
  ui-ngx/src/assets/help/en_US/calculated-field/test-expression_fn.md
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI, Ignore for release

#12437 [TBEL] Fix parsing double with scientific notation
  common/script/script-api/src/main/java/org/thingsboard/script/api/tbel/TbUtils.java
  common/script/script-api/src/test/java/org/thingsboard/script/api/tbel/TbUtilsTest.java
Labels: bug, Tbel
