Repository thingsboard/thingsboard, pull requests merged in 2025-04, with the labels that each got.

#13073 Fixed default action header button color
  ui-ngx/src/app/modules/home/components/widget/action/widget-action-dialog.component.ts
Labels: bug, UI, Ignore for release

#13080 Fixed positioning for color picker popover
  ui-ngx/src/app/shared/components/color-input.component.ts
Labels: bug, UI, Ignore for release

#13084 Add to place map item action - customize tooltip
  ui-ngx/src/app/core/services/utils.service.ts
  ui-ngx/src/app/modules/home/components/widget/lib/maps/map.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/map-item-tooltips.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/map-item-tooltips.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/widget-action.component.html
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/action/widget-action.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/widget-settings-common.module.ts
  ui-ngx/src/app/shared/models/widget.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI, Ignore for release

#13086 Fixed typo in 'Calculate Field' script section title
  ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.html
Labels: bug, UI, Ignore for release

#13087 Fixed time-unit component not correctly calculating selected time
  ui-ngx/src/app/modules/home/components/rule-node/common/time-unit-input.component.ts
Labels: bug, UI, Ignore for release

#13090 Add fetch function for string items list; fix double item addition on blur
  ui-ngx/src/app/shared/components/string-items-list.component.html
  ui-ngx/src/app/shared/components/string-items-list.component.ts
Labels: bug, enhancement, UI, Ignore for release

#13092 Error icon with tooltip for toggle select for Map widget settings
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/map/map-settings.component.html
  ui-ngx/src/app/shared/components/toggle-header.component.html
  ui-ngx/src/app/shared/components/toggle-header.component.scss
  ui-ngx/src/app/shared/components/toggle-header.component.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI, Ignore for release

#12843 Fix RuleChainMetadata for older Edge versions
  application/src/main/java/org/thingsboard/server/service/edge/EdgeMsgConstructorUtils.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/EdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/alarm/AlarmEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/alarm/comment/AlarmCommentEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/asset/AssetEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/asset/profile/AssetProfileEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/customer/CustomerEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/dashboard/DashboardEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/device/DeviceEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/device/profile/DeviceProfileEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/edge/EdgeEntityProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/entityview/EntityViewEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/notification/NotificationRuleEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/notification/NotificationTargetEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/notification/NotificationTemplateEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/oauth2/DomainEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/oauth2/OAuth2ClientEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/ota/OtaPackageEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/queue/QueueEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/relation/RelationEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/resource/ResourceEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/rule/RuleChainEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/rule/RuleChainMetadataEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/settings/AdminSettingsEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/tenant/TenantEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/tenant/TenantProfileEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/user/UserEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/widget/WidgetBundleEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/widget/WidgetTypeEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/utils/EdgeVersionUtils.java
  application/src/test/java/org/thingsboard/server/service/edge/EdgeMsgConstructorUtilsTest.java
Labels: bug, Edge, Ignore for release

#13070 Different data type comparison
  application/src/test/java/org/thingsboard/server/service/entitiy/EntityServiceTest.java
  common/edqs/src/main/java/org/thingsboard/server/edqs/data/dp/BoolDataPoint.java
  common/edqs/src/main/java/org/thingsboard/server/edqs/data/dp/DoubleDataPoint.java
  common/edqs/src/main/java/org/thingsboard/server/edqs/data/dp/LongDataPoint.java
Labels: Ignore for release

#13081 EDQS: “N/A” message doesn’t display
  application/src/test/java/org/thingsboard/server/controller/EntityQueryControllerTest.java
  common/edqs/src/main/java/org/thingsboard/server/edqs/util/RepositoryUtils.java
Labels: Ignore for release

#13025 [Telemetry] WS Subscription: Older telemetry overwrites newer data on UI
  application/src/main/java/org/thingsboard/server/service/subscription/DefaultTbLocalSubscriptionService.java
  application/src/main/java/org/thingsboard/server/service/ws/DefaultWebSocketService.java
  application/src/test/java/org/thingsboard/server/controller/TbTestWebSocketClient.java
  application/src/test/java/org/thingsboard/server/controller/WebsocketApiTest.java
  common/data/src/main/java/org/thingsboard/server/common/data/DataConstants.java
Labels: bug

#12876 fix_bug_lwm2m_fota_3
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/secure/LwM2mCredentialsSecurityInfoValidator.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/DefaultLwM2mTransportService.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/LwM2mTransportCoapResource.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/client/LwM2mClientContextImpl.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/utils/LwM2MTransportUtil.java
Labels: bug, Transport

#13056 Query timeout is not working for EntityDataQuery
  dao/src/main/java/org/thingsboard/server/dao/sql/NamedParameterJdbcTemplateConfiguration.java
  dao/src/test/java/org/thingsboard/server/dao/sql/JdbcTemplateTest.java
Labels: bug

#13121 EDQS: added error handling while data sync
  application/src/main/java/org/thingsboard/server/service/edqs/EdqsSyncService.java
Labels: Ignore for release

#13117 Configurable gateway image version
  application/src/main/resources/thingsboard.yml
  application/src/test/java/org/thingsboard/server/controller/DeviceConnectivityControllerTest.java
  dao/src/main/java/org/thingsboard/server/dao/device/DeviceConnectivityServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/util/DeviceConnectivityUtil.java
Labels: Ignore for release

#13105 Color settings panel tab validation
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/color-settings-panel.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/common/map/data-layer-color-settings-panel.component.ts
Labels: enhancement, UI

#13106 Fixed enter press trigger click handler in dialogs
  ui-ngx/src/app/modules/home/components/entity/debug/entity-debug-settings-button.component.html
Labels: bug, UI, Ignore for release

#13108 Add link, table and image for text editor panel
  ui-ngx/src/app/modules/home/pages/mobile/common/editor-panel.component.ts
Labels: enhancement, UI

#13111 Fixed calculated fields translation
  ui-ngx/src/app/modules/home/components/calculated-fields/components/debug-dialog/calculated-field-debug-dialog.component.html
  ui-ngx/src/app/modules/home/components/calculated-fields/components/debug-dialog/calculated-field-debug-dialog.component.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.html
  ui-ngx/src/app/modules/home/components/event/event-table-config.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI, Ignore for release

#13126 Updated default value maxDebugModeDurationMinutes in tenant profile
  ui-ngx/src/app/shared/models/tenant.model.ts
Labels: enhancement, UI, Ignore for release

#13127 Fixed import file dialog when long file name
  ui-ngx/src/app/shared/import-export/import-dialog.component.html
Labels: bug, UI, Ignore for release

#13116 Fixed debug settings panel; Improved model data entity debug setting panel
  ui-ngx/src/app/core/auth/auth.models.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/calculated-fields-table-config.ts
  ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.html
  ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.ts
  ui-ngx/src/app/modules/home/components/entity/debug/entity-debug-settings-button.component.ts
  ui-ngx/src/app/modules/home/components/entity/debug/entity-debug-settings-panel.component.html
  ui-ngx/src/app/modules/home/components/entity/debug/entity-debug-settings-panel.component.ts
  ui-ngx/src/app/modules/home/components/entity/debug/entity-debug-settings.model.ts
  ui-ngx/src/app/modules/home/pages/rulechain/rule-node-details.component.html
  ui-ngx/src/app/modules/home/pages/rulechain/rule-node-details.component.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: bug, UI, Ignore for release

#13135 Fixed bug in delete enabled calculation in JS library
  ui-ngx/src/app/modules/home/pages/admin/resource/js-library-table-config.resolver.ts
Labels: bug, UI, Ignore for release

#13132 Added show help on math funcs in Calculated field simple expression
  ui-ngx/src/app/modules/home/components/calculated-fields/components/dialog/calculated-field-dialog.component.html
  ui-ngx/src/app/modules/home/components/rule-node/action/math-function-config.component.html
  ui-ngx/src/assets/help/en_US/math/math-methods_fn.md
Labels: enhancement, UI

#13139 Fixed customer home dashboard not correct work active/inactive device link
  ui-ngx/src/assets/dashboard/customer_user_home_page.json
Labels: bug, UI

#13146 Fixed show popover some time not showing occasionally on first interaction
  ui-ngx/src/app/shared/components/popover.component.ts
Labels: bug, UI

#7912 Now, when you reset password, you redirected to login page
  application/src/main/java/org/thingsboard/server/controller/AuthController.java
  application/src/test/java/org/thingsboard/server/controller/UserControllerTest.java
  ui-ngx/src/app/core/auth/auth.service.ts
  ui-ngx/src/app/modules/login/pages/login/reset-password.component.ts
Labels: UI, Core

#13149 Update locale.constant-zh_CN
  ui-ngx/src/assets/locale/locale.constant-zh_CN.json
Labels: UI, Ignore for release

#13130 Avoid Creation of Unnecessary Public Customers During Edge Connection
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeSyncCursor.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/customer/CustomerEdgeProcessor.java
  application/src/main/java/org/thingsboard/server/service/queue/DefaultTbClusterService.java
  application/src/main/java/org/thingsboard/server/service/queue/DefaultTbEdgeConsumerService.java
  application/src/test/java/org/thingsboard/server/controller/EdgeControllerTest.java
  application/src/test/java/org/thingsboard/server/edge/AbstractEdgeTest.java
  application/src/test/java/org/thingsboard/server/edge/TenantProfileEdgeTest.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/customer/CustomerService.java
  dao/src/main/java/org/thingsboard/server/dao/customer/CustomerServiceImpl.java
Labels: Edge

#13147 Enhance Edge Queue Processing with Rate Limiting and Logging Improvements
  application/src/main/java/org/thingsboard/server/service/edge/EdgeMsgConstructorUtils.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java
  application/src/main/resources/thingsboard.yml
  common/queue/src/main/java/org/thingsboard/server/queue/discovery/TopicService.java
  common/queue/src/main/java/org/thingsboard/server/queue/kafka/TbKafkaSettings.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/TbCoreQueueProducerProvider.java
Labels: bug, Ignore for release

#13156 Fix overwrite of externalId on save widget
  ui-ngx/src/app/modules/home/models/widget-component.models.ts
  ui-ngx/src/app/shared/models/widget.models.ts
Labels: bug, UI

#13158 Add Echart in modules map
  ui-ngx/src/app/modules/common/modules-map.ts
Labels: UI, Ignore for release

#13160 JavaScript library style enhancement
  ui-ngx/src/app/modules/home/pages/admin/resource/js-resource.component.html
  ui-ngx/src/app/shared/components/js-func.component.scss
Labels: enhancement, UI

#13171 Added timezone selection in widget settings timewindow
  ui-ngx/src/app/modules/home/components/widget/config/timewindow-config-panel.component.html
Labels: bug, UI

#13172 Improved CSS styles for copy-code button in markdown
  ui-ngx/src/app/modules/home/pages/device/device-check-connectivity-dialog.component.scss
  ui-ngx/src/app/shared/components/markdown.component.scss
Labels: enhancement, UI

#13110 Show Error msg for bad xml on save SCADA symbol
  ui-ngx/src/app/modules/home/components/widget/lib/scada/scada-symbol.models.ts
  ui-ngx/src/app/modules/home/pages/scada-symbol/scada-symbol.component.ts
  ui-ngx/src/app/shared/components/image/upload-image-dialog.component.html
  ui-ngx/src/app/shared/components/image/upload-image-dialog.component.ts
Labels: enhancement, UI

#13181 Fixed visability actions table header in preview mode for widget settings
  ui-ngx/src/app/modules/home/components/widget/action/manage-widget-actions.component.scss
Labels: bug, UI

#13184 Remove echart from module map
  ui-ngx/src/app/modules/common/modules-map.ts
Labels: UI, Ignore for release

#13176 Implement Unique Consumer Groups for Edge Notifications to Improve Stability
  application/src/main/java/org/thingsboard/server/service/edge/rpc/KafkaEdgeGrpcSession.java
  application/src/main/java/org/thingsboard/server/service/ttl/KafkaEdgeTopicsCleanUpService.java
  common/cluster-api/src/main/java/org/thingsboard/server/queue/TbEdgeQueueAdmin.java
  common/queue/src/main/java/org/thingsboard/server/queue/kafka/TbKafkaAdmin.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/KafkaMonolithQueueFactory.java
  common/queue/src/main/java/org/thingsboard/server/queue/provider/KafkaTbCoreQueueFactory.java
Labels: bug, Edge, Ignore for release

#13186 Added validation for entity name filter
  dao/src/main/java/org/thingsboard/server/dao/entity/BaseEntityService.java
Labels: Ignore for release

#13192 Fixed Customer permission checks
  application/src/test/java/org/thingsboard/server/service/entitiy/EntityServiceTest.java
  common/edqs/src/main/java/org/thingsboard/server/edqs/query/processor/AbstractQueryProcessor.java
Labels: Ignore for release

#13168 Fix RuleChainMetadata for older Edge versions
  application/src/main/java/org/thingsboard/server/service/edge/EdgeMsgConstructorUtils.java
  application/src/test/java/org/thingsboard/server/service/edge/EdgeMsgConstructorUtilsTest.java
Labels: Edge, Ignore for release

#13182 Gateway release 4.0 update
  application/src/main/data/json/system/widget_bundles/gateway_widgets.json
  application/src/main/data/json/system/widget_types/gateway_general_configuration.json
  application/src/main/data/json/system/widget_types/gateway_status.json
  application/src/main/data/resources/dashboards/gateways_dashboard.json
  application/src/main/data/resources/js_modules/gateway-management-extension.js
Labels: UI, Ignore for release

#13187 Fixed empty delete dialog in javascript library panel
  ui-ngx/src/app/modules/home/models/entity/entity-details-page-component.models.ts
  ui-ngx/src/app/modules/home/pages/admin/resource/js-library-table-config.resolver.ts
  ui-ngx/src/app/modules/home/pages/admin/resource/js-resource.component.html
  ui-ngx/src/app/modules/home/pages/admin/resource/js-resource.component.ts
Labels: bug, UI, Ignore for release

#13188 Fixed show help popover
  ui-ngx/src/app/shared/components/popover.component.ts
Labels: bug, UI, Ignore for release

#13191 [Docker Compose] Fix EDQS-related scripts
  docker/compose-utils.sh
  docker/docker-install-tb.sh
  docker/docker-update-service.sh
  docker/docker-upgrade-tb.sh
Labels: Build Scripts

#13194 DeviceProfile alarm - Profile state alarm schedule dynamic attributeSource null
  rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/profile/ProfileState.java
  rule-engine/rule-engine-components/src/test/java/org/thingsboard/rule/engine/profile/ProfileStateTest.java
Labels: bug, Rule Engine

#13202 Add example in shape fill image how to use attribute
  ui-ngx/src/assets/help/en_US/widget/lib/map/shape_fill_image_fn.md
Labels: enhancement, UI, Ignore for release

#13203 Updated map help
  ui-ngx/src/assets/help/en_US/widget/lib/map/clustering_color_fn.md
  ui-ngx/src/assets/help/en_US/widget/lib/map/color_fn_examples.md
  ui-ngx/src/assets/help/en_US/widget/lib/map/label_fn_examples.md
  ui-ngx/src/assets/help/en_US/widget/lib/map/marker_image_fn.md
  ui-ngx/src/assets/help/en_US/widget/lib/map/tooltip_fn_examples.md
Labels: enhancement, UI, Ignore for release

#13201 Edge - slow down processing of edge events for SYS_TENANT_ID
  application/src/main/java/org/thingsboard/server/service/edge/EdgeEventSourcingListener.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/EdgeGrpcSession.java
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/BaseEdgeProcessor.java
  common/dao-api/src/main/java/org/thingsboard/server/dao/edge/EdgeService.java
  dao/src/main/java/org/thingsboard/server/dao/edge/EdgeDao.java
  dao/src/main/java/org/thingsboard/server/dao/edge/EdgeServiceImpl.java
  dao/src/main/java/org/thingsboard/server/dao/sql/edge/EdgeRepository.java
  dao/src/main/java/org/thingsboard/server/dao/sql/edge/JpaEdgeDao.java
Labels: Ignore for release

#13204 BaseEdgeProcessor - Fixed incorrect return
  application/src/main/java/org/thingsboard/server/service/edge/rpc/processor/BaseEdgeProcessor.java
Labels: Ignore for release

#13209 Updated properties to exclude tags
  application/src/main/resources/thingsboard.yml
Labels: Ignore for release

#13214 Fix saving issue for dynamic form array items of type 'fieldset'
  ui-ngx/src/app/shared/models/dynamic-form.models.ts
Labels: bug, UI

#13215 Fix type checking for Date and Array in iframes
  ui-ngx/src/app/core/utils.ts
Labels: bug, UI

#13218 Fixed early updatePosition call to prevent CDK overlay crash in matSuffix context
  ui-ngx/src/app/shared/components/popover.component.ts
Labels: bug, UI

#13226 Fix mutation of default widget settings
  ui-ngx/src/app/modules/home/components/widget/lib/settings/alarm/alarm-count-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/button/action-button-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/button/command-button-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/button/power-button-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/button/segmented-button-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/button/toggle-button-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/aggregated-value-card-key-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/aggregated-value-card-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/label-card-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/label-value-card-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/mobile-app-qr-code-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/progress-bar-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/unread-notification-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/cards/value-chart-card-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/chart/bar-chart-with-labels-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/chart/latest-chart-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/chart/range-chart-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/chart/time-series-chart-key-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/chart/time-series-chart-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/control/single-switch-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/control/slider-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/control/value-stepper-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/entity/entity-count-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/indicator/battery-level-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/indicator/signal-strength-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/indicator/status-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/map/legacy/map-widget-settings-legacy.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/map/legacy/route-map-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/map/legacy/trip-animation-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/map/map-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/scada/scada-symbol-widget-settings.component.ts
  ui-ngx/src/app/modules/home/components/widget/lib/settings/weather/wind-speed-direction-widget-settings.component.ts
  ui-ngx/src/app/shared/models/widget.models.ts
Labels: bug, UI

#13217 Updated links for the rule nodes
  ui-ngx/src/app/shared/models/constants.ts
  ui-ngx/src/app/shared/models/rule-node.models.ts
Labels: enhancement, UI

#13229 Fixed SCADA HP bottom right elbow connector pipe
  application/src/main/data/json/system/scada_symbols/bottom-right-elbow-connector-hp.svg
Labels: bug, UI

#13243 Fixed 404 error when accessing LwM2M Profile Transport Configuration with LwM2M disabled
  application/src/main/java/org/thingsboard/server/controller/Lwm2mController.java
  application/src/main/java/org/thingsboard/server/service/lwm2m/LwM2MServiceImpl.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/config/LwM2MTransportBootstrapConfig.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/config/LwM2MTransportServerConfig.java
Labels: bug, Transport

#12799 Use LwM2M Object 19 to send OTA update metadata
  application/src/main/java/org/thingsboard/server/service/device/DeviceBulkImportService.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/AbstractLwM2MIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/ota/AbstractOtaLwM2MIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/ota/sql/Ota5LwM2MIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/ota/sql/Ota9LwM2MIntegrationTest.java
  application/src/test/java/org/thingsboard/server/transport/lwm2m/rpc/sql/RpcLwm2mIntegrationWriteTest.java
  common/data/src/main/java/org/thingsboard/server/common/data/device/profile/lwm2m/OtherConfiguration.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/downlink/DefaultLwM2mDownlinkMsgHandler.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/ota/DefaultLwM2MOtaUpdateService.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/ota/LwM2MClientOtaInfo.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/ota/firmware/LwM2MClientFwOtaInfo.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/ota/software/LwM2MClientSwOtaInfo.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/server/uplink/DefaultLwM2mUplinkMsgHandler.java
  common/transport/lwm2m/src/main/java/org/thingsboard/server/transport/lwm2m/utils/LwM2mValueConverterImpl.java
  common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/util/JsonUtils.java
  ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-device-profile-transport-configuration.component.html
  ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-device-profile-transport-configuration.component.ts
  ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-profile-config.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: feature, Transport

#13258 lwm2m_fix_bug_object19_For_Ota
  application/src/test/java/org/thingsboard/server/transport/lwm2m/ota/AbstractOtaLwM2MIntegrationTest.java
  ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-device-profile-transport-configuration.component.html
  ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-device-profile-transport-configuration.component.ts
  ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-profile-config.models.ts
Labels: Ignore for release

#13287 Device profile lwm2m transport added Observe strategy selector
  ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-device-profile-transport-configuration.component.html
  ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-device-profile-transport-configuration.component.ts
  ui-ngx/src/app/modules/home/components/profile/device/lwm2m/lwm2m-profile-config.models.ts
  ui-ngx/src/assets/locale/locale.constant-en_US.json
Labels: enhancement, UI
